import type { Section } from '../../types'

export const section: Section = {
  title: 'Sectie 2 · Dagelijks leven',
  cefr: 'A1+',
  units: [
    {
      id: 'de-u5',
      title: 'Getallen & tijd',
      icon: '🕰️',
      lessons: [
        {
          id: 'de-u5-l1',
          title: 'Getallen',
          exercises: [
            { type: 'new', word: 'zwei', nl: 'twee', example: 'Ich habe zwei Brüder.', exampleNl: 'Ik heb twee broers.' },
            { type: 'new', word: 'drei', nl: 'drie', example: 'Wir haben drei Kinder.', exampleNl: 'Wij hebben drie kinderen.' },
            { type: 'new', word: 'fünf', nl: 'vijf', example: 'Ich habe fünf Freunde.', exampleNl: 'Ik heb vijf vrienden.' },
            { type: 'new', word: 'zehn', nl: 'tien', example: 'Der Zug fährt in zehn Minuten.', exampleNl: 'De trein vertrekt over tien minuten.' },
            { type: 'select', prompt: 'twee', options: ['drei', 'zwei', 'zehn'], correct: 1 },
            { type: 'select', prompt: 'fünf', speak: 'fünf', options: ['vijf', 'vier', 'tien'], correct: 0 },
            { type: 'listen', target: 'zehn', options: ['zwei', 'zehn', 'drei'], correct: 1 },
            {
              type: 'match',
              pairs: [
                { nl: 'twee', target: 'zwei' },
                { nl: 'drie', target: 'drei' },
                { nl: 'vijf', target: 'fünf' },
                { nl: 'tien', target: 'zehn' },
              ],
            },
            { type: 'wordbank', nl: 'Ik heb twee broers.', target: 'Ich habe zwei Brüder', distractors: ['drei', 'Schwestern', 'bin'] },
            { type: 'fill', before: 'Wir', after: 'drei Kinder.', nl: 'Wij hebben drie kinderen.', options: ['haben', 'habe', 'hat'], correct: 0 },
            { type: 'type', nl: 'tien', target: 'zehn', accept: ['Zehn', 'zehn.', 'Zehn.'] },
            { type: 'select', prompt: 'Der Zug fährt in zehn Minuten.', speak: 'Der Zug fährt in zehn Minuten.', options: ['De trein vertrekt over twee minuten.', 'De trein vertrekt over tien minuten.', 'De bus vertrekt over tien minuten.'], correct: 1 },
          ],
        },
        {
          id: 'de-u5-l2',
          title: 'Hoe laat is het?',
          exercises: [
            { type: 'new', word: 'die Uhr', nl: 'het uur / de klok', example: 'Es ist zwei Uhr.', exampleNl: 'Het is twee uur.' },
            { type: 'new', word: 'um', nl: 'om (tijdstip)', example: 'Der Zug fährt um drei Uhr.', exampleNl: 'De trein vertrekt om drie uur.' },
            { type: 'new', word: 'heute', nl: 'vandaag', example: 'Heute trinke ich Tee.', exampleNl: 'Vandaag drink ik thee.' },
            { type: 'new', word: 'jetzt', nl: 'nu', example: 'Wir essen jetzt.', exampleNl: 'Wij eten nu.' },
            { type: 'select', prompt: 'vandaag', options: ['jetzt', 'heute', 'morgen'], correct: 1 },
            { type: 'select', prompt: 'Es ist fünf Uhr.', speak: 'Es ist fünf Uhr.', options: ['Het is twee uur.', 'Het is vijf uur.', 'Het is tien uur.'], correct: 1 },
            { type: 'fill', before: 'Der Zug fährt', after: 'zwei Uhr.', nl: 'De trein vertrekt om twee uur.', options: ['um', 'nach', 'in'], correct: 0 },
            { type: 'listen', target: 'Es ist zehn Uhr.', options: ['Es ist zwei Uhr.', 'Es ist drei Uhr.', 'Es ist zehn Uhr.'], correct: 2 },
            {
              type: 'match',
              pairs: [
                { nl: 'nu', target: 'jetzt' },
                { nl: 'vandaag', target: 'heute' },
                { nl: 'om', target: 'um' },
                { nl: 'het uur', target: 'die Uhr' },
              ],
            },
            { type: 'wordbank', nl: 'Vandaag drink ik thee.', target: 'Heute trinke ich Tee', distractors: ['jetzt', 'Kaffee', 'esse'] },
            { type: 'type', nl: 'nu', target: 'jetzt', accept: ['Jetzt', 'jetzt.', 'Jetzt.'] },
            { type: 'fill', before: 'Heute', after: 'ich Tee.', nl: 'Vandaag drink ik thee.', options: ['trinke', 'trinkst', 'trinkt'], correct: 0 },
          ],
        },
        {
          id: 'de-u5-l3',
          title: 'Herhaling: getallen & tijd',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'twee', target: 'zwei' },
                { nl: 'vijf', target: 'fünf' },
                { nl: 'tien', target: 'zehn' },
                { nl: 'vandaag', target: 'heute' },
                { nl: 'nu', target: 'jetzt' },
              ],
            },
            { type: 'type', nl: 'Het is drie uur.', target: 'Es ist drei Uhr', accept: ['es ist drei uhr', 'Es ist drei Uhr.'] },
            { type: 'wordbank', nl: 'De trein vertrekt om vijf uur.', target: 'Der Zug fährt um fünf Uhr', distractors: ['jetzt', 'zwei', 'nach'] },
            { type: 'fill', before: 'Der Zug fährt', after: 'zehn Uhr.', nl: 'De trein vertrekt om tien uur.', options: ['um', 'in', 'nach'], correct: 0 },
            { type: 'type', nl: 'vandaag', target: 'heute', accept: ['Heute', 'heute.', 'Heute.'] },
            { type: 'wordbank', nl: 'Nu drinken wij koffie.', target: 'Jetzt trinken wir Kaffee', distractors: ['heute', 'esse', 'Tee'] },
            { type: 'listen', target: 'Es ist zwei Uhr.', options: ['Es ist zwei Uhr.', 'Es ist zehn Uhr.', 'Es ist drei Uhr.'], correct: 0 },
            { type: 'select', prompt: 'Heute ist meine Mutter in Berlin.', speak: 'Heute ist meine Mutter in Berlin.', options: ['Vandaag is mijn moeder in Berlijn.', 'Morgen is mijn moeder in Berlijn.', 'Vandaag is mijn vader in Berlijn.'], correct: 0 },
            { type: 'type', nl: 'Ik heb twee kinderen.', target: 'Ich habe zwei Kinder', accept: ['ich habe zwei kinder', 'Ich habe zwei Kinder.'] },
            { type: 'fill', before: 'Meine Schwester', after: 'jetzt Tee.', nl: 'Mijn zus drinkt nu thee.', options: ['trinkt', 'trinke', 'trinkst'], correct: 0 },
            { type: 'wordbank', nl: 'Vandaag eet ik brood.', target: 'Heute esse ich Brot', distractors: ['trinke', 'jetzt', 'Wasser'] },
            { type: 'type', nl: 'vijf', target: 'fünf', accept: ['Fünf', 'fuenf', 'fünf.'] },
          ],
        },
      ],
    },
    {
      id: 'de-u6',
      title: 'Boodschappen & geld',
      icon: '🛍️',
      lessons: [
        {
          id: 'de-u6-l1',
          title: 'In de supermarkt',
          exercises: [
            { type: 'new', word: 'kaufen', nl: 'kopen', example: 'Ich kaufe Brot und Milch.', exampleNl: 'Ik koop brood en melk.' },
            { type: 'new', word: 'der Supermarkt', nl: 'de supermarkt', example: 'Der Supermarkt ist links.', exampleNl: 'De supermarkt is links.' },
            { type: 'new', word: 'das Geld', nl: 'het geld', example: 'Hast du Geld?', exampleNl: 'Heb jij geld?' },
            { type: 'new', word: 'der Euro', nl: 'de euro', example: 'Ich habe zehn Euro.', exampleNl: 'Ik heb tien euro.' },
            { type: 'select', prompt: 'kopen', options: ['essen', 'trinken', 'kaufen'], correct: 2 },
            { type: 'select', prompt: 'der Supermarkt', speak: 'der Supermarkt', options: ['het station', 'de supermarkt', 'de straat'], correct: 1 },
            { type: 'listen', target: 'das Geld', options: ['der Euro', 'das Geld', 'das Brot'], correct: 1 },
            {
              type: 'match',
              pairs: [
                { nl: 'kopen', target: 'kaufen' },
                { nl: 'het geld', target: 'das Geld' },
                { nl: 'de euro', target: 'der Euro' },
                { nl: 'de supermarkt', target: 'der Supermarkt' },
              ],
            },
            { type: 'wordbank', nl: 'Ik koop brood en melk.', target: 'Ich kaufe Brot und Milch', distractors: ['trinke', 'Wasser', 'der'] },
            { type: 'fill', before: 'Du', after: 'Kaffee.', nl: 'Jij koopt koffie.', options: ['kaufst', 'kaufe', 'kauft'], correct: 0 },
            { type: 'type', nl: 'het geld', target: 'das Geld', accept: ['Das Geld', 'das geld', 'Geld'] },
            { type: 'select', prompt: 'Ich habe zehn Euro.', speak: 'Ich habe zehn Euro.', options: ['Ik heb tien euro.', 'Ik heb twee euro.', 'Ik koop tien appels.'], correct: 0 },
          ],
        },
        {
          id: 'de-u6-l2',
          title: 'Hoeveel kost het?',
          exercises: [
            { type: 'new', word: 'kosten', nl: 'kosten', example: 'Was kostet der Apfel?', exampleNl: 'Wat kost de appel?' },
            { type: 'new', word: 'teuer', nl: 'duur', example: 'Das Hotel ist teuer.', exampleNl: 'Het hotel is duur.' },
            { type: 'new', word: 'billig', nl: 'goedkoop', example: 'Das Brot ist billig.', exampleNl: 'Het brood is goedkoop.' },
            { type: 'new', word: 'bezahlen', nl: 'betalen', example: 'Ich bezahle den Kaffee.', exampleNl: 'Ik betaal de koffie.' },
            { type: 'select', prompt: 'duur', options: ['billig', 'teuer', 'gut'], correct: 1 },
            { type: 'select', prompt: 'Was kostet das Brot?', speak: 'Was kostet das Brot?', options: ['Wat kost het brood?', 'Wat kost de koffie?', 'Waar is het brood?'], correct: 0 },
            { type: 'fill', before: 'Was', after: 'der Apfel?', nl: 'Wat kost de appel?', options: ['kostet', 'kosten', 'kostest'], correct: 0 },
            { type: 'listen', target: 'Das ist teuer.', options: ['Das ist teuer.', 'Das ist billig.', 'Das ist gut.'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'de appel', target: 'der Apfel' },
                { nl: 'duur', target: 'teuer' },
                { nl: 'goedkoop', target: 'billig' },
                { nl: 'betalen', target: 'bezahlen' },
              ],
            },
            { type: 'wordbank', nl: 'Ik betaal de koffie.', target: 'Ich bezahle den Kaffee', distractors: ['kaufe', 'das', 'Tee'] },
            { type: 'type', nl: 'goedkoop', target: 'billig', accept: ['Billig', 'billig.', 'Billig.'] },
            { type: 'fill', before: 'Ich bezahle', after: 'Kaffee.', nl: 'Ik betaal de koffie.', options: ['den', 'die', 'das'], correct: 0 },
          ],
        },
        {
          id: 'de-u6-l3',
          title: 'Herhaling: boodschappen',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'kopen', target: 'kaufen' },
                { nl: 'betalen', target: 'bezahlen' },
                { nl: 'het geld', target: 'das Geld' },
                { nl: 'duur', target: 'teuer' },
                { nl: 'goedkoop', target: 'billig' },
              ],
            },
            { type: 'type', nl: 'kopen', target: 'kaufen', accept: ['Kaufen', 'kaufen.', 'Kaufen.'] },
            { type: 'wordbank', nl: 'Het brood kost twee euro.', target: 'Das Brot kostet zwei Euro', distractors: ['teuer', 'kaufe', 'der'] },
            { type: 'fill', before: 'Der Supermarkt', after: 'links.', nl: 'De supermarkt is links.', options: ['ist', 'sind', 'bin'], correct: 0 },
            { type: 'select', prompt: 'Der Apfel ist billig.', speak: 'Der Apfel ist billig.', options: ['De appel is duur.', 'De appel is goedkoop.', 'Het brood is goedkoop.'], correct: 1 },
            { type: 'type', nl: 'Het hotel is duur.', target: 'Das Hotel ist teuer', accept: ['das hotel ist teuer', 'Das Hotel ist teuer.'] },
            { type: 'listen', target: 'Was kostet der Kaffee?', options: ['Was kostet der Tee?', 'Wo ist der Kaffee?', 'Was kostet der Kaffee?'], correct: 2 },
            { type: 'wordbank', nl: 'Wij kopen brood en melk.', target: 'Wir kaufen Brot und Milch', distractors: ['bezahlen', 'Wasser', 'kauft'] },
            { type: 'fill', before: 'Meine Mutter', after: 'Brot.', nl: 'Mijn moeder koopt brood.', options: ['kauft', 'kaufe', 'kaufst'], correct: 0 },
            { type: 'type', nl: 'Ik heb vijf euro.', target: 'Ich habe fünf Euro', accept: ['ich habe fünf euro', 'Ich habe fuenf Euro', 'Ich habe fünf Euro.'] },
            { type: 'wordbank', nl: 'Wat kost het water?', target: 'Was kostet das Wasser', distractors: ['Wo', 'der', 'Milch'] },
            { type: 'type', nl: 'betalen', target: 'bezahlen', accept: ['Bezahlen', 'bezahlen.', 'Bezahlen.'] },
          ],
        },
      ],
    },
    {
      id: 'de-u7',
      title: 'Huis & wonen',
      icon: '🏠',
      lessons: [
        {
          id: 'de-u7-l1',
          title: 'Mijn huis',
          exercises: [
            { type: 'new', word: 'das Haus', nl: 'het huis', example: 'Das Haus ist groß.', exampleNl: 'Het huis is groot.' },
            { type: 'new', word: 'die Wohnung', nl: 'de woning', example: 'Die Wohnung ist klein.', exampleNl: 'De woning is klein.' },
            { type: 'new', word: 'das Zimmer', nl: 'de kamer', example: 'Mein Zimmer ist schön.', exampleNl: 'Mijn kamer is mooi.' },
            { type: 'new', word: 'die Küche', nl: 'de keuken', example: 'Die Küche ist neu.', exampleNl: 'De keuken is nieuw.' },
            { type: 'select', prompt: 'het huis', options: ['die Wohnung', 'das Haus', 'das Zimmer'], correct: 1 },
            { type: 'select', prompt: 'die Küche', speak: 'die Küche', options: ['de keuken', 'de kamer', 'de woning'], correct: 0 },
            { type: 'listen', target: 'das Zimmer', options: ['das Zimmer', 'die Küche', 'das Haus'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'het huis', target: 'das Haus' },
                { nl: 'de woning', target: 'die Wohnung' },
                { nl: 'de kamer', target: 'das Zimmer' },
                { nl: 'de keuken', target: 'die Küche' },
              ],
            },
            { type: 'fill', before: '', after: 'Wohnung ist klein.', nl: 'De woning is klein.', options: ['Die', 'Der', 'Das'], correct: 0 },
            { type: 'wordbank', nl: 'Het huis is groot.', target: 'Das Haus ist groß', distractors: ['Die', 'klein', 'Zimmer'] },
            { type: 'type', nl: 'de keuken', target: 'die Küche', accept: ['Die Küche', 'die küche', 'Küche'] },
            { type: 'select', prompt: 'de kamer', options: ['das Zimmer', 'die Küche', 'das Haus'], correct: 0 },
          ],
        },
        {
          id: 'de-u7-l2',
          title: 'Wonen & meubels',
          exercises: [
            { type: 'new', word: 'wohnen', nl: 'wonen', example: 'Ich wohne in Hamburg.', exampleNl: 'Ik woon in Hamburg.' },
            { type: 'new', word: 'der Tisch', nl: 'de tafel', example: 'Der Tisch ist neu.', exampleNl: 'De tafel is nieuw.' },
            { type: 'new', word: 'der Stuhl', nl: 'de stoel', example: 'Der Stuhl ist klein.', exampleNl: 'De stoel is klein.' },
            { type: 'new', word: 'das Bett', nl: 'het bed', example: 'Das Bett ist warm.', exampleNl: 'Het bed is warm.' },
            { type: 'select', prompt: 'wonen', options: ['kaufen', 'essen', 'wohnen'], correct: 2 },
            { type: 'select', prompt: 'Ich wohne in Hamburg.', speak: 'Ich wohne in Hamburg.', options: ['Ik woon in Hamburg.', 'Ik werk in Hamburg.', 'Ik woon in Berlijn.'], correct: 0 },
            { type: 'fill', before: 'Du', after: 'in Köln.', nl: 'Jij woont in Keulen.', options: ['wohnst', 'wohne', 'wohnt'], correct: 0 },
            { type: 'listen', target: 'Das Bett ist warm.', options: ['Das Bett ist kalt.', 'Das Bett ist warm.', 'Der Tisch ist warm.'], correct: 1 },
            {
              type: 'match',
              pairs: [
                { nl: 'wonen', target: 'wohnen' },
                { nl: 'de tafel', target: 'der Tisch' },
                { nl: 'de stoel', target: 'der Stuhl' },
                { nl: 'het bed', target: 'das Bett' },
              ],
            },
            { type: 'wordbank', nl: 'Ik woon in Hamburg.', target: 'Ich wohne in Hamburg', distractors: ['wohnst', 'Berlin', 'Haus'] },
            { type: 'type', nl: 'de tafel', target: 'der Tisch', accept: ['Der Tisch', 'der tisch', 'Tisch'] },
            { type: 'fill', before: '', after: 'Stuhl ist klein.', nl: 'De stoel is klein.', options: ['Der', 'Die', 'Das'], correct: 0 },
          ],
        },
        {
          id: 'de-u7-l3',
          title: 'Herhaling: huis & wonen',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'het huis', target: 'das Haus' },
                { nl: 'de kamer', target: 'das Zimmer' },
                { nl: 'de keuken', target: 'die Küche' },
                { nl: 'de tafel', target: 'der Tisch' },
                { nl: 'het bed', target: 'das Bett' },
              ],
            },
            { type: 'type', nl: 'de woning', target: 'die Wohnung', accept: ['Die Wohnung', 'die wohnung', 'Wohnung'] },
            { type: 'wordbank', nl: 'Mijn kamer is mooi.', target: 'Mein Zimmer ist schön', distractors: ['Meine', 'klein', 'Küche'] },
            { type: 'fill', before: 'Meine Schwester', after: 'in Berlin.', nl: 'Mijn zus woont in Berlijn.', options: ['wohnt', 'wohne', 'wohnst'], correct: 0 },
            { type: 'select', prompt: 'Die Küche ist neu.', speak: 'Die Küche ist neu.', options: ['De keuken is klein.', 'De keuken is nieuw.', 'De kamer is nieuw.'], correct: 1 },
            { type: 'type', nl: 'Ik woon in Berlijn.', target: 'Ich wohne in Berlin', accept: ['ich wohne in berlin', 'Ich wohne in Berlin.'] },
            { type: 'listen', target: 'Das Haus ist groß.', options: ['Das Haus ist klein.', 'Das Bett ist groß.', 'Das Haus ist groß.'], correct: 2 },
            { type: 'wordbank', nl: 'De tafel en het bed zijn nieuw.', target: 'Der Tisch und das Bett sind neu', distractors: ['ist', 'die', 'Stuhl'] },
            { type: 'fill', before: 'Wo', after: 'du?', nl: 'Waar woon jij?', options: ['wohnst', 'wohnt', 'wohne'], correct: 0 },
            { type: 'type', nl: 'het bed', target: 'das Bett', accept: ['Das Bett', 'das bett', 'Bett'] },
            { type: 'wordbank', nl: 'Waar is de keuken?', target: 'Wo ist die Küche', distractors: ['der', 'Zimmer', 'was'] },
            { type: 'type', nl: 'Het huis is groot.', target: 'Das Haus ist groß', accept: ['das haus ist groß', 'Das Haus ist gross', 'Das Haus ist groß.'] },
          ],
        },
      ],
    },
    {
      id: 'de-u8',
      title: 'Werk & school',
      icon: '💼',
      lessons: [
        {
          id: 'de-u8-l1',
          title: 'Op het werk',
          exercises: [
            { type: 'new', word: 'arbeiten', nl: 'werken', example: 'Ich arbeite in Berlin.', exampleNl: 'Ik werk in Berlijn.' },
            { type: 'new', word: 'die Arbeit', nl: 'het werk', example: 'Die Arbeit beginnt um zehn Uhr.', exampleNl: 'Het werk begint om tien uur.' },
            { type: 'new', word: 'das Büro', nl: 'het kantoor', example: 'Das Büro ist groß.', exampleNl: 'Het kantoor is groot.' },
            { type: 'new', word: 'der Lehrer', nl: 'de leraar', example: 'Der Lehrer heißt Herr Braun.', exampleNl: 'De leraar heet meneer Braun.' },
            { type: 'select', prompt: 'werken', options: ['arbeiten', 'wohnen', 'kaufen'], correct: 0 },
            { type: 'select', prompt: 'das Büro', speak: 'das Büro', options: ['het werk', 'het kantoor', 'de school'], correct: 1 },
            { type: 'listen', target: 'die Arbeit', options: ['die Arbeit', 'der Lehrer', 'das Büro'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'werken', target: 'arbeiten' },
                { nl: 'het werk', target: 'die Arbeit' },
                { nl: 'het kantoor', target: 'das Büro' },
                { nl: 'de leraar', target: 'der Lehrer' },
              ],
            },
            { type: 'fill', before: 'Ich', after: 'in Hamburg.', nl: 'Ik werk in Hamburg.', options: ['arbeite', 'arbeitest', 'arbeitet'], correct: 0 },
            { type: 'wordbank', nl: 'Ik werk in Berlijn.', target: 'Ich arbeite in Berlin', distractors: ['wohne', 'Büro', 'arbeitest'] },
            { type: 'type', nl: 'de leraar', target: 'der Lehrer', accept: ['Der Lehrer', 'der lehrer', 'Lehrer'] },
            { type: 'select', prompt: 'Die Arbeit beginnt um zehn Uhr.', speak: 'Die Arbeit beginnt um zehn Uhr.', options: ['Het werk begint om tien uur.', 'Het werk begint om twee uur.', 'De school begint om tien uur.'], correct: 0 },
          ],
        },
        {
          id: 'de-u8-l2',
          title: 'Naar school',
          exercises: [
            { type: 'new', word: 'die Schule', nl: 'de school', example: 'Die Schule ist neu und groß.', exampleNl: 'De school is nieuw en groot.' },
            { type: 'new', word: 'lernen', nl: 'leren', example: 'Ich lerne Deutsch.', exampleNl: 'Ik leer Duits.' },
            { type: 'new', word: 'das Buch', nl: 'het boek', example: 'Das Buch ist gut.', exampleNl: 'Het boek is goed.' },
            { type: 'new', word: 'schreiben', nl: 'schrijven', example: 'Ich schreibe eine E-Mail.', exampleNl: 'Ik schrijf een e-mail.' },
            { type: 'select', prompt: 'leren', options: ['schreiben', 'arbeiten', 'lernen'], correct: 2 },
            { type: 'select', prompt: 'Ich lerne Deutsch.', speak: 'Ich lerne Deutsch.', options: ['Ik leer Duits.', 'Ik schrijf Duits.', 'Ik leer Engels.'], correct: 0 },
            { type: 'fill', before: 'Du', after: 'Deutsch.', nl: 'Jij leert Duits.', options: ['lernst', 'lerne', 'lernt'], correct: 0 },
            { type: 'listen', target: 'Das Buch ist gut.', options: ['Das Brot ist gut.', 'Das Buch ist gut.', 'Das Buch ist neu.'], correct: 1 },
            {
              type: 'match',
              pairs: [
                { nl: 'de school', target: 'die Schule' },
                { nl: 'leren', target: 'lernen' },
                { nl: 'het boek', target: 'das Buch' },
                { nl: 'schrijven', target: 'schreiben' },
              ],
            },
            { type: 'wordbank', nl: 'Ik schrijf een e-mail.', target: 'Ich schreibe eine E-Mail', distractors: ['lerne', 'ein', 'Buch'] },
            { type: 'type', nl: 'het boek', target: 'das Buch', accept: ['Das Buch', 'das buch', 'Buch'] },
            { type: 'fill', before: 'Die Schule ist', after: 'und groß.', nl: 'De school is nieuw en groot.', options: ['neu', 'neue', 'neues'], correct: 0 },
          ],
        },
        {
          id: 'de-u8-l3',
          title: 'Herhaling: werk & school',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'werken', target: 'arbeiten' },
                { nl: 'leren', target: 'lernen' },
                { nl: 'schrijven', target: 'schreiben' },
                { nl: 'het kantoor', target: 'das Büro' },
                { nl: 'de school', target: 'die Schule' },
              ],
            },
            { type: 'type', nl: 'leren', target: 'lernen', accept: ['Lernen', 'lernen.', 'Lernen.'] },
            { type: 'wordbank', nl: 'Ik leer Duits en werk in Berlijn.', target: 'Ich lerne Deutsch und arbeite in Berlin', distractors: ['wohne', 'lernst', 'die'] },
            { type: 'fill', before: 'Mein Bruder', after: 'in Berlin.', nl: 'Mijn broer werkt in Berlijn.', options: ['arbeitet', 'arbeite', 'arbeitest'], correct: 0 },
            { type: 'select', prompt: 'Der Lehrer schreibt ein Buch.', speak: 'Der Lehrer schreibt ein Buch.', options: ['De leraar leest een boek.', 'De leraar schrijft een boek.', 'De leraar koopt een boek.'], correct: 1 },
            { type: 'type', nl: 'de school', target: 'die Schule', accept: ['Die Schule', 'die schule', 'Schule'] },
            { type: 'listen', target: 'Ich lerne Deutsch.', options: ['Ich lerne Englisch.', 'Ich lerne Deutsch.', 'Ich lehre Deutsch.'], correct: 1 },
            { type: 'wordbank', nl: 'Het werk begint om tien uur.', target: 'Die Arbeit beginnt um zehn Uhr', distractors: ['Schule', 'zwei', 'jetzt'] },
            { type: 'fill', before: '', after: 'Buch ist gut.', nl: 'Het boek is goed.', options: ['Das', 'Der', 'Die'], correct: 0 },
            { type: 'type', nl: 'Ik schrijf een e-mail.', target: 'Ich schreibe eine E-Mail', accept: ['ich schreibe eine e-mail', 'Ich schreibe eine E-Mail.', 'Ich schreibe eine Email'] },
            { type: 'wordbank', nl: 'De leraar heet meneer Braun.', target: 'Der Lehrer heißt Herr Braun', distractors: ['Die', 'Frau', 'wohnt'] },
            { type: 'type', nl: 'het kantoor', target: 'das Büro', accept: ['Das Büro', 'das büro', 'Büro', 'das Buero'] },
          ],
        },
      ],
    },
    {
      id: 'de-u9',
      title: 'Gesprekken voeren',
      icon: '💬',
      lessons: [
        {
          id: 'de-u9-l1',
          title: 'Een praatje maken',
          exercises: [
            { type: 'new', word: 'sprechen', nl: 'spreken', example: 'Sprechen Sie Deutsch?', exampleNl: 'Spreekt u Duits?' },
            { type: 'new', word: 'verstehen', nl: 'begrijpen / verstaan', example: 'Ich verstehe das nicht.', exampleNl: 'Ik begrijp het niet.' },
            { type: 'new', word: 'ein bisschen', nl: 'een beetje', example: 'Ich spreche ein bisschen Deutsch.', exampleNl: 'Ik spreek een beetje Duits.' },
            { type: 'new', word: 'Entschuldigung', nl: 'pardon / sorry', example: 'Entschuldigung, wo ist der Bahnhof?', exampleNl: 'Pardon, waar is het station?' },
            { type: 'select', prompt: 'spreken', options: ['sprechen', 'verstehen', 'schreiben'], correct: 0 },
            { type: 'select', prompt: 'Sprechen Sie Deutsch?', speak: 'Sprechen Sie Deutsch?', options: ['Spreekt u Duits?', 'Leert u Duits?', 'Schrijft u Duits?'], correct: 0 },
            { type: 'listen', target: 'Entschuldigung!', options: ['Entschuldigung!', 'Guten Morgen!', 'Danke schön!'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'spreken', target: 'sprechen' },
                { nl: 'begrijpen', target: 'verstehen' },
                { nl: 'een beetje', target: 'ein bisschen' },
                { nl: 'pardon', target: 'Entschuldigung' },
              ],
            },
            { type: 'wordbank', nl: 'Ik spreek een beetje Duits.', target: 'Ich spreche ein bisschen Deutsch', distractors: ['verstehe', 'gut', 'sprichst'] },
            { type: 'fill', before: 'Ich', after: 'das nicht.', nl: 'Ik begrijp het niet.', options: ['verstehe', 'verstehst', 'versteht'], correct: 0 },
            { type: 'type', nl: 'pardon', target: 'Entschuldigung', accept: ['entschuldigung', 'Entschuldigung!'] },
            { type: 'select', prompt: 'Entschuldigung, wo ist der Supermarkt?', speak: 'Entschuldigung, wo ist der Supermarkt?', options: ['Pardon, waar is de supermarkt?', 'Pardon, waar is het station?', 'Hallo, waar is de supermarkt?'], correct: 0 },
          ],
        },
        {
          id: 'de-u9-l2',
          title: 'Vragen stellen',
          exercises: [
            { type: 'new', word: 'wer', nl: 'wie (vraagwoord)', example: 'Wer ist das?', exampleNl: 'Wie is dat?' },
            { type: 'new', word: 'warum', nl: 'waarom', example: 'Warum lernst du Deutsch?', exampleNl: 'Waarom leer jij Duits?' },
            { type: 'new', word: 'wie viel', nl: 'hoeveel', example: 'Wie viel kostet das Zimmer?', exampleNl: 'Hoeveel kost de kamer?' },
            { type: 'new', word: 'natürlich', nl: 'natuurlijk', example: 'Ja, natürlich!', exampleNl: 'Ja, natuurlijk!' },
            { type: 'select', prompt: 'waarom', options: ['wer', 'warum', 'wo'], correct: 1 },
            { type: 'select', prompt: 'Wer ist die Frau?', speak: 'Wer ist die Frau?', options: ['Waar is de vrouw?', 'Wie is de man?', 'Wie is de vrouw?'], correct: 2 },
            { type: 'fill', before: '', after: 'kostet das Bett?', nl: 'Hoeveel kost het bed?', options: ['Wie viel', 'Wer', 'Warum'], correct: 0 },
            { type: 'listen', target: 'Warum lernst du Deutsch?', options: ['Wo lernst du Deutsch?', 'Warum lernst du Englisch?', 'Warum lernst du Deutsch?'], correct: 2 },
            {
              type: 'match',
              pairs: [
                { nl: 'wie', target: 'wer' },
                { nl: 'waarom', target: 'warum' },
                { nl: 'hoeveel', target: 'wie viel' },
                { nl: 'natuurlijk', target: 'natürlich' },
                { nl: 'waar', target: 'wo' },
              ],
            },
            { type: 'wordbank', nl: 'Hoeveel kost de woning?', target: 'Wie viel kostet die Wohnung', distractors: ['Warum', 'das', 'teuer'] },
            { type: 'type', nl: 'natuurlijk', target: 'natürlich', accept: ['Natürlich', 'natuerlich', 'natürlich!'] },
            { type: 'fill', before: 'Warum', after: 'du Kaffee?', nl: 'Waarom drink jij koffie?', options: ['trinkst', 'trinke', 'trinkt'], correct: 0 },
          ],
        },
        {
          id: 'de-u9-l3',
          title: 'Herhaling: dagelijks leven',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'spreken', target: 'sprechen' },
                { nl: 'kopen', target: 'kaufen' },
                { nl: 'wonen', target: 'wohnen' },
                { nl: 'werken', target: 'arbeiten' },
                { nl: 'leren', target: 'lernen' },
              ],
            },
            { type: 'type', nl: 'Pardon, waar is het station?', target: 'Entschuldigung, wo ist der Bahnhof?', accept: ['entschuldigung wo ist der bahnhof', 'Entschuldigung wo ist der Bahnhof', 'Entschuldigung, wo ist der Bahnhof'] },
            { type: 'wordbank', nl: 'Wij kopen vandaag brood.', target: 'Wir kaufen heute Brot', distractors: ['jetzt', 'bezahlen', 'Milch'] },
            { type: 'fill', before: 'Wie viel', after: 'das Buch?', nl: 'Hoeveel kost het boek?', options: ['kostet', 'kosten', 'kostest'], correct: 0 },
            { type: 'type', nl: 'Ik begrijp het niet.', target: 'Ich verstehe das nicht', accept: ['ich verstehe das nicht', 'Ich verstehe das nicht.'] },
            { type: 'listen', target: 'Wie viel kostet das Hotel?', options: ['Wie viel kostet das Hotel?', 'Wie viel kostet das Haus?', 'Wo ist das Hotel?'], correct: 0 },
            { type: 'wordbank', nl: 'Waarom werk jij vandaag?', target: 'Warum arbeitest du heute', distractors: ['arbeite', 'jetzt', 'wer'] },
            { type: 'select', prompt: 'Ich verstehe ein bisschen Deutsch.', speak: 'Ich verstehe ein bisschen Deutsch.', options: ['Ik begrijp een beetje Duits.', 'Ik spreek een beetje Duits.', 'Ik begrijp geen Duits.'], correct: 0 },
            { type: 'type', nl: 'Wie is dat?', target: 'Wer ist das', accept: ['wer ist das', 'Wer ist das?'] },
            { type: 'fill', before: 'Entschuldigung,', after: 'ist die Schule?', nl: 'Pardon, waar is de school?', options: ['wo', 'wer', 'was'], correct: 0 },
            { type: 'wordbank', nl: 'Mijn vriend woont en werkt in Hamburg.', target: 'Mein Freund wohnt und arbeitet in Hamburg', distractors: ['wohne', 'arbeite', 'die'] },
            { type: 'type', nl: 'Hoeveel kost de koffie?', target: 'Wie viel kostet der Kaffee', accept: ['wie viel kostet der kaffee', 'Wie viel kostet der Kaffee?'] },
            { type: 'wordbank', nl: 'Ja natuurlijk, het huis is groot en mooi.', target: 'Ja natürlich das Haus ist groß und schön', distractors: ['klein', 'die', 'teuer'] },
          ],
        },
      ],
    },
  ],
}
