import type { Section } from '../../types'

export const section: Section = {
  title: 'Sectie 3 · Op weg naar A2',
  cefr: 'A2',
  units: [
    {
      id: 'de-u10',
      title: 'Reizen & vervoer',
      icon: '✈️',
      lessons: [
        {
          id: 'de-u10-l1',
          title: 'Op reis',
          exercises: [
            { type: 'new', word: 'die Fahrkarte', nl: 'het kaartje', example: 'Ich brauche eine Fahrkarte nach München.', exampleNl: 'Ik heb een kaartje naar München nodig.' },
            { type: 'new', word: 'der Koffer', nl: 'de koffer', example: 'Mein Koffer ist schwer.', exampleNl: 'Mijn koffer is zwaar.' },
            { type: 'new', word: 'der Bus', nl: 'de bus', example: 'Der Bus kommt in zehn Minuten.', exampleNl: 'De bus komt over tien minuten.' },
            { type: 'new', word: 'das Flugzeug', nl: 'het vliegtuig', example: 'Das Flugzeug fliegt nach Wien.', exampleNl: 'Het vliegtuig vliegt naar Wenen.' },
            { type: 'select', prompt: 'het kaartje', options: ['der Koffer', 'die Fahrkarte', 'der Bus'], correct: 1 },
            { type: 'select', prompt: 'Das Flugzeug fliegt nach Wien.', speak: 'Das Flugzeug fliegt nach Wien.', options: ['Het vliegtuig vliegt naar Wenen.', 'De trein rijdt naar Wenen.', 'Het vliegtuig vliegt naar Berlijn.'], correct: 0 },
            { type: 'listen', target: 'der Koffer', options: ['der Kaffee', 'der Koffer', 'die Fahrkarte'], correct: 1 },
            {
              type: 'match',
              pairs: [
                { nl: 'het kaartje', target: 'die Fahrkarte' },
                { nl: 'de koffer', target: 'der Koffer' },
                { nl: 'de bus', target: 'der Bus' },
                { nl: 'het vliegtuig', target: 'das Flugzeug' },
                { nl: 'de trein', target: 'der Zug' },
              ],
            },
            { type: 'fill', before: '', after: 'Bus kommt in zehn Minuten.', nl: 'De bus komt over tien minuten.', options: ['Der', 'Die', 'Das'], correct: 0 },
            { type: 'wordbank', nl: 'Mijn koffer is zwaar.', target: 'Mein Koffer ist schwer', distractors: ['Meine', 'leicht', 'Kaffee'] },
            { type: 'type', nl: 'de bus', target: 'der Bus', accept: ['Der Bus', 'der bus', 'Bus'] },
            { type: 'select', prompt: 'het vliegtuig', options: ['das Flugzeug', 'der Bus', 'der Zug'], correct: 0 },
          ],
        },
        {
          id: 'de-u10-l2',
          title: 'Vertrek en aankomst',
          exercises: [
            { type: 'new', word: 'der Flughafen', nl: 'het vliegveld', example: 'Wir fahren zum Flughafen.', exampleNl: 'Wij rijden naar het vliegveld.' },
            { type: 'new', word: 'die Reise', nl: 'de reis', example: 'Die Reise nach Berlin ist lang.', exampleNl: 'De reis naar Berlijn is lang.' },
            { type: 'new', word: 'abfahren', nl: 'vertrekken', example: 'Der Zug fährt um neun Uhr ab.', exampleNl: 'De trein vertrekt om negen uur.' },
            { type: 'new', word: 'ankommen', nl: 'aankomen', example: 'Wir kommen um zehn Uhr an.', exampleNl: 'Wij komen om tien uur aan.' },
            { type: 'select', prompt: 'het vliegveld', options: ['das Flugzeug', 'der Flughafen', 'der Bahnhof'], correct: 1 },
            { type: 'select', prompt: 'Die Reise ist lang.', speak: 'Die Reise ist lang.', options: ['De reis is lang.', 'De straat is lang.', 'De reis is kort.'], correct: 0 },
            { type: 'listen', target: 'der Flughafen', options: ['der Flughafen', 'das Flugzeug', 'der Bahnhof'], correct: 0 },
            { type: 'fill', before: 'Der Zug fährt um neun Uhr', after: '.', nl: 'De trein vertrekt om negen uur.', options: ['ab', 'an', 'aus'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'het vliegveld', target: 'der Flughafen' },
                { nl: 'de reis', target: 'die Reise' },
                { nl: 'vertrekken', target: 'abfahren' },
                { nl: 'aankomen', target: 'ankommen' },
              ],
            },
            { type: 'wordbank', nl: 'Wij komen om tien uur aan.', target: 'Wir kommen um zehn Uhr an', distractors: ['ab', 'fährt', 'Flughafen'] },
            { type: 'type', nl: 'de reis', target: 'die Reise', accept: ['Die Reise', 'die reise', 'Reise'] },
            { type: 'fill', before: 'Wann kommt der Bus', after: '?', nl: 'Wanneer komt de bus aan?', options: ['an', 'ab', 'auf'], correct: 0 },
          ],
        },
        {
          id: 'de-u10-l3',
          title: 'Herhaling: onderweg',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'het kaartje', target: 'die Fahrkarte' },
                { nl: 'de koffer', target: 'der Koffer' },
                { nl: 'het vliegtuig', target: 'das Flugzeug' },
                { nl: 'het vliegveld', target: 'der Flughafen' },
                { nl: 'de trein', target: 'der Zug' },
              ],
            },
            { type: 'type', nl: 'het vliegveld', target: 'der Flughafen', accept: ['Der Flughafen', 'der flughafen', 'Flughafen'] },
            { type: 'wordbank', nl: 'De trein vertrekt om negen uur.', target: 'Der Zug fährt um neun Uhr ab', distractors: ['an', 'kommt', 'Bus'] },
            { type: 'type', nl: 'de koffer', target: 'der Koffer', accept: ['Der Koffer', 'der koffer', 'Koffer'] },
            { type: 'fill', before: '', after: 'Reise nach Wien ist lang.', nl: 'De reis naar Wenen is lang.', options: ['Die', 'Der', 'Das'], correct: 0 },
            { type: 'listen', target: 'Das Flugzeug fliegt nach Berlin.', options: ['Das Flugzeug fliegt nach Berlin.', 'Das Flugzeug fliegt nach Wien.', 'Der Zug fährt nach Berlin.'], correct: 0 },
            { type: 'wordbank', nl: 'Wij rijden met de bus naar het vliegveld.', target: 'Wir fahren mit dem Bus zum Flughafen', distractors: ['der', 'Zug', 'ab'] },
            { type: 'type', nl: 'Het vliegtuig vliegt naar Wenen.', target: 'Das Flugzeug fliegt nach Wien', accept: ['das flugzeug fliegt nach wien', 'Das Flugzeug fliegt nach Wien.'] },
            { type: 'select', prompt: 'Wann fährt der Zug ab?', speak: 'Wann fährt der Zug ab?', options: ['Wanneer vertrekt de trein?', 'Wanneer komt de trein aan?', 'Waar vertrekt de bus?'], correct: 0 },
            { type: 'wordbank', nl: 'De bus komt over tien minuten.', target: 'Der Bus kommt in zehn Minuten', distractors: ['Die', 'Uhr', 'fährt'] },
            { type: 'fill', before: 'Wir fahren', after: 'Flughafen.', nl: 'Wij rijden naar het vliegveld.', options: ['zum', 'nach', 'bei'], correct: 0 },
            { type: 'type', nl: 'vertrekken', target: 'abfahren', accept: ['Abfahren'] },
          ],
        },
      ],
    },
    {
      id: 'de-u11',
      title: 'Gezondheid & lichaam',
      icon: '🌿',
      lessons: [
        {
          id: 'de-u11-l1',
          title: 'Hoe voel je je?',
          exercises: [
            { type: 'new', word: 'der Kopf', nl: 'het hoofd', example: 'Mein Kopf tut weh.', exampleNl: 'Mijn hoofd doet pijn.' },
            { type: 'new', word: 'der Bauch', nl: 'de buik', example: 'Mein Bauch tut weh.', exampleNl: 'Mijn buik doet pijn.' },
            { type: 'new', word: 'krank', nl: 'ziek', example: 'Ich bin heute krank.', exampleNl: 'Ik ben vandaag ziek.' },
            { type: 'new', word: 'müde', nl: 'moe', example: 'Ich bin müde und gehe ins Bett.', exampleNl: 'Ik ben moe en ga naar bed.' },
            { type: 'select', prompt: 'ziek', options: ['müde', 'krank', 'gut'], correct: 1 },
            { type: 'select', prompt: 'Ich bin müde.', speak: 'Ich bin müde.', options: ['Ik ben moe.', 'Ik ben ziek.', 'Ik ben goed.'], correct: 0 },
            { type: 'listen', target: 'Mein Kopf tut weh.', options: ['Mein Kopf tut weh.', 'Mein Bauch tut weh.', 'Mein Kopf ist rot.'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'het hoofd', target: 'der Kopf' },
                { nl: 'de buik', target: 'der Bauch' },
                { nl: 'ziek', target: 'krank' },
                { nl: 'moe', target: 'müde' },
              ],
            },
            { type: 'fill', before: 'Mein Kopf', after: 'weh.', nl: 'Mijn hoofd doet pijn.', options: ['tut', 'macht', 'ist'], correct: 0 },
            { type: 'wordbank', nl: 'Ik ben vandaag ziek.', target: 'Ich bin heute krank', distractors: ['müde', 'gut', 'habe'] },
            { type: 'type', nl: 'moe', target: 'müde', accept: ['Müde', 'muede'] },
            { type: 'select', prompt: 'de buik', options: ['der Kopf', 'der Bauch', 'das Bein'], correct: 1 },
          ],
        },
        {
          id: 'de-u11-l2',
          title: 'Bij de dokter',
          exercises: [
            { type: 'new', word: 'der Arzt', nl: 'de dokter', example: 'Ich gehe morgen zum Arzt.', exampleNl: 'Ik ga morgen naar de dokter.' },
            { type: 'new', word: 'die Apotheke', nl: 'de apotheek', example: 'Die Apotheke ist neben dem Bahnhof.', exampleNl: 'De apotheek is naast het station.' },
            { type: 'new', word: 'das Fieber', nl: 'de koorts', example: 'Das Kind hat Fieber.', exampleNl: 'Het kind heeft koorts.' },
            { type: 'new', word: 'helfen', nl: 'helpen', example: 'Können Sie mir helfen?', exampleNl: 'Kunt u mij helpen?' },
            { type: 'select', prompt: 'de dokter', options: ['die Apotheke', 'der Arzt', 'der Mann'], correct: 1 },
            { type: 'select', prompt: 'Das Kind hat Fieber.', speak: 'Das Kind hat Fieber.', options: ['Het kind heeft koorts.', 'Het kind is moe.', 'De vrouw heeft koorts.'], correct: 0 },
            { type: 'listen', target: 'die Apotheke', options: ['die Apotheke', 'der Apfel', 'der Arzt'], correct: 0 },
            { type: 'fill', before: 'Ich gehe', after: 'Arzt.', nl: 'Ik ga naar de dokter.', options: ['zum', 'nach', 'bei'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'de dokter', target: 'der Arzt' },
                { nl: 'de apotheek', target: 'die Apotheke' },
                { nl: 'de koorts', target: 'das Fieber' },
                { nl: 'helpen', target: 'helfen' },
              ],
            },
            { type: 'wordbank', nl: 'Kunt u mij helpen?', target: 'Können Sie mir helfen', distractors: ['du', 'mich', 'habe'] },
            { type: 'type', nl: 'de koorts', target: 'das Fieber', accept: ['Das Fieber', 'das fieber', 'Fieber'] },
            { type: 'fill', before: 'Das Kind', after: 'Fieber.', nl: 'Het kind heeft koorts.', options: ['hat', 'hast', 'habe'], correct: 0 },
          ],
        },
        {
          id: 'de-u11-l3',
          title: 'Herhaling: gezondheid',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'het hoofd', target: 'der Kopf' },
                { nl: 'de buik', target: 'der Bauch' },
                { nl: 'de dokter', target: 'der Arzt' },
                { nl: 'de apotheek', target: 'die Apotheke' },
                { nl: 'de koorts', target: 'das Fieber' },
              ],
            },
            { type: 'type', nl: 'Mijn hoofd doet pijn.', target: 'Mein Kopf tut weh', accept: ['mein kopf tut weh', 'Mein Kopf tut weh.'] },
            { type: 'wordbank', nl: 'Ik ben ziek en ga naar de dokter.', target: 'Ich bin krank und gehe zum Arzt', distractors: ['müde', 'Apotheke', 'habe'] },
            { type: 'type', nl: 'de dokter', target: 'der Arzt', accept: ['Der Arzt', 'der arzt', 'Arzt'] },
            { type: 'fill', before: '', after: 'Apotheke ist neben dem Bahnhof.', nl: 'De apotheek is naast het station.', options: ['Die', 'Der', 'Das'], correct: 0 },
            { type: 'listen', target: 'Ich habe Fieber.', options: ['Ich habe Fieber.', 'Ich habe Hunger.', 'Ich bin müde.'], correct: 0 },
            { type: 'wordbank', nl: 'Mijn buik doet pijn.', target: 'Mein Bauch tut weh', distractors: ['Kopf', 'ist', 'mir'] },
            { type: 'select', prompt: 'Können Sie mir helfen?', speak: 'Können Sie mir helfen?', options: ['Kunt u mij helpen?', 'Kunt u mij horen?', 'Wilt u mij betalen?'], correct: 0 },
            { type: 'type', nl: 'de apotheek', target: 'die Apotheke', accept: ['Die Apotheke', 'die apotheke', 'Apotheke'] },
            { type: 'fill', before: 'Ich bin müde', after: 'gehe ins Bett.', nl: 'Ik ben moe en ga naar bed.', options: ['und', 'oder', 'aber'], correct: 0 },
            { type: 'wordbank', nl: 'Het kind is ziek en heeft koorts.', target: 'Das Kind ist krank und hat Fieber', distractors: ['müde', 'Arzt', 'habe'] },
            { type: 'type', nl: 'Ik ga morgen naar de dokter.', target: 'Ich gehe morgen zum Arzt', accept: ['ich gehe morgen zum arzt', 'Ich gehe morgen zum Arzt.'] },
          ],
        },
      ],
    },
    {
      id: 'de-u12',
      title: 'Weer & seizoenen',
      icon: '🌦️',
      lessons: [
        {
          id: 'de-u12-l1',
          title: 'Wat voor weer is het?',
          exercises: [
            { type: 'new', word: 'das Wetter', nl: 'het weer', example: 'Das Wetter ist heute schön.', exampleNl: 'Het weer is vandaag mooi.' },
            { type: 'new', word: 'die Sonne', nl: 'de zon', example: 'Die Sonne scheint.', exampleNl: 'De zon schijnt.' },
            { type: 'new', word: 'der Regen', nl: 'de regen', example: 'Ich mag den Regen nicht.', exampleNl: 'Ik houd niet van de regen.' },
            { type: 'new', word: 'der Schnee', nl: 'de sneeuw', example: 'Der Schnee ist weiß.', exampleNl: 'De sneeuw is wit.' },
            { type: 'select', prompt: 'het weer', options: ['die Sonne', 'das Wetter', 'der Regen'], correct: 1 },
            { type: 'select', prompt: 'Die Sonne scheint.', speak: 'Die Sonne scheint.', options: ['De zon schijnt.', 'Het regent.', 'De sneeuw is wit.'], correct: 0 },
            { type: 'listen', target: 'der Regen', options: ['der Regen', 'der Schnee', 'die Sonne'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'het weer', target: 'das Wetter' },
                { nl: 'de zon', target: 'die Sonne' },
                { nl: 'de regen', target: 'der Regen' },
                { nl: 'de sneeuw', target: 'der Schnee' },
              ],
            },
            { type: 'fill', before: '', after: 'Sonne scheint.', nl: 'De zon schijnt.', options: ['Die', 'Der', 'Das'], correct: 0 },
            { type: 'wordbank', nl: 'Het weer is vandaag mooi.', target: 'Das Wetter ist heute schön', distractors: ['Regen', 'kalt', 'Die'] },
            { type: 'type', nl: 'de sneeuw', target: 'der Schnee', accept: ['Der Schnee', 'der schnee', 'Schnee'] },
            { type: 'select', prompt: 'de regen', options: ['der Regen', 'der Schnee', 'das Wetter'], correct: 0 },
            { type: 'fill', before: 'Heute', after: 'die Sonne.', nl: 'Vandaag schijnt de zon.', options: ['scheint', 'regnet', 'schneit'], correct: 0 },
          ],
        },
        {
          id: 'de-u12-l2',
          title: 'De seizoenen',
          exercises: [
            { type: 'new', word: 'der Frühling', nl: 'de lente', example: 'Im Frühling ist alles grün.', exampleNl: 'In de lente is alles groen.' },
            { type: 'new', word: 'der Sommer', nl: 'de zomer', example: 'Der Sommer ist warm.', exampleNl: 'De zomer is warm.' },
            { type: 'new', word: 'der Herbst', nl: 'de herfst', example: 'Im Herbst regnet es viel.', exampleNl: 'In de herfst regent het veel.' },
            { type: 'new', word: 'der Winter', nl: 'de winter', example: 'Der Winter in Berlin ist kalt.', exampleNl: 'De winter in Berlijn is koud.' },
            { type: 'select', prompt: 'de zomer', options: ['der Winter', 'der Sommer', 'der Herbst'], correct: 1 },
            { type: 'select', prompt: 'Im Herbst regnet es viel.', speak: 'Im Herbst regnet es viel.', options: ['In de herfst regent het veel.', 'In de lente regent het veel.', 'In de herfst sneeuwt het veel.'], correct: 0 },
            { type: 'listen', target: 'der Winter', options: ['der Winter', 'der Herbst', 'das Wetter'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'de lente', target: 'der Frühling' },
                { nl: 'de zomer', target: 'der Sommer' },
                { nl: 'de herfst', target: 'der Herbst' },
                { nl: 'de winter', target: 'der Winter' },
              ],
            },
            { type: 'fill', before: '', after: 'Winter liegt Schnee.', nl: 'In de winter ligt er sneeuw.', options: ['Im', 'Am', 'Um'], correct: 0 },
            { type: 'wordbank', nl: 'De zomer is warm en mooi.', target: 'Der Sommer ist warm und schön', distractors: ['kalt', 'Winter', 'Die'] },
            { type: 'type', nl: 'de herfst', target: 'der Herbst', accept: ['Der Herbst', 'der herbst', 'Herbst'] },
            { type: 'fill', before: 'Im Frühling', after: 'alles grün.', nl: 'In de lente is alles groen.', options: ['ist', 'sind', 'hat'], correct: 0 },
          ],
        },
        {
          id: 'de-u12-l3',
          title: 'Herhaling: het weer',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'het weer', target: 'das Wetter' },
                { nl: 'de zon', target: 'die Sonne' },
                { nl: 'de regen', target: 'der Regen' },
                { nl: 'de lente', target: 'der Frühling' },
                { nl: 'de winter', target: 'der Winter' },
              ],
            },
            { type: 'type', nl: 'De zon schijnt.', target: 'Die Sonne scheint', accept: ['die sonne scheint', 'Die Sonne scheint.'] },
            { type: 'wordbank', nl: 'In de winter is het koud.', target: 'Im Winter ist es kalt', distractors: ['Sommer', 'warm', 'die'] },
            { type: 'type', nl: 'de lente', target: 'der Frühling', accept: ['Der Frühling', 'der frühling', 'Frühling', 'Fruehling'] },
            { type: 'fill', before: 'Im Sommer trinke ich viel', after: '.', nl: 'In de zomer drink ik veel water.', options: ['Wasser', 'Brot', 'Schnee'], correct: 0 },
            { type: 'listen', target: 'Im Herbst regnet es viel.', options: ['Im Herbst regnet es viel.', 'Im Frühling regnet es viel.', 'Im Herbst schneit es viel.'], correct: 0 },
            { type: 'wordbank', nl: 'Vandaag schijnt de zon.', target: 'Heute scheint die Sonne', distractors: ['Regen', 'ist', 'der'] },
            { type: 'select', prompt: 'Der Winter ist kalt, der Sommer ist warm.', speak: 'Der Winter ist kalt, der Sommer ist warm.', options: ['De winter is koud, de zomer is warm.', 'De winter is warm, de zomer is koud.', 'De herfst is koud, de lente is warm.'], correct: 0 },
            { type: 'type', nl: 'de winter', target: 'der Winter', accept: ['Der Winter', 'der winter', 'Winter'] },
            { type: 'fill', before: '', after: 'Regen ist kalt.', nl: 'De regen is koud.', options: ['Der', 'Die', 'Das'], correct: 0 },
            { type: 'wordbank', nl: 'De sneeuw is wit en mooi.', target: 'Der Schnee ist weiß und schön', distractors: ['Die', 'Regen', 'warm'] },
            { type: 'type', nl: 'het weer', target: 'das Wetter', accept: ['Das Wetter', 'das wetter', 'Wetter'] },
          ],
        },
      ],
    },
    {
      id: 'de-u13',
      title: 'Uitgaan & cultuur',
      icon: '🎭',
      lessons: [
        {
          id: 'de-u13-l1',
          title: 'Film en muziek',
          exercises: [
            { type: 'new', word: 'das Kino', nl: 'de bioscoop', example: 'Wir gehen heute Abend ins Kino.', exampleNl: 'Wij gaan vanavond naar de bioscoop.' },
            { type: 'new', word: 'der Film', nl: 'de film', example: 'Der Film ist sehr gut.', exampleNl: 'De film is erg goed.' },
            { type: 'new', word: 'die Musik', nl: 'de muziek', example: 'Ich höre gern Musik.', exampleNl: 'Ik luister graag naar muziek.' },
            { type: 'new', word: 'das Konzert', nl: 'het concert', example: 'Das Konzert beginnt um acht Uhr.', exampleNl: 'Het concert begint om acht uur.' },
            { type: 'select', prompt: 'de bioscoop', options: ['das Konzert', 'das Kino', 'der Film'], correct: 1 },
            { type: 'select', prompt: 'Ich höre gern Musik.', speak: 'Ich höre gern Musik.', options: ['Ik luister graag naar muziek.', 'Ik maak graag muziek.', 'Ik luister graag naar de radio.'], correct: 0 },
            { type: 'listen', target: 'das Kino', options: ['das Kino', 'das Kind', 'das Konzert'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'de bioscoop', target: 'das Kino' },
                { nl: 'de film', target: 'der Film' },
                { nl: 'de muziek', target: 'die Musik' },
                { nl: 'het concert', target: 'das Konzert' },
              ],
            },
            { type: 'fill', before: 'Wir gehen', after: 'Kino.', nl: 'Wij gaan naar de bioscoop.', options: ['ins', 'zum', 'nach'], correct: 0 },
            { type: 'wordbank', nl: 'De film is erg goed.', target: 'Der Film ist sehr gut', distractors: ['Die', 'Musik', 'schön'] },
            { type: 'type', nl: 'het concert', target: 'das Konzert', accept: ['Das Konzert', 'das konzert', 'Konzert'] },
            { type: 'fill', before: 'Das Konzert beginnt', after: 'acht Uhr.', nl: 'Het concert begint om acht uur.', options: ['um', 'am', 'im'], correct: 0 },
          ],
        },
        {
          id: 'de-u13-l2',
          title: 'Samen afspreken',
          exercises: [
            { type: 'new', word: 'das Museum', nl: 'het museum', example: 'Das Museum ist heute offen.', exampleNl: 'Het museum is vandaag open.' },
            { type: 'new', word: 'das Restaurant', nl: 'het restaurant', example: 'Wir essen im Restaurant.', exampleNl: 'Wij eten in het restaurant.' },
            { type: 'new', word: 'zusammen', nl: 'samen', example: 'Wir gehen zusammen ins Kino.', exampleNl: 'Wij gaan samen naar de bioscoop.' },
            { type: 'new', word: 'heute Abend', nl: 'vanavond', example: 'Was machst du heute Abend?', exampleNl: 'Wat doe je vanavond?' },
            { type: 'select', prompt: 'samen', options: ['zusammen', 'heute Abend', 'gern'], correct: 0 },
            { type: 'select', prompt: 'Was machst du heute Abend?', speak: 'Was machst du heute Abend?', options: ['Wat doe je vanavond?', 'Wat doe je vandaag?', 'Waar ben je vanavond?'], correct: 0 },
            { type: 'listen', target: 'das Museum', options: ['das Museum', 'die Musik', 'das Restaurant'], correct: 0 },
            { type: 'fill', before: 'Wir essen', after: 'Restaurant.', nl: 'Wij eten in het restaurant.', options: ['im', 'ins', 'am'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'het museum', target: 'das Museum' },
                { nl: 'het restaurant', target: 'das Restaurant' },
                { nl: 'samen', target: 'zusammen' },
                { nl: 'vanavond', target: 'heute Abend' },
              ],
            },
            { type: 'wordbank', nl: 'Gaan we samen naar het concert?', target: 'Gehen wir zusammen ins Konzert', distractors: ['Kino', 'heute', 'im'] },
            { type: 'type', nl: 'het museum', target: 'das Museum', accept: ['Das Museum', 'das museum', 'Museum'] },
            { type: 'wordbank', nl: 'Wat doe je vanavond?', target: 'Was machst du heute Abend', distractors: ['machen', 'ich', 'morgen'] },
            { type: 'fill', before: 'Das Museum ist heute', after: '.', nl: 'Het museum is vandaag open.', options: ['offen', 'kalt', 'klein'], correct: 0 },
            { type: 'type', nl: 'vanavond', target: 'heute Abend', accept: ['Heute Abend', 'heute abend'] },
          ],
        },
        {
          id: 'de-u13-l3',
          title: 'Herhaling: uitgaan',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'de bioscoop', target: 'das Kino' },
                { nl: 'de film', target: 'der Film' },
                { nl: 'de muziek', target: 'die Musik' },
                { nl: 'het concert', target: 'das Konzert' },
                { nl: 'het museum', target: 'das Museum' },
              ],
            },
            { type: 'type', nl: 'de film', target: 'der Film', accept: ['Der Film', 'der film', 'Film'] },
            { type: 'wordbank', nl: 'Wij gaan vanavond samen naar de bioscoop.', target: 'Wir gehen heute Abend zusammen ins Kino', distractors: ['Museum', 'im', 'morgen'] },
            { type: 'type', nl: 'de muziek', target: 'die Musik', accept: ['Die Musik', 'die musik', 'Musik'] },
            { type: 'fill', before: '', after: 'Film beginnt um neun Uhr.', nl: 'De film begint om negen uur.', options: ['Der', 'Die', 'Das'], correct: 0 },
            { type: 'listen', target: 'Das Konzert beginnt um acht Uhr.', options: ['Das Konzert beginnt um acht Uhr.', 'Der Film beginnt um acht Uhr.', 'Das Konzert beginnt um sieben Uhr.'], correct: 0 },
            { type: 'select', prompt: 'Wir essen zusammen im Restaurant.', speak: 'Wir essen zusammen im Restaurant.', options: ['Wij eten samen in het restaurant.', 'Wij eten vanavond in het restaurant.', 'Wij drinken samen in het café.'], correct: 0 },
            { type: 'wordbank', nl: 'Ik luister graag naar muziek.', target: 'Ich höre gern Musik', distractors: ['esse', 'Film', 'nicht'] },
            { type: 'type', nl: 'het restaurant', target: 'das Restaurant', accept: ['Das Restaurant', 'das restaurant', 'Restaurant'] },
            { type: 'fill', before: 'Gehen wir', after: 'ins Museum?', nl: 'Gaan we samen naar het museum?', options: ['zusammen', 'offen', 'gern'], correct: 0 },
            { type: 'wordbank', nl: 'Het concert begint om acht uur.', target: 'Das Konzert beginnt um acht Uhr', distractors: ['Der', 'Film', 'im'] },
            { type: 'type', nl: 'Wij gaan naar de bioscoop.', target: 'Wir gehen ins Kino', accept: ['wir gehen ins kino', 'Wir gehen ins Kino.'] },
          ],
        },
      ],
    },
    {
      id: 'de-u14',
      title: 'De grote herhaling',
      icon: '🏆',
      lessons: [
        {
          id: 'de-u14-l1',
          title: 'Grote mix: onderweg & gezond',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'de trein', target: 'der Zug' },
                { nl: 'het vliegtuig', target: 'das Flugzeug' },
                { nl: 'de dokter', target: 'der Arzt' },
                { nl: 'de koffie', target: 'der Kaffee' },
                { nl: 'het hoofd', target: 'der Kopf' },
              ],
            },
            { type: 'select', prompt: 'Der Zug fährt um acht Uhr ab.', speak: 'Der Zug fährt um acht Uhr ab.', options: ['De trein vertrekt om acht uur.', 'De trein komt om acht uur aan.', 'De bus vertrekt om acht uur.'], correct: 0 },
            { type: 'wordbank', nl: 'Ik ben ziek en drink thee.', target: 'Ich bin krank und trinke Tee', distractors: ['esse', 'müde', 'Kaffee'] },
            { type: 'type', nl: 'Mijn buik doet pijn.', target: 'Mein Bauch tut weh', accept: ['mein bauch tut weh', 'Mein Bauch tut weh.'] },
            { type: 'fill', before: 'Wir fahren mit dem Zug', after: 'Berlin.', nl: 'Wij reizen met de trein naar Berlijn.', options: ['nach', 'zum', 'ins'], correct: 0 },
            { type: 'listen', target: 'Ich gehe zum Arzt.', options: ['Ich gehe zum Arzt.', 'Ich gehe zur Apotheke.', 'Ich fahre zum Arzt.'], correct: 0 },
            { type: 'select', prompt: 'het station', options: ['der Bahnhof', 'der Flughafen', 'die Straße'], correct: 0 },
            { type: 'wordbank', nl: 'Waar is de apotheek?', target: 'Wo ist die Apotheke', distractors: ['der', 'Arzt', 'wann'] },
            { type: 'type', nl: 'de trein', target: 'der Zug', accept: ['Der Zug', 'der zug', 'Zug'] },
            { type: 'fill', before: 'Das Kind', after: 'Fieber und ist müde.', nl: 'Het kind heeft koorts en is moe.', options: ['hat', 'ist', 'habe'], correct: 0 },
            { type: 'wordbank', nl: 'De koffer is in de trein.', target: 'Der Koffer ist im Zug', distractors: ['Kaffee', 'Bus', 'am'] },
            { type: 'select', prompt: 'moe', options: ['krank', 'müde', 'gut'], correct: 1 },
          ],
        },
        {
          id: 'de-u14-l2',
          title: 'Grote mix: weer & uitgaan',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'de zon', target: 'die Sonne' },
                { nl: 'de winter', target: 'der Winter' },
                { nl: 'de film', target: 'der Film' },
                { nl: 'het museum', target: 'das Museum' },
                { nl: 'het water', target: 'das Wasser' },
              ],
            },
            { type: 'select', prompt: 'Im Sommer gehen wir gern ins Kino.', speak: 'Im Sommer gehen wir gern ins Kino.', options: ['In de zomer gaan wij graag naar de bioscoop.', 'In de winter gaan wij graag naar de bioscoop.', 'In de zomer gaan wij graag naar het museum.'], correct: 0 },
            { type: 'wordbank', nl: 'Het regent en wij gaan naar het museum.', target: 'Es regnet und wir gehen ins Museum', distractors: ['Regen', 'Kino', 'im'] },
            { type: 'type', nl: 'de zomer', target: 'der Sommer', accept: ['Der Sommer', 'der sommer', 'Sommer'] },
            { type: 'fill', before: '', after: 'Wetter ist heute schön.', nl: 'Het weer is vandaag mooi.', options: ['Das', 'Der', 'Die'], correct: 0 },
            { type: 'listen', target: 'Die Sonne scheint und es ist warm.', options: ['Die Sonne scheint und es ist warm.', 'Die Sonne scheint und es ist kalt.', 'Es regnet und es ist warm.'], correct: 0 },
            { type: 'select', prompt: 'het brood', options: ['das Brot', 'der Apfel', 'die Milch'], correct: 0 },
            { type: 'wordbank', nl: 'Vanavond drinken wij koffie met melk.', target: 'Heute Abend trinken wir Kaffee mit Milch', distractors: ['essen', 'Tee', 'im'] },
            { type: 'type', nl: 'In de winter is het koud.', target: 'Im Winter ist es kalt', accept: ['im winter ist es kalt', 'Im Winter ist es kalt.'] },
            { type: 'fill', before: 'Das Konzert beginnt', after: 'sieben Uhr.', nl: 'Het concert begint om zeven uur.', options: ['um', 'am', 'im'], correct: 0 },
            { type: 'wordbank', nl: 'De film begint om negen uur.', target: 'Der Film beginnt um neun Uhr', distractors: ['Das', 'Konzert', 'am'] },
            { type: 'select', prompt: 'die Musik', speak: 'die Musik', options: ['de muziek', 'het museum', 'de melk'], correct: 0 },
          ],
        },
        {
          id: 'de-u14-l3',
          title: 'De finale',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'de moeder', target: 'die Mutter' },
                { nl: 'het vliegveld', target: 'der Flughafen' },
                { nl: 'de koorts', target: 'das Fieber' },
                { nl: 'de herfst', target: 'der Herbst' },
                { nl: 'de bioscoop', target: 'das Kino' },
              ],
            },
            { type: 'wordbank', nl: 'Mijn moeder gaat morgen naar de dokter.', target: 'Meine Mutter geht morgen zum Arzt', distractors: ['Mein', 'fährt', 'Apotheke'] },
            { type: 'type', nl: 'Waar is het station?', target: 'Wo ist der Bahnhof', accept: ['wo ist der bahnhof', 'Wo ist der Bahnhof?'] },
            { type: 'select', prompt: 'Meine Schwester wohnt in Wien.', speak: 'Meine Schwester wohnt in Wien.', options: ['Mijn zus woont in Wenen.', 'Mijn zus werkt in Wenen.', 'Mijn broer woont in Wenen.'], correct: 0 },
            { type: 'fill', before: 'Im Winter', after: 'Schnee.', nl: 'In de winter ligt er sneeuw.', options: ['liegt', 'legt', 'liest'], correct: 0 },
            { type: 'wordbank', nl: 'Wij eten brood en drinken thee.', target: 'Wir essen Brot und trinken Tee', distractors: ['Wasser', 'Milch', 'isst'] },
            { type: 'listen', target: 'Der Bus kommt in zehn Minuten an.', options: ['Der Bus kommt in zehn Minuten an.', 'Der Zug kommt in zehn Minuten an.', 'Der Bus fährt in zehn Minuten ab.'], correct: 0 },
            { type: 'type', nl: 'Het weer is vandaag mooi.', target: 'Das Wetter ist heute schön', accept: ['das wetter ist heute schön', 'Das Wetter ist heute schön.', 'Das Wetter ist heute schoen'] },
            { type: 'fill', before: 'Können Sie', after: 'helfen?', nl: 'Kunt u mij helpen?', options: ['mir', 'mich', 'mein'], correct: 0 },
            { type: 'wordbank', nl: 'Mijn vriend luistert graag naar muziek.', target: 'Mein Freund hört gern Musik', distractors: ['Meine', 'Film', 'isst'] },
            { type: 'select', prompt: 'goedemorgen', options: ['guten Morgen', 'guten Abend', 'gute Nacht'], correct: 0 },
            { type: 'type', nl: 'De zon schijnt en de zomer is warm.', target: 'Die Sonne scheint und der Sommer ist warm', accept: ['die sonne scheint und der sommer ist warm', 'Die Sonne scheint und der Sommer ist warm.'] },
            { type: 'wordbank', nl: 'Doei, tot morgen!', target: 'Tschüss bis morgen', distractors: ['hallo', 'danke', 'heute'] },
          ],
        },
      ],
    },
  ],
}
