import type { Course } from '../../types'

export const course: Course = {
  id: 'de',
  name: 'Duits',
  flag: '🇩🇪',
  tagline: 'De taal van onze buren',
  ttsLang: 'de-DE',
  sections: [
    {
      title: 'Sectie 1 · Eerste stappen',
      cefr: 'A1',
      units: [
        {
          id: 'de-u1',
          title: 'Begroetingen & basis',
          icon: '👋',
          lessons: [
            {
              id: 'de-u1-l1',
              title: 'Hallo zeggen',
              exercises: [
                { type: 'new', word: 'hallo', nl: 'hallo', example: 'Hallo, ich bin Anna.', exampleNl: 'Hallo, ik ben Anna.' },
                { type: 'new', word: 'guten Morgen', nl: 'goedemorgen', example: 'Guten Morgen, Herr Müller!', exampleNl: 'Goedemorgen, meneer Müller!' },
                { type: 'new', word: 'tschüss', nl: 'doei', example: 'Tschüss, bis morgen!', exampleNl: 'Doei, tot morgen!' },
                { type: 'new', word: 'danke', nl: 'dank je', example: 'Danke, das ist nett.', exampleNl: 'Dank je, dat is aardig.' },
                { type: 'select', prompt: 'hallo', options: ['tschüss', 'hallo', 'danke'], correct: 1 },
                { type: 'select', prompt: 'guten Morgen', speak: 'Guten Morgen', options: ['goedemorgen', 'goedenavond', 'welterusten'], correct: 0 },
                { type: 'listen', target: 'Tschüss!', options: ['Tschüss!', 'Danke!', 'Hallo!'], correct: 0 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'hallo', target: 'hallo' },
                    { nl: 'doei', target: 'tschüss' },
                    { nl: 'dank je', target: 'danke' },
                    { nl: 'goedemorgen', target: 'guten Morgen' },
                  ],
                },
                { type: 'wordbank', nl: 'Goedemorgen, ik ben Anna.', target: 'Guten Morgen ich bin Anna', distractors: ['danke', 'tschüss', 'du'] },
                { type: 'select', prompt: 'dank je', options: ['bitte', 'danke', 'hallo'], correct: 1 },
                { type: 'type', nl: 'doei', target: 'tschüss', accept: ['Tschüss', 'tschüss!', 'Tschüss!'] },
                { type: 'listen', target: 'Guten Morgen', options: ['Guten Morgen', 'Guten Abend', 'Gute Nacht'], correct: 0 },
              ],
            },
            {
              id: 'de-u1-l2',
              title: 'Hoe gaat het?',
              exercises: [
                { type: 'new', word: 'gut', nl: 'goed', example: "Wie geht's? – Danke, gut!", exampleNl: 'Hoe gaat het? – Dank je, goed!' },
                { type: 'new', word: 'ja', nl: 'ja', example: 'Ja, gerne!', exampleNl: 'Ja, graag!' },
                { type: 'new', word: 'nein', nl: 'nee', example: 'Nein, danke.', exampleNl: 'Nee, dank je.' },
                { type: 'new', word: 'bitte', nl: 'alsjeblieft / graag gedaan', example: 'Bitte, kein Problem!', exampleNl: 'Graag gedaan, geen probleem!' },
                { type: 'select', prompt: 'goed', options: ['gut', 'ja', 'nein'], correct: 0 },
                { type: 'select', prompt: "Wie geht's?", speak: "Wie geht's?", options: ['Hoe gaat het?', 'Hoe heet je?', 'Waar woon je?'], correct: 0 },
                { type: 'fill', before: 'Mir geht es', after: '.', nl: 'Het gaat goed met mij.', options: ['gut', 'ja', 'bitte'], correct: 0 },
                { type: 'listen', target: 'Nein, danke.', options: ['Nein, danke.', 'Ja, danke.', 'Ja, bitte.'], correct: 0 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'ja', target: 'ja' },
                    { nl: 'nee', target: 'nein' },
                    { nl: 'goed', target: 'gut' },
                    { nl: 'alsjeblieft', target: 'bitte' },
                  ],
                },
                { type: 'wordbank', nl: 'Het gaat goed met mij.', target: 'Mir geht es gut', distractors: ['nein', 'danke', 'bitte'] },
                { type: 'type', nl: 'nee', target: 'nein', accept: ['Nein', 'nein.', 'Nein.'] },
                { type: 'select', prompt: 'ja, graag', options: ['ja, gerne', 'nein, danke', 'bitte schön'], correct: 0 },
              ],
            },
            {
              id: 'de-u1-l3',
              title: 'Herhaling: begroetingen',
              exercises: [
                { type: 'select', prompt: 'Tschüss, bis morgen!', speak: 'Tschüss, bis morgen!', options: ['Doei, tot morgen!', 'Hallo, goedemorgen!', 'Dank je wel!'], correct: 0 },
                { type: 'type', nl: 'dank je', target: 'danke', accept: ['Danke', 'danke!', 'Danke!'] },
                { type: 'wordbank', nl: 'Goedemorgen, hoe gaat het?', target: "Guten Morgen wie geht's", distractors: ['danke', 'tschüss', 'gut'] },
                { type: 'fill', before: 'Guten', after: ', Herr Müller!', nl: 'Goedemorgen, meneer Müller!', options: ['Morgen', 'Abend', 'Nacht'], correct: 0 },
                { type: 'listen', target: 'Danke, gut!', options: ['Danke, gut!', 'Danke, ja!', 'Bitte, gut!'], correct: 0 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'hallo', target: 'hallo' },
                    { nl: 'doei', target: 'tschüss' },
                    { nl: 'dank je', target: 'danke' },
                    { nl: 'ja', target: 'ja' },
                    { nl: 'nee', target: 'nein' },
                  ],
                },
                { type: 'type', nl: 'goedemorgen', target: 'guten Morgen', accept: ['Guten Morgen', 'guten morgen', 'Guten Morgen!'] },
                { type: 'wordbank', nl: 'Nee dank je, doei!', target: 'Nein danke tschüss', distractors: ['ja', 'bitte', 'hallo'] },
                { type: 'select', prompt: 'graag gedaan', options: ['bitte', 'danke', 'tschüss'], correct: 0 },
                { type: 'type', nl: 'Het gaat goed met mij.', target: 'Mir geht es gut', accept: ['mir geht es gut', 'Mir geht es gut.', 'Es geht mir gut'] },
                { type: 'fill', before: 'Nein,', after: '!', nl: 'Nee, dank je!', options: ['danke', 'bitte', 'hallo'], correct: 0 },
                { type: 'wordbank', nl: 'Hallo, ik ben Anna.', target: 'Hallo ich bin Anna', distractors: ['du', 'gut', 'nein', 'danke'] },
              ],
            },
          ],
        },
        {
          id: 'de-u2',
          title: 'Eten & drinken',
          icon: '☕',
          lessons: [
            {
              id: 'de-u2-l1',
              title: 'Koffie en brood',
              exercises: [
                { type: 'new', word: 'der Kaffee', nl: 'de koffie', example: 'Der Kaffee ist heiß.', exampleNl: 'De koffie is heet.' },
                { type: 'new', word: 'das Brot', nl: 'het brood', example: 'Das Brot ist frisch.', exampleNl: 'Het brood is vers.' },
                { type: 'new', word: 'das Wasser', nl: 'het water', example: 'Ich trinke Wasser.', exampleNl: 'Ik drink water.' },
                { type: 'new', word: 'der Tee', nl: 'de thee', example: 'Der Tee ist warm.', exampleNl: 'De thee is warm.' },
                { type: 'select', prompt: 'de koffie', options: ['der Tee', 'der Kaffee', 'das Wasser'], correct: 1 },
                { type: 'select', prompt: 'das Brot', speak: 'das Brot', options: ['het brood', 'het water', 'de thee'], correct: 0 },
                { type: 'listen', target: 'der Kaffee', options: ['der Kaffee', 'der Tee', 'das Wasser'], correct: 0 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de koffie', target: 'der Kaffee' },
                    { nl: 'het brood', target: 'das Brot' },
                    { nl: 'het water', target: 'das Wasser' },
                    { nl: 'de thee', target: 'der Tee' },
                  ],
                },
                { type: 'fill', before: '', after: 'Kaffee ist heiß.', nl: 'De koffie is heet.', options: ['Der', 'Das', 'Die'], correct: 0 },
                { type: 'wordbank', nl: 'Ik drink water.', target: 'Ich trinke Wasser', distractors: ['Brot', 'esse', 'der'] },
                { type: 'type', nl: 'de thee', target: 'der Tee', accept: ['Der Tee', 'der tee', 'Tee'] },
                { type: 'select', prompt: 'het water', options: ['das Wasser', 'das Brot', 'der Kaffee'], correct: 0 },
              ],
            },
            {
              id: 'de-u2-l2',
              title: 'In het café',
              exercises: [
                { type: 'new', word: 'essen', nl: 'eten', example: 'Wir essen Brot.', exampleNl: 'Wij eten brood.' },
                { type: 'new', word: 'trinken', nl: 'drinken', example: 'Was trinkst du?', exampleNl: 'Wat drink jij?' },
                { type: 'new', word: 'der Apfel', nl: 'de appel', example: 'Der Apfel ist rot.', exampleNl: 'De appel is rood.' },
                { type: 'new', word: 'die Milch', nl: 'de melk', example: 'Die Milch ist kalt.', exampleNl: 'De melk is koud.' },
                { type: 'select', prompt: 'eten', options: ['trinken', 'essen', 'haben'], correct: 1 },
                { type: 'select', prompt: 'die Milch', speak: 'die Milch', options: ['de melk', 'de appel', 'het brood'], correct: 0 },
                { type: 'fill', before: 'Du', after: 'Tee.', nl: 'Jij drinkt thee.', options: ['trinkst', 'trinke', 'trinkt'], correct: 0 },
                { type: 'listen', target: 'Wir essen Brot.', options: ['Wir essen Brot.', 'Wir trinken Brot.', 'Wir essen Milch.'], correct: 0 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'eten', target: 'essen' },
                    { nl: 'drinken', target: 'trinken' },
                    { nl: 'de appel', target: 'der Apfel' },
                    { nl: 'de melk', target: 'die Milch' },
                  ],
                },
                { type: 'wordbank', nl: 'Wat drink jij?', target: 'Was trinkst du', distractors: ['isst', 'ich', 'Milch'] },
                { type: 'type', nl: 'de appel', target: 'der Apfel', accept: ['Der Apfel', 'der apfel', 'Apfel'] },
                { type: 'fill', before: '', after: 'Milch ist kalt.', nl: 'De melk is koud.', options: ['Die', 'Der', 'Das'], correct: 0 },
              ],
            },
            {
              id: 'de-u2-l3',
              title: 'Herhaling: eten & drinken',
              exercises: [
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de koffie', target: 'der Kaffee' },
                    { nl: 'de thee', target: 'der Tee' },
                    { nl: 'de melk', target: 'die Milch' },
                    { nl: 'het brood', target: 'das Brot' },
                    { nl: 'de appel', target: 'der Apfel' },
                  ],
                },
                { type: 'type', nl: 'drinken', target: 'trinken', accept: ['Trinken'] },
                { type: 'wordbank', nl: 'Ik drink koffie met melk.', target: 'Ich trinke Kaffee mit Milch', distractors: ['esse', 'Tee', 'das'] },
                { type: 'fill', before: 'Wir', after: 'Brot.', nl: 'Wij eten brood.', options: ['essen', 'esse', 'isst'], correct: 0 },
                { type: 'select', prompt: 'Der Apfel ist rot.', speak: 'Der Apfel ist rot.', options: ['De appel is rood.', 'De appel is groot.', 'Het brood is rood.'], correct: 0 },
                { type: 'type', nl: 'het water', target: 'das Wasser', accept: ['Das Wasser', 'das wasser', 'Wasser'] },
                { type: 'listen', target: 'Ich trinke Tee.', options: ['Ich trinke Tee.', 'Ich trinke Kaffee.', 'Ich esse Brot.'], correct: 0 },
                { type: 'wordbank', nl: 'De koffie is heet.', target: 'Der Kaffee ist heiß', distractors: ['Die', 'kalt', 'Wasser', 'trinke'] },
                { type: 'fill', before: '', after: 'Tee ist warm.', nl: 'De thee is warm.', options: ['Der', 'Die', 'Das'], correct: 0 },
                { type: 'type', nl: 'Ik drink water.', target: 'Ich trinke Wasser', accept: ['ich trinke wasser', 'Ich trinke Wasser.'] },
                { type: 'select', prompt: 'de melk', options: ['die Milch', 'der Apfel', 'das Brot'], correct: 0 },
                { type: 'wordbank', nl: 'Jij drinkt melk.', target: 'Du trinkst Milch', distractors: ['trinke', 'esse', 'Wasser'] },
              ],
            },
          ],
        },
        {
          id: 'de-u3',
          title: 'Mensen & familie',
          icon: '💛',
          lessons: [
            {
              id: 'de-u3-l1',
              title: 'Mijn familie',
              exercises: [
                { type: 'new', word: 'die Mutter', nl: 'de moeder', example: 'Meine Mutter heißt Petra.', exampleNl: 'Mijn moeder heet Petra.' },
                { type: 'new', word: 'der Vater', nl: 'de vader', example: 'Mein Vater ist groß.', exampleNl: 'Mijn vader is groot.' },
                { type: 'new', word: 'der Bruder', nl: 'de broer', example: 'Mein Bruder ist jung.', exampleNl: 'Mijn broer is jong.' },
                { type: 'new', word: 'die Schwester', nl: 'de zus', example: 'Meine Schwester wohnt in Berlin.', exampleNl: 'Mijn zus woont in Berlijn.' },
                { type: 'select', prompt: 'de moeder', options: ['der Vater', 'die Mutter', 'die Schwester'], correct: 1 },
                { type: 'select', prompt: 'der Bruder', speak: 'der Bruder', options: ['de broer', 'de zus', 'de vader'], correct: 0 },
                { type: 'listen', target: 'die Schwester', options: ['die Schwester', 'die Mutter', 'der Bruder'], correct: 0 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de moeder', target: 'die Mutter' },
                    { nl: 'de vader', target: 'der Vater' },
                    { nl: 'de broer', target: 'der Bruder' },
                    { nl: 'de zus', target: 'die Schwester' },
                  ],
                },
                { type: 'fill', before: '', after: 'Mutter heißt Petra.', nl: 'Mijn moeder heet Petra.', options: ['Meine', 'Mein', 'Meinen'], correct: 0 },
                { type: 'wordbank', nl: 'Mijn vader is groot.', target: 'Mein Vater ist groß', distractors: ['Meine', 'Bruder', 'klein'] },
                { type: 'type', nl: 'de zus', target: 'die Schwester', accept: ['Die Schwester', 'die schwester', 'Schwester'] },
                { type: 'select', prompt: 'de vader', options: ['der Vater', 'der Bruder', 'die Mutter'], correct: 0 },
              ],
            },
            {
              id: 'de-u3-l2',
              title: 'Mensen om je heen',
              exercises: [
                { type: 'new', word: 'der Mann', nl: 'de man', example: 'Der Mann trinkt Kaffee.', exampleNl: 'De man drinkt koffie.' },
                { type: 'new', word: 'die Frau', nl: 'de vrouw', example: 'Die Frau heißt Sabine.', exampleNl: 'De vrouw heet Sabine.' },
                { type: 'new', word: 'das Kind', nl: 'het kind', example: 'Das Kind ist klein.', exampleNl: 'Het kind is klein.' },
                { type: 'new', word: 'der Freund', nl: 'de vriend', example: 'Mein Freund wohnt in Köln.', exampleNl: 'Mijn vriend woont in Keulen.' },
                { type: 'select', prompt: 'de vrouw', options: ['der Mann', 'die Frau', 'das Kind'], correct: 1 },
                { type: 'select', prompt: 'Das Kind ist klein.', speak: 'Das Kind ist klein.', options: ['Het kind is klein.', 'Het kind is groot.', 'De man is klein.'], correct: 0 },
                { type: 'fill', before: 'Meine Schwester', after: 'jung.', nl: 'Mijn zus is jong.', options: ['ist', 'bin', 'sind'], correct: 0 },
                { type: 'listen', target: 'Die Frau heißt Sabine.', options: ['Die Frau heißt Sabine.', 'Der Mann heißt Stefan.', 'Die Frau heißt Petra.'], correct: 0 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de man', target: 'der Mann' },
                    { nl: 'de vrouw', target: 'die Frau' },
                    { nl: 'het kind', target: 'das Kind' },
                    { nl: 'de vriend', target: 'der Freund' },
                  ],
                },
                { type: 'wordbank', nl: 'De man drinkt koffie.', target: 'Der Mann trinkt Kaffee', distractors: ['Die', 'Frau', 'isst'] },
                { type: 'type', nl: 'het kind', target: 'das Kind', accept: ['Das Kind', 'das kind', 'Kind'] },
                { type: 'fill', before: 'Ich', after: 'einen Bruder.', nl: 'Ik heb een broer.', options: ['habe', 'hast', 'hat'], correct: 0 },
              ],
            },
            {
              id: 'de-u3-l3',
              title: 'Herhaling: familie',
              exercises: [
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de moeder', target: 'die Mutter' },
                    { nl: 'de vader', target: 'der Vater' },
                    { nl: 'de zus', target: 'die Schwester' },
                    { nl: 'de man', target: 'der Mann' },
                    { nl: 'het kind', target: 'das Kind' },
                  ],
                },
                { type: 'type', nl: 'de broer', target: 'der Bruder', accept: ['Der Bruder', 'der bruder', 'Bruder'] },
                { type: 'wordbank', nl: 'Mijn moeder heet Petra.', target: 'Meine Mutter heißt Petra', distractors: ['Mein', 'Vater', 'ist'] },
                { type: 'fill', before: 'Mein Bruder', after: 'ein Kind.', nl: 'Mijn broer heeft een kind.', options: ['hat', 'habe', 'hast'], correct: 0 },
                { type: 'select', prompt: 'Mein Freund wohnt in Köln.', speak: 'Mein Freund wohnt in Köln.', options: ['Mijn vriend woont in Keulen.', 'Mijn broer woont in Berlijn.', 'Mijn vriend werkt in Keulen.'], correct: 0 },
                { type: 'type', nl: 'de vrouw', target: 'die Frau', accept: ['Die Frau', 'die frau', 'Frau'] },
                { type: 'wordbank', nl: 'Het kind is klein.', target: 'Das Kind ist klein', distractors: ['Die', 'groß', 'Mann'] },
                { type: 'listen', target: 'Ich habe eine Schwester.', options: ['Ich habe eine Schwester.', 'Ich habe einen Bruder.', 'Ich habe eine Mutter.'], correct: 0 },
                { type: 'fill', before: '', after: 'Frau trinkt Tee.', nl: 'De vrouw drinkt thee.', options: ['Die', 'Der', 'Das'], correct: 0 },
                { type: 'type', nl: 'Mijn vader is groot.', target: 'Mein Vater ist groß', accept: ['mein vater ist groß', 'Mein Vater ist gross', 'Mein Vater ist groß.'] },
                { type: 'select', prompt: 'de vriend', options: ['der Freund', 'der Mann', 'das Kind'], correct: 0 },
                { type: 'wordbank', nl: 'Ik heb een broer en een zus.', target: 'Ich habe einen Bruder und eine Schwester', distractors: ['ein', 'Vater', 'hat'] },
              ],
            },
          ],
        },
        {
          id: 'de-u4',
          title: 'Onderweg in de stad',
          icon: '🧭',
          lessons: [
            {
              id: 'de-u4-l1',
              title: 'Waar is...?',
              exercises: [
                { type: 'new', word: 'die Stadt', nl: 'de stad', example: 'Die Stadt ist schön.', exampleNl: 'De stad is mooi.' },
                { type: 'new', word: 'der Bahnhof', nl: 'het station', example: 'Wo ist der Bahnhof?', exampleNl: 'Waar is het station?' },
                { type: 'new', word: 'die Straße', nl: 'de straat', example: 'Die Straße ist lang.', exampleNl: 'De straat is lang.' },
                { type: 'new', word: 'wo', nl: 'waar', example: 'Wo ist das Hotel?', exampleNl: 'Waar is het hotel?' },
                { type: 'select', prompt: 'de stad', options: ['die Straße', 'die Stadt', 'der Bahnhof'], correct: 1 },
                { type: 'select', prompt: 'Wo ist der Bahnhof?', speak: 'Wo ist der Bahnhof?', options: ['Waar is het station?', 'Waar is de straat?', 'Wat is het station?'], correct: 0 },
                { type: 'listen', target: 'die Straße', options: ['die Straße', 'die Stadt', 'der Bahnhof'], correct: 0 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de stad', target: 'die Stadt' },
                    { nl: 'het station', target: 'der Bahnhof' },
                    { nl: 'de straat', target: 'die Straße' },
                    { nl: 'waar', target: 'wo' },
                  ],
                },
                { type: 'fill', before: '', after: 'ist der Bahnhof?', nl: 'Waar is het station?', options: ['Wo', 'Was', 'Wie'], correct: 0 },
                { type: 'wordbank', nl: 'Waar is de straat?', target: 'Wo ist die Straße', distractors: ['der', 'Stadt', 'was'] },
                { type: 'type', nl: 'de stad', target: 'die Stadt', accept: ['Die Stadt', 'die stadt', 'Stadt'] },
                { type: 'select', prompt: 'het station', options: ['der Bahnhof', 'die Straße', 'das Hotel'], correct: 0 },
              ],
            },
            {
              id: 'de-u4-l2',
              title: 'Naar links, naar rechts',
              exercises: [
                { type: 'new', word: 'links', nl: 'links', example: 'Das Hotel ist links.', exampleNl: 'Het hotel is links.' },
                { type: 'new', word: 'rechts', nl: 'rechts', example: 'Der Bahnhof ist rechts.', exampleNl: 'Het station is rechts.' },
                { type: 'new', word: 'das Hotel', nl: 'het hotel', example: 'Das Hotel ist neu.', exampleNl: 'Het hotel is nieuw.' },
                { type: 'new', word: 'der Zug', nl: 'de trein', example: 'Der Zug fährt nach Berlin.', exampleNl: 'De trein rijdt naar Berlijn.' },
                { type: 'select', prompt: 'links', options: ['rechts', 'links', 'geradeaus'], correct: 1 },
                { type: 'select', prompt: 'Der Zug fährt nach Berlin.', speak: 'Der Zug fährt nach Berlin.', options: ['De trein rijdt naar Berlijn.', 'De trein rijdt naar Keulen.', 'De bus rijdt naar Berlijn.'], correct: 0 },
                { type: 'fill', before: 'Der Zug fährt', after: 'Berlin.', nl: 'De trein rijdt naar Berlijn.', options: ['nach', 'zu', 'in'], correct: 0 },
                { type: 'listen', target: 'Das Hotel ist links.', options: ['Das Hotel ist links.', 'Das Hotel ist rechts.', 'Der Bahnhof ist links.'], correct: 0 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'links', target: 'links' },
                    { nl: 'rechts', target: 'rechts' },
                    { nl: 'het hotel', target: 'das Hotel' },
                    { nl: 'de trein', target: 'der Zug' },
                  ],
                },
                { type: 'wordbank', nl: 'Het station is rechts.', target: 'Der Bahnhof ist rechts', distractors: ['links', 'Das', 'Straße'] },
                { type: 'type', nl: 'de trein', target: 'der Zug', accept: ['Der Zug', 'der zug', 'Zug'] },
                { type: 'fill', before: 'Wo ist', after: 'Hotel?', nl: 'Waar is het hotel?', options: ['das', 'der', 'die'], correct: 0 },
              ],
            },
            {
              id: 'de-u4-l3',
              title: 'Herhaling: de stad',
              exercises: [
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de stad', target: 'die Stadt' },
                    { nl: 'de straat', target: 'die Straße' },
                    { nl: 'het hotel', target: 'das Hotel' },
                    { nl: 'de trein', target: 'der Zug' },
                    { nl: 'het station', target: 'der Bahnhof' },
                  ],
                },
                { type: 'type', nl: 'waar', target: 'wo', accept: ['Wo', 'wo?', 'Wo?'] },
                { type: 'wordbank', nl: 'Waar is het hotel?', target: 'Wo ist das Hotel', distractors: ['der', 'links', 'Bahnhof'] },
                { type: 'fill', before: 'Die Stadt', after: 'schön.', nl: 'De stad is mooi.', options: ['ist', 'sind', 'bin'], correct: 0 },
                { type: 'select', prompt: 'Die Straße ist lang.', speak: 'Die Straße ist lang.', options: ['De straat is lang.', 'De straat is mooi.', 'De stad is lang.'], correct: 0 },
                { type: 'type', nl: 'het hotel', target: 'das Hotel', accept: ['Das Hotel', 'das hotel', 'Hotel'] },
                { type: 'listen', target: 'Der Zug fährt nach Köln.', options: ['Der Zug fährt nach Köln.', 'Der Zug fährt nach Berlin.', 'Der Zug fährt nach Wien.'], correct: 0 },
                { type: 'wordbank', nl: 'De trein rijdt naar Berlijn.', target: 'Der Zug fährt nach Berlin', distractors: ['das', 'links', 'Hotel', 'zu'] },
                { type: 'fill', before: 'Das Hotel ist', after: ', nicht rechts.', nl: 'Het hotel is links, niet rechts.', options: ['links', 'rechts', 'lang'], correct: 0 },
                { type: 'type', nl: 'Waar is het station?', target: 'Wo ist der Bahnhof', accept: ['wo ist der bahnhof', 'Wo ist der Bahnhof?'] },
                { type: 'select', prompt: 'de straat', options: ['die Straße', 'die Stadt', 'der Zug'], correct: 0 },
                { type: 'wordbank', nl: 'De stad is mooi en de straat is lang.', target: 'Die Stadt ist schön und die Straße ist lang', distractors: ['der', 'links', 'Hotel'] },
              ],
            },
          ],
        },
      ],
    },
  ],
}
