import type { Section } from '../../types'

export const section: Section = {
  title: 'Sectie 2 · Dagelijks leven',
  cefr: 'A1+',
  units: [
    {
      id: 'en-u5',
      title: 'Getallen & tijd',
      icon: '🕰️',
      lessons: [
        {
          id: 'en-u5-l1',
          title: 'Tellen tot tien',
          exercises: [
            { type: 'new', word: 'one', nl: 'één', example: 'One coffee, please.', exampleNl: 'Eén koffie, alsjeblieft.' },
            { type: 'new', word: 'two', nl: 'twee', example: 'I have two brothers.', exampleNl: 'Ik heb twee broers.' },
            { type: 'new', word: 'three', nl: 'drie', example: 'The bus leaves at three.', exampleNl: 'De bus vertrekt om drie uur.' },
            { type: 'new', word: 'four', nl: 'vier', example: 'My sister has four cats.', exampleNl: 'Mijn zus heeft vier katten.' },
            { type: 'new', word: 'ten', nl: 'tien', example: 'The train leaves at ten.', exampleNl: 'De trein vertrekt om tien uur.' },
            { type: 'select', prompt: 'twee', options: ['three', 'two', 'four'], correct: 1 },
            { type: 'select', prompt: 'three', speak: 'three', options: ['drie', 'twee', 'vier'], correct: 0 },
            { type: 'listen', target: 'I have two brothers.', options: ['I have two brothers.', 'I have two sisters.', 'I have three brothers.'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'één', target: 'one' },
                { nl: 'twee', target: 'two' },
                { nl: 'drie', target: 'three' },
                { nl: 'vier', target: 'four' },
                { nl: 'tien', target: 'ten' },
              ],
            },
            { type: 'wordbank', nl: 'Ik heb twee broers.', target: 'I have two brothers', distractors: ['three', 'sisters', 'has', 'the'] },
            { type: 'fill', before: 'My sister', after: 'four cats.', nl: 'Mijn zus heeft vier katten.', options: ['have', 'has', 'is'], correct: 1 },
            { type: 'type', nl: 'drie', target: 'three', accept: ['Three'] },
            { type: 'select', prompt: 'One coffee, please.', speak: 'One coffee, please.', options: ['Eén koffie, alsjeblieft.', 'Twee koffie, alsjeblieft.', 'Eén thee, alsjeblieft.'], correct: 0 },
          ],
        },
        {
          id: 'en-u5-l2',
          title: 'Hoe laat is het?',
          exercises: [
            { type: 'new', word: 'what time is it?', nl: 'hoe laat is het?', example: 'What time is it, Tom?', exampleNl: 'Hoe laat is het, Tom?' },
            { type: 'new', word: "o'clock", nl: 'uur', example: "It's three o'clock.", exampleNl: 'Het is drie uur.' },
            { type: 'new', word: 'half past nine', nl: 'half tien', example: 'The shop opens at half past nine.', exampleNl: 'De winkel gaat om half tien open.' },
            { type: 'new', word: 'late', nl: 'laat', example: 'The bus is late.', exampleNl: 'De bus is laat.' },
            { type: 'select', prompt: 'hoe laat is het?', options: ['How are you?', 'What time is it?', 'Where is it?'], correct: 1 },
            { type: 'select', prompt: "It's three o'clock.", speak: "It's three o'clock.", options: ['Het is drie uur.', 'Het is vier uur.', 'Het is half drie.'], correct: 0 },
            { type: 'listen', target: 'What time is it?', options: ['What time is it?', 'How are you?', 'Where is the station?'], correct: 0 },
            { type: 'fill', before: 'The shop opens', after: 'half past nine.', nl: 'De winkel gaat om half tien open.', options: ['at', 'on', 'in'], correct: 0 },
            { type: 'wordbank', nl: 'Het is drie uur.', target: "It's three o'clock", distractors: ['four', 'half', 'at', 'time'] },
            {
              type: 'match',
              pairs: [
                { nl: 'uur', target: "o'clock" },
                { nl: 'half tien', target: 'half past nine' },
                { nl: 'laat', target: 'late' },
                { nl: 'tijd', target: 'time' },
              ],
            },
            { type: 'type', nl: 'Hoe laat is het?', target: 'What time is it?', accept: ['what time is it', 'What time is it', 'what time is it?'] },
            { type: 'fill', before: 'Sorry, the bus', after: 'late.', nl: 'Sorry, de bus is laat.', options: ['are', 'is', 'am'], correct: 1 },
            { type: 'select', prompt: 'laat', options: ['late', 'early', 'left'], correct: 0 },
          ],
        },
        {
          id: 'en-u5-l3',
          title: 'Herhaling: getallen & tijd',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'één', target: 'one' },
                { nl: 'drie', target: 'three' },
                { nl: 'vier', target: 'four' },
                { nl: 'uur', target: "o'clock" },
                { nl: 'laat', target: 'late' },
              ],
            },
            { type: 'type', nl: 'twee', target: 'two', accept: ['Two'] },
            { type: 'wordbank', nl: 'Hoe laat is het, Tom?', target: 'What time is it Tom', distractors: ['how', 'where', 'late', 'clock'] },
            { type: 'listen', target: "It's half past nine.", options: ["It's half past nine.", "It's half past four.", "It's three o'clock."], correct: 0 },
            { type: 'type', nl: 'Het is vier uur.', target: "It's four o'clock", accept: ["it's four o'clock", "It is four o'clock", "It's four o'clock."] },
            { type: 'fill', before: 'The bus to London leaves', after: 'ten.', nl: 'De bus naar Londen vertrekt om tien uur.', options: ['at', 'on', 'to'], correct: 0 },
            { type: 'wordbank', nl: 'De winkel gaat om half tien open.', target: 'The shop opens at half past nine', distractors: ['ten', 'closes', 'on', 'clock'] },
            { type: 'select', prompt: 'The bus is late.', speak: 'The bus is late.', options: ['De bus is laat.', 'De bus is te vroeg.', 'De trein is laat.'], correct: 0 },
            { type: 'type', nl: 'vier', target: 'four', accept: ['Four'] },
            { type: 'wordbank', nl: 'Ik heb drie zussen.', target: 'I have three sisters', distractors: ['two', 'sister', 'has', 'my'] },
            { type: 'type', nl: 'Sorry, ik ben te laat.', target: "Sorry, I'm late", accept: ["sorry i'm late", "Sorry I'm late", 'Sorry I am late', "Sorry, I'm late."] },
            { type: 'fill', before: 'I', after: 'two sisters.', nl: 'Ik heb twee zussen.', options: ['has', 'have', 'am'], correct: 1 },
          ],
        },
      ],
    },
    {
      id: 'en-u6',
      title: 'Boodschappen & geld',
      icon: '🛍️',
      lessons: [
        {
          id: 'en-u6-l1',
          title: 'In de supermarkt',
          exercises: [
            { type: 'new', word: 'money', nl: 'geld', example: 'I have no money.', exampleNl: 'Ik heb geen geld.' },
            { type: 'new', word: 'to buy', nl: 'kopen', example: 'I buy bread and cheese.', exampleNl: 'Ik koop brood en kaas.' },
            { type: 'new', word: 'expensive', nl: 'duur', example: 'The coffee is very expensive.', exampleNl: 'De koffie is erg duur.' },
            { type: 'new', word: 'cheap', nl: 'goedkoop', example: 'The apples are cheap today.', exampleNl: 'De appels zijn vandaag goedkoop.' },
            { type: 'select', prompt: 'geld', options: ['milk', 'money', 'morning'], correct: 1 },
            { type: 'select', prompt: 'expensive', speak: 'expensive', options: ['goedkoop', 'duur', 'vers'], correct: 1 },
            { type: 'listen', target: 'I buy bread and cheese.', options: ['I buy bread and cheese.', 'I buy bread and milk.', 'I buy cheese and apples.'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'geld', target: 'money' },
                { nl: 'kopen', target: 'to buy' },
                { nl: 'duur', target: 'expensive' },
                { nl: 'goedkoop', target: 'cheap' },
              ],
            },
            { type: 'fill', before: 'The apples', after: 'cheap today.', nl: 'De appels zijn vandaag goedkoop.', options: ['is', 'are', 'am'], correct: 1 },
            { type: 'wordbank', nl: 'De koffie is erg duur.', target: 'The coffee is very expensive', distractors: ['cheap', 'tea', 'are', 'money'] },
            { type: 'type', nl: 'geld', target: 'money', accept: ['Money', 'the money'] },
            { type: 'select', prompt: 'The coffee is very expensive.', speak: 'The coffee is very expensive.', options: ['De koffie is erg goedkoop.', 'De koffie is erg duur.', 'De thee is erg duur.'], correct: 1 },
          ],
        },
        {
          id: 'en-u6-l2',
          title: 'Afrekenen',
          exercises: [
            { type: 'new', word: 'how much', nl: 'hoeveel', example: 'How much is the cheese?', exampleNl: 'Hoeveel kost de kaas?' },
            { type: 'new', word: 'pound', nl: 'pond', example: 'That is three pounds, please.', exampleNl: 'Dat is drie pond, alsjeblieft.' },
            { type: 'new', word: 'to pay', nl: 'betalen', example: 'Can I pay with my card?', exampleNl: 'Kan ik met mijn kaart betalen?' },
            { type: 'new', word: 'to cost', nl: 'kosten', example: 'The bread costs two pounds.', exampleNl: 'Het brood kost twee pond.' },
            { type: 'select', prompt: 'hoeveel', options: ['how much', 'how are you', 'where'], correct: 0 },
            { type: 'select', prompt: 'How much is the cheese?', speak: 'How much is the cheese?', options: ['Hoeveel kost de kaas?', 'Waar is de kaas?', 'Hoe vers is de kaas?'], correct: 0 },
            { type: 'listen', target: 'The bread costs two pounds.', options: ['The bread costs two pounds.', 'The bread costs three pounds.', 'The cheese costs two pounds.'], correct: 0 },
            { type: 'fill', before: 'The bread', after: 'two pounds.', nl: 'Het brood kost twee pond.', options: ['cost', 'costs', 'costing'], correct: 1 },
            { type: 'wordbank', nl: 'Hoeveel kost de koffie?', target: 'How much is the coffee', distractors: ['costs', 'where', 'pound', 'money'] },
            {
              type: 'match',
              pairs: [
                { nl: 'hoeveel', target: 'how much' },
                { nl: 'pond', target: 'pound' },
                { nl: 'betalen', target: 'to pay' },
                { nl: 'kosten', target: 'to cost' },
              ],
            },
            { type: 'type', nl: 'Hoeveel kost het brood?', target: 'How much is the bread?', accept: ['how much is the bread', 'How much is the bread', 'How much does the bread cost?', 'how much does the bread cost'] },
            { type: 'fill', before: 'Can I', after: 'with my card?', nl: 'Kan ik met mijn kaart betalen?', options: ['pay', 'pays', 'paying'], correct: 0 },
            { type: 'select', prompt: 'That is three pounds, please.', speak: 'That is three pounds, please.', options: ['Dat is drie pond, alsjeblieft.', 'Dat is vier pond, alsjeblieft.', 'Dat is drie euro, alsjeblieft.'], correct: 0 },
          ],
        },
        {
          id: 'en-u6-l3',
          title: 'Herhaling: boodschappen & geld',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'geld', target: 'money' },
                { nl: 'duur', target: 'expensive' },
                { nl: 'goedkoop', target: 'cheap' },
                { nl: 'pond', target: 'pound' },
                { nl: 'kopen', target: 'to buy' },
              ],
            },
            { type: 'type', nl: 'duur', target: 'expensive', accept: ['Expensive'] },
            { type: 'wordbank', nl: 'Ik koop brood en kaas.', target: 'I buy bread and cheese', distractors: ['pay', 'milk', 'the', 'buys'] },
            { type: 'listen', target: 'How much is the coffee?', options: ['How much is the coffee?', 'How much is the cheese?', 'Where is the coffee?'], correct: 0 },
            { type: 'type', nl: 'goedkoop', target: 'cheap', accept: ['Cheap'] },
            { type: 'wordbank', nl: 'Hoeveel kost de kaas?', target: 'How much is the cheese', distractors: ['costs', 'money', 'where', 'pounds'] },
            { type: 'fill', before: 'I would like to', after: 'apples.', nl: 'Ik wil graag appels kopen.', options: ['buy', 'pay', 'cost'], correct: 0 },
            { type: 'select', prompt: 'The apples are cheap today.', speak: 'The apples are cheap today.', options: ['De appels zijn vandaag duur.', 'De appels zijn vandaag goedkoop.', 'De appels zijn vandaag vers.'], correct: 1 },
            { type: 'type', nl: 'Het brood kost twee pond.', target: 'The bread costs two pounds', accept: ['the bread costs two pounds', 'The bread costs two pounds.'] },
            { type: 'wordbank', nl: 'Kan ik met mijn kaart betalen?', target: 'Can I pay with my card', distractors: ['money', 'buy', 'pounds', 'you'] },
            { type: 'type', nl: 'betalen', target: 'to pay', accept: ['pay', 'To pay', 'Pay'] },
            { type: 'fill', before: 'How much', after: 'the apples?', nl: 'Hoeveel kosten de appels?', options: ['is', 'are', 'am'], correct: 1 },
          ],
        },
      ],
    },
    {
      id: 'en-u7',
      title: 'Huis & wonen',
      icon: '🏠',
      lessons: [
        {
          id: 'en-u7-l1',
          title: 'Ons huis',
          exercises: [
            { type: 'new', word: 'house', nl: 'huis', example: 'Our house is in a quiet street.', exampleNl: 'Ons huis staat in een rustige straat.' },
            { type: 'new', word: 'kitchen', nl: 'keuken', example: 'The kitchen is very big.', exampleNl: 'De keuken is erg groot.' },
            { type: 'new', word: 'garden', nl: 'tuin', example: 'The children play in the garden.', exampleNl: 'De kinderen spelen in de tuin.' },
            { type: 'new', word: 'room', nl: 'kamer', example: 'My room is small.', exampleNl: 'Mijn kamer is klein.' },
            { type: 'select', prompt: 'huis', options: ['garden', 'house', 'kitchen'], correct: 1 },
            { type: 'select', prompt: 'kitchen', speak: 'kitchen', options: ['kamer', 'tuin', 'keuken'], correct: 2 },
            { type: 'listen', target: 'The kitchen is very big.', options: ['The kitchen is very big.', 'The kitchen is very small.', 'The garden is very big.'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'huis', target: 'house' },
                { nl: 'keuken', target: 'kitchen' },
                { nl: 'tuin', target: 'garden' },
                { nl: 'kamer', target: 'room' },
                { nl: 'klein', target: 'small' },
              ],
            },
            { type: 'fill', before: 'The children', after: 'in the garden.', nl: 'De kinderen spelen in de tuin.', options: ['play', 'plays', 'playing'], correct: 0 },
            { type: 'wordbank', nl: 'Mijn kamer is klein.', target: 'My room is small', distractors: ['big', 'house', 'are', 'the'] },
            { type: 'type', nl: 'keuken', target: 'kitchen', accept: ['Kitchen', 'the kitchen'] },
            { type: 'fill', before: 'Our house is', after: 'a quiet street.', nl: 'Ons huis staat in een rustige straat.', options: ['in', 'from', 'at'], correct: 0 },
          ],
        },
        {
          id: 'en-u7-l2',
          title: 'In de kamer',
          exercises: [
            { type: 'new', word: 'table', nl: 'tafel', example: 'The tea is on the table.', exampleNl: 'De thee staat op de tafel.' },
            { type: 'new', word: 'chair', nl: 'stoel', example: 'This chair is very old.', exampleNl: 'Deze stoel is erg oud.' },
            { type: 'new', word: 'bed', nl: 'bed', example: 'The cat sleeps on my bed.', exampleNl: 'De kat slaapt op mijn bed.' },
            { type: 'new', word: 'window', nl: 'raam', example: 'The window is open.', exampleNl: 'Het raam staat open.' },
            { type: 'select', prompt: 'stoel', options: ['table', 'bed', 'chair'], correct: 2 },
            { type: 'select', prompt: 'window', speak: 'window', options: ['raam', 'bed', 'tafel'], correct: 0 },
            { type: 'listen', target: 'The cat sleeps on my bed.', options: ['The cat sleeps on my bed.', 'The cat sleeps on my chair.', 'The cat plays on my bed.'], correct: 0 },
            { type: 'fill', before: 'The tea is', after: 'the table.', nl: 'De thee staat op de tafel.', options: ['on', 'in', 'at'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'tafel', target: 'table' },
                { nl: 'stoel', target: 'chair' },
                { nl: 'bed', target: 'bed' },
                { nl: 'raam', target: 'window' },
              ],
            },
            { type: 'wordbank', nl: 'Het raam staat open.', target: 'The window is open', distractors: ['door', 'opens', 'are', 'a'] },
            { type: 'type', nl: 'tafel', target: 'table', accept: ['Table', 'the table', 'a table'] },
            { type: 'fill', before: 'This chair', after: 'very old.', nl: 'Deze stoel is erg oud.', options: ['are', 'is', 'am'], correct: 1 },
          ],
        },
        {
          id: 'en-u7-l3',
          title: 'Herhaling: huis & wonen',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'huis', target: 'house' },
                { nl: 'keuken', target: 'kitchen' },
                { nl: 'tuin', target: 'garden' },
                { nl: 'tafel', target: 'table' },
                { nl: 'raam', target: 'window' },
              ],
            },
            { type: 'type', nl: 'kamer', target: 'room', accept: ['Room', 'a room'] },
            { type: 'wordbank', nl: 'De keuken is erg groot.', target: 'The kitchen is very big', distractors: ['small', 'garden', 'are', 'house'] },
            { type: 'listen', target: 'My room is small.', options: ['My room is small.', 'My house is small.', 'My room is big.'], correct: 0 },
            { type: 'type', nl: 'tuin', target: 'garden', accept: ['Garden', 'the garden'] },
            { type: 'wordbank', nl: 'De kat slaapt op mijn bed.', target: 'The cat sleeps on my bed', distractors: ['chair', 'table', 'sleep', 'in'] },
            { type: 'fill', before: 'The children play', after: 'the garden.', nl: 'De kinderen spelen in de tuin.', options: ['on', 'at', 'in'], correct: 2 },
            { type: 'select', prompt: 'This chair is very old.', speak: 'This chair is very old.', options: ['Deze stoel is erg oud.', 'Deze tafel is erg oud.', 'Deze stoel is erg klein.'], correct: 0 },
            { type: 'type', nl: 'Het raam staat open.', target: 'The window is open', accept: ['the window is open', 'The window is open.'] },
            { type: 'wordbank', nl: 'Ons huis heeft een grote tuin.', target: 'Our house has a big garden', distractors: ['small', 'kitchen', 'have', 'the'] },
            { type: 'type', nl: 'stoel', target: 'chair', accept: ['Chair', 'a chair', 'the chair'] },
            { type: 'fill', before: 'My bed is in my', after: '.', nl: 'Mijn bed staat in mijn kamer.', options: ['room', 'table', 'window'], correct: 0 },
          ],
        },
      ],
    },
    {
      id: 'en-u8',
      title: 'Werk & school',
      icon: '💼',
      lessons: [
        {
          id: 'en-u8-l1',
          title: 'Op het werk',
          exercises: [
            { type: 'new', word: 'work', nl: 'werk', example: 'My work starts at nine.', exampleNl: 'Mijn werk begint om negen uur.' },
            { type: 'new', word: 'office', nl: 'kantoor', example: 'I work in an office in the city.', exampleNl: 'Ik werk op een kantoor in de stad.' },
            { type: 'new', word: 'job', nl: 'baan', example: 'She has a new job.', exampleNl: 'Zij heeft een nieuwe baan.' },
            { type: 'new', word: 'busy', nl: 'druk', example: 'I am very busy today.', exampleNl: 'Ik ben erg druk vandaag.' },
            { type: 'select', prompt: 'kantoor', options: ['job', 'office', 'shop'], correct: 1 },
            { type: 'select', prompt: 'busy', speak: 'busy', options: ['druk', 'laat', 'duur'], correct: 0 },
            { type: 'listen', target: 'I work in an office in the city.', options: ['I work in an office in the city.', 'I work in a shop in the city.', 'I live in an office in the city.'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'werk', target: 'work' },
                { nl: 'kantoor', target: 'office' },
                { nl: 'baan', target: 'job' },
                { nl: 'druk', target: 'busy' },
              ],
            },
            { type: 'fill', before: 'I work', after: 'an office.', nl: 'Ik werk op een kantoor.', options: ['in', 'on', 'to'], correct: 0 },
            { type: 'wordbank', nl: 'Zij heeft een nieuwe baan.', target: 'She has a new job', distractors: ['work', 'have', 'old', 'the'] },
            { type: 'type', nl: 'werk', target: 'work', accept: ['Work', 'the work'] },
            { type: 'fill', before: 'My work', after: 'at nine.', nl: 'Mijn werk begint om negen uur.', options: ['start', 'starts', 'starting'], correct: 1 },
          ],
        },
        {
          id: 'en-u8-l2',
          title: 'Naar school',
          exercises: [
            { type: 'new', word: 'school', nl: 'school', example: 'The children go to school by bus.', exampleNl: 'De kinderen gaan met de bus naar school.' },
            { type: 'new', word: 'teacher', nl: 'leraar', example: 'Our teacher is very friendly.', exampleNl: 'Onze leraar is erg aardig.' },
            { type: 'new', word: 'to learn', nl: 'leren', example: 'I learn English at school.', exampleNl: 'Ik leer Engels op school.' },
            { type: 'new', word: 'book', nl: 'boek', example: 'This book is about London.', exampleNl: 'Dit boek gaat over Londen.' },
            { type: 'select', prompt: 'leraar', options: ['teacher', 'child', 'friend'], correct: 0 },
            { type: 'select', prompt: 'I learn English at school.', speak: 'I learn English at school.', options: ['Ik leer Engels op school.', 'Ik leer Engels thuis.', 'Ik geef Engels op school.'], correct: 0 },
            { type: 'listen', target: 'Our teacher is very friendly.', options: ['Our teacher is very friendly.', 'Our teacher is very busy.', 'Our teacher is very tall.'], correct: 0 },
            { type: 'fill', before: 'The children go', after: 'school by bus.', nl: 'De kinderen gaan met de bus naar school.', options: ['to', 'at', 'in'], correct: 0 },
            { type: 'wordbank', nl: 'Ik leer Engels op school.', target: 'I learn English at school', distractors: ['teacher', 'work', 'book', 'the'] },
            {
              type: 'match',
              pairs: [
                { nl: 'school', target: 'school' },
                { nl: 'leraar', target: 'teacher' },
                { nl: 'leren', target: 'to learn' },
                { nl: 'boek', target: 'book' },
              ],
            },
            { type: 'type', nl: 'boek', target: 'book', accept: ['Book', 'a book', 'the book'] },
            { type: 'fill', before: 'This book is', after: 'London.', nl: 'Dit boek gaat over Londen.', options: ['about', 'over', 'from'], correct: 0 },
            { type: 'type', nl: 'Ik leer Engels.', target: 'I learn English', accept: ['i learn english', 'I learn English.', 'I am learning English'] },
          ],
        },
        {
          id: 'en-u8-l3',
          title: 'Herhaling: werk & school',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'werk', target: 'work' },
                { nl: 'baan', target: 'job' },
                { nl: 'druk', target: 'busy' },
                { nl: 'leraar', target: 'teacher' },
                { nl: 'boek', target: 'book' },
              ],
            },
            { type: 'type', nl: 'kantoor', target: 'office', accept: ['Office', 'an office', 'the office'] },
            { type: 'wordbank', nl: 'Ik werk op een kantoor.', target: 'I work in an office', distractors: ['school', 'at', 'shop', 'the'] },
            { type: 'listen', target: 'She has a new job.', options: ['She has a new job.', 'She has a new book.', 'He has a new job.'], correct: 0 },
            { type: 'type', nl: 'druk', target: 'busy', accept: ['Busy'] },
            { type: 'wordbank', nl: 'De kinderen gaan met de bus naar school.', target: 'The children go to school by bus', distractors: ['work', 'walk', 'at', 'car'] },
            { type: 'fill', before: 'She', after: 'a new job.', nl: 'Zij heeft een nieuwe baan.', options: ['have', 'has', 'is'], correct: 1 },
            { type: 'select', prompt: 'My work starts at nine.', speak: 'My work starts at nine.', options: ['Mijn werk begint om negen uur.', 'Mijn werk stopt om negen uur.', 'Mijn school begint om negen uur.'], correct: 0 },
            { type: 'type', nl: 'leraar', target: 'teacher', accept: ['Teacher', 'the teacher', 'a teacher'] },
            { type: 'wordbank', nl: 'Onze leraar is erg aardig.', target: 'Our teacher is very friendly', distractors: ['busy', 'friend', 'are', 'my'] },
            { type: 'fill', before: 'I', after: 'English at school.', nl: 'Ik leer Engels op school.', options: ['learn', 'learns', 'learning'], correct: 0 },
            { type: 'type', nl: 'Ik ben erg druk vandaag.', target: 'I am very busy today', accept: ['i am very busy today', "I'm very busy today", 'I am very busy today.'] },
          ],
        },
      ],
    },
    {
      id: 'en-u9',
      title: 'Gesprekken voeren',
      icon: '💬',
      lessons: [
        {
          id: 'en-u9-l1',
          title: 'Vragen stellen',
          exercises: [
            { type: 'new', word: 'excuse me', nl: 'pardon', example: 'Excuse me, where is the station?', exampleNl: 'Pardon, waar is het station?' },
            { type: 'new', word: 'to understand', nl: 'begrijpen', example: "Sorry, I don't understand.", exampleNl: 'Sorry, ik begrijp het niet.' },
            { type: 'new', word: 'to speak', nl: 'spreken', example: 'Do you speak English?', exampleNl: 'Spreek je Engels?' },
            { type: 'new', word: 'again', nl: 'opnieuw', example: 'Can you say that again, please?', exampleNl: 'Kun je dat opnieuw zeggen, alsjeblieft?' },
            { type: 'select', prompt: 'pardon', options: ['please', 'excuse me', 'goodbye'], correct: 1 },
            { type: 'select', prompt: 'Do you speak English?', speak: 'Do you speak English?', options: ['Spreek je Engels?', 'Begrijp je Engels?', 'Leer je Engels?'], correct: 0 },
            { type: 'listen', target: "Sorry, I don't understand.", options: ["Sorry, I don't understand.", "Sorry, I don't know.", "Sorry, I'm late."], correct: 0 },
            { type: 'fill', before: 'Do you', after: 'English?', nl: 'Spreek je Engels?', options: ['speak', 'speaks', 'speaking'], correct: 0 },
            { type: 'wordbank', nl: 'Pardon, waar is het station?', target: 'Excuse me where is the station', distractors: ['sorry', 'what', 'shop', 'a'] },
            {
              type: 'match',
              pairs: [
                { nl: 'pardon', target: 'excuse me' },
                { nl: 'begrijpen', target: 'to understand' },
                { nl: 'spreken', target: 'to speak' },
                { nl: 'opnieuw', target: 'again' },
              ],
            },
            { type: 'type', nl: 'Spreek je Engels?', target: 'Do you speak English?', accept: ['do you speak english', 'Do you speak English', 'do you speak English?'] },
            { type: 'fill', before: "I don't", after: 'the teacher.', nl: 'Ik begrijp de leraar niet.', options: ['understand', 'understands', 'understanding'], correct: 0 },
          ],
        },
        {
          id: 'en-u9-l2',
          title: 'Een praatje maken',
          exercises: [
            { type: 'new', word: 'of course', nl: 'natuurlijk', example: 'Of course, no problem.', exampleNl: 'Natuurlijk, geen probleem.' },
            { type: 'new', word: 'maybe', nl: 'misschien', example: 'Maybe tomorrow, I am busy today.', exampleNl: 'Misschien morgen, ik ben vandaag druk.' },
            { type: 'new', word: 'I think', nl: 'ik denk', example: 'I think the coffee here is very good.', exampleNl: 'Ik denk dat de koffie hier erg goed is.' },
            { type: 'new', word: 'see you later', nl: 'tot straks', example: 'See you later, Tom!', exampleNl: 'Tot straks, Tom!' },
            { type: 'select', prompt: 'misschien', options: ['of course', 'maybe', 'again'], correct: 1 },
            { type: 'select', prompt: 'Of course, no problem.', speak: 'Of course, no problem.', options: ['Natuurlijk, geen probleem.', 'Misschien, geen probleem.', 'Natuurlijk, een groot probleem.'], correct: 0 },
            { type: 'listen', target: 'See you later, Tom!', options: ['See you later, Tom!', 'See you tomorrow, Tom!', 'Thank you, Tom!'], correct: 0 },
            { type: 'fill', before: 'I', after: 'the tea is very good.', nl: 'Ik denk dat de thee erg goed is.', options: ['think', 'thinks', 'thinking'], correct: 0 },
            { type: 'wordbank', nl: 'Misschien morgen, ik ben vandaag druk.', target: 'Maybe tomorrow I am busy today', distractors: ['think', 'later', 'work', 'very'] },
            {
              type: 'match',
              pairs: [
                { nl: 'natuurlijk', target: 'of course' },
                { nl: 'misschien', target: 'maybe' },
                { nl: 'ik denk', target: 'I think' },
                { nl: 'tot straks', target: 'see you later' },
              ],
            },
            { type: 'type', nl: 'tot straks', target: 'see you later', accept: ['See you later', 'see you later!', 'See you later!'] },
            { type: 'select', prompt: 'natuurlijk', options: ['maybe', 'of course', 'no problem'], correct: 1 },
            { type: 'fill', before: 'Maybe the shop', after: 'open.', nl: 'Misschien is de winkel open.', options: ['is', 'are', 'am'], correct: 0 },
          ],
        },
        {
          id: 'en-u9-l3',
          title: 'Herhaling: gesprekken',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'pardon', target: 'excuse me' },
                { nl: 'misschien', target: 'maybe' },
                { nl: 'natuurlijk', target: 'of course' },
                { nl: 'spreken', target: 'to speak' },
                { nl: 'tot straks', target: 'see you later' },
              ],
            },
            { type: 'wordbank', nl: 'Pardon, hoe laat is het?', target: 'Excuse me what time is it', distractors: ['how', 'where', 'late', 'you'] },
            { type: 'type', nl: 'Ik begrijp het niet.', target: "I don't understand", accept: ["i don't understand", 'I do not understand', "I don't understand."] },
            { type: 'listen', target: 'Do you speak English?', options: ['Do you speak English?', 'Do you learn English?', 'Do you understand English?'], correct: 0 },
            { type: 'wordbank', nl: 'Ik denk dat de koffie erg goed is.', target: 'I think the coffee is very good', distractors: ['tea', 'cheap', 'maybe', 'are'] },
            { type: 'fill', before: 'Excuse me,', after: 'much is the cheese?', nl: 'Pardon, hoeveel kost de kaas?', options: ['how', 'what', 'where'], correct: 0 },
            { type: 'type', nl: 'misschien', target: 'maybe', accept: ['Maybe'] },
            { type: 'select', prompt: 'Can you say that again, please?', speak: 'Can you say that again, please?', options: ['Kun je dat opnieuw zeggen, alsjeblieft?', 'Kun je dat opschrijven, alsjeblieft?', 'Kun je dat morgen zeggen, alsjeblieft?'], correct: 0 },
            { type: 'wordbank', nl: 'Natuurlijk, ik betaal met mijn kaart.', target: 'Of course I pay with my card', distractors: ['buy', 'money', 'maybe', 'you'] },
            { type: 'type', nl: 'Natuurlijk, geen probleem.', target: 'Of course, no problem', accept: ['of course no problem', 'Of course no problem', 'Of course, no problem.'] },
            { type: 'fill', before: 'Maybe my teacher', after: 'at school.', nl: 'Misschien is mijn leraar op school.', options: ['is', 'are', 'am'], correct: 0 },
            { type: 'type', nl: 'Pardon, waar is het station?', target: 'Excuse me, where is the station?', accept: ['excuse me where is the station', 'Excuse me where is the station?', 'Excuse me, where is the station'] },
            { type: 'wordbank', nl: 'Tot straks, ik ga naar mijn werk.', target: 'See you later I am going to work', distractors: ['my', 'school', 'busy', 'office'] },
          ],
        },
      ],
    },
  ],
}
