import type { Section } from '../../types'

export const section: Section = {
  title: 'Sectie 3 · Op weg naar A2',
  cefr: 'A2',
  units: [
    {
      id: 'en-u10',
      title: 'Reizen & vervoer',
      icon: '✈️',
      lessons: [
        {
          id: 'en-u10-l1',
          title: 'Op het station',
          exercises: [
            { type: 'new', word: 'train', nl: 'trein', example: 'The train to Manchester leaves at ten.', exampleNl: 'De trein naar Manchester vertrekt om tien uur.' },
            { type: 'new', word: 'ticket', nl: 'kaartje', example: 'A ticket to York, please.', exampleNl: 'Een kaartje naar York, alsjeblieft.' },
            { type: 'new', word: 'platform', nl: 'perron', example: 'The train leaves from platform two.', exampleNl: 'De trein vertrekt van perron twee.' },
            { type: 'new', word: 'to travel', nl: 'reizen', example: 'I travel to work by bus.', exampleNl: 'Ik reis met de bus naar mijn werk.' },
            { type: 'select', prompt: 'trein', options: ['bus', 'train', 'ticket'], correct: 1 },
            { type: 'select', prompt: 'ticket', speak: 'ticket', options: ['trein', 'kaartje', 'perron'], correct: 1 },
            { type: 'listen', target: 'The train leaves from platform two.', options: ['The train leaves from platform two.', 'The bus leaves from platform two.', 'The train leaves at platform ten.'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'trein', target: 'train' },
                { nl: 'kaartje', target: 'ticket' },
                { nl: 'perron', target: 'platform' },
                { nl: 'reizen', target: 'to travel' },
              ],
            },
            { type: 'fill', before: 'The train', after: 'at ten.', nl: 'De trein vertrekt om tien uur.', options: ['leave', 'leaves', 'leaving'], correct: 1 },
            { type: 'wordbank', nl: 'Een kaartje naar Londen, alsjeblieft.', target: 'A ticket to London please', distractors: ['train', 'from', 'the', 'bus'] },
            { type: 'type', nl: 'trein', target: 'train', accept: ['Train', 'the train', 'a train'] },
            { type: 'fill', before: 'I travel to work', after: 'bus.', nl: 'Ik reis met de bus naar mijn werk.', options: ['by', 'with', 'on'], correct: 0 },
          ],
        },
        {
          id: 'en-u10-l2',
          title: 'Op vakantie',
          exercises: [
            { type: 'new', word: 'holiday', nl: 'vakantie', example: 'We are on holiday in Scotland.', exampleNl: 'We zijn op vakantie in Schotland.' },
            { type: 'new', word: 'suitcase', nl: 'koffer', example: 'My suitcase is very heavy.', exampleNl: 'Mijn koffer is erg zwaar.' },
            { type: 'new', word: 'hotel', nl: 'hotel', example: 'The hotel is near the station.', exampleNl: 'Het hotel is vlak bij het station.' },
            { type: 'new', word: 'to arrive', nl: 'aankomen', example: 'The train arrives at six.', exampleNl: 'De trein komt om zes uur aan.' },
            { type: 'select', prompt: 'vakantie', options: ['suitcase', 'holiday', 'hotel'], correct: 1 },
            { type: 'select', prompt: 'suitcase', speak: 'suitcase', options: ['koffer', 'kaartje', 'vakantie'], correct: 0 },
            { type: 'listen', target: 'The hotel is near the station.', options: ['The hotel is near the station.', 'The hotel is in the station.', 'The shop is near the station.'], correct: 0 },
            { type: 'fill', before: 'We are', after: 'holiday in Scotland.', nl: 'We zijn op vakantie in Schotland.', options: ['on', 'in', 'at'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'vakantie', target: 'holiday' },
                { nl: 'koffer', target: 'suitcase' },
                { nl: 'aankomen', target: 'to arrive' },
                { nl: 'zwaar', target: 'heavy' },
              ],
            },
            { type: 'wordbank', nl: 'Mijn koffer is erg zwaar.', target: 'My suitcase is very heavy', distractors: ['ticket', 'light', 'the', 'has'] },
            { type: 'type', nl: 'vakantie', target: 'holiday', accept: ['Holiday', 'a holiday', 'holidays'] },
            { type: 'fill', before: 'The train', after: 'at six.', nl: 'De trein komt om zes uur aan.', options: ['arrive', 'arrives', 'arriving'], correct: 1 },
          ],
        },
        {
          id: 'en-u10-l3',
          title: 'Herhaling: reizen & vervoer',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'trein', target: 'train' },
                { nl: 'kaartje', target: 'ticket' },
                { nl: 'vakantie', target: 'holiday' },
                { nl: 'koffer', target: 'suitcase' },
                { nl: 'perron', target: 'platform' },
              ],
            },
            { type: 'type', nl: 'kaartje', target: 'ticket', accept: ['Ticket', 'a ticket'] },
            { type: 'wordbank', nl: 'De trein naar Manchester vertrekt om tien uur.', target: 'The train to Manchester leaves at ten', distractors: ['bus', 'arrives', 'from', 'a'] },
            { type: 'listen', target: 'A ticket to York, please.', options: ['A ticket to York, please.', 'A ticket to Leeds, please.', 'Two tickets to York, please.'], correct: 0 },
            { type: 'type', nl: 'Wij zijn op vakantie.', target: 'We are on holiday', accept: ['we are on holiday', 'We are on holiday.', "We're on holiday"] },
            { type: 'fill', before: 'The hotel is', after: 'the station.', nl: 'Het hotel is vlak bij het station.', options: ['near', 'far', 'under'], correct: 0 },
            { type: 'wordbank', nl: 'Waar is mijn koffer?', target: 'Where is my suitcase', distractors: ['ticket', 'the', 'are', 'hotel'] },
            { type: 'type', nl: 'De trein komt om zes uur aan.', target: 'The train arrives at six', accept: ['the train arrives at six', 'The train arrives at six.', "The train arrives at six o'clock"] },
            { type: 'select', prompt: 'I travel to work by bus.', speak: 'I travel to work by bus.', options: ['Ik reis met de trein naar mijn werk.', 'Ik reis met de bus naar mijn werk.', 'Ik loop naar mijn werk.'], correct: 1 },
            { type: 'fill', before: 'The train leaves', after: 'platform two.', nl: 'De trein vertrekt van perron twee.', options: ['from', 'of', 'to'], correct: 0 },
            { type: 'type', nl: 'koffer', target: 'suitcase', accept: ['Suitcase', 'a suitcase', 'my suitcase'] },
            { type: 'wordbank', nl: 'Het hotel is vlak bij het station.', target: 'The hotel is near the station', distractors: ['far', 'holiday', 'a', 'to'] },
          ],
        },
      ],
    },
    {
      id: 'en-u11',
      title: 'Gezondheid & lichaam',
      icon: '🌿',
      lessons: [
        {
          id: 'en-u11-l1',
          title: 'Ik voel me niet lekker',
          exercises: [
            { type: 'new', word: 'head', nl: 'hoofd', example: 'My head hurts.', exampleNl: 'Mijn hoofd doet pijn.' },
            { type: 'new', word: 'ill', nl: 'ziek', example: 'Emma is ill, she is at home.', exampleNl: 'Emma is ziek, ze is thuis.' },
            { type: 'new', word: 'doctor', nl: 'dokter', example: 'I would like to see a doctor.', exampleNl: 'Ik wil graag een dokter zien.' },
            { type: 'new', word: 'to hurt', nl: 'pijn doen', example: 'My head hurts a lot.', exampleNl: 'Mijn hoofd doet erg pijn.' },
            { type: 'select', prompt: 'ziek', options: ['fine', 'ill', 'late'], correct: 1 },
            { type: 'select', prompt: 'doctor', speak: 'doctor', options: ['dokter', 'ziekenhuis', 'hoofd'], correct: 0 },
            { type: 'listen', target: 'My head hurts.', options: ['My head hurts.', 'My hand hurts.', 'My head is hot.'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'hoofd', target: 'head' },
                { nl: 'ziek', target: 'ill' },
                { nl: 'dokter', target: 'doctor' },
                { nl: 'pijn doen', target: 'to hurt' },
              ],
            },
            { type: 'fill', before: 'Emma is ill, she is', after: 'home.', nl: 'Emma is ziek, ze is thuis.', options: ['at', 'in', 'on'], correct: 0 },
            { type: 'wordbank', nl: 'Ik wil graag een dokter zien.', target: 'I would like to see a doctor', distractors: ['the', 'ill', 'am', 'head'] },
            { type: 'type', nl: 'ziek', target: 'ill', accept: ['Ill', 'sick', 'Sick'] },
            { type: 'fill', before: 'My head', after: 'a lot.', nl: 'Mijn hoofd doet erg pijn.', options: ['hurt', 'hurts', 'hurting'], correct: 1 },
          ],
        },
        {
          id: 'en-u11-l2',
          title: 'Beter worden',
          exercises: [
            { type: 'new', word: 'hand', nl: 'hand', example: 'My hand hurts.', exampleNl: 'Mijn hand doet pijn.' },
            { type: 'new', word: 'tired', nl: 'moe', example: 'I am very tired today.', exampleNl: 'Ik ben erg moe vandaag.' },
            { type: 'new', word: 'medicine', nl: 'medicijn', example: 'Take this medicine with water.', exampleNl: 'Neem dit medicijn met water.' },
            { type: 'new', word: 'better', nl: 'beter', example: 'I am much better now.', exampleNl: 'Ik ben nu veel beter.' },
            { type: 'select', prompt: 'moe', options: ['ill', 'tired', 'better'], correct: 1 },
            { type: 'select', prompt: 'better', speak: 'better', options: ['moe', 'ziek', 'beter'], correct: 2 },
            { type: 'select', prompt: 'Mijn hand doet pijn.', options: ['My hand hurts.', 'My head hurts.', 'My hand is cold.'], correct: 0 },
            { type: 'listen', target: 'I am very tired today.', options: ['I am very tired today.', 'I am very ill today.', 'I am much better today.'], correct: 0 },
            { type: 'fill', before: 'Take this medicine', after: 'water.', nl: 'Neem dit medicijn met water.', options: ['with', 'of', 'by'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'moe', target: 'tired' },
                { nl: 'medicijn', target: 'medicine' },
                { nl: 'beter', target: 'better' },
                { nl: 'neem', target: 'take' },
              ],
            },
            { type: 'wordbank', nl: 'Ik ben nu veel beter.', target: 'I am much better now', distractors: ['tired', 'more', 'the', 'ill'] },
            { type: 'type', nl: 'moe', target: 'tired', accept: ['Tired'] },
            { type: 'type', nl: 'Ik ben erg moe.', target: 'I am very tired', accept: ['i am very tired', 'I am very tired.', "I'm very tired"] },
            { type: 'fill', before: 'She', after: 'much better now.', nl: 'Ze is nu veel beter.', options: ['am', 'is', 'are'], correct: 1 },
          ],
        },
        {
          id: 'en-u11-l3',
          title: 'Herhaling: gezondheid',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'hoofd', target: 'head' },
                { nl: 'ziek', target: 'ill' },
                { nl: 'dokter', target: 'doctor' },
                { nl: 'moe', target: 'tired' },
                { nl: 'medicijn', target: 'medicine' },
              ],
            },
            { type: 'type', nl: 'hoofd', target: 'head', accept: ['Head', 'my head'] },
            { type: 'wordbank', nl: 'Mijn hoofd doet erg pijn.', target: 'My head hurts a lot', distractors: ['hand', 'is', 'the', 'ill'] },
            { type: 'listen', target: 'I would like to see a doctor.', options: ['I would like to see a doctor.', 'I would like to see the city.', 'I would like a glass of water.'], correct: 0 },
            { type: 'type', nl: 'Ik ben ziek.', target: 'I am ill', accept: ['i am ill', 'I am ill.', "I'm ill", 'I am sick'] },
            { type: 'fill', before: 'My hands', after: 'cold.', nl: 'Mijn handen zijn koud.', options: ['is', 'are', 'am'], correct: 1 },
            { type: 'wordbank', nl: 'Neem dit medicijn met water.', target: 'Take this medicine with water', distractors: ['tea', 'my', 'better', 'hurts'] },
            { type: 'type', nl: 'dokter', target: 'doctor', accept: ['Doctor', 'a doctor', 'the doctor'] },
            { type: 'select', prompt: 'Emma is ill, she is at home.', speak: 'Emma is ill, she is at home.', options: ['Emma is moe, ze is thuis.', 'Emma is ziek, ze is thuis.', 'Emma is ziek, ze is bij de dokter.'], correct: 1 },
            { type: 'type', nl: 'Ik ben erg moe vandaag.', target: 'I am very tired today', accept: ['i am very tired today', 'I am very tired today.', "I'm very tired today"] },
            { type: 'wordbank', nl: 'Mijn broer is nu veel beter.', target: 'My brother is much better now', distractors: ['sister', 'tired', 'more', 'am'] },
            { type: 'fill', before: 'She', after: 'to see a doctor.', nl: 'Ze wil graag een dokter zien.', options: ['would like', 'would likes', 'like'], correct: 0 },
          ],
        },
      ],
    },
    {
      id: 'en-u12',
      title: 'Weer & seizoenen',
      icon: '🌦️',
      lessons: [
        {
          id: 'en-u12-l1',
          title: 'Wat voor weer is het?',
          exercises: [
            { type: 'new', word: 'rain', nl: 'regen', example: 'It often rains in England.', exampleNl: 'Het regent vaak in Engeland.' },
            { type: 'new', word: 'sun', nl: 'zon', example: 'The sun is shining today.', exampleNl: 'De zon schijnt vandaag.' },
            { type: 'new', word: 'cold', nl: 'koud', example: 'It is cold outside.', exampleNl: 'Het is koud buiten.' },
            { type: 'new', word: 'warm', nl: 'warm', example: 'The water is warm.', exampleNl: 'Het water is warm.' },
            { type: 'select', prompt: 'regen', options: ['sun', 'rain', 'water'], correct: 1 },
            { type: 'select', prompt: 'cold', speak: 'cold', options: ['warm', 'koud', 'zon'], correct: 1 },
            { type: 'listen', target: 'It is cold outside.', options: ['It is cold outside.', 'It is warm outside.', 'It is cold at home.'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'regen', target: 'rain' },
                { nl: 'zon', target: 'sun' },
                { nl: 'koud', target: 'cold' },
                { nl: 'buiten', target: 'outside' },
              ],
            },
            { type: 'fill', before: 'It often', after: 'in England.', nl: 'Het regent vaak in Engeland.', options: ['rain', 'rains', 'raining'], correct: 1 },
            { type: 'wordbank', nl: 'Het is koud buiten.', target: 'It is cold outside', distractors: ['warm', 'the', 'sun', 'at'] },
            { type: 'type', nl: 'zon', target: 'sun', accept: ['Sun', 'the sun'] },
            { type: 'fill', before: 'The sun', after: 'today.', nl: 'De zon schijnt vandaag.', options: ['is shining', 'shining', 'are shining'], correct: 0 },
          ],
        },
        {
          id: 'en-u12-l2',
          title: 'De vier seizoenen',
          exercises: [
            { type: 'new', word: 'summer', nl: 'zomer', example: 'In summer we eat outside.', exampleNl: 'In de zomer eten we buiten.' },
            { type: 'new', word: 'winter', nl: 'winter', example: 'Winter in Scotland is very cold.', exampleNl: 'De winter in Schotland is erg koud.' },
            { type: 'new', word: 'spring', nl: 'lente', example: 'In spring the parks are green.', exampleNl: 'In de lente zijn de parken groen.' },
            { type: 'new', word: 'autumn', nl: 'herfst', example: 'It often rains in autumn.', exampleNl: 'Het regent vaak in de herfst.' },
            { type: 'select', prompt: 'zomer', options: ['winter', 'summer', 'spring'], correct: 1 },
            { type: 'select', prompt: 'autumn', speak: 'autumn', options: ['herfst', 'lente', 'winter'], correct: 0 },
            { type: 'listen', target: 'Winter in Scotland is very cold.', options: ['Winter in Scotland is very cold.', 'Summer in Scotland is very warm.', 'Winter in England is very cold.'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'zomer', target: 'summer' },
                { nl: 'lente', target: 'spring' },
                { nl: 'herfst', target: 'autumn' },
                { nl: 'seizoen', target: 'season' },
              ],
            },
            { type: 'fill', before: 'It often rains', after: 'autumn.', nl: 'Het regent vaak in de herfst.', options: ['in', 'on', 'at'], correct: 0 },
            { type: 'wordbank', nl: 'In de zomer eten we buiten.', target: 'In summer we eat outside', distractors: ['winter', 'the', 'cold', 'rains'] },
            { type: 'type', nl: 'winter', target: 'winter', accept: ['Winter', 'the winter'] },
            { type: 'type', nl: 'lente', target: 'spring', accept: ['Spring', 'the spring'] },
            { type: 'fill', before: 'In spring the parks', after: 'green.', nl: 'In de lente zijn de parken groen.', options: ['is', 'are', 'am'], correct: 1 },
          ],
        },
        {
          id: 'en-u12-l3',
          title: 'Herhaling: weer & seizoenen',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'regen', target: 'rain' },
                { nl: 'zon', target: 'sun' },
                { nl: 'zomer', target: 'summer' },
                { nl: 'herfst', target: 'autumn' },
                { nl: 'lente', target: 'spring' },
              ],
            },
            { type: 'type', nl: 'koud', target: 'cold', accept: ['Cold'] },
            { type: 'wordbank', nl: 'Het regent vaak in Engeland.', target: 'It often rains in England', distractors: ['sun', 'rain', 'the', 'cold'] },
            { type: 'listen', target: 'The sun is shining today.', options: ['The sun is shining today.', 'The sun is shining in spring.', 'It is raining today.'], correct: 0 },
            { type: 'type', nl: 'Het is warm vandaag.', target: 'It is warm today', accept: ['it is warm today', 'It is warm today.', "It's warm today"] },
            { type: 'fill', before: 'Winter in Scotland', after: 'very cold.', nl: 'De winter in Schotland is erg koud.', options: ['are', 'is', 'am'], correct: 1 },
            { type: 'wordbank', nl: 'De winter is koud en de zomer is warm.', target: 'Winter is cold and summer is warm', distractors: ['spring', 'the', 'rains', 'hot'] },
            { type: 'type', nl: 'herfst', target: 'autumn', accept: ['Autumn', 'the autumn'] },
            { type: 'select', prompt: 'In summer we eat outside.', speak: 'In summer we eat outside.', options: ['In de winter eten we buiten.', 'In de zomer eten we buiten.', 'In de zomer eten we thuis.'], correct: 1 },
            { type: 'type', nl: 'Het is koud buiten.', target: 'It is cold outside', accept: ['it is cold outside', 'It is cold outside.', "It's cold outside"] },
            { type: 'fill', before: 'It is warm', after: 'summer.', nl: 'Het is warm in de zomer.', options: ['in', 'on', 'at'], correct: 0 },
            { type: 'wordbank', nl: 'De zon schijnt en het is warm.', target: 'The sun is shining and it is warm', distractors: ['rain', 'cold', 'winter', 'are'] },
          ],
        },
      ],
    },
    {
      id: 'en-u13',
      title: 'Uitgaan & cultuur',
      icon: '🎭',
      lessons: [
        {
          id: 'en-u13-l1',
          title: 'Naar de bioscoop',
          exercises: [
            { type: 'new', word: 'film', nl: 'film', example: 'The film starts at eight.', exampleNl: 'De film begint om acht uur.' },
            { type: 'new', word: 'cinema', nl: 'bioscoop', example: 'The cinema is in the city centre.', exampleNl: 'De bioscoop is in het stadscentrum.' },
            { type: 'new', word: 'music', nl: 'muziek', example: 'I listen to music at home.', exampleNl: 'Ik luister thuis naar muziek.' },
            { type: 'new', word: 'to dance', nl: 'dansen', example: 'She dances very well.', exampleNl: 'Ze danst erg goed.' },
            { type: 'select', prompt: 'bioscoop', options: ['film', 'cinema', 'music'], correct: 1 },
            { type: 'select', prompt: 'music', speak: 'music', options: ['film', 'dansen', 'muziek'], correct: 2 },
            { type: 'listen', target: 'The film starts at eight.', options: ['The film starts at eight.', 'The film starts at ten.', 'The shop opens at eight.'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'bioscoop', target: 'cinema' },
                { nl: 'muziek', target: 'music' },
                { nl: 'dansen', target: 'to dance' },
                { nl: 'beginnen', target: 'to start' },
              ],
            },
            { type: 'fill', before: 'The film', after: 'at eight.', nl: 'De film begint om acht uur.', options: ['start', 'starts', 'starting'], correct: 1 },
            { type: 'wordbank', nl: 'De bioscoop is in het stadscentrum.', target: 'The cinema is in the city centre', distractors: ['film', 'at', 'a', 'station'] },
            { type: 'type', nl: 'muziek', target: 'music', accept: ['Music', 'the music'] },
            { type: 'fill', before: 'I listen', after: 'music at home.', nl: 'Ik luister thuis naar muziek.', options: ['to', 'at', 'for'], correct: 0 },
          ],
        },
        {
          id: 'en-u13-l2',
          title: 'Een dagje uit',
          exercises: [
            { type: 'new', word: 'to visit', nl: 'bezoeken', example: 'We visit my sister in London.', exampleNl: 'We bezoeken mijn zus in Londen.' },
            { type: 'new', word: 'museum', nl: 'museum', example: 'The museum is very old.', exampleNl: 'Het museum is erg oud.' },
            { type: 'new', word: 'theatre', nl: 'theater', example: 'The theatre opens at seven.', exampleNl: 'Het theater gaat om zeven uur open.' },
            { type: 'new', word: 'weekend', nl: 'weekend', example: 'See you at the weekend!', exampleNl: 'Tot in het weekend!' },
            { type: 'select', prompt: 'theater', options: ['theatre', 'museum', 'cinema'], correct: 0 },
            { type: 'select', prompt: 'We visit my sister in London.', speak: 'We visit my sister in London.', options: ['We bezoeken mijn zus in Londen.', 'We bezoeken mijn broer in Londen.', 'Mijn zus woont in Londen.'], correct: 0 },
            { type: 'listen', target: 'The theatre opens at seven.', options: ['The theatre opens at seven.', 'The museum opens at seven.', 'The theatre opens at eleven.'], correct: 0 },
            { type: 'fill', before: 'See you', after: 'the weekend!', nl: 'Tot in het weekend!', options: ['at', 'in', 'on'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'bezoeken', target: 'to visit' },
                { nl: 'oud', target: 'old' },
                { nl: 'theater', target: 'theatre' },
                { nl: 'stadscentrum', target: 'city centre' },
              ],
            },
            { type: 'wordbank', nl: 'We bezoeken het museum vandaag.', target: 'We visit the museum today', distractors: ['theatre', 'weekend', 'a', 'visits'] },
            { type: 'type', nl: 'weekend', target: 'weekend', accept: ['Weekend', 'the weekend'] },
            { type: 'fill', before: 'My friends', after: 'London in summer.', nl: 'Mijn vrienden bezoeken Londen in de zomer.', options: ['visits', 'visit', 'visiting'], correct: 1 },
            { type: 'type', nl: 'We bezoeken het theater.', target: 'We visit the theatre', accept: ['we visit the theatre', 'We visit the theatre.', 'We visit the theater'] },
          ],
        },
        {
          id: 'en-u13-l3',
          title: 'Herhaling: uitgaan & cultuur',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'bioscoop', target: 'cinema' },
                { nl: 'muziek', target: 'music' },
                { nl: 'dansen', target: 'to dance' },
                { nl: 'bezoeken', target: 'to visit' },
                { nl: 'theater', target: 'theatre' },
              ],
            },
            { type: 'type', nl: 'film', target: 'film', accept: ['Film', 'a film', 'movie'] },
            { type: 'wordbank', nl: 'De film begint om acht uur.', target: 'The film starts at eight', distractors: ['cinema', 'opens', 'a', 'ten'] },
            { type: 'listen', target: 'I listen to music at home.', options: ['I listen to music at home.', 'I listen to music at the weekend.', 'I dance at home.'], correct: 0 },
            { type: 'type', nl: 'Ze danst erg goed.', target: 'She dances very well', accept: ['she dances very well', 'She dances very well.'] },
            { type: 'fill', before: 'We', after: 'the museum today.', nl: 'We bezoeken het museum vandaag.', options: ['visit', 'visits', 'visiting'], correct: 0 },
            { type: 'wordbank', nl: 'Het theater is in het stadscentrum.', target: 'The theatre is in the city centre', distractors: ['cinema', 'at', 'station', 'a'] },
            { type: 'type', nl: 'bioscoop', target: 'cinema', accept: ['Cinema', 'the cinema'] },
            { type: 'select', prompt: 'The museum is very old.', speak: 'The museum is very old.', options: ['Het museum is erg oud.', 'Het museum is erg groot.', 'Het theater is erg oud.'], correct: 0 },
            { type: 'type', nl: 'dansen', target: 'to dance', accept: ['dance', 'Dance', 'To dance'] },
            { type: 'fill', before: 'The cinema is', after: 'the city centre.', nl: 'De bioscoop is in het stadscentrum.', options: ['in', 'on', 'at'], correct: 0 },
            { type: 'wordbank', nl: 'Tot in het weekend!', target: 'See you at the weekend', distractors: ['goodbye', 'in', 'on', 'tomorrow'] },
          ],
        },
      ],
    },
    {
      id: 'en-u14',
      title: 'De grote herhaling',
      icon: '🏆',
      lessons: [
        {
          id: 'en-u14-l1',
          title: 'Terugblik: van hallo tot nu',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'koffie', target: 'coffee' },
                { nl: 'trein', target: 'train' },
                { nl: 'ziek', target: 'ill' },
                { nl: 'zon', target: 'sun' },
                { nl: 'bioscoop', target: 'cinema' },
              ],
            },
            { type: 'select', prompt: 'Ik wil graag een kopje thee.', options: ['I would like a cup of tea.', 'I would like a glass of water.', 'A cup of coffee, please.'], correct: 0 },
            { type: 'wordbank', nl: 'Mijn moeder is moe en mijn vader is ziek.', target: 'My mother is tired and my father is ill', distractors: ['brother', 'better', 'am', 'the'] },
            { type: 'listen', target: 'Where is the station, please?', options: ['Where is the station, please?', 'Where is the cinema, please?', 'Where is the hotel, please?'], correct: 0 },
            { type: 'type', nl: 'Ik wil graag een kaartje naar Londen.', target: 'I would like a ticket to London', accept: ['i would like a ticket to london', 'I would like a ticket to London.'] },
            { type: 'fill', before: 'My father', after: 'in London.', nl: 'Mijn vader werkt in Londen.', options: ['work', 'works', 'working'], correct: 1 },
            { type: 'select', prompt: 'The bus to the city centre leaves at ten.', speak: 'The bus to the city centre leaves at ten.', options: ['De bus naar het stadscentrum vertrekt om tien uur.', 'De trein naar het stadscentrum vertrekt om tien uur.', 'De bus naar het station vertrekt om tien uur.'], correct: 0 },
            { type: 'wordbank', nl: 'Sla linksaf bij de bioscoop.', target: 'Turn left at the cinema', distractors: ['right', 'station', 'to', 'on'] },
            { type: 'type', nl: 'Het gaat goed, dank je.', target: "I'm fine, thanks", accept: ["I'm fine thanks", "i'm fine, thanks", 'I am fine, thanks', "I'm fine, thank you"] },
            { type: 'fill', before: 'Tea', after: 'milk, please.', nl: 'Thee met melk, alsjeblieft.', options: ['with', 'of', 'and'], correct: 0 },
            { type: 'select', prompt: 'winkel', options: ['shop', 'street', 'station'], correct: 0 },
            { type: 'type', nl: 'De winkel gaat om negen uur open.', target: 'The shop opens at nine', accept: ['the shop opens at nine', 'The shop opens at nine.'] },
          ],
        },
        {
          id: 'en-u14-l2',
          title: 'Alles door elkaar',
          exercises: [
            { type: 'listen', target: 'My suitcase is very heavy.', options: ['My suitcase is very heavy.', 'My suitcase is very old.', 'My ticket is very old.'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'vakantie', target: 'holiday' },
                { nl: 'herfst', target: 'autumn' },
                { nl: 'hoofd', target: 'head' },
                { nl: 'muziek', target: 'music' },
                { nl: 'kaartje', target: 'ticket' },
              ],
            },
            { type: 'wordbank', nl: 'In de winter is het koud in Schotland.', target: 'In winter it is cold in Scotland', distractors: ['summer', 'warm', 'the', 'rains'] },
            { type: 'type', nl: 'De trein vertrekt van perron twee.', target: 'The train leaves from platform two', accept: ['the train leaves from platform two', 'The train leaves from platform two.'] },
            { type: 'select', prompt: 'It often rains in autumn.', speak: 'It often rains in autumn.', options: ['Het regent vaak in de herfst.', 'Het regent vaak in de lente.', 'Het is vaak koud in de herfst.'], correct: 0 },
            { type: 'fill', before: 'I would like', after: 'see a doctor.', nl: 'Ik wil graag een dokter zien.', options: ['to', 'for', 'at'], correct: 0 },
            { type: 'wordbank', nl: 'We bezoeken mijn broer in het weekend.', target: 'We visit my brother at the weekend', distractors: ['sister', 'in', 'on', 'visits'] },
            { type: 'type', nl: 'Het is warm en de zon schijnt.', target: 'It is warm and the sun is shining', accept: ['it is warm and the sun is shining', 'It is warm and the sun is shining.', "It's warm and the sun is shining"] },
            { type: 'select', prompt: 'moe', options: ['ill', 'tired', 'heavy'], correct: 1 },
            { type: 'fill', before: 'The woman has two', after: '.', nl: 'De vrouw heeft twee kinderen.', options: ['childs', 'children', 'child'], correct: 1 },
            { type: 'listen', target: 'The film starts at eight.', options: ['The film starts at eight.', 'The film starts at six.', 'The theatre opens at eight.'], correct: 0 },
            { type: 'type', nl: 'Neem dit medicijn met water.', target: 'Take this medicine with water', accept: ['take this medicine with water', 'Take this medicine with water.'] },
          ],
        },
        {
          id: 'en-u14-l3',
          title: 'De grote finale',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'dokter', target: 'doctor' },
                { nl: 'lente', target: 'spring' },
                { nl: 'theater', target: 'theatre' },
                { nl: 'perron', target: 'platform' },
                { nl: 'koffer', target: 'suitcase' },
              ],
            },
            { type: 'type', nl: 'Waar is het station?', target: 'Where is the station?', accept: ['where is the station', 'Where is the station', 'where is the station?'] },
            { type: 'wordbank', nl: 'In de zomer reis ik met de trein.', target: 'In summer I travel by train', distractors: ['bus', 'the', 'travels', 'winter'] },
            { type: 'type', nl: 'Mijn hoofd doet pijn en ik ben moe.', target: 'My head hurts and I am tired', accept: ['my head hurts and i am tired', 'My head hurts and I am tired.', "My head hurts and I'm tired"] },
            { type: 'fill', before: 'She', after: 'very well.', nl: 'Ze danst erg goed.', options: ['dance', 'dances', 'dancing'], correct: 1 },
            { type: 'wordbank', nl: 'Het hotel is vlak bij het theater.', target: 'The hotel is near the theatre', distractors: ['cinema', 'far', 'at', 'a'] },
            { type: 'type', nl: 'Ik wil graag een koffie, alsjeblieft.', target: 'I would like a coffee please', accept: ['i would like a coffee please', 'I would like a coffee, please.', 'I would like a coffee, please'] },
            { type: 'listen', target: 'Goodbye, see you at the weekend!', options: ['Goodbye, see you at the weekend!', 'Goodbye, see you tomorrow!', 'Hello, see you at the weekend!'], correct: 0 },
            { type: 'type', nl: 'In de lente zijn de parken groen.', target: 'In spring the parks are green', accept: ['in spring the parks are green', 'In spring the parks are green.'] },
            { type: 'fill', before: 'We are', after: 'holiday in Scotland.', nl: 'We zijn op vakantie in Schotland.', options: ['on', 'in', 'at'], correct: 0 },
            { type: 'wordbank', nl: 'Dank je wel en tot ziens!', target: 'Thank you and goodbye', distractors: ['please', 'hello', 'sorry', 'morning'] },
            { type: 'type', nl: 'De bus naar de stad vertrekt om tien uur.', target: 'The bus to the city leaves at ten', accept: ['the bus to the city leaves at ten', 'The bus to the city leaves at ten.'] },
          ],
        },
      ],
    },
  ],
}
