import type { Course } from '../../types'

export const course: Course = {
  id: 'en',
  name: 'Engels',
  flag: '🇬🇧',
  tagline: 'De wereldtaal, verfijnd beheerst',
  ttsLang: 'en-GB',
  sections: [
    {
      title: 'Sectie 1 · Eerste stappen',
      cefr: 'A1',
      units: [
        {
          id: 'en-u1',
          title: 'Begroetingen & basis',
          icon: '👋',
          lessons: [
            {
              id: 'en-u1-l1',
              title: 'Hallo zeggen',
              exercises: [
                { type: 'new', word: 'hello', nl: 'hallo', example: 'Hello, nice to meet you.', exampleNl: 'Hallo, leuk je te ontmoeten.' },
                { type: 'new', word: 'good morning', nl: 'goedemorgen', example: 'Good morning, Emma.', exampleNl: 'Goedemorgen, Emma.' },
                { type: 'new', word: 'goodbye', nl: 'tot ziens', example: 'Goodbye, see you tomorrow.', exampleNl: 'Tot ziens, tot morgen.' },
                { type: 'new', word: 'thank you', nl: 'dank je wel', example: 'Thank you very much.', exampleNl: 'Heel erg bedankt.' },
                { type: 'select', prompt: 'hallo', options: ['goodbye', 'hello', 'good morning'], correct: 1 },
                { type: 'select', prompt: 'good morning', speak: 'good morning', options: ['goedenavond', 'tot ziens', 'goedemorgen'], correct: 2 },
                { type: 'listen', target: 'thank you', options: ['good morning', 'thank you', 'goodbye'], correct: 1 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'hallo', target: 'hello' },
                    { nl: 'tot ziens', target: 'goodbye' },
                    { nl: 'dank je wel', target: 'thank you' },
                    { nl: 'goedemorgen', target: 'good morning' },
                  ],
                },
                { type: 'select', prompt: 'tot ziens', options: ['hello', 'thank you', 'goodbye'], correct: 2 },
                { type: 'wordbank', nl: 'Hallo, ik ben Tom.', target: 'Hello I am Tom', distractors: ['goodbye', 'you', 'she', 'morning'] },
                { type: 'type', nl: 'hallo', target: 'hello', accept: ['Hello', 'hello!', 'Hello!'] },
                { type: 'select', prompt: 'goodbye', speak: 'goodbye', options: ['tot ziens', 'dank je wel', 'goedemorgen'], correct: 0 },
              ],
            },
            {
              id: 'en-u1-l2',
              title: 'Hoe gaat het?',
              exercises: [
                { type: 'new', word: 'how are you?', nl: 'hoe gaat het?', example: 'How are you, James?', exampleNl: 'Hoe gaat het, James?' },
                { type: 'new', word: "I'm fine", nl: 'het gaat goed', example: "I'm fine, thanks.", exampleNl: 'Het gaat goed, dank je.' },
                { type: 'new', word: 'please', nl: 'alsjeblieft', example: 'A cup of tea, please.', exampleNl: 'Een kopje thee, alsjeblieft.' },
                { type: 'new', word: 'sorry', nl: 'sorry', example: "Sorry, I'm late.", exampleNl: 'Sorry, ik ben te laat.' },
                { type: 'select', prompt: 'alsjeblieft', options: ['sorry', 'thank you', 'please'], correct: 2 },
                { type: 'select', prompt: 'How are you?', speak: 'How are you?', options: ['Wie ben jij?', 'Hoe gaat het?', 'Waar ben je?'], correct: 1 },
                { type: 'listen', target: "I'm fine, thanks.", options: ["I'm late, sorry.", "I'm fine, thanks.", 'How are you?'], correct: 1 },
                { type: 'fill', before: 'How', after: 'you?', nl: 'Hoe gaat het met je?', options: ['is', 'are', 'am'], correct: 1 },
                { type: 'wordbank', nl: 'Het gaat goed, dank je.', target: "I'm fine thank you", distractors: ['sorry', 'goodbye', 'please', 'how'] },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'alsjeblieft', target: 'please' },
                    { nl: 'het spijt me', target: 'sorry' },
                    { nl: 'goed', target: 'fine' },
                    { nl: 'hoe', target: 'how' },
                  ],
                },
                { type: 'type', nl: 'alsjeblieft', target: 'please', accept: ['Please', 'please.'] },
                { type: 'fill', before: 'Sorry,', after: 'late.', nl: 'Sorry, ik ben te laat.', options: ['I', "I'm", 'am'], correct: 1 },
              ],
            },
            {
              id: 'en-u1-l3',
              title: 'Herhaling: eerste woorden',
              exercises: [
                { type: 'select', prompt: 'goedemorgen', options: ['good night', 'good morning', 'goodbye'], correct: 1 },
                { type: 'listen', target: 'Hello, how are you?', options: ['Hello, how are you?', 'Goodbye, thank you.', 'Sorry, I am late.'], correct: 0 },
                { type: 'type', nl: 'dank je wel', target: 'thank you', accept: ['Thank you', 'thanks', 'Thanks', 'thank you!'] },
                { type: 'wordbank', nl: 'Hallo, hoe gaat het?', target: 'Hello how are you', distractors: ['fine', 'goodbye', 'please', 'am'] },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'hallo', target: 'hello' },
                    { nl: 'dank je wel', target: 'thank you' },
                    { nl: 'alsjeblieft', target: 'please' },
                    { nl: 'tot ziens', target: 'goodbye' },
                    { nl: 'het spijt me', target: 'sorry' },
                  ],
                },
                { type: 'type', nl: 'tot ziens', target: 'goodbye', accept: ['Goodbye', 'bye', 'Bye', 'good bye'] },
                { type: 'fill', before: 'Good', after: ', Emma.', nl: 'Goedemorgen, Emma.', options: ['morning', 'you', 'fine'], correct: 0 },
                { type: 'wordbank', nl: 'Het gaat goed, dank je.', target: "I'm fine thanks", distractors: ['sorry', 'how', 'goodbye', 'please'] },
                { type: 'select', prompt: 'Thank you very much.', speak: 'Thank you very much.', options: ['Tot morgen.', 'Het spijt me.', 'Heel erg bedankt.'], correct: 2 },
                { type: 'type', nl: 'goedemorgen', target: 'good morning', accept: ['Good morning', 'goodmorning'] },
                { type: 'wordbank', nl: 'Tot ziens, tot morgen.', target: 'Goodbye see you tomorrow', distractors: ['hello', 'thanks', 'morning', 'am'] },
                { type: 'type', nl: 'Hoe gaat het?', target: 'How are you?', accept: ['how are you', 'How are you', 'how are you?'] },
              ],
            },
          ],
        },
        {
          id: 'en-u2',
          title: 'Eten & drinken',
          icon: '☕',
          lessons: [
            {
              id: 'en-u2-l1',
              title: 'In het café',
              exercises: [
                { type: 'new', word: 'tea', nl: 'thee', example: 'A cup of tea, please.', exampleNl: 'Een kopje thee, alsjeblieft.' },
                { type: 'new', word: 'coffee', nl: 'koffie', example: 'The coffee is hot.', exampleNl: 'De koffie is heet.' },
                { type: 'new', word: 'water', nl: 'water', example: 'A glass of water, please.', exampleNl: 'Een glas water, alsjeblieft.' },
                { type: 'new', word: 'milk', nl: 'melk', example: 'Tea with milk, please.', exampleNl: 'Thee met melk, alsjeblieft.' },
                { type: 'select', prompt: 'thee', options: ['coffee', 'tea', 'milk'], correct: 1 },
                { type: 'select', prompt: 'coffee', speak: 'coffee', options: ['thee', 'koffie', 'water'], correct: 1 },
                { type: 'listen', target: 'A cup of tea, please.', options: ['A cup of coffee, please.', 'A glass of water, please.', 'A cup of tea, please.'], correct: 2 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'thee', target: 'tea' },
                    { nl: 'koffie', target: 'coffee' },
                    { nl: 'melk', target: 'milk' },
                    { nl: 'een kopje', target: 'a cup' },
                  ],
                },
                { type: 'fill', before: 'A cup', after: 'tea, please.', nl: 'Een kopje thee, alsjeblieft.', options: ['with', 'of', 'for'], correct: 1 },
                { type: 'wordbank', nl: 'Thee met melk, alsjeblieft.', target: 'Tea with milk please', distractors: ['coffee', 'water', 'cup', 'the'] },
                { type: 'type', nl: 'koffie', target: 'coffee', accept: ['Coffee', 'a coffee'] },
                { type: 'fill', before: 'The coffee', after: 'hot.', nl: 'De koffie is heet.', options: ['are', 'am', 'is'], correct: 2 },
              ],
            },
            {
              id: 'en-u2-l2',
              title: 'Iets bestellen',
              exercises: [
                { type: 'new', word: 'bread', nl: 'brood', example: 'The bread is fresh.', exampleNl: 'Het brood is vers.' },
                { type: 'new', word: 'cheese', nl: 'kaas', example: 'A cheese sandwich, please.', exampleNl: 'Een broodje kaas, alsjeblieft.' },
                { type: 'new', word: 'apple', nl: 'appel', example: 'The apple is green.', exampleNl: 'De appel is groen.' },
                { type: 'new', word: 'I would like', nl: 'ik wil graag', example: 'I would like a coffee, please.', exampleNl: 'Ik wil graag een koffie, alsjeblieft.' },
                { type: 'select', prompt: 'brood', options: ['cheese', 'apple', 'bread'], correct: 2 },
                { type: 'select', prompt: 'cheese', speak: 'cheese', options: ['brood', 'kaas', 'melk'], correct: 1 },
                { type: 'listen', target: 'I would like a cheese sandwich.', options: ['I would like a cheese sandwich.', 'I would like a cup of tea.', 'The bread is fresh.'], correct: 0 },
                { type: 'fill', before: 'I would like', after: 'apple.', nl: 'Ik wil graag een appel.', options: ['a', 'an', 'the'], correct: 1 },
                { type: 'wordbank', nl: 'Ik wil graag een koffie, alsjeblieft.', target: 'I would like a coffee please', distractors: ['tea', 'the', 'want', 'milk'] },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'brood', target: 'bread' },
                    { nl: 'kaas', target: 'cheese' },
                    { nl: 'appel', target: 'apple' },
                    { nl: 'broodje', target: 'sandwich' },
                  ],
                },
                { type: 'type', nl: 'brood', target: 'bread', accept: ['Bread', 'the bread'] },
                { type: 'type', nl: 'Ik wil graag thee.', target: 'I would like tea', accept: ['i would like tea', 'I would like tea.', 'I would like some tea'] },
              ],
            },
            {
              id: 'en-u2-l3',
              title: 'Herhaling: eten & drinken',
              exercises: [
                {
                  type: 'match',
                  pairs: [
                    { nl: 'thee', target: 'tea' },
                    { nl: 'koffie', target: 'coffee' },
                    { nl: 'melk', target: 'milk' },
                    { nl: 'brood', target: 'bread' },
                    { nl: 'kaas', target: 'cheese' },
                  ],
                },
                { type: 'select', prompt: 'appel', options: ['bread', 'apple', 'cheese'], correct: 1 },
                { type: 'listen', target: 'Tea with milk, please.', options: ['Coffee with milk, please.', 'Tea with milk, please.', 'Tea with cheese, please.'], correct: 1 },
                { type: 'type', nl: 'melk', target: 'milk', accept: ['Milk', 'the milk'] },
                { type: 'wordbank', nl: 'Ik wil graag een glas water.', target: 'I would like a glass of water', distractors: ['cup', 'tea', 'the', 'milk'] },
                { type: 'fill', before: 'A glass', after: 'water, please.', nl: 'Een glas water, alsjeblieft.', options: ['of', 'with', 'on'], correct: 0 },
                { type: 'type', nl: 'thee', target: 'tea', accept: ['Tea', 'a tea'] },
                { type: 'wordbank', nl: 'De koffie is heet.', target: 'The coffee is hot', distractors: ['tea', 'are', 'cold', 'a'] },
                { type: 'select', prompt: 'The bread is fresh.', speak: 'The bread is fresh.', options: ['Het brood is oud.', 'Het brood is vers.', 'De kaas is vers.'], correct: 1 },
                { type: 'type', nl: 'kaas', target: 'cheese', accept: ['Cheese', 'the cheese'] },
                { type: 'fill', before: 'I would like', after: 'cup of tea.', nl: 'Ik wil graag een kopje thee.', options: ['an', 'a', 'the'], correct: 1 },
                { type: 'type', nl: 'Ik wil graag koffie.', target: 'I would like coffee', accept: ['i would like coffee', 'I would like coffee.', 'I would like a coffee'] },
              ],
            },
          ],
        },
        {
          id: 'en-u3',
          title: 'Mensen & familie',
          icon: '💛',
          lessons: [
            {
              id: 'en-u3-l1',
              title: 'Mijn familie',
              exercises: [
                { type: 'new', word: 'mother', nl: 'moeder', example: 'My mother is at home.', exampleNl: 'Mijn moeder is thuis.' },
                { type: 'new', word: 'father', nl: 'vader', example: 'My father works in London.', exampleNl: 'Mijn vader werkt in Londen.' },
                { type: 'new', word: 'brother', nl: 'broer', example: 'My brother is ten.', exampleNl: 'Mijn broer is tien.' },
                { type: 'new', word: 'sister', nl: 'zus', example: 'My sister has a cat.', exampleNl: 'Mijn zus heeft een kat.' },
                { type: 'select', prompt: 'moeder', options: ['father', 'sister', 'mother'], correct: 2 },
                { type: 'select', prompt: 'brother', speak: 'brother', options: ['broer', 'zus', 'vader'], correct: 0 },
                { type: 'listen', target: 'My sister has a cat.', options: ['My brother has a cat.', 'My sister has a cat.', 'My mother has a cat.'], correct: 1 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'moeder', target: 'mother' },
                    { nl: 'vader', target: 'father' },
                    { nl: 'broer', target: 'brother' },
                    { nl: 'zus', target: 'sister' },
                  ],
                },
                { type: 'fill', before: 'My father', after: 'in London.', nl: 'Mijn vader werkt in Londen.', options: ['work', 'works', 'working'], correct: 1 },
                { type: 'wordbank', nl: 'Mijn broer is tien.', target: 'My brother is ten', distractors: ['sister', 'has', 'are', 'the'] },
                { type: 'type', nl: 'vader', target: 'father', accept: ['Father', 'dad', 'Dad', 'my father'] },
                { type: 'select', prompt: 'My mother is at home.', speak: 'My mother is at home.', options: ['Mijn moeder is thuis.', 'Mijn vader is thuis.', 'Mijn moeder is in Londen.'], correct: 0 },
              ],
            },
            {
              id: 'en-u3-l2',
              title: 'Vrienden & mensen',
              exercises: [
                { type: 'new', word: 'friend', nl: 'vriend', example: 'Tom is my best friend.', exampleNl: 'Tom is mijn beste vriend.' },
                { type: 'new', word: 'man', nl: 'man', example: 'That man is very tall.', exampleNl: 'Die man is erg lang.' },
                { type: 'new', word: 'woman', nl: 'vrouw', example: 'The woman has two children.', exampleNl: 'De vrouw heeft twee kinderen.' },
                { type: 'new', word: 'child', nl: 'kind', example: 'The child is playing outside.', exampleNl: 'Het kind speelt buiten.' },
                { type: 'select', prompt: 'vriend', options: ['man', 'friend', 'child'], correct: 1 },
                { type: 'select', prompt: 'woman', speak: 'woman', options: ['kind', 'man', 'vrouw'], correct: 2 },
                { type: 'listen', target: 'Tom is my best friend.', options: ['Tom is my best friend.', 'Tom is my big brother.', 'Tom is my little sister.'], correct: 0 },
                { type: 'fill', before: 'The woman has two', after: '.', nl: 'De vrouw heeft twee kinderen.', options: ['childs', 'children', 'child'], correct: 1 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'vriend', target: 'friend' },
                    { nl: 'vrouw', target: 'woman' },
                    { nl: 'kind', target: 'child' },
                    { nl: 'kinderen', target: 'children' },
                  ],
                },
                { type: 'wordbank', nl: 'Die man is erg lang.', target: 'That man is very tall', distractors: ['woman', 'short', 'the', 'has'] },
                { type: 'fill', before: 'Sarah is', after: 'sister.', nl: 'Sarah is mijn zus.', options: ['me', 'I', 'my'], correct: 2 },
                { type: 'type', nl: 'kind', target: 'child', accept: ['Child', 'a child', 'kid'] },
              ],
            },
            {
              id: 'en-u3-l3',
              title: 'Herhaling: mensen & familie',
              exercises: [
                {
                  type: 'match',
                  pairs: [
                    { nl: 'moeder', target: 'mother' },
                    { nl: 'vader', target: 'father' },
                    { nl: 'zus', target: 'sister' },
                    { nl: 'vriend', target: 'friend' },
                    { nl: 'kind', target: 'child' },
                  ],
                },
                { type: 'select', prompt: 'kinderen', options: ['children', 'child', 'friends'], correct: 0 },
                { type: 'listen', target: 'My brother is my best friend.', options: ['My sister is my best friend.', 'My brother is my best friend.', 'My father is my best friend.'], correct: 1 },
                { type: 'type', nl: 'zus', target: 'sister', accept: ['Sister', 'my sister'] },
                { type: 'wordbank', nl: 'De vrouw heeft twee kinderen.', target: 'The woman has two children', distractors: ['child', 'man', 'is', 'my'] },
                { type: 'fill', before: 'My sister', after: 'a cat.', nl: 'Mijn zus heeft een kat.', options: ['have', 'has', 'is'], correct: 1 },
                { type: 'type', nl: 'broer', target: 'brother', accept: ['Brother', 'my brother'] },
                { type: 'wordbank', nl: 'Mijn vader werkt in Londen.', target: 'My father works in London', distractors: ['mother', 'work', 'the', 'at'] },
                { type: 'select', prompt: 'That man is very tall.', speak: 'That man is very tall.', options: ['Die vrouw is erg lang.', 'Die man is erg klein.', 'Die man is erg lang.'], correct: 2 },
                { type: 'type', nl: 'vriend', target: 'friend', accept: ['Friend', 'a friend', 'my friend'] },
                { type: 'fill', before: 'The', after: 'is playing outside.', nl: 'Het kind speelt buiten.', options: ['children', 'child', 'childs'], correct: 1 },
                { type: 'type', nl: 'Mijn moeder is thuis.', target: 'My mother is at home', accept: ['my mother is at home', 'My mother is at home.', 'My mum is at home'] },
              ],
            },
          ],
        },
        {
          id: 'en-u4',
          title: 'Onderweg in de stad',
          icon: '🧭',
          lessons: [
            {
              id: 'en-u4-l1',
              title: 'Plekken in de stad',
              exercises: [
                { type: 'new', word: 'street', nl: 'straat', example: 'I live in this street.', exampleNl: 'Ik woon in deze straat.' },
                { type: 'new', word: 'station', nl: 'station', example: 'The station is over there.', exampleNl: 'Het station is daar.' },
                { type: 'new', word: 'shop', nl: 'winkel', example: 'The shop opens at nine.', exampleNl: 'De winkel gaat om negen uur open.' },
                { type: 'new', word: 'city', nl: 'stad', example: 'London is a big city.', exampleNl: 'Londen is een grote stad.' },
                { type: 'select', prompt: 'winkel', options: ['station', 'shop', 'street'], correct: 1 },
                { type: 'select', prompt: 'city', speak: 'city', options: ['straat', 'station', 'stad'], correct: 2 },
                { type: 'listen', target: 'London is a big city.', options: ['London is a big city.', 'London is a big shop.', 'The station is in the city.'], correct: 0 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'straat', target: 'street' },
                    { nl: 'winkel', target: 'shop' },
                    { nl: 'stad', target: 'city' },
                    { nl: 'groot', target: 'big' },
                  ],
                },
                { type: 'fill', before: 'The station is', after: 'there.', nl: 'Het station is daar.', options: ['over', 'on', 'at'], correct: 0 },
                { type: 'wordbank', nl: 'Ik woon in deze straat.', target: 'I live in this street', distractors: ['city', 'shop', 'the', 'at'] },
                { type: 'type', nl: 'stad', target: 'city', accept: ['City', 'a city', 'town'] },
                { type: 'fill', before: 'London is', after: 'big city.', nl: 'Londen is een grote stad.', options: ['an', 'the', 'a'], correct: 2 },
              ],
            },
            {
              id: 'en-u4-l2',
              title: 'De weg vragen',
              exercises: [
                { type: 'new', word: 'left', nl: 'links', example: 'Turn left at the station.', exampleNl: 'Sla linksaf bij het station.' },
                { type: 'new', word: 'right', nl: 'rechts', example: 'The shop is on the right.', exampleNl: 'De winkel is aan de rechterkant.' },
                { type: 'new', word: 'where', nl: 'waar', example: 'Where is the station?', exampleNl: 'Waar is het station?' },
                { type: 'new', word: 'bus', nl: 'bus', example: 'The bus to London leaves at ten.', exampleNl: 'De bus naar Londen vertrekt om tien uur.' },
                { type: 'select', prompt: 'links', options: ['right', 'straight on', 'left'], correct: 2 },
                { type: 'select', prompt: 'Where is the station?', speak: 'Where is the station?', options: ['Waar is de winkel?', 'Waar is het station?', 'Wat is het station?'], correct: 1 },
                { type: 'listen', target: 'Turn left at the station.', options: ['Turn right at the station.', 'Turn left at the shop.', 'Turn left at the station.'], correct: 2 },
                { type: 'fill', before: 'The shop is', after: 'the right.', nl: 'De winkel is aan de rechterkant.', options: ['in', 'on', 'at'], correct: 1 },
                { type: 'wordbank', nl: 'Waar is de bus naar Londen?', target: 'Where is the bus to London', distractors: ['train', 'from', 'a', 'station'] },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'links', target: 'left' },
                    { nl: 'rechts', target: 'right' },
                    { nl: 'waar', target: 'where' },
                    { nl: 'sla af', target: 'turn' },
                  ],
                },
                { type: 'type', nl: 'rechts', target: 'right', accept: ['Right', 'on the right'] },
                { type: 'fill', before: 'Where', after: 'the shops?', nl: 'Waar zijn de winkels?', options: ['is', 'are', 'am'], correct: 1 },
              ],
            },
            {
              id: 'en-u4-l3',
              title: 'Herhaling: in de stad',
              exercises: [
                {
                  type: 'match',
                  pairs: [
                    { nl: 'straat', target: 'street' },
                    { nl: 'winkel', target: 'shop' },
                    { nl: 'stad', target: 'city' },
                    { nl: 'links', target: 'left' },
                    { nl: 'rechts', target: 'right' },
                  ],
                },
                { type: 'select', prompt: 'waar', options: ['there', 'what', 'where'], correct: 2 },
                { type: 'listen', target: 'Where is the bus to London?', options: ['Where is the bus to London?', 'Where is the train to London?', 'Where is the bus to Leeds?'], correct: 0 },
                { type: 'type', nl: 'straat', target: 'street', accept: ['Street', 'a street'] },
                { type: 'wordbank', nl: 'Sla linksaf bij het station.', target: 'Turn left at the station', distractors: ['right', 'shop', 'to', 'on'] },
                { type: 'fill', before: 'I live', after: 'this street.', nl: 'Ik woon in deze straat.', options: ['at', 'in', 'of'], correct: 1 },
                { type: 'type', nl: 'links', target: 'left', accept: ['Left', 'on the left'] },
                { type: 'wordbank', nl: 'De winkel is aan de rechterkant.', target: 'The shop is on the right', distractors: ['left', 'station', 'a', 'at'] },
                { type: 'select', prompt: 'The shop opens at nine.', speak: 'The shop opens at nine.', options: ['De winkel sluit om negen uur.', 'De winkel gaat om negen uur open.', 'Het station gaat om negen uur open.'], correct: 1 },
                { type: 'type', nl: 'winkel', target: 'shop', accept: ['Shop', 'a shop', 'store'] },
                { type: 'fill', before: 'The bus', after: 'at ten.', nl: 'De bus vertrekt om tien uur.', options: ['leave', 'leaving', 'leaves'], correct: 2 },
                { type: 'type', nl: 'Waar is het station?', target: 'Where is the station?', accept: ['where is the station', 'Where is the station', 'where is the station?'] },
              ],
            },
          ],
        },
      ],
    },
  ],
}
