import type { Section } from '../../types'

export const section: Section = {
  title: 'Sectie 2 · Dagelijks leven',
  cefr: 'A1+',
  units: [
    {
      id: 'es-u5',
      title: 'Getallen & tijd',
      icon: '🕰️',
      lessons: [
        {
          id: 'es-u5-l1',
          title: 'De eerste getallen',
          exercises: [
            { type: 'new', word: 'uno', nl: 'één', example: 'Solo quiero uno, gracias.', exampleNl: 'Ik wil er maar één, dank je.' },
            { type: 'new', word: 'dos', nl: 'twee', example: 'Dos cafés, por favor.', exampleNl: 'Twee koffie, alsjeblieft.' },
            { type: 'new', word: 'tres', nl: 'drie', example: 'Tengo tres hermanos.', exampleNl: 'Ik heb drie broers.' },
            { type: 'new', word: 'cuatro', nl: 'vier', example: 'Vivo en el número cuatro.', exampleNl: 'Ik woon op nummer vier.' },
            { type: 'select', prompt: 'twee', options: ['dos', 'tres', 'uno'], correct: 0 },
            { type: 'select', prompt: 'tres', speak: 'Tres', options: ['vier', 'drie', 'twee'], correct: 1 },
            { type: 'listen', target: 'cuatro', options: ['cuatro', 'dos', 'tres'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'één', target: 'uno' },
                { nl: 'twee', target: 'dos' },
                { nl: 'drie', target: 'tres' },
                { nl: 'vier', target: 'cuatro' },
              ],
            },
            { type: 'wordbank', nl: 'Twee koffie, alsjeblieft.', target: 'Dos cafés por favor', distractors: ['tres', 'un', 'cuatro', 'cuenta'] },
            { type: 'fill', before: 'Dos', after: ', por favor.', nl: 'Twee koffie, alsjeblieft.', options: ['café', 'cafés', 'un café'], correct: 1 },
            { type: 'type', nl: 'drie', target: 'tres', accept: ['Tres', 'tres.', 'Tres.'] },
            { type: 'listen', target: 'dos', options: ['tres', 'dos', 'diez'], correct: 1 },
          ],
        },
        {
          id: 'es-u5-l2',
          title: 'Hoe laat is het?',
          exercises: [
            { type: 'new', word: '¿qué hora es?', nl: 'hoe laat is het?', example: '¿Qué hora es, por favor?', exampleNl: 'Hoe laat is het, alsjeblieft?' },
            { type: 'new', word: 'la hora', nl: 'het uur / de tijd', example: '¿A qué hora sale el tren?', exampleNl: 'Hoe laat vertrekt de trein?' },
            { type: 'new', word: 'hoy', nl: 'vandaag', example: 'Hoy quiero comer en la plaza.', exampleNl: 'Vandaag wil ik op het plein eten.' },
            { type: 'new', word: 'mañana', nl: 'morgen', example: 'Mañana trabajo en Madrid.', exampleNl: 'Morgen werk ik in Madrid.' },
            { type: 'select', prompt: 'vandaag', options: ['mañana', 'hoy', 'la hora'], correct: 1 },
            { type: 'select', prompt: '¿Qué hora es?', speak: '¿Qué hora es?', options: ['Hoe gaat het?', 'Hoe laat is het?', 'Waar is het?'], correct: 1 },
            { type: 'fill', before: 'Son', after: 'tres.', nl: 'Het is drie uur.', options: ['la', 'las', 'los'], correct: 1 },
            { type: 'listen', target: 'mañana', options: ['ahora', 'mañana', 'la hora'], correct: 1 },
            { type: 'wordbank', nl: 'Hoe laat vertrekt de trein?', target: 'A qué hora sale el tren', distractors: ['las', 'son', 'hoy', 'está'] },
            {
              type: 'match',
              pairs: [
                { nl: 'vandaag', target: 'hoy' },
                { nl: 'morgen', target: 'mañana' },
                { nl: 'het uur', target: 'la hora' },
                { nl: 'hoe laat is het?', target: '¿qué hora es?' },
              ],
            },
            { type: 'type', nl: 'vandaag', target: 'hoy', accept: ['Hoy', 'hoy.', 'Hoy.'] },
            { type: 'fill', before: 'Es', after: 'una.', nl: 'Het is één uur.', options: ['las', 'la', 'el'], correct: 1 },
          ],
        },
        {
          id: 'es-u5-l3',
          title: 'Herhaling: getallen & tijd',
          exercises: [
            { type: 'type', nl: 'Hoe laat is het?', target: 'Qué hora es', accept: ['¿Qué hora es?', 'qué hora es', 'que hora es', 'Que hora es'] },
            { type: 'wordbank', nl: 'De trein vertrekt om drie uur.', target: 'El tren sale a las tres', distractors: ['hora', 'cuatro', 'es', 'la'] },
            { type: 'select', prompt: 'Mañana trabajo en Madrid.', speak: 'Mañana trabajo en Madrid.', options: ['Vandaag werk ik in Madrid.', 'Morgen werk ik in Madrid.', 'Morgen woon ik in Madrid.'], correct: 1 },
            { type: 'type', nl: 'twee', target: 'dos', accept: ['Dos', 'dos.', 'Dos.'] },
            {
              type: 'match',
              pairs: [
                { nl: 'één', target: 'uno' },
                { nl: 'drie', target: 'tres' },
                { nl: 'vier', target: 'cuatro' },
                { nl: 'vandaag', target: 'hoy' },
                { nl: 'morgen', target: 'mañana' },
              ],
            },
            { type: 'fill', before: '¿A qué', after: 'sale el tren?', nl: 'Hoe laat vertrekt de trein?', options: ['hora', 'horas', 'hoy'], correct: 0 },
            { type: 'wordbank', nl: 'Vandaag wil ik iets eten.', target: 'Hoy quiero comer algo', distractors: ['mañana', 'bien', 'las', 'hora'] },
            { type: 'listen', target: 'son las cuatro', options: ['son las cuatro', 'son las tres', 'es la una'], correct: 0 },
            { type: 'type', nl: 'morgen', target: 'mañana', accept: ['Mañana', 'mañana.', 'manana'] },
            { type: 'fill', before: 'Es la', after: '.', nl: 'Het is één uur.', options: ['una', 'uno', 'un'], correct: 0 },
            { type: 'type', nl: 'Het is drie uur.', target: 'Son las tres', accept: ['son las tres', 'Son las tres.', 'son las tres.'] },
            { type: 'wordbank', nl: 'Morgen vertrekt de trein om vier uur.', target: 'Mañana el tren sale a las cuatro', distractors: ['hoy', 'tres', 'la', 'es'] },
          ],
        },
      ],
    },
    {
      id: 'es-u6',
      title: 'Boodschappen & geld',
      icon: '🛍️',
      lessons: [
        {
          id: 'es-u6-l1',
          title: 'In de winkel',
          exercises: [
            { type: 'new', word: 'la tienda', nl: 'de winkel', example: 'La tienda está en la calle Mayor.', exampleNl: 'De winkel is in de Calle Mayor.' },
            { type: 'new', word: 'comprar', nl: 'kopen', example: 'Quiero comprar pan.', exampleNl: 'Ik wil brood kopen.' },
            { type: 'new', word: '¿cuánto cuesta?', nl: 'hoeveel kost het?', example: '¿Cuánto cuesta el vino?', exampleNl: 'Hoeveel kost de wijn?' },
            { type: 'new', word: 'el dinero', nl: 'het geld', example: 'No tengo dinero.', exampleNl: 'Ik heb geen geld.' },
            { type: 'select', prompt: 'de winkel', options: ['la tienda', 'la cuenta', 'la estación'], correct: 0 },
            { type: 'select', prompt: '¿Cuánto cuesta?', speak: '¿Cuánto cuesta?', options: ['Hoeveel kost het?', 'Waar is het?', 'Hoe laat is het?'], correct: 0 },
            { type: 'listen', target: 'el dinero', options: ['el dinero', 'la tienda', 'el vino'], correct: 0 },
            { type: 'fill', before: 'Quiero', after: 'pan.', nl: 'Ik wil brood kopen.', options: ['compro', 'comprar', 'compras'], correct: 1 },
            {
              type: 'match',
              pairs: [
                { nl: 'de winkel', target: 'la tienda' },
                { nl: 'het geld', target: 'el dinero' },
                { nl: 'kopen', target: 'comprar' },
                { nl: 'hoeveel kost het?', target: '¿cuánto cuesta?' },
              ],
            },
            { type: 'wordbank', nl: 'Hoeveel kost de koffie?', target: 'Cuánto cuesta el café', distractors: ['dinero', 'la', 'tienda', 'está'] },
            { type: 'type', nl: 'het geld', target: 'el dinero', accept: ['dinero', 'El dinero', 'el dinero.'] },
            { type: 'fill', before: 'No', after: 'dinero.', nl: 'Ik heb geen geld.', options: ['tengo', 'tiene', 'tienes'], correct: 0 },
          ],
        },
        {
          id: 'es-u6-l2',
          title: 'Op de markt',
          exercises: [
            { type: 'new', word: 'el mercado', nl: 'de markt', example: 'El mercado está en la plaza.', exampleNl: 'De markt is op het plein.' },
            { type: 'new', word: 'la fruta', nl: 'het fruit', example: 'La fruta del mercado está muy buena.', exampleNl: 'Het fruit van de markt is erg lekker.' },
            { type: 'new', word: 'barato', nl: 'goedkoop', example: 'El pan aquí es muy barato.', exampleNl: 'Het brood is hier erg goedkoop.' },
            { type: 'new', word: 'caro', nl: 'duur', example: 'El vino es muy caro.', exampleNl: 'De wijn is erg duur.' },
            { type: 'select', prompt: 'duur', options: ['barato', 'caro', 'claro'], correct: 1 },
            { type: 'select', prompt: 'El mercado', speak: 'El mercado', options: ['de winkel', 'de markt', 'het museum'], correct: 1 },
            { type: 'listen', target: 'barato', options: ['barato', 'caro', 'cuatro'], correct: 0 },
            { type: 'fill', before: 'La fruta', after: 'muy buena.', nl: 'Het fruit is erg lekker.', options: ['es', 'está', 'estás'], correct: 1 },
            {
              type: 'match',
              pairs: [
                { nl: 'de markt', target: 'el mercado' },
                { nl: 'het fruit', target: 'la fruta' },
                { nl: 'goedkoop', target: 'barato' },
                { nl: 'duur', target: 'caro' },
                { nl: 'het geld', target: 'el dinero' },
              ],
            },
            { type: 'wordbank', nl: 'De markt is op het plein.', target: 'El mercado está en la plaza', distractors: ['tienda', 'a', 'fruta', 'calle'] },
            { type: 'type', nl: 'het fruit', target: 'la fruta', accept: ['fruta', 'La fruta', 'la fruta.'] },
            { type: 'select', prompt: 'goedkoop', options: ['caro', 'bien', 'barato'], correct: 2 },
          ],
        },
        {
          id: 'es-u6-l3',
          title: 'Herhaling: boodschappen',
          exercises: [
            { type: 'type', nl: 'de winkel', target: 'la tienda', accept: ['tienda', 'La tienda', 'la tienda.'] },
            { type: 'wordbank', nl: 'Ik wil fruit kopen op de markt.', target: 'Quiero comprar fruta en el mercado', distractors: ['la', 'tienda', 'dinero', 'cuesta'] },
            { type: 'select', prompt: 'No tengo dinero.', speak: 'No tengo dinero.', options: ['Ik heb geen tijd.', 'Ik heb geen geld.', 'Ik heb geen fruit.'], correct: 1 },
            { type: 'fill', before: '¿Cuánto', after: 'la fruta?', nl: 'Hoeveel kost het fruit?', options: ['cuesta', 'cuestan', 'cuenta'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'kopen', target: 'comprar' },
                { nl: 'de winkel', target: 'la tienda' },
                { nl: 'duur', target: 'caro' },
                { nl: 'het fruit', target: 'la fruta' },
                { nl: 'hoeveel kost het?', target: '¿cuánto cuesta?' },
              ],
            },
            { type: 'type', nl: 'Hoeveel kost het brood?', target: 'Cuánto cuesta el pan', accept: ['¿Cuánto cuesta el pan?', 'cuánto cuesta el pan', 'Cuanto cuesta el pan', 'cuanto cuesta el pan'] },
            { type: 'listen', target: 'el mercado', options: ['el mercado', 'el museo', 'la tienda'], correct: 0 },
            { type: 'wordbank', nl: 'De wijn is erg duur.', target: 'El vino es muy caro', distractors: ['barato', 'está', 'la', 'cuesta'] },
            { type: 'fill', before: 'El pan es muy', after: '.', nl: 'Het brood is erg goedkoop.', options: ['barato', 'barata', 'baratos'], correct: 0 },
            { type: 'type', nl: 'de markt', target: 'el mercado', accept: ['mercado', 'El mercado', 'el mercado.'] },
            { type: 'wordbank', nl: 'Hoeveel kost een koffie met melk?', target: 'Cuánto cuesta un café con leche', distractors: ['el', 'dinero', 'una', 'barato'] },
            { type: 'type', nl: 'Ik heb geen geld.', target: 'No tengo dinero', accept: ['no tengo dinero', 'No tengo dinero.', 'no tengo dinero.'] },
          ],
        },
      ],
    },
    {
      id: 'es-u7',
      title: 'Huis & wonen',
      icon: '🏠',
      lessons: [
        {
          id: 'es-u7-l1',
          title: 'Mijn huis',
          exercises: [
            { type: 'new', word: 'la casa', nl: 'het huis', example: 'La casa de mi familia está en Sevilla.', exampleNl: 'Het huis van mijn familie staat in Sevilla.' },
            { type: 'new', word: 'la cocina', nl: 'de keuken', example: 'La cocina es muy grande.', exampleNl: 'De keuken is erg groot.' },
            { type: 'new', word: 'el baño', nl: 'de badkamer', example: '¿Dónde está el baño, por favor?', exampleNl: 'Waar is de badkamer, alsjeblieft?' },
            { type: 'new', word: 'la habitación', nl: 'de kamer', example: 'Mi habitación es pequeña.', exampleNl: 'Mijn kamer is klein.' },
            { type: 'select', prompt: 'het huis', options: ['la casa', 'la cocina', 'la calle'], correct: 0 },
            { type: 'select', prompt: 'La cocina', speak: 'La cocina', options: ['de kamer', 'de keuken', 'de badkamer'], correct: 1 },
            { type: 'listen', target: 'la habitación', options: ['la habitación', 'la estación', 'la cocina'], correct: 0 },
            { type: 'fill', before: 'La cocina', after: 'muy grande.', nl: 'De keuken is erg groot.', options: ['está', 'es', 'eres'], correct: 1 },
            {
              type: 'match',
              pairs: [
                { nl: 'het huis', target: 'la casa' },
                { nl: 'de keuken', target: 'la cocina' },
                { nl: 'de badkamer', target: 'el baño' },
                { nl: 'de kamer', target: 'la habitación' },
              ],
            },
            { type: 'wordbank', nl: 'Waar is de badkamer?', target: 'Dónde está el baño', distractors: ['la', 'cocina', 'casa', 'es'] },
            { type: 'type', nl: 'het huis', target: 'la casa', accept: ['casa', 'La casa', 'la casa.'] },
            { type: 'fill', before: 'Mi habitación es', after: '.', nl: 'Mijn kamer is klein.', options: ['pequeña', 'pequeño', 'pequeñas'], correct: 0 },
          ],
        },
        {
          id: 'es-u7-l2',
          title: 'In de kamer',
          exercises: [
            { type: 'new', word: 'la mesa', nl: 'de tafel', example: 'La mesa está en la cocina.', exampleNl: 'De tafel staat in de keuken.' },
            { type: 'new', word: 'la silla', nl: 'de stoel', example: 'Hay una silla en la habitación.', exampleNl: 'Er staat een stoel in de kamer.' },
            { type: 'new', word: 'la puerta', nl: 'de deur', example: 'La puerta está a la derecha.', exampleNl: 'De deur is aan de rechterkant.' },
            { type: 'new', word: 'la ventana', nl: 'het raam', example: 'La habitación tiene dos ventanas.', exampleNl: 'De kamer heeft twee ramen.' },
            { type: 'select', prompt: 'de deur', options: ['la puerta', 'la ventana', 'la mesa'], correct: 0 },
            { type: 'select', prompt: 'La silla', speak: 'La silla', options: ['de tafel', 'de stoel', 'de deur'], correct: 1 },
            { type: 'listen', target: 'la ventana', options: ['la ventana', 'la puerta', 'la mesa'], correct: 0 },
            { type: 'fill', before: 'La mesa', after: 'en la cocina.', nl: 'De tafel staat in de keuken.', options: ['es', 'está', 'hay'], correct: 1 },
            {
              type: 'match',
              pairs: [
                { nl: 'de tafel', target: 'la mesa' },
                { nl: 'de stoel', target: 'la silla' },
                { nl: 'de deur', target: 'la puerta' },
                { nl: 'het raam', target: 'la ventana' },
                { nl: 'het huis', target: 'la casa' },
              ],
            },
            { type: 'wordbank', nl: 'De deur is aan de rechterkant.', target: 'La puerta está a la derecha', distractors: ['ventana', 'izquierda', 'el', 'es'] },
            { type: 'type', nl: 'het raam', target: 'la ventana', accept: ['ventana', 'La ventana', 'la ventana.'] },
            { type: 'fill', before: 'La habitación', after: 'dos ventanas.', nl: 'De kamer heeft twee ramen.', options: ['tiene', 'tengo', 'tienes'], correct: 0 },
          ],
        },
        {
          id: 'es-u7-l3',
          title: 'Herhaling: huis & wonen',
          exercises: [
            { type: 'type', nl: 'de keuken', target: 'la cocina', accept: ['cocina', 'La cocina', 'la cocina.'] },
            { type: 'wordbank', nl: 'Mijn huis heeft vier kamers.', target: 'Mi casa tiene cuatro habitaciones', distractors: ['tengo', 'la', 'ventanas', 'dos'] },
            { type: 'select', prompt: 'La mesa está en la cocina.', speak: 'La mesa está en la cocina.', options: ['De stoel staat in de keuken.', 'De tafel staat in de keuken.', 'De tafel staat in de kamer.'], correct: 1 },
            { type: 'fill', before: 'La puerta está', after: 'la izquierda.', nl: 'De deur is aan de linkerkant.', options: ['a', 'en', 'de'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'de keuken', target: 'la cocina' },
                { nl: 'de badkamer', target: 'el baño' },
                { nl: 'het raam', target: 'la ventana' },
                { nl: 'de stoel', target: 'la silla' },
                { nl: 'de tafel', target: 'la mesa' },
              ],
            },
            { type: 'type', nl: 'Waar is de badkamer?', target: 'Dónde está el baño', accept: ['¿Dónde está el baño?', 'dónde está el baño', 'Donde esta el bano', 'donde esta el baño'] },
            { type: 'listen', target: 'la puerta', options: ['la puerta', 'la fruta', 'la plaza'], correct: 0 },
            { type: 'wordbank', nl: 'Er staat een stoel in de kamer.', target: 'Hay una silla en la habitación', distractors: ['mesa', 'está', 'el', 'dos'] },
            { type: 'fill', before: 'Mi familia', after: 'en una casa grande.', nl: 'Mijn familie woont in een groot huis.', options: ['vive', 'vivo', 'vives'], correct: 0 },
            { type: 'type', nl: 'de tafel', target: 'la mesa', accept: ['mesa', 'La mesa', 'la mesa.'] },
            { type: 'wordbank', nl: 'Het raam van de keuken is groot.', target: 'La ventana de la cocina es grande', distractors: ['puerta', 'está', 'el', 'pequeña'] },
            { type: 'type', nl: 'Mijn kamer is klein.', target: 'Mi habitación es pequeña', accept: ['mi habitación es pequeña', 'Mi habitacion es pequena', 'mi habitacion es pequeña', 'Mi habitación es pequeña.'] },
          ],
        },
      ],
    },
    {
      id: 'es-u8',
      title: 'Werk & school',
      icon: '💼',
      lessons: [
        {
          id: 'es-u8-l1',
          title: 'Op het werk',
          exercises: [
            { type: 'new', word: 'el trabajo', nl: 'het werk', example: 'Tengo un trabajo nuevo.', exampleNl: 'Ik heb een nieuwe baan.' },
            { type: 'new', word: 'trabajar', nl: 'werken', example: 'Quiero trabajar en España.', exampleNl: 'Ik wil in Spanje werken.' },
            { type: 'new', word: 'la oficina', nl: 'het kantoor', example: 'La oficina está en la plaza.', exampleNl: 'Het kantoor is op het plein.' },
            { type: 'new', word: 'el médico', nl: 'de arts', example: 'El médico trabaja en Sevilla.', exampleNl: 'De arts werkt in Sevilla.' },
            { type: 'select', prompt: 'werken', options: ['trabajar', 'comprar', 'comer'], correct: 0 },
            { type: 'select', prompt: 'La oficina', speak: 'La oficina', options: ['de winkel', 'het kantoor', 'de school'], correct: 1 },
            { type: 'listen', target: 'el trabajo', options: ['el trabajo', 'trabajar', 'trabaja'], correct: 0 },
            { type: 'fill', before: 'Mi padre', after: 'en una oficina.', nl: 'Mijn vader werkt op een kantoor.', options: ['trabaja', 'trabajo', 'trabajar'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'het werk', target: 'el trabajo' },
                { nl: 'werken', target: 'trabajar' },
                { nl: 'het kantoor', target: 'la oficina' },
                { nl: 'de arts', target: 'el médico' },
              ],
            },
            { type: 'wordbank', nl: 'Ik wil in Madrid werken.', target: 'Quiero trabajar en Madrid', distractors: ['trabajo', 'la', 'oficina', 'a'] },
            { type: 'type', nl: 'het kantoor', target: 'la oficina', accept: ['oficina', 'La oficina', 'la oficina.'] },
            { type: 'select', prompt: 'de arts', options: ['el médico', 'el amigo', 'el hombre'], correct: 0 },
          ],
        },
        {
          id: 'es-u8-l2',
          title: 'Naar school',
          exercises: [
            { type: 'new', word: 'la escuela', nl: 'de school', example: 'La escuela está cerca de casa.', exampleNl: 'De school is dichtbij huis.' },
            { type: 'new', word: 'el libro', nl: 'het boek', example: 'Quiero comprar un libro.', exampleNl: 'Ik wil een boek kopen.' },
            { type: 'new', word: 'estudiar', nl: 'studeren', example: 'Quiero estudiar español.', exampleNl: 'Ik wil Spaans studeren.' },
            { type: 'new', word: 'el profesor', nl: 'de leraar', example: 'El profesor se llama señor López.', exampleNl: 'De leraar heet meneer López.' },
            { type: 'select', prompt: 'het boek', options: ['el libro', 'el trabajo', 'la escuela'], correct: 0 },
            { type: 'select', prompt: 'Estudiar', speak: 'Estudiar', options: ['werken', 'studeren', 'kopen'], correct: 1 },
            { type: 'listen', target: 'la escuela', options: ['la escuela', 'la oficina', 'la tienda'], correct: 0 },
            { type: 'fill', before: 'Quiero', after: 'español.', nl: 'Ik wil Spaans studeren.', options: ['estudio', 'estudiar', 'estudia'], correct: 1 },
            {
              type: 'match',
              pairs: [
                { nl: 'de school', target: 'la escuela' },
                { nl: 'het boek', target: 'el libro' },
                { nl: 'studeren', target: 'estudiar' },
                { nl: 'de leraar', target: 'el profesor' },
                { nl: 'de arts', target: 'el médico' },
              ],
            },
            { type: 'wordbank', nl: 'De leraar werkt op de school.', target: 'El profesor trabaja en la escuela', distractors: ['médico', 'oficina', 'a', 'estudia'] },
            { type: 'type', nl: 'de school', target: 'la escuela', accept: ['escuela', 'La escuela', 'la escuela.'] },
            { type: 'fill', before: 'La escuela está', after: 'de casa.', nl: 'De school is dichtbij huis.', options: ['cerca', 'lejos', 'a'], correct: 0 },
          ],
        },
        {
          id: 'es-u8-l3',
          title: 'Herhaling: werk & school',
          exercises: [
            { type: 'type', nl: 'het werk', target: 'el trabajo', accept: ['trabajo', 'El trabajo', 'el trabajo.'] },
            { type: 'wordbank', nl: 'Mijn zus studeert in Madrid.', target: 'Mi hermana estudia en Madrid', distractors: ['estudiar', 'trabaja', 'la', 'escuela'] },
            { type: 'select', prompt: 'El médico trabaja en Sevilla.', speak: 'El médico trabaja en Sevilla.', options: ['De leraar werkt in Sevilla.', 'De arts werkt in Sevilla.', 'De arts woont in Sevilla.'], correct: 1 },
            { type: 'fill', before: 'Quiero comprar dos', after: '.', nl: 'Ik wil twee boeken kopen.', options: ['libros', 'libro', 'el libro'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'het werk', target: 'el trabajo' },
                { nl: 'het kantoor', target: 'la oficina' },
                { nl: 'het boek', target: 'el libro' },
                { nl: 'de leraar', target: 'el profesor' },
                { nl: 'studeren', target: 'estudiar' },
              ],
            },
            { type: 'type', nl: 'Ik wil Spaans studeren.', target: 'Quiero estudiar español', accept: ['quiero estudiar español', 'Quiero estudiar espanol', 'quiero estudiar espanol', 'Quiero estudiar español.'] },
            { type: 'listen', target: 'el profesor', options: ['el profesor', 'el médico', 'la profesora'], correct: 0 },
            { type: 'wordbank', nl: 'Mijn moeder werkt op een kantoor.', target: 'Mi madre trabaja en una oficina', distractors: ['el', 'escuela', 'estudia', 'trabajo'] },
            { type: 'fill', before: 'Mi amigo', after: 'médico.', nl: 'Mijn vriend is arts.', options: ['es', 'está', 'tiene'], correct: 0 },
            { type: 'type', nl: 'de leraar', target: 'el profesor', accept: ['profesor', 'El profesor', 'el profesor.'] },
            { type: 'wordbank', nl: 'Ik werk vandaag niet.', target: 'Hoy no trabajo', distractors: ['trabajar', 'mañana', 'es', 'el'] },
            { type: 'type', nl: 'het boek', target: 'el libro', accept: ['libro', 'El libro', 'el libro.'] },
          ],
        },
      ],
    },
    {
      id: 'es-u9',
      title: 'Gesprekken voeren',
      icon: '💬',
      lessons: [
        {
          id: 'es-u9-l1',
          title: 'Een praatje maken',
          exercises: [
            { type: 'new', word: 'perdona', nl: 'pardon / sorry', example: 'Perdona, ¿qué hora es?', exampleNl: 'Pardon, hoe laat is het?' },
            { type: 'new', word: 'también', nl: 'ook', example: 'Yo también quiero un café.', exampleNl: 'Ik wil ook een koffie.' },
            { type: 'new', word: 'claro', nl: 'natuurlijk', example: '¿Un café? ¡Claro!', exampleNl: 'Een koffie? Natuurlijk!' },
            { type: 'new', word: '¿de dónde eres?', nl: 'waar kom je vandaan?', example: '¿De dónde eres? Soy de Ámsterdam.', exampleNl: 'Waar kom je vandaan? Ik kom uit Amsterdam.' },
            { type: 'select', prompt: 'ook', options: ['también', 'claro', 'bien'], correct: 0 },
            { type: 'select', prompt: 'Perdona', speak: 'Perdona', options: ['natuurlijk', 'pardon', 'alsjeblieft'], correct: 1 },
            { type: 'listen', target: 'claro', options: ['claro', 'caro', 'cuatro'], correct: 0 },
            { type: 'fill', before: '¿De dónde eres? —', after: 'de Madrid.', nl: 'Waar kom je vandaan? — Ik kom uit Madrid.', options: ['Soy', 'Estoy', 'Eres'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'pardon', target: 'perdona' },
                { nl: 'ook', target: 'también' },
                { nl: 'natuurlijk', target: 'claro' },
                { nl: 'waar kom je vandaan?', target: '¿de dónde eres?' },
              ],
            },
            { type: 'wordbank', nl: 'Pardon, waar is het station?', target: 'Perdona dónde está la estación', distractors: ['claro', 'el', 'qué', 'también'] },
            { type: 'type', nl: 'ook', target: 'también', accept: ['También', 'tambien', 'también.'] },
            { type: 'select', prompt: 'Yo también quiero un café.', speak: 'Yo también quiero un café.', options: ['Ik wil ook een koffie.', 'Ik wil ook een biertje.', 'Ik wil geen koffie.'], correct: 0 },
          ],
        },
        {
          id: 'es-u9-l2',
          title: 'Afspreken',
          exercises: [
            { type: 'new', word: 'hasta luego', nl: 'tot straks', example: '¡Hasta luego, Carmen!', exampleNl: 'Tot straks, Carmen!' },
            { type: 'new', word: 'lo siento', nl: 'het spijt me', example: 'Lo siento, no tengo dinero.', exampleNl: 'Het spijt me, ik heb geen geld.' },
            { type: 'new', word: 'vale', nl: 'oké / prima', example: '¿En la plaza a las cuatro? Vale.', exampleNl: 'Op het plein om vier uur? Oké.' },
            { type: 'new', word: 'nos vemos', nl: 'we zien elkaar', example: 'Nos vemos mañana en la oficina.', exampleNl: 'We zien elkaar morgen op kantoor.' },
            { type: 'select', prompt: 'tot straks', options: ['hasta luego', 'lo siento', 'buenos días'], correct: 0 },
            { type: 'select', prompt: 'Lo siento', speak: 'Lo siento', options: ['het spijt me', 'tot straks', 'oké'], correct: 0 },
            { type: 'listen', target: 'vale', options: ['vale', 'bien', 'calle'], correct: 0 },
            { type: 'fill', before: 'Nos vemos', after: 'las tres.', nl: 'We zien elkaar om drie uur.', options: ['a', 'en', 'de'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'tot straks', target: 'hasta luego' },
                { nl: 'het spijt me', target: 'lo siento' },
                { nl: 'oké', target: 'vale' },
                { nl: 'we zien elkaar', target: 'nos vemos' },
              ],
            },
            { type: 'wordbank', nl: 'Het spijt me, ik heb geen geld.', target: 'Lo siento no tengo dinero', distractors: ['vale', 'tiene', 'el', 'hasta'] },
            { type: 'type', nl: 'tot straks', target: 'hasta luego', accept: ['Hasta luego', 'hasta luego.', 'Hasta luego.'] },
            { type: 'wordbank', nl: 'We zien elkaar morgen op het plein.', target: 'Nos vemos mañana en la plaza', distractors: ['hoy', 'vale', 'a', 'luego'] },
          ],
        },
        {
          id: 'es-u9-l3',
          title: 'Herhaling: dagelijks leven',
          exercises: [
            { type: 'type', nl: 'Pardon, hoe laat is het?', target: 'Perdona qué hora es', accept: ['Perdona, ¿qué hora es?', 'perdona qué hora es', 'Perdona, qué hora es', 'perdona que hora es'] },
            { type: 'wordbank', nl: 'Ik wil brood kopen op de markt.', target: 'Quiero comprar pan en el mercado', distractors: ['fruta', 'tienda', 'la', 'dinero'] },
            { type: 'select', prompt: 'Nos vemos mañana en la oficina.', speak: 'Nos vemos mañana en la oficina.', options: ['We zien elkaar vandaag op kantoor.', 'We zien elkaar morgen op kantoor.', 'We zien elkaar morgen op school.'], correct: 1 },
            { type: 'fill', before: 'Perdona, ¿', after: 'está el baño?', nl: 'Pardon, waar is de badkamer?', options: ['dónde', 'cómo', 'qué'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'ook', target: 'también' },
                { nl: 'de school', target: 'la escuela' },
                { nl: 'het geld', target: 'el dinero' },
                { nl: 'het raam', target: 'la ventana' },
                { nl: 'tot straks', target: 'hasta luego' },
              ],
            },
            { type: 'type', nl: 'Het spijt me.', target: 'Lo siento', accept: ['lo siento', 'Lo siento.', 'lo siento.'] },
            { type: 'listen', target: 'nos vemos mañana', options: ['nos vemos mañana', 'nos vemos hoy', 'hasta luego mañana'], correct: 0 },
            { type: 'wordbank', nl: 'Het huis heeft een grote keuken.', target: 'La casa tiene una cocina grande', distractors: ['pequeña', 'ventana', 'el', 'es'] },
            { type: 'fill', before: 'Yo', after: 'quiero una cerveza.', nl: 'Ik wil ook een biertje.', options: ['también', 'tampoco', 'claro'], correct: 0 },
            { type: 'type', nl: 'Hoeveel kost het boek?', target: 'Cuánto cuesta el libro', accept: ['¿Cuánto cuesta el libro?', 'cuánto cuesta el libro', 'Cuanto cuesta el libro', 'cuanto cuesta el libro'] },
            { type: 'wordbank', nl: 'Morgen studeer ik op school.', target: 'Mañana estudio en la escuela', distractors: ['estudiar', 'trabajo', 'hoy', 'el'] },
            { type: 'type', nl: 'We zien elkaar om drie uur.', target: 'Nos vemos a las tres', accept: ['nos vemos a las tres', 'Nos vemos a las tres.', 'nos vemos a las tres.'] },
          ],
        },
      ],
    },
  ],
}
