import type { Section } from '../../types'

export const section: Section = {
  title: 'Sectie 3 · Op weg naar A2',
  cefr: 'A2',
  units: [
    {
      id: 'es-u10',
      title: 'Reizen & vervoer',
      icon: '✈️',
      lessons: [
        {
          id: 'es-u10-l1',
          title: 'Op reis',
          exercises: [
            { type: 'new', word: 'el viaje', nl: 'de reis', example: 'El viaje a Barcelona es largo.', exampleNl: 'De reis naar Barcelona is lang.' },
            { type: 'new', word: 'el billete', nl: 'het kaartje', example: 'Quiero un billete para Madrid.', exampleNl: 'Ik wil graag een kaartje naar Madrid.' },
            { type: 'new', word: 'el avión', nl: 'het vliegtuig', example: 'El avión sale a las diez.', exampleNl: 'Het vliegtuig vertrekt om tien uur.' },
            { type: 'new', word: 'el aeropuerto', nl: 'het vliegveld', example: '¿Dónde está el aeropuerto?', exampleNl: 'Waar is het vliegveld?' },
            { type: 'select', prompt: 'het vliegtuig', options: ['el aeropuerto', 'el avión', 'el billete'], correct: 1 },
            { type: 'select', prompt: 'el billete', speak: 'El billete', options: ['de koffer', 'het kaartje', 'de reis'], correct: 1 },
            { type: 'listen', target: 'el avión', options: ['el avión', 'el aeropuerto', 'el viaje'], correct: 0 },
            { type: 'fill', before: 'El avión sale', after: 'las diez.', nl: 'Het vliegtuig vertrekt om tien uur.', options: ['a', 'en', 'de'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'de reis', target: 'el viaje' },
                { nl: 'het kaartje', target: 'el billete' },
                { nl: 'het vliegtuig', target: 'el avión' },
                { nl: 'het vliegveld', target: 'el aeropuerto' },
              ],
            },
            { type: 'wordbank', nl: 'Waar is het vliegveld?', target: 'Dónde está el aeropuerto', distractors: ['avión', 'la', 'billete'] },
            { type: 'type', nl: 'het kaartje', target: 'el billete', accept: ['billete', 'El billete', 'el billete.'] },
            { type: 'select', prompt: 'de reis', options: ['el viaje', 'el avión', 'la estación'], correct: 0 },
          ],
        },
        {
          id: 'es-u10-l2',
          title: 'Met bus en taxi',
          exercises: [
            { type: 'new', word: 'el autobús', nl: 'de bus', example: 'El autobús llega en cinco minutos.', exampleNl: 'De bus komt over vijf minuten.' },
            { type: 'new', word: 'el taxi', nl: 'de taxi', example: 'Quiero un taxi, por favor.', exampleNl: 'Ik wil graag een taxi, alsjeblieft.' },
            { type: 'new', word: 'la maleta', nl: 'de koffer', example: 'Mi maleta está en el tren.', exampleNl: 'Mijn koffer is in de trein.' },
            { type: 'new', word: 'el hotel', nl: 'het hotel', example: 'El hotel está en la Plaza Mayor.', exampleNl: 'Het hotel is aan de Plaza Mayor.' },
            { type: 'select', prompt: 'de koffer', options: ['la maleta', 'el hotel', 'el autobús'], correct: 0 },
            { type: 'select', prompt: 'el autobús', speak: 'El autobús', options: ['de trein', 'de bus', 'de taxi'], correct: 1 },
            { type: 'listen', target: 'la maleta', options: ['la maleta', 'la cuenta', 'la calle'], correct: 0 },
            { type: 'fill', before: 'El hotel está', after: 'la Plaza Mayor.', nl: 'Het hotel is aan de Plaza Mayor.', options: ['en', 'a', 'de'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'de bus', target: 'el autobús' },
                { nl: 'de koffer', target: 'la maleta' },
                { nl: 'het hotel', target: 'el hotel' },
                { nl: 'de taxi', target: 'el taxi' },
                { nl: 'de trein', target: 'el tren' },
              ],
            },
            { type: 'wordbank', nl: 'Mijn koffer is in de trein.', target: 'Mi maleta está en el tren', distractors: ['hotel', 'la', 'autobús', 'a'] },
            { type: 'type', nl: 'het hotel', target: 'el hotel', accept: ['hotel', 'El hotel', 'el hotel.'] },
            { type: 'fill', before: 'El autobús llega', after: 'cinco minutos.', nl: 'De bus komt over vijf minuten.', options: ['en', 'a', 'por'], correct: 0 },
          ],
        },
        {
          id: 'es-u10-l3',
          title: 'Herhaling: op reis',
          exercises: [
            { type: 'type', nl: 'het vliegtuig', target: 'el avión', accept: ['avión', 'avion', 'El avión', 'el avion'] },
            { type: 'wordbank', nl: 'Ik wil graag een kaartje naar Sevilla.', target: 'Quiero un billete para Sevilla', distractors: ['maleta', 'el', 'viaje', 'tren'] },
            { type: 'select', prompt: 'El avión sale a las diez.', speak: 'El avión sale a las diez.', options: ['Het vliegtuig vertrekt om tien uur.', 'Het vliegtuig komt om tien uur aan.', 'De trein vertrekt om tien uur.'], correct: 0 },
            { type: 'type', nl: 'de bus', target: 'el autobús', accept: ['autobús', 'autobus', 'El autobús', 'el autobus'] },
            {
              type: 'match',
              pairs: [
                { nl: 'de reis', target: 'el viaje' },
                { nl: 'het kaartje', target: 'el billete' },
                { nl: 'de koffer', target: 'la maleta' },
                { nl: 'het vliegveld', target: 'el aeropuerto' },
                { nl: 'het station', target: 'la estación' },
              ],
            },
            { type: 'fill', before: 'Mi maleta está', after: 'el hotel.', nl: 'Mijn koffer is in het hotel.', options: ['a', 'en', 'de'], correct: 1 },
            { type: 'listen', target: 'el aeropuerto', options: ['el aeropuerto', 'el autobús', 'el avión'], correct: 0 },
            { type: 'wordbank', nl: 'De bus komt over vijf minuten.', target: 'El autobús llega en cinco minutos', distractors: ['sale', 'taxi', 'a', 'la'] },
            { type: 'type', nl: 'de koffer', target: 'la maleta', accept: ['maleta', 'La maleta', 'la maleta.'] },
            { type: 'type', nl: 'Waar is het hotel?', target: 'Dónde está el hotel', accept: ['¿Dónde está el hotel?', 'dónde está el hotel', 'Donde esta el hotel', 'donde esta el hotel'] },
            { type: 'fill', before: 'Quiero un billete', after: 'Barcelona.', nl: 'Ik wil graag een kaartje naar Barcelona.', options: ['para', 'de', 'en'], correct: 0 },
            { type: 'wordbank', nl: 'De taxi is aan de rechterkant.', target: 'El taxi está a la derecha', distractors: ['izquierda', 'en', 'autobús'] },
          ],
        },
      ],
    },
    {
      id: 'es-u11',
      title: 'Gezondheid & lichaam',
      icon: '🌿',
      lessons: [
        {
          id: 'es-u11-l1',
          title: 'Hoe voel je je?',
          exercises: [
            { type: 'new', word: 'la cabeza', nl: 'het hoofd', example: 'Me duele la cabeza.', exampleNl: 'Ik heb hoofdpijn.' },
            { type: 'new', word: 'me duele', nl: 'ik heb pijn aan', example: 'Me duele mucho la cabeza.', exampleNl: 'Mijn hoofd doet erg pijn.' },
            { type: 'new', word: 'enfermo', nl: 'ziek', example: 'Mi hermano está enfermo.', exampleNl: 'Mijn broer is ziek.' },
            { type: 'new', word: 'el médico', nl: 'de dokter', example: '¿Dónde está el médico?', exampleNl: 'Waar is de dokter?' },
            { type: 'select', prompt: 'het hoofd', options: ['el médico', 'la cabeza', 'la calle'], correct: 1 },
            { type: 'select', prompt: 'enfermo', speak: 'Enfermo', options: ['moe', 'ziek', 'gezond'], correct: 1 },
            { type: 'listen', target: 'me duele la cabeza', options: ['me duele la cabeza', 'me duele la muela', 'me duele mucho'], correct: 0 },
            { type: 'fill', before: 'Mi hermano', after: 'enfermo.', nl: 'Mijn broer is ziek.', options: ['es', 'está', 'estás'], correct: 1 },
            {
              type: 'match',
              pairs: [
                { nl: 'het hoofd', target: 'la cabeza' },
                { nl: 'de dokter', target: 'el médico' },
                { nl: 'ziek', target: 'enfermo' },
                { nl: 'ik heb pijn aan', target: 'me duele' },
              ],
            },
            { type: 'wordbank', nl: 'Ik heb hoofdpijn.', target: 'Me duele la cabeza', distractors: ['el', 'médico', 'enfermo', 'estoy'] },
            { type: 'type', nl: 'de dokter', target: 'el médico', accept: ['médico', 'medico', 'El médico', 'el medico'] },
            { type: 'select', prompt: 'Me duele la cabeza.', speak: 'Me duele la cabeza.', options: ['Ik heb buikpijn.', 'Ik heb hoofdpijn.', 'Ik ben ziek.'], correct: 1 },
          ],
        },
        {
          id: 'es-u11-l2',
          title: 'Bij de apotheek',
          exercises: [
            { type: 'new', word: 'la farmacia', nl: 'de apotheek', example: 'La farmacia está cerca de la plaza.', exampleNl: 'De apotheek is dicht bij het plein.' },
            { type: 'new', word: 'necesito', nl: 'ik heb nodig', example: 'Necesito un médico.', exampleNl: 'Ik heb een dokter nodig.' },
            { type: 'new', word: 'la medicina', nl: 'het medicijn', example: 'Esta medicina es muy buena.', exampleNl: 'Dit medicijn is erg goed.' },
            { type: 'new', word: 'cansado', nl: 'moe', example: 'Estoy muy cansado.', exampleNl: 'Ik ben erg moe.' },
            { type: 'select', prompt: 'de apotheek', options: ['la farmacia', 'la medicina', 'la estación'], correct: 0 },
            { type: 'select', prompt: 'cansado', speak: 'Cansado', options: ['ziek', 'moe', 'druk'], correct: 1 },
            { type: 'listen', target: 'la farmacia', options: ['la farmacia', 'la familia', 'la estación'], correct: 0 },
            { type: 'fill', before: 'Mi padre está muy', after: '.', nl: 'Mijn vader is erg moe.', options: ['cansada', 'cansados', 'cansado'], correct: 2 },
            {
              type: 'match',
              pairs: [
                { nl: 'de apotheek', target: 'la farmacia' },
                { nl: 'het medicijn', target: 'la medicina' },
                { nl: 'moe', target: 'cansado' },
                { nl: 'ik heb nodig', target: 'necesito' },
                { nl: 'ziek', target: 'enfermo' },
              ],
            },
            { type: 'wordbank', nl: 'Ik heb een medicijn nodig.', target: 'Necesito una medicina', distractors: ['quiero', 'la', 'farmacia', 'un'] },
            { type: 'type', nl: 'de apotheek', target: 'la farmacia', accept: ['farmacia', 'La farmacia', 'la farmacia.'] },
            { type: 'fill', before: 'Necesito', after: 'medicina.', nl: 'Ik heb een medicijn nodig.', options: ['un', 'una', 'el'], correct: 1 },
          ],
        },
        {
          id: 'es-u11-l3',
          title: 'Herhaling: gezondheid',
          exercises: [
            { type: 'type', nl: 'het hoofd', target: 'la cabeza', accept: ['cabeza', 'La cabeza', 'la cabeza.'] },
            { type: 'wordbank', nl: 'Waar is de apotheek?', target: 'Dónde está la farmacia', distractors: ['médico', 'el', 'medicina'] },
            { type: 'select', prompt: 'Necesito un médico.', speak: 'Necesito un médico.', options: ['Ik heb een medicijn nodig.', 'Ik heb een dokter nodig.', 'Ik wil naar de apotheek.'], correct: 1 },
            { type: 'type', nl: 'ziek', target: 'enfermo', accept: ['Enfermo', 'enferma', 'enfermo.'] },
            { type: 'fill', before: 'Me', after: 'la cabeza.', nl: 'Ik heb hoofdpijn.', options: ['duele', 'duelo', 'dueles'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'moe', target: 'cansado' },
                { nl: 'de dokter', target: 'el médico' },
                { nl: 'het medicijn', target: 'la medicina' },
                { nl: 'het hoofd', target: 'la cabeza' },
                { nl: 'de apotheek', target: 'la farmacia' },
              ],
            },
            { type: 'listen', target: 'necesito una medicina', options: ['necesito una medicina', 'necesito un médico', 'quiero una medicina'], correct: 0 },
            { type: 'wordbank', nl: 'Mijn moeder is ziek.', target: 'Mi madre está enferma', distractors: ['enfermo', 'es', 'cansada', 'el'] },
            { type: 'type', nl: 'Ik ben erg moe.', target: 'Estoy muy cansado', accept: ['estoy muy cansado', 'Estoy muy cansada', 'estoy muy cansada', 'Estoy muy cansado.'] },
            { type: 'fill', before: 'La farmacia está cerca', after: 'la plaza.', nl: 'De apotheek is dicht bij het plein.', options: ['de', 'a', 'en'], correct: 0 },
            { type: 'type', nl: 'Ik heb een dokter nodig.', target: 'Necesito un médico', accept: ['necesito un médico', 'Necesito un medico', 'necesito un medico', 'Necesito un médico.'] },
            { type: 'wordbank', nl: 'Mijn hoofd doet erg pijn.', target: 'Me duele mucho la cabeza', distractors: ['el', 'estómago', 'está'] },
          ],
        },
      ],
    },
    {
      id: 'es-u12',
      title: 'Weer & seizoenen',
      icon: '🌦️',
      lessons: [
        {
          id: 'es-u12-l1',
          title: 'Wat voor weer is het?',
          exercises: [
            { type: 'new', word: 'hoy', nl: 'vandaag', example: 'Hoy estoy en Madrid.', exampleNl: 'Vandaag ben ik in Madrid.' },
            { type: 'new', word: 'hace sol', nl: 'de zon schijnt', example: 'Hoy hace sol en Valencia.', exampleNl: 'Vandaag schijnt de zon in Valencia.' },
            { type: 'new', word: 'llueve', nl: 'het regent', example: 'En Galicia llueve mucho.', exampleNl: 'In Galicië regent het veel.' },
            { type: 'new', word: 'hace frío', nl: 'het is koud', example: 'Hoy hace frío en la calle.', exampleNl: 'Het is vandaag koud op straat.' },
            { type: 'select', prompt: 'het regent', options: ['hace sol', 'llueve', 'hace frío'], correct: 1 },
            { type: 'select', prompt: 'hace frío', speak: 'Hace frío', options: ['het is warm', 'de zon schijnt', 'het is koud'], correct: 2 },
            { type: 'listen', target: 'llueve', options: ['llueve', 'nueve', 'mueve'], correct: 0 },
            { type: 'fill', before: 'Hoy', after: 'sol.', nl: 'Vandaag schijnt de zon.', options: ['hace', 'está', 'es'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'vandaag', target: 'hoy' },
                { nl: 'het regent', target: 'llueve' },
                { nl: 'het is koud', target: 'hace frío' },
                { nl: 'de zon schijnt', target: 'hace sol' },
              ],
            },
            { type: 'wordbank', nl: 'Vandaag schijnt de zon in Valencia.', target: 'Hoy hace sol en Valencia', distractors: ['llueve', 'frío', 'está'] },
            { type: 'type', nl: 'vandaag', target: 'hoy', accept: ['Hoy', 'hoy.', 'Hoy.'] },
            { type: 'select', prompt: 'En Galicia llueve mucho.', speak: 'En Galicia llueve mucho.', options: ['In Galicië is het erg koud.', 'In Galicië regent het veel.', 'In Galicië schijnt vaak de zon.'], correct: 1 },
          ],
        },
        {
          id: 'es-u12-l2',
          title: 'De seizoenen',
          exercises: [
            { type: 'new', word: 'hace calor', nl: 'het is warm', example: 'En Sevilla hace mucho calor.', exampleNl: 'In Sevilla is het erg warm.' },
            { type: 'new', word: 'el verano', nl: 'de zomer', example: 'En verano hace calor.', exampleNl: 'In de zomer is het warm.' },
            { type: 'new', word: 'el invierno', nl: 'de winter', example: 'En invierno llueve mucho.', exampleNl: 'In de winter regent het veel.' },
            { type: 'new', word: 'la primavera', nl: 'de lente', example: 'La primavera es muy bonita.', exampleNl: 'De lente is erg mooi.' },
            { type: 'select', prompt: 'de zomer', options: ['el invierno', 'el verano', 'la primavera'], correct: 1 },
            { type: 'select', prompt: 'el invierno', speak: 'El invierno', options: ['de winter', 'de herfst', 'de lente'], correct: 0 },
            { type: 'listen', target: 'la primavera', options: ['la primavera', 'el verano', 'la primera'], correct: 0 },
            { type: 'fill', before: 'En Sevilla hace mucho', after: 'en verano.', nl: 'In Sevilla is het in de zomer erg warm.', options: ['frío', 'calor', 'sol'], correct: 1 },
            {
              type: 'match',
              pairs: [
                { nl: 'de zomer', target: 'el verano' },
                { nl: 'de winter', target: 'el invierno' },
                { nl: 'de lente', target: 'la primavera' },
                { nl: 'het is warm', target: 'hace calor' },
                { nl: 'het is koud', target: 'hace frío' },
              ],
            },
            { type: 'wordbank', nl: 'In de winter regent het veel.', target: 'En invierno llueve mucho', distractors: ['verano', 'hace', 'calor', 'el'] },
            { type: 'type', nl: 'de zomer', target: 'el verano', accept: ['verano', 'El verano', 'el verano.'] },
            { type: 'fill', before: 'La primavera', after: 'muy bonita.', nl: 'De lente is erg mooi.', options: ['está', 'es', 'hace'], correct: 1 },
          ],
        },
        {
          id: 'es-u12-l3',
          title: 'Herhaling: het weer',
          exercises: [
            { type: 'type', nl: 'het regent', target: 'llueve', accept: ['Llueve', 'llueve.', 'Llueve.'] },
            { type: 'wordbank', nl: 'Vandaag is het koud op straat.', target: 'Hoy hace frío en la calle', distractors: ['calor', 'llueve', 'está'] },
            { type: 'select', prompt: 'En invierno llueve mucho.', speak: 'En invierno llueve mucho.', options: ['In de winter sneeuwt het veel.', 'In de winter regent het veel.', 'In de zomer regent het veel.'], correct: 1 },
            { type: 'type', nl: 'de winter', target: 'el invierno', accept: ['invierno', 'El invierno', 'el invierno.'] },
            { type: 'fill', before: 'En verano', after: 'calor.', nl: 'In de zomer is het warm.', options: ['hace', 'es', 'está'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'vandaag', target: 'hoy' },
                { nl: 'de lente', target: 'la primavera' },
                { nl: 'de zon schijnt', target: 'hace sol' },
                { nl: 'het regent', target: 'llueve' },
                { nl: 'de zomer', target: 'el verano' },
              ],
            },
            { type: 'listen', target: 'hace mucho calor', options: ['hace mucho calor', 'hace mucho frío', 'hace mucho sol'], correct: 0 },
            { type: 'wordbank', nl: 'De lente in Madrid is erg mooi.', target: 'La primavera en Madrid es muy bonita', distractors: ['está', 'invierno', 'hace'] },
            { type: 'type', nl: 'Het is vandaag warm.', target: 'Hoy hace calor', accept: ['hoy hace calor', 'Hoy hace calor.', 'Hace calor hoy'] },
            { type: 'fill', before: 'Hoy', after: 'mucho en Galicia.', nl: 'Vandaag regent het veel in Galicië.', options: ['llueve', 'lluevo', 'llueves'], correct: 0 },
            { type: 'type', nl: 'het is koud', target: 'hace frío', accept: ['Hace frío', 'hace frio', 'Hace frio'] },
            { type: 'wordbank', nl: 'In de zomer is het erg warm in Sevilla.', target: 'En verano hace mucho calor en Sevilla', distractors: ['frío', 'el', 'invierno'] },
          ],
        },
      ],
    },
    {
      id: 'es-u13',
      title: 'Uitgaan & cultuur',
      icon: '🎭',
      lessons: [
        {
          id: 'es-u13-l1',
          title: 'Feest & muziek',
          exercises: [
            { type: 'new', word: 'la fiesta', nl: 'het feest', example: 'La fiesta empieza a las diez.', exampleNl: 'Het feest begint om tien uur.' },
            { type: 'new', word: 'la música', nl: 'de muziek', example: 'La música española es muy bonita.', exampleNl: 'Spaanse muziek is erg mooi.' },
            { type: 'new', word: 'me gusta', nl: 'ik vind leuk / ik hou van', example: 'Me gusta la música.', exampleNl: 'Ik hou van muziek.' },
            { type: 'new', word: 'bailar', nl: 'dansen', example: 'Quiero bailar en la fiesta.', exampleNl: 'Ik wil dansen op het feest.' },
            { type: 'select', prompt: 'het feest', options: ['la música', 'la fiesta', 'la familia'], correct: 1 },
            { type: 'select', prompt: 'me gusta', speak: 'Me gusta', options: ['ik wil', 'ik vind leuk', 'ik heb nodig'], correct: 1 },
            { type: 'listen', target: 'me gusta la música', options: ['me gusta la música', 'me gusta la fiesta', 'me gusta bailar'], correct: 0 },
            { type: 'fill', before: 'Me', after: 'la música española.', nl: 'Ik hou van Spaanse muziek.', options: ['gusta', 'gusto', 'gustas'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'het feest', target: 'la fiesta' },
                { nl: 'de muziek', target: 'la música' },
                { nl: 'dansen', target: 'bailar' },
                { nl: 'ik vind leuk', target: 'me gusta' },
              ],
            },
            { type: 'wordbank', nl: 'Ik wil dansen op het feest.', target: 'Quiero bailar en la fiesta', distractors: ['música', 'me', 'gusta', 'el'] },
            { type: 'type', nl: 'de muziek', target: 'la música', accept: ['música', 'musica', 'La música', 'la musica'] },
            { type: 'select', prompt: 'dansen', options: ['cantar', 'bailar', 'comer'], correct: 1 },
          ],
        },
        {
          id: 'es-u13-l2',
          title: 'Film & theater',
          exercises: [
            { type: 'new', word: 'el cine', nl: 'de bioscoop', example: 'El cine está cerca de la plaza.', exampleNl: 'De bioscoop is dicht bij het plein.' },
            { type: 'new', word: 'la película', nl: 'de film', example: 'La película empieza a las nueve.', exampleNl: 'De film begint om negen uur.' },
            { type: 'new', word: 'el teatro', nl: 'het theater', example: 'Me gusta mucho el teatro.', exampleNl: 'Ik hou erg van theater.' },
            { type: 'new', word: 'la entrada', nl: 'het toegangskaartje', example: 'Quiero dos entradas, por favor.', exampleNl: 'Ik wil graag twee kaartjes, alsjeblieft.' },
            { type: 'select', prompt: 'de film', options: ['la entrada', 'el cine', 'la película'], correct: 2 },
            { type: 'select', prompt: 'el teatro', speak: 'El teatro', options: ['het theater', 'de bioscoop', 'het museum'], correct: 0 },
            { type: 'listen', target: 'la película', options: ['la película', 'la música', 'la entrada'], correct: 0 },
            { type: 'fill', before: 'Quiero dos', after: ', por favor.', nl: 'Ik wil graag twee kaartjes, alsjeblieft.', options: ['entrada', 'entradas', 'entrado'], correct: 1 },
            {
              type: 'match',
              pairs: [
                { nl: 'de bioscoop', target: 'el cine' },
                { nl: 'de film', target: 'la película' },
                { nl: 'het theater', target: 'el teatro' },
                { nl: 'het toegangskaartje', target: 'la entrada' },
                { nl: 'de muziek', target: 'la música' },
              ],
            },
            { type: 'wordbank', nl: 'De film begint om negen uur.', target: 'La película empieza a las nueve', distractors: ['el', 'cine', 'sale', 'teatro'] },
            { type: 'type', nl: 'de bioscoop', target: 'el cine', accept: ['cine', 'El cine', 'el cine.'] },
            { type: 'fill', before: 'Me gusta mucho', after: 'teatro.', nl: 'Ik hou erg van theater.', options: ['la', 'el', 'un'], correct: 1 },
          ],
        },
        {
          id: 'es-u13-l3',
          title: 'Herhaling: uitgaan',
          exercises: [
            { type: 'type', nl: 'het feest', target: 'la fiesta', accept: ['fiesta', 'La fiesta', 'la fiesta.'] },
            { type: 'wordbank', nl: 'Ik wil graag twee kaartjes voor de film.', target: 'Quiero dos entradas para la película', distractors: ['el', 'cine', 'entrada', 'a'] },
            { type: 'select', prompt: 'Me gusta mucho el teatro.', speak: 'Me gusta mucho el teatro.', options: ['Ik hou erg van theater.', 'Ik hou erg van muziek.', 'Ik ga vaak naar de bioscoop.'], correct: 0 },
            { type: 'type', nl: 'de film', target: 'la película', accept: ['película', 'pelicula', 'La película', 'la pelicula'] },
            { type: 'fill', before: 'La fiesta empieza', after: 'las diez.', nl: 'Het feest begint om tien uur.', options: ['a', 'en', 'de'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'dansen', target: 'bailar' },
                { nl: 'het toegangskaartje', target: 'la entrada' },
                { nl: 'de bioscoop', target: 'el cine' },
                { nl: 'het theater', target: 'el teatro' },
                { nl: 'het feest', target: 'la fiesta' },
              ],
            },
            { type: 'listen', target: 'quiero bailar', options: ['quiero bailar', 'quiero cantar', 'quiero comer'], correct: 0 },
            { type: 'wordbank', nl: 'Ik hou van Spaanse muziek.', target: 'Me gusta la música española', distractors: ['el', 'fiesta', 'bailar', 'quiero'] },
            { type: 'type', nl: 'Ik hou van dansen.', target: 'Me gusta bailar', accept: ['me gusta bailar', 'Me gusta bailar.', 'me gusta bailar.'] },
            { type: 'fill', before: 'Me', after: 'las fiestas españolas.', nl: 'Ik hou van Spaanse feesten.', options: ['gusta', 'gustan', 'gusto'], correct: 1 },
            { type: 'type', nl: 'het theater', target: 'el teatro', accept: ['teatro', 'El teatro', 'el teatro.'] },
            { type: 'wordbank', nl: 'De bioscoop is dicht bij het plein.', target: 'El cine está cerca de la plaza', distractors: ['teatro', 'en', 'lejos', 'museo'] },
          ],
        },
      ],
    },
    {
      id: 'es-u14',
      title: 'De grote herhaling',
      icon: '🏆',
      lessons: [
        {
          id: 'es-u14-l1',
          title: 'Terugblik: reizen & gezondheid',
          exercises: [
            { type: 'select', prompt: 'Necesito un taxi al aeropuerto.', speak: 'Necesito un taxi al aeropuerto.', options: ['Ik heb een taxi naar het vliegveld nodig.', 'Ik wil een bus naar het station.', 'Ik heb een kaartje naar het vliegveld nodig.'], correct: 0 },
            { type: 'wordbank', nl: 'Waar is het station?', target: 'Dónde está la estación', distractors: ['aeropuerto', 'el', 'farmacia'] },
            {
              type: 'match',
              pairs: [
                { nl: 'de koffer', target: 'la maleta' },
                { nl: 'de dokter', target: 'el médico' },
                { nl: 'de rekening', target: 'la cuenta' },
                { nl: 'het kaartje', target: 'el billete' },
                { nl: 'het hoofd', target: 'la cabeza' },
              ],
            },
            { type: 'type', nl: 'Ik heb hoofdpijn.', target: 'Me duele la cabeza', accept: ['me duele la cabeza', 'Me duele la cabeza.', 'me duele la cabeza.'] },
            { type: 'fill', before: 'El tren', after: 'a las nueve.', nl: 'De trein vertrekt om negen uur.', options: ['sale', 'llega', 'está'], correct: 0 },
            { type: 'listen', target: 'quiero un billete para Madrid', options: ['quiero un billete para Madrid', 'quiero un billete para Sevilla', 'necesito un billete para Madrid'], correct: 0 },
            { type: 'select', prompt: 'ziek', options: ['cansado', 'enfermo', 'bien'], correct: 1 },
            { type: 'wordbank', nl: 'Mijn vader is erg moe.', target: 'Mi padre está muy cansado', distractors: ['es', 'enfermo', 'madre', 'el'] },
            { type: 'type', nl: 'Ik wil graag een koffie, alsjeblieft.', target: 'Quiero un café por favor', accept: ['quiero un café por favor', 'Quiero un café, por favor', 'Quiero un café, por favor.', 'quiero un cafe por favor'] },
            { type: 'fill', before: 'Mi hermano', after: 'muy enfermo.', nl: 'Mijn broer is erg ziek.', options: ['es', 'está', 'estás'], correct: 1 },
            { type: 'select', prompt: 'het vliegveld', options: ['el aeropuerto', 'la estación', 'el avión'], correct: 0 },
            { type: 'wordbank', nl: 'De apotheek is aan de linkerkant.', target: 'La farmacia está a la izquierda', distractors: ['derecha', 'en', 'médico'] },
          ],
        },
        {
          id: 'es-u14-l2',
          title: 'Terugblik: weer & uitgaan',
          exercises: [
            { type: 'select', prompt: 'Hoy llueve mucho.', speak: 'Hoy llueve mucho.', options: ['Vandaag regent het veel.', 'Vandaag is het erg koud.', 'Morgen regent het veel.'], correct: 0 },
            { type: 'wordbank', nl: 'In de zomer is het warm in Madrid.', target: 'En verano hace calor en Madrid', distractors: ['frío', 'invierno', 'llueve'] },
            {
              type: 'match',
              pairs: [
                { nl: 'de zon schijnt', target: 'hace sol' },
                { nl: 'de film', target: 'la película' },
                { nl: 'de winter', target: 'el invierno' },
                { nl: 'het feest', target: 'la fiesta' },
                { nl: 'de wijn', target: 'el vino' },
              ],
            },
            { type: 'type', nl: 'Ik hou van muziek.', target: 'Me gusta la música', accept: ['me gusta la música', 'Me gusta la musica', 'me gusta la musica', 'Me gusta la música.'] },
            { type: 'fill', before: 'En invierno', after: 'mucho frío.', nl: 'In de winter is het erg koud.', options: ['hace', 'es', 'está'], correct: 0 },
            { type: 'listen', target: 'la película empieza a las nueve', options: ['la película empieza a las nueve', 'la película empieza a las diez', 'la fiesta empieza a las nueve'], correct: 0 },
            { type: 'select', prompt: 'de lente', options: ['el verano', 'la primavera', 'el invierno'], correct: 1 },
            { type: 'wordbank', nl: 'Ik wil graag twee kaartjes voor het theater.', target: 'Quiero dos entradas para el teatro', distractors: ['cine', 'la', 'billete'] },
            { type: 'type', nl: 'het is warm', target: 'hace calor', accept: ['Hace calor', 'hace calor.', 'Hace calor.'] },
            { type: 'fill', before: 'Una cerveza fría,', after: 'favor.', nl: 'Een koud biertje, alsjeblieft.', options: ['por', 'para', 'de'], correct: 0 },
            { type: 'select', prompt: 'la entrada', speak: 'La entrada', options: ['de uitgang', 'het toegangskaartje', 'de film'], correct: 1 },
            { type: 'wordbank', nl: 'Vandaag regent het veel in Galicië.', target: 'Hoy llueve mucho en Galicia', distractors: ['hace', 'sol', 'frío'] },
          ],
        },
        {
          id: 'es-u14-l3',
          title: 'De grote finale',
          exercises: [
            { type: 'type', nl: 'Goedemorgen, ik heet Carmen.', target: 'Buenos días me llamo Carmen', accept: ['buenos días me llamo Carmen', 'Buenos días, me llamo Carmen', 'Buenos días, me llamo Carmen.', 'buenos dias me llamo carmen'] },
            { type: 'wordbank', nl: 'Ik wil graag een kaartje naar Barcelona.', target: 'Quiero un billete para Barcelona', distractors: ['entrada', 'el', 'viaje'] },
            { type: 'type', nl: 'Waar is de apotheek?', target: 'Dónde está la farmacia', accept: ['¿Dónde está la farmacia?', 'dónde está la farmacia', 'Donde esta la farmacia', 'donde esta la farmacia'] },
            { type: 'fill', before: 'Me', after: 'mucho la cabeza.', nl: 'Mijn hoofd doet erg pijn.', options: ['duele', 'duelen', 'gusta'], correct: 0 },
            { type: 'wordbank', nl: 'In de winter regent het veel in Galicië.', target: 'En invierno llueve mucho en Galicia', distractors: ['verano', 'hace', 'frío'] },
            { type: 'type', nl: 'Ik hou van dansen op het feest.', target: 'Me gusta bailar en la fiesta', accept: ['me gusta bailar en la fiesta', 'Me gusta bailar en la fiesta.'] },
            {
              type: 'match',
              pairs: [
                { nl: 'de reis', target: 'el viaje' },
                { nl: 'moe', target: 'cansado' },
                { nl: 'de lente', target: 'la primavera' },
                { nl: 'het theater', target: 'el teatro' },
                { nl: 'de zus', target: 'la hermana' },
              ],
            },
            { type: 'listen', target: 'hoy hace mucho calor', options: ['hoy hace mucho calor', 'hoy hace mucho frío', 'hoy hace mucho sol'], correct: 0 },
            { type: 'type', nl: 'Mijn koffer is in het hotel.', target: 'Mi maleta está en el hotel', accept: ['mi maleta está en el hotel', 'Mi maleta esta en el hotel', 'mi maleta esta en el hotel', 'Mi maleta está en el hotel.'] },
            { type: 'fill', before: 'Quiero dos entradas', after: 'el cine.', nl: 'Ik wil graag twee kaartjes voor de bioscoop.', options: ['para', 'por', 'de'], correct: 0 },
            { type: 'wordbank', nl: 'Het vliegtuig vertrekt om tien uur.', target: 'El avión sale a las diez', distractors: ['tren', 'llega', 'nueve', 'la'] },
            { type: 'type', nl: 'Vandaag schijnt de zon.', target: 'Hoy hace sol', accept: ['hoy hace sol', 'Hoy hace sol.', 'Hace sol hoy'] },
            { type: 'select', prompt: 'La cuenta, por favor.', speak: 'La cuenta, por favor.', options: ['De rekening, alsjeblieft.', 'De kaart, alsjeblieft.', 'Een koffie, alsjeblieft.'], correct: 0 },
          ],
        },
      ],
    },
  ],
}
