import type { Course } from '../../types'

export const course: Course = {
  id: 'es',
  name: 'Spaans',
  flag: '🇪🇸',
  tagline: 'De taal van 500 miljoen mensen',
  ttsLang: 'es-ES',
  sections: [
    {
      title: 'Sectie 1 · Eerste stappen',
      cefr: 'A1',
      units: [
        {
          id: 'es-u1',
          title: 'Begroetingen & basis',
          icon: '👋',
          lessons: [
            {
              id: 'es-u1-l1',
              title: 'Hallo zeggen',
              exercises: [
                { type: 'new', word: 'hola', nl: 'hallo', example: 'Hola, ¿qué tal?', exampleNl: 'Hallo, hoe gaat het?' },
                { type: 'new', word: 'buenos días', nl: 'goedemorgen', example: '¡Buenos días, señora García!', exampleNl: 'Goedemorgen, mevrouw García!' },
                { type: 'new', word: 'adiós', nl: 'dag / tot ziens', example: 'Adiós, hasta mañana.', exampleNl: 'Dag, tot morgen.' },
                { type: 'new', word: 'gracias', nl: 'dank je', example: 'Muchas gracias, señor.', exampleNl: 'Dank u wel, meneer.' },
                { type: 'select', prompt: 'hallo', options: ['adiós', 'hola', 'gracias'], correct: 1 },
                { type: 'select', prompt: 'buenos días', speak: 'Buenos días', options: ['goedenavond', 'tot ziens', 'goedemorgen'], correct: 2 },
                { type: 'listen', target: 'adiós', options: ['gracias', 'adiós', 'hola'], correct: 1 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'hallo', target: 'hola' },
                    { nl: 'dag', target: 'adiós' },
                    { nl: 'dank je', target: 'gracias' },
                    { nl: 'goedemorgen', target: 'buenos días' },
                  ],
                },
                { type: 'select', prompt: 'dank je', options: ['gracias', 'buenos días', 'adiós'], correct: 0 },
                { type: 'wordbank', nl: 'Goedemorgen, mevrouw García.', target: 'Buenos días señora García', distractors: ['hola', 'adiós', 'gracias'] },
                { type: 'type', nl: 'hallo', target: 'hola', accept: ['Hola', 'hola.', 'Hola.'] },
                { type: 'listen', target: 'hola', options: ['hola', 'adiós', 'gracias'], correct: 0 },
              ],
            },
            {
              id: 'es-u1-l2',
              title: 'Hoe gaat het?',
              exercises: [
                { type: 'new', word: '¿cómo estás?', nl: 'hoe gaat het?', example: 'Hola María, ¿cómo estás?', exampleNl: 'Hallo María, hoe gaat het?' },
                { type: 'new', word: 'bien', nl: 'goed', example: 'Estoy bien, gracias.', exampleNl: 'Het gaat goed, dank je.' },
                { type: 'new', word: 'por favor', nl: 'alsjeblieft', example: 'Un momento, por favor.', exampleNl: 'Een momentje, alsjeblieft.' },
                { type: 'new', word: 'me llamo', nl: 'ik heet', example: 'Me llamo Carmen.', exampleNl: 'Ik heet Carmen.' },
                { type: 'select', prompt: 'goed', options: ['mal', 'bien', 'buenos días'], correct: 1 },
                { type: 'select', prompt: 'por favor', speak: 'Por favor', options: ['dank je wel', 'tot ziens', 'alsjeblieft'], correct: 2 },
                { type: 'fill', before: 'Me', after: 'Lucía.', nl: 'Ik heet Lucía.', options: ['llama', 'llamo', 'llamas'], correct: 1 },
                { type: 'listen', target: 'bien', options: ['bien', 'buenos días', 'por favor'], correct: 0 },
                { type: 'wordbank', nl: 'Hallo, hoe gaat het?', target: 'Hola cómo estás', distractors: ['bien', 'llamo', 'gracias', 'adiós'] },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'goed', target: 'bien' },
                    { nl: 'alsjeblieft', target: 'por favor' },
                    { nl: 'ik heet', target: 'me llamo' },
                    { nl: 'dank je', target: 'gracias' },
                    { nl: 'hallo', target: 'hola' },
                  ],
                },
                { type: 'type', nl: 'alsjeblieft', target: 'por favor', accept: ['Por favor', 'por favor.', 'Por favor.'] },
                { type: 'type', nl: 'Ik heet Ana.', target: 'Me llamo Ana', accept: ['me llamo Ana', 'Me llamo Ana.', 'me llamo ana'] },
              ],
            },
            {
              id: 'es-u1-l3',
              title: 'Herhaling: eerste woorden',
              exercises: [
                { type: 'select', prompt: '¿Cómo estás?', speak: '¿Cómo estás?', options: ['hoe heet je?', 'hoe gaat het?', 'waar woon je?'], correct: 1 },
                { type: 'type', nl: 'goedemorgen', target: 'buenos días', accept: ['Buenos días', 'buenos dias', 'Buenos dias'] },
                { type: 'wordbank', nl: 'Het gaat goed, dank je.', target: 'Estoy bien gracias', distractors: ['mal', 'por', 'favor', 'adiós'] },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'goedemorgen', target: 'buenos días' },
                    { nl: 'dag', target: 'adiós' },
                    { nl: 'alsjeblieft', target: 'por favor' },
                    { nl: 'goed', target: 'bien' },
                    { nl: 'ik heet', target: 'me llamo' },
                  ],
                },
                { type: 'type', nl: 'dank je', target: 'gracias', accept: ['Gracias', 'gracias.', 'Gracias.'] },
                { type: 'fill', before: 'Estoy', after: ', gracias.', nl: 'Het gaat goed, dank je.', options: ['bueno', 'buenas', 'bien'], correct: 2 },
                { type: 'listen', target: 'me llamo', options: ['me llama', 'me llamo', 'te llamas'], correct: 1 },
                { type: 'wordbank', nl: 'Goedemorgen, ik heet Pablo.', target: 'Buenos días me llamo Pablo', distractors: ['hola', 'estás', 'gracias'] },
                { type: 'select', prompt: 'tot ziens', options: ['buenos días', 'por favor', 'adiós'], correct: 2 },
                { type: 'type', nl: 'Hoe gaat het?', target: 'Cómo estás', accept: ['¿Cómo estás?', 'cómo estás', 'como estas', 'Como estas'] },
                { type: 'listen', target: 'buenos días', options: ['buenos días', 'buenas tardes', 'buenas noches'], correct: 0 },
                { type: 'type', nl: 'Ik heet Sofía.', target: 'Me llamo Sofía', accept: ['me llamo Sofía', 'Me llamo Sofia', 'me llamo Sofia', 'Me llamo Sofía.'] },
              ],
            },
          ],
        },
        {
          id: 'es-u2',
          title: 'Eten & drinken',
          icon: '☕',
          lessons: [
            {
              id: 'es-u2-l1',
              title: 'In het café',
              exercises: [
                { type: 'new', word: 'el café', nl: 'de koffie', example: 'Un café con leche, por favor.', exampleNl: 'Een koffie met melk, alsjeblieft.' },
                { type: 'new', word: 'el agua', nl: 'het water', example: 'Un agua mineral, por favor.', exampleNl: 'Een mineraalwater, alsjeblieft.' },
                { type: 'new', word: 'quiero', nl: 'ik wil (graag)', example: 'Quiero un café, por favor.', exampleNl: 'Ik wil graag een koffie, alsjeblieft.' },
                { type: 'new', word: 'el pan', nl: 'het brood', example: 'El pan está muy bueno.', exampleNl: 'Het brood is erg lekker.' },
                { type: 'select', prompt: 'de koffie', options: ['el agua', 'el pan', 'el café'], correct: 2 },
                { type: 'select', prompt: 'el agua', speak: 'El agua', options: ['het water', 'de melk', 'de wijn'], correct: 0 },
                { type: 'listen', target: 'quiero', options: ['quiere', 'quieres', 'quiero'], correct: 2 },
                { type: 'fill', before: 'Quiero', after: 'café, por favor.', nl: 'Ik wil graag een koffie, alsjeblieft.', options: ['una', 'un', 'el'], correct: 1 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de koffie', target: 'el café' },
                    { nl: 'het water', target: 'el agua' },
                    { nl: 'het brood', target: 'el pan' },
                    { nl: 'ik wil', target: 'quiero' },
                  ],
                },
                { type: 'wordbank', nl: 'Ik wil graag een koffie, alsjeblieft.', target: 'Quiero un café por favor', distractors: ['agua', 'el', 'pan', 'gracias'] },
                { type: 'type', nl: 'het brood', target: 'el pan', accept: ['pan', 'El pan', 'el pan.'] },
                { type: 'select', prompt: 'ik wil (graag)', options: ['quiero', 'quieres', 'queso'], correct: 0 },
              ],
            },
            {
              id: 'es-u2-l2',
              title: 'Bestellen',
              exercises: [
                { type: 'new', word: 'el vino', nl: 'de wijn', example: 'Un vino tinto, por favor.', exampleNl: 'Een rode wijn, alsjeblieft.' },
                { type: 'new', word: 'la cerveza', nl: 'het bier', example: 'Una cerveza fría, por favor.', exampleNl: 'Een koud biertje, alsjeblieft.' },
                { type: 'new', word: 'la cuenta', nl: 'de rekening', example: 'La cuenta, por favor.', exampleNl: 'De rekening, alsjeblieft.' },
                { type: 'new', word: 'comer', nl: 'eten', example: 'Quiero comer algo.', exampleNl: 'Ik wil iets eten.' },
                { type: 'select', prompt: 'la cuenta', speak: 'La cuenta', options: ['de kaart', 'de rekening', 'de keuken'], correct: 1 },
                { type: 'fill', before: 'Una', after: 'fría, por favor.', nl: 'Een koud biertje, alsjeblieft.', options: ['vino', 'cerveza', 'pan'], correct: 1 },
                { type: 'listen', target: 'la cerveza', options: ['la cerveza', 'la cuenta', 'la cocina'], correct: 0 },
                { type: 'wordbank', nl: 'De rekening, alsjeblieft.', target: 'La cuenta por favor', distractors: ['el', 'vino', 'quiero', 'gracias'] },
                { type: 'select', prompt: 'de wijn', options: ['la cerveza', 'el agua', 'el vino'], correct: 2 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de wijn', target: 'el vino' },
                    { nl: 'het bier', target: 'la cerveza' },
                    { nl: 'de rekening', target: 'la cuenta' },
                    { nl: 'eten', target: 'comer' },
                    { nl: 'de koffie', target: 'el café' },
                  ],
                },
                { type: 'type', nl: 'de rekening', target: 'la cuenta', accept: ['La cuenta', 'cuenta', 'la cuenta.'] },
                { type: 'fill', before: 'Quiero', after: 'algo.', nl: 'Ik wil iets eten.', options: ['come', 'comer', 'como'], correct: 1 },
              ],
            },
            {
              id: 'es-u2-l3',
              title: 'Herhaling: eten & drinken',
              exercises: [
                { type: 'type', nl: 'de koffie', target: 'el café', accept: ['café', 'cafe', 'el cafe', 'El café'] },
                { type: 'wordbank', nl: 'Ik wil graag een bier, alsjeblieft.', target: 'Quiero una cerveza por favor', distractors: ['un', 'vino', 'cuenta', 'gracias'] },
                { type: 'select', prompt: 'Quiero comer algo.', speak: 'Quiero comer algo.', options: ['Ik wil iets drinken.', 'Ik wil de rekening.', 'Ik wil iets eten.'], correct: 2 },
                { type: 'fill', before: 'El', after: 'está muy bueno.', nl: 'Het brood is erg lekker.', options: ['cuenta', 'pan', 'cerveza'], correct: 1 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'het brood', target: 'el pan' },
                    { nl: 'het water', target: 'el agua' },
                    { nl: 'de rekening', target: 'la cuenta' },
                    { nl: 'de wijn', target: 'el vino' },
                    { nl: 'eten', target: 'comer' },
                  ],
                },
                { type: 'type', nl: 'het water', target: 'el agua', accept: ['agua', 'El agua', 'el agua.'] },
                { type: 'listen', target: 'la cuenta por favor', options: ['la cuenta por favor', 'la cerveza por favor', 'un café por favor'], correct: 0 },
                { type: 'wordbank', nl: 'Een koffie met melk, alsjeblieft.', target: 'Un café con leche por favor', distractors: ['una', 'agua', 'vino'] },
                { type: 'type', nl: 'het bier', target: 'la cerveza', accept: ['cerveza', 'La cerveza', 'la cerveza.'] },
                { type: 'fill', before: 'Quiero', after: 'agua mineral.', nl: 'Ik wil graag een mineraalwater.', options: ['una', 'el', 'un'], correct: 2 },
                { type: 'type', nl: 'Ik wil eten.', target: 'Quiero comer', accept: ['quiero comer', 'Quiero comer.', 'quiero comer.'] },
                { type: 'select', prompt: 'de rekening', options: ['la cuenta', 'la cerveza', 'el pan'], correct: 0 },
              ],
            },
          ],
        },
        {
          id: 'es-u3',
          title: 'Mensen & familie',
          icon: '💛',
          lessons: [
            {
              id: 'es-u3-l1',
              title: 'Mijn familie',
              exercises: [
                { type: 'new', word: 'la madre', nl: 'de moeder', example: 'Mi madre se llama Elena.', exampleNl: 'Mijn moeder heet Elena.' },
                { type: 'new', word: 'el padre', nl: 'de vader', example: 'Mi padre trabaja en Madrid.', exampleNl: 'Mijn vader werkt in Madrid.' },
                { type: 'new', word: 'el hermano', nl: 'de broer', example: 'Tengo un hermano mayor.', exampleNl: 'Ik heb een oudere broer.' },
                { type: 'new', word: 'la hermana', nl: 'de zus', example: 'Mi hermana tiene veinte años.', exampleNl: 'Mijn zus is twintig jaar.' },
                { type: 'select', prompt: 'de moeder', options: ['el padre', 'la madre', 'la hermana'], correct: 1 },
                { type: 'select', prompt: 'el hermano', speak: 'El hermano', options: ['de zus', 'de vader', 'de broer'], correct: 2 },
                { type: 'listen', target: 'la hermana', options: ['la hermana', 'el hermano', 'la madre'], correct: 0 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de moeder', target: 'la madre' },
                    { nl: 'de vader', target: 'el padre' },
                    { nl: 'de broer', target: 'el hermano' },
                    { nl: 'de zus', target: 'la hermana' },
                  ],
                },
                { type: 'fill', before: 'Mi', after: 'se llama Elena.', nl: 'Mijn moeder heet Elena.', options: ['madre', 'padre', 'hermano'], correct: 0 },
                { type: 'wordbank', nl: 'Ik heb een broer.', target: 'Tengo un hermano', distractors: ['una', 'hermana', 'madre', 'la'] },
                { type: 'type', nl: 'de zus', target: 'la hermana', accept: ['hermana', 'La hermana', 'la hermana.'] },
                { type: 'fill', before: 'Tengo', after: 'hermana.', nl: 'Ik heb een zus.', options: ['un', 'el', 'una'], correct: 2 },
              ],
            },
            {
              id: 'es-u3-l2',
              title: 'Vrienden & mensen',
              exercises: [
                { type: 'new', word: 'el amigo', nl: 'de vriend', example: 'Carlos es mi mejor amigo.', exampleNl: 'Carlos is mijn beste vriend.' },
                { type: 'new', word: 'la familia', nl: 'de familie', example: 'Mi familia vive en Sevilla.', exampleNl: 'Mijn familie woont in Sevilla.' },
                { type: 'new', word: 'el hombre', nl: 'de man', example: 'Ese hombre es mi padre.', exampleNl: 'Die man is mijn vader.' },
                { type: 'new', word: 'la mujer', nl: 'de vrouw', example: 'La mujer se llama Rosa.', exampleNl: 'De vrouw heet Rosa.' },
                { type: 'select', prompt: 'la familia', speak: 'La familia', options: ['de familie', 'de vriendin', 'de vrouw'], correct: 0 },
                { type: 'select', prompt: 'de man', options: ['la mujer', 'el hombre', 'el amigo'], correct: 1 },
                { type: 'listen', target: 'el amigo', options: ['la amiga', 'el amigo', 'el hombre'], correct: 1 },
                { type: 'fill', before: 'Carlos es mi mejor', after: '.', nl: 'Carlos is mijn beste vriend.', options: ['amiga', 'amigos', 'amigo'], correct: 2 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de vriend', target: 'el amigo' },
                    { nl: 'de familie', target: 'la familia' },
                    { nl: 'de man', target: 'el hombre' },
                    { nl: 'de vrouw', target: 'la mujer' },
                    { nl: 'de moeder', target: 'la madre' },
                  ],
                },
                { type: 'wordbank', nl: 'Die man is mijn vader.', target: 'Ese hombre es mi padre', distractors: ['mujer', 'la', 'hermano'] },
                { type: 'type', nl: 'de vrouw', target: 'la mujer', accept: ['mujer', 'La mujer', 'la mujer.'] },
                { type: 'fill', before: 'Mi familia vive', after: 'Sevilla.', nl: 'Mijn familie woont in Sevilla.', options: ['a', 'en', 'de'], correct: 1 },
              ],
            },
            {
              id: 'es-u3-l3',
              title: 'Herhaling: familie',
              exercises: [
                { type: 'type', nl: 'de moeder', target: 'la madre', accept: ['madre', 'La madre', 'la madre.'] },
                { type: 'wordbank', nl: 'Mijn zus heet Lucía.', target: 'Mi hermana se llama Lucía', distractors: ['hermano', 'el', 'madre', 'llamo'] },
                { type: 'select', prompt: 'Tengo un hermano mayor.', speak: 'Tengo un hermano mayor.', options: ['Ik heb een grote familie.', 'Ik heb een oudere broer.', 'Ik heb een jongere zus.'], correct: 1 },
                { type: 'type', nl: 'de familie', target: 'la familia', accept: ['familia', 'La familia', 'la familia.'] },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de vader', target: 'el padre' },
                    { nl: 'de vrouw', target: 'la mujer' },
                    { nl: 'de man', target: 'el hombre' },
                    { nl: 'de zus', target: 'la hermana' },
                    { nl: 'de vriend', target: 'el amigo' },
                  ],
                },
                { type: 'fill', before: 'Mi hermana', after: 'veinte años.', nl: 'Mijn zus is twintig jaar.', options: ['tengo', 'es', 'tiene'], correct: 2 },
                { type: 'wordbank', nl: 'De vrouw heet Rosa.', target: 'La mujer se llama Rosa', distractors: ['el', 'hombre', 'llamo', 'mi'] },
                { type: 'listen', target: 'mi familia', options: ['mi familia', 'mi hermana', 'la familia'], correct: 0 },
                { type: 'type', nl: 'de broer', target: 'el hermano', accept: ['hermano', 'El hermano', 'el hermano.'] },
                { type: 'fill', before: 'Ese', after: 'es mi padre.', nl: 'Die man is mijn vader.', options: ['mujer', 'hombre', 'hombres'], correct: 1 },
                { type: 'type', nl: 'Ik heb een zus.', target: 'Tengo una hermana', accept: ['tengo una hermana', 'Tengo una hermana.', 'tengo una hermana.'] },
                { type: 'wordbank', nl: 'Mijn vader werkt in Madrid.', target: 'Mi padre trabaja en Madrid', distractors: ['vive', 'madre', 'el'] },
              ],
            },
          ],
        },
        {
          id: 'es-u4',
          title: 'Onderweg in de stad',
          icon: '🧭',
          lessons: [
            {
              id: 'es-u4-l1',
              title: 'De weg vragen',
              exercises: [
                { type: 'new', word: 'la calle', nl: 'de straat', example: 'Vivo en la calle Mayor.', exampleNl: 'Ik woon in de Calle Mayor.' },
                { type: 'new', word: '¿dónde está?', nl: 'waar is?', example: '¿Dónde está la estación?', exampleNl: 'Waar is het station?' },
                { type: 'new', word: 'la estación', nl: 'het station', example: 'La estación está cerca.', exampleNl: 'Het station is dichtbij.' },
                { type: 'new', word: 'a la izquierda', nl: 'naar links', example: 'El museo está a la izquierda.', exampleNl: 'Het museum is aan de linkerkant.' },
                { type: 'select', prompt: 'de straat', options: ['la estación', 'la calle', 'la plaza'], correct: 1 },
                { type: 'select', prompt: 'a la izquierda', speak: 'A la izquierda', options: ['naar rechts', 'rechtdoor', 'naar links'], correct: 2 },
                { type: 'listen', target: 'la estación', options: ['la estación', 'la calle', 'la habitación'], correct: 0 },
                { type: 'fill', before: '¿Dónde', after: 'la estación?', nl: 'Waar is het station?', options: ['es', 'está', 'estás'], correct: 1 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de straat', target: 'la calle' },
                    { nl: 'het station', target: 'la estación' },
                    { nl: 'naar links', target: 'a la izquierda' },
                    { nl: 'waar is?', target: '¿dónde está?' },
                  ],
                },
                { type: 'wordbank', nl: 'Waar is het station?', target: 'Dónde está la estación', distractors: ['calle', 'izquierda', 'el', 'a'] },
                { type: 'type', nl: 'de straat', target: 'la calle', accept: ['calle', 'La calle', 'la calle.'] },
                { type: 'select', prompt: 'waar is?', options: ['¿cómo estás?', '¿dónde está?', '¿qué es?'], correct: 1 },
              ],
            },
            {
              id: 'es-u4-l2',
              title: 'Plekken in de stad',
              exercises: [
                { type: 'new', word: 'la plaza', nl: 'het plein', example: 'La Plaza Mayor es muy bonita.', exampleNl: 'De Plaza Mayor is erg mooi.' },
                { type: 'new', word: 'el museo', nl: 'het museum', example: 'El Museo del Prado está en Madrid.', exampleNl: 'Het Prado-museum is in Madrid.' },
                { type: 'new', word: 'el tren', nl: 'de trein', example: 'El tren sale a las nueve.', exampleNl: 'De trein vertrekt om negen uur.' },
                { type: 'new', word: 'a la derecha', nl: 'naar rechts', example: 'La plaza está a la derecha.', exampleNl: 'Het plein is aan de rechterkant.' },
                { type: 'select', prompt: 'el museo', speak: 'El museo', options: ['het plein', 'het museum', 'het station'], correct: 1 },
                { type: 'select', prompt: 'de trein', options: ['el tren', 'el museo', 'la plaza'], correct: 0 },
                { type: 'listen', target: 'a la derecha', options: ['a la izquierda', 'a la derecha', 'la estación'], correct: 1 },
                { type: 'fill', before: 'El museo está', after: 'la derecha.', nl: 'Het museum is aan de rechterkant.', options: ['en', 'de', 'a'], correct: 2 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'het plein', target: 'la plaza' },
                    { nl: 'het museum', target: 'el museo' },
                    { nl: 'de trein', target: 'el tren' },
                    { nl: 'naar rechts', target: 'a la derecha' },
                    { nl: 'de straat', target: 'la calle' },
                  ],
                },
                { type: 'wordbank', nl: 'Het plein is aan de rechterkant.', target: 'La plaza está a la derecha', distractors: ['izquierda', 'el', 'museo', 'en'] },
                { type: 'type', nl: 'het museum', target: 'el museo', accept: ['museo', 'El museo', 'el museo.'] },
                { type: 'fill', before: 'El', after: 'sale a las nueve.', nl: 'De trein vertrekt om negen uur.', options: ['plaza', 'tren', 'estación'], correct: 1 },
              ],
            },
            {
              id: 'es-u4-l3',
              title: 'Herhaling: de stad',
              exercises: [
                { type: 'type', nl: 'het station', target: 'la estación', accept: ['estación', 'La estación', 'la estacion', 'estacion'] },
                { type: 'wordbank', nl: 'Waar is het museum?', target: 'Dónde está el museo', distractors: ['la', 'plaza', 'derecha', 'tren'] },
                { type: 'select', prompt: 'El tren sale a las nueve.', speak: 'El tren sale a las nueve.', options: ['De trein komt om negen uur aan.', 'De trein vertrekt om negen uur.', 'De bus vertrekt om negen uur.'], correct: 1 },
                { type: 'type', nl: 'het plein', target: 'la plaza', accept: ['plaza', 'La plaza', 'la plaza.'] },
                { type: 'fill', before: 'La estación está', after: 'la izquierda.', nl: 'Het station is aan de linkerkant.', options: ['a', 'en', 'por'], correct: 0 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de trein', target: 'el tren' },
                    { nl: 'het plein', target: 'la plaza' },
                    { nl: 'naar links', target: 'a la izquierda' },
                    { nl: 'naar rechts', target: 'a la derecha' },
                    { nl: 'het museum', target: 'el museo' },
                  ],
                },
                { type: 'wordbank', nl: 'De straat is aan de linkerkant.', target: 'La calle está a la izquierda', distractors: ['derecha', 'el', 'dónde', 'plaza'] },
                { type: 'listen', target: 'dónde está la plaza', options: ['dónde está la playa', 'dónde está la plaza', 'dónde está la calle'], correct: 1 },
                { type: 'type', nl: 'naar rechts', target: 'a la derecha', accept: ['derecha', 'A la derecha', 'a la derecha.'] },
                { type: 'fill', before: '¿', after: 'está la calle Mayor?', nl: 'Waar is de Calle Mayor?', options: ['Cómo', 'Qué', 'Dónde'], correct: 2 },
                { type: 'type', nl: 'Waar is het station?', target: 'Dónde está la estación', accept: ['¿Dónde está la estación?', 'dónde está la estación', 'Donde esta la estacion', 'donde esta la estacion'] },
                { type: 'wordbank', nl: 'De trein vertrekt om negen uur.', target: 'El tren sale a las nueve', distractors: ['la', 'estación', 'está', 'plaza'] },
              ],
            },
          ],
        },
      ],
    },
  ],
}
