import type { Section } from '../../types'

export const section: Section = {
  title: 'Sectie 2 · Dagelijks leven',
  cefr: 'A1+',
  units: [
    {
      id: 'fr-u5',
      title: 'Getallen & tijd',
      icon: '🕰️',
      lessons: [
        {
          id: 'fr-u5-l1',
          title: 'Tellen tot tien',
          exercises: [
            { type: 'new', word: 'deux', nl: 'twee', example: "J'ai deux frères.", exampleNl: 'Ik heb twee broers.' },
            { type: 'new', word: 'trois', nl: 'drie', example: "Trois cafés, s'il vous plaît.", exampleNl: 'Drie koffie, alstublieft.' },
            { type: 'new', word: 'cinq', nl: 'vijf', example: 'Cinq croissants, madame ?', exampleNl: 'Vijf croissants, mevrouw?' },
            { type: 'new', word: 'dix', nl: 'tien', example: 'Le musée est à dix minutes.', exampleNl: 'Het museum is op tien minuten.' },
            { type: 'select', prompt: 'twee', options: ['trois', 'deux', 'dix'], correct: 1 },
            { type: 'select', prompt: 'cinq', speak: 'cinq', options: ['vijf', 'drie', 'tien'], correct: 0 },
            { type: 'listen', target: 'trois', options: ['trois', 'deux', 'dix'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'twee', target: 'deux' },
                { nl: 'drie', target: 'trois' },
                { nl: 'vijf', target: 'cinq' },
                { nl: 'tien', target: 'dix' },
              ],
            },
            { type: 'wordbank', nl: 'Ik heb twee broers.', target: "J'ai deux frères", distractors: ['trois', 'sœurs', 'une'] },
            { type: 'fill', before: 'Trois cafés et', after: " thés, s'il vous plaît.", nl: 'Drie koffie en twee thee, alstublieft.', options: ['dix', 'deux', 'cinq'], correct: 1 },
            { type: 'type', nl: 'tien', target: 'dix', accept: ['Dix'] },
            { type: 'listen', target: 'dix', options: ['deux', 'dix', 'trois'], correct: 1 },
          ],
        },
        {
          id: 'fr-u5-l2',
          title: 'Hoe laat is het?',
          exercises: [
            { type: 'new', word: "l'heure", nl: 'het uur', example: 'Quelle heure est-il ?', exampleNl: 'Hoe laat is het?' },
            { type: 'new', word: 'midi', nl: 'twaalf uur (middag)', example: 'Il est midi.', exampleNl: 'Het is twaalf uur.' },
            { type: 'new', word: 'le matin', nl: 'de ochtend', example: 'Je prends un café le matin.', exampleNl: "Ik neem 's ochtends een koffie." },
            { type: 'new', word: 'le soir', nl: 'de avond', example: 'Le soir, je prends un thé.', exampleNl: "'s Avonds neem ik een thee." },
            { type: 'select', prompt: 'de ochtend', options: ['le soir', 'le matin', 'midi'], correct: 1 },
            { type: 'select', prompt: 'Il est midi.', speak: 'Il est midi.', options: ['Het is twaalf uur.', 'Het is ochtend.', 'Het is avond.'], correct: 0 },
            { type: 'listen', target: 'le soir', options: ['le soir', 'le matin', "l'heure"], correct: 0 },
            { type: 'fill', before: 'Il est trois', after: '.', nl: 'Het is drie uur.', options: ['heures', 'heure', 'matin'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'het uur', target: "l'heure" },
                { nl: 'de ochtend', target: 'le matin' },
                { nl: 'de avond', target: 'le soir' },
                { nl: 'twaalf uur (middag)', target: 'midi' },
              ],
            },
            { type: 'wordbank', nl: 'Hoe laat is het?', target: 'Quelle heure est-il', distractors: ['midi', 'où', 'le'] },
            { type: 'type', nl: 'de avond', target: 'le soir', accept: ['soir', 'Le soir'] },
            { type: 'fill', before: 'Je prends le métro', after: ' matin.', nl: "Ik neem 's ochtends de metro.", options: ['le', 'la', 'au'], correct: 0 },
          ],
        },
        {
          id: 'fr-u5-l3',
          title: 'Herhaling: de hele dag',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'twee', target: 'deux' },
                { nl: 'vijf', target: 'cinq' },
                { nl: 'tien', target: 'dix' },
                { nl: 'de ochtend', target: 'le matin' },
                { nl: 'de avond', target: 'le soir' },
              ],
            },
            { type: 'type', nl: 'twee', target: 'deux', accept: ['Deux'] },
            { type: 'wordbank', nl: 'Het is tien uur.', target: 'Il est dix heures', distractors: ['deux', 'heure', 'midi'] },
            { type: 'type', nl: 'het uur', target: "l'heure", accept: ['heure', "L'heure", 'l heure'] },
            { type: 'listen', target: 'il est midi', options: ['il est midi', 'il est dix heures', 'le matin'], correct: 0 },
            { type: 'wordbank', nl: "'s Ochtends neem ik een koffie.", target: 'Le matin je prends un café', distractors: ['soir', 'thé', 'midi'] },
            { type: 'fill', before: 'Il', after: ' trois heures.', nl: 'Het is drie uur.', options: ['est', 'es', 'et'], correct: 0 },
            { type: 'type', nl: 'vijf', target: 'cinq', accept: ['Cinq'] },
            { type: 'select', prompt: 'Quelle heure est-il ?', speak: 'Quelle heure est-il ?', options: ['Hoe laat is het?', 'Waar is het station?', 'Hoe gaat het?'], correct: 0 },
            { type: 'wordbank', nl: "'s Avonds neem ik de metro.", target: 'Le soir je prends le métro', distractors: ['matin', 'la', 'gare'] },
            { type: 'type', nl: 'twaalf uur (middag)', target: 'midi', accept: ['Midi'] },
            { type: 'wordbank', nl: 'Twee koffie en drie croissants, alstublieft.', target: "Deux cafés et trois croissants s'il vous plaît", distractors: ['cinq', 'thés', 'dix'] },
          ],
        },
      ],
    },
    {
      id: 'fr-u6',
      title: 'Boodschappen & geld',
      icon: '🛍️',
      lessons: [
        {
          id: 'fr-u6-l1',
          title: 'Op de markt',
          exercises: [
            { type: 'new', word: 'le marché', nl: 'de markt', example: 'Le marché est à gauche.', exampleNl: 'De markt is links.' },
            { type: 'new', word: 'les fruits', nl: 'het fruit', example: 'Les fruits sont bons.', exampleNl: 'Het fruit is lekker.' },
            { type: 'new', word: 'les légumes', nl: 'de groenten', example: 'Je voudrais des légumes.', exampleNl: 'Ik wil graag groenten.' },
            { type: 'new', word: 'acheter', nl: 'kopen', example: "J'achète du pain au marché.", exampleNl: 'Ik koop brood op de markt.' },
            { type: 'select', prompt: 'de markt', options: ['le musée', 'le marché', 'la gare'], correct: 1 },
            { type: 'select', prompt: 'les légumes', speak: 'les légumes', options: ['het fruit', 'de groenten', 'het brood'], correct: 1 },
            { type: 'listen', target: 'les fruits', options: ['les fruits', 'les légumes', 'le fromage'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'de markt', target: 'le marché' },
                { nl: 'het fruit', target: 'les fruits' },
                { nl: 'de groenten', target: 'les légumes' },
                { nl: 'kopen', target: 'acheter' },
              ],
            },
            { type: 'fill', before: 'Je voudrais', after: ' légumes.', nl: 'Ik wil graag groenten.', options: ['des', 'un', 'une'], correct: 0 },
            { type: 'wordbank', nl: 'Ik koop brood op de markt.', target: "J'achète du pain au marché", distractors: ['le', 'fruits', 'à'] },
            { type: 'type', nl: 'de markt', target: 'le marché', accept: ['marché', 'Le marché', 'le marche'] },
            { type: 'listen', target: 'le marché', options: ['le musée', 'le marché', 'la mère'], correct: 1 },
          ],
        },
        {
          id: 'fr-u6-l2',
          title: 'Hoeveel kost het?',
          exercises: [
            { type: 'new', word: 'combien', nl: 'hoeveel', example: "C'est combien, le fromage ?", exampleNl: 'Hoeveel kost de kaas?' },
            { type: 'new', word: 'ça coûte', nl: 'het kost', example: 'Ça coûte deux euros.', exampleNl: 'Het kost twee euro.' },
            { type: 'new', word: "l'euro", nl: 'de euro', example: 'Ça coûte dix euros.', exampleNl: 'Het kost tien euro.' },
            { type: 'new', word: 'cher', nl: 'duur', example: "C'est trop cher !", exampleNl: 'Dat is te duur!' },
            { type: 'select', prompt: 'hoeveel', options: ['combien', 'comment', 'où'], correct: 0 },
            { type: 'select', prompt: "C'est trop cher.", speak: "C'est trop cher.", options: ['Dat is te duur.', 'Dat is heel lekker.', 'Dat is links.'], correct: 0 },
            { type: 'listen', target: 'combien', options: ['combien', 'bien', 'cinq'], correct: 0 },
            { type: 'wordbank', nl: 'Hoeveel kost de wijn?', target: "C'est combien le vin", distractors: ['coûte', 'cher', 'la'] },
            { type: 'fill', before: 'Ça', after: ' cinq euros.', nl: 'Het kost vijf euro.', options: ['coûte', 'coûtes', 'coûtent'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'hoeveel', target: 'combien' },
                { nl: 'het kost', target: 'ça coûte' },
                { nl: 'de euro', target: "l'euro" },
                { nl: 'duur', target: 'cher' },
              ],
            },
            { type: 'type', nl: 'duur', target: 'cher', accept: ['Cher'] },
            { type: 'wordbank', nl: 'De kaas kost tien euro.', target: 'Le fromage coûte dix euros', distractors: ['cher', 'deux', 'la'] },
          ],
        },
        {
          id: 'fr-u6-l3',
          title: 'Herhaling: op de markt',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'de markt', target: 'le marché' },
                { nl: 'het fruit', target: 'les fruits' },
                { nl: 'de groenten', target: 'les légumes' },
                { nl: 'duur', target: 'cher' },
                { nl: 'de euro', target: "l'euro" },
              ],
            },
            { type: 'type', nl: 'hoeveel', target: 'combien', accept: ['Combien'] },
            { type: 'wordbank', nl: 'Ik koop fruit op de markt.', target: "J'achète des fruits au marché", distractors: ['légumes', 'le', 'cher'] },
            { type: 'fill', before: 'Le vin coûte', after: ' euros.', nl: 'De wijn kost tien euro.', options: ['dix', 'deux', 'cinq'], correct: 0 },
            { type: 'type', nl: 'het kost', target: 'ça coûte', accept: ['Ça coûte', 'ca coute', 'ça coute', 'ca coûte'] },
            { type: 'listen', target: 'ça coûte deux euros', options: ['ça coûte deux euros', 'ça coûte dix euros', "c'est combien"], correct: 0 },
            { type: 'select', prompt: "C'est combien, le pain ?", speak: "C'est combien, le pain ?", options: ['Hoeveel kost het brood?', 'Waar is het brood?', 'Wilt u brood?'], correct: 0 },
            { type: 'type', nl: 'de groenten', target: 'les légumes', accept: ['légumes', 'Les légumes', 'les legumes'] },
            { type: 'wordbank', nl: 'Dat is te duur!', target: "C'est trop cher", distractors: ['coûte', 'bien', 'très'] },
            { type: 'fill', before: "J'achète du pain", after: ' marché.', nl: 'Ik koop brood op de markt.', options: ['au', 'à la', 'le'], correct: 0 },
            { type: 'type', nl: 'het fruit', target: 'les fruits', accept: ['fruits', 'Les fruits'] },
            { type: 'wordbank', nl: 'Een koffie kost twee euro.', target: 'Un café coûte deux euros', distractors: ['dix', 'cher', 'le'] },
          ],
        },
      ],
    },
    {
      id: 'fr-u7',
      title: 'Huis & wonen',
      icon: '🏠',
      lessons: [
        {
          id: 'fr-u7-l1',
          title: 'Mijn huis',
          exercises: [
            { type: 'new', word: 'la maison', nl: 'het huis', example: 'Ma maison est grande.', exampleNl: 'Mijn huis is groot.' },
            { type: 'new', word: "j'habite", nl: 'ik woon', example: "J'habite à Paris.", exampleNl: 'Ik woon in Parijs.' },
            { type: 'new', word: 'la cuisine', nl: 'de keuken', example: 'La cuisine est petite.', exampleNl: 'De keuken is klein.' },
            { type: 'new', word: 'la chambre', nl: 'de slaapkamer', example: 'Ma chambre est à gauche.', exampleNl: 'Mijn slaapkamer is links.' },
            { type: 'select', prompt: 'het huis', options: ['la chambre', 'la maison', 'la cuisine'], correct: 1 },
            { type: 'select', prompt: "j'habite", speak: "j'habite", options: ['ik koop', 'ik woon', 'ik neem'], correct: 1 },
            { type: 'listen', target: 'la cuisine', options: ['la cuisine', 'la chambre', 'la maison'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'het huis', target: 'la maison' },
                { nl: 'de keuken', target: 'la cuisine' },
                { nl: 'de slaapkamer', target: 'la chambre' },
                { nl: 'ik woon', target: "j'habite" },
              ],
            },
            { type: 'fill', before: "J'habite", after: ' Paris.', nl: 'Ik woon in Parijs.', options: ['à', 'au', 'en'], correct: 0 },
            { type: 'wordbank', nl: 'Ik woon in een groot huis.', target: "J'habite dans une grande maison", distractors: ['grand', 'la', 'à'] },
            { type: 'type', nl: 'het huis', target: 'la maison', accept: ['maison', 'La maison'] },
            { type: 'listen', target: 'la chambre', options: ['la chambre', 'la cuisine', 'la gare'], correct: 0 },
          ],
        },
        {
          id: 'fr-u7-l2',
          title: 'In de kamer',
          exercises: [
            { type: 'new', word: 'la table', nl: 'de tafel', example: 'Le pain est sur la table.', exampleNl: 'Het brood ligt op tafel.' },
            { type: 'new', word: 'la chaise', nl: 'de stoel', example: 'La chaise est petite.', exampleNl: 'De stoel is klein.' },
            { type: 'new', word: 'la porte', nl: 'de deur', example: 'La porte est à droite.', exampleNl: 'De deur is rechts.' },
            { type: 'new', word: 'la fenêtre', nl: 'het raam', example: 'La fenêtre est grande.', exampleNl: 'Het raam is groot.' },
            { type: 'select', prompt: 'de deur', options: ['la fenêtre', 'la table', 'la porte'], correct: 2 },
            { type: 'select', prompt: 'la fenêtre', speak: 'la fenêtre', options: ['de tafel', 'het raam', 'de deur'], correct: 1 },
            { type: 'listen', target: 'la table', options: ['la table', 'la porte', 'la chaise'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'de tafel', target: 'la table' },
                { nl: 'de stoel', target: 'la chaise' },
                { nl: 'de deur', target: 'la porte' },
                { nl: 'het raam', target: 'la fenêtre' },
              ],
            },
            { type: 'fill', before: 'Le café est', after: ' la table.', nl: 'De koffie staat op tafel.', options: ['sur', 'sous', 'dans'], correct: 0 },
            { type: 'wordbank', nl: 'De deur is links en het raam is rechts.', target: 'La porte est à gauche et la fenêtre est à droite', distractors: ['table', 'le', 'sur'] },
            { type: 'type', nl: 'de tafel', target: 'la table', accept: ['table', 'La table'] },
            { type: 'listen', target: 'la porte', options: ['la porte', 'la table', 'la ville'], correct: 0 },
          ],
        },
        {
          id: 'fr-u7-l3',
          title: 'Herhaling: thuis',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'het huis', target: 'la maison' },
                { nl: 'de keuken', target: 'la cuisine' },
                { nl: 'de slaapkamer', target: 'la chambre' },
                { nl: 'de tafel', target: 'la table' },
                { nl: 'het raam', target: 'la fenêtre' },
              ],
            },
            { type: 'type', nl: 'ik woon', target: "j'habite", accept: ["J'habite", 'j habite', 'jhabite'] },
            { type: 'wordbank', nl: 'Mijn huis is groot en mijn keuken is klein.', target: 'Ma maison est grande et ma cuisine est petite', distractors: ['grand', 'la', 'petit'] },
            { type: 'type', nl: 'de slaapkamer', target: 'la chambre', accept: ['chambre', 'La chambre'] },
            { type: 'fill', before: 'Ma chambre', after: ' à droite.', nl: 'Mijn slaapkamer is rechts.', options: ['est', 'et', 'es'], correct: 0 },
            { type: 'listen', target: "j'habite à Paris", options: ["j'habite à Paris", "j'habite à Lyon", 'ma maison est grande'], correct: 0 },
            { type: 'wordbank', nl: 'De stoel staat in de keuken.', target: 'La chaise est dans la cuisine', distractors: ['sur', 'chambre', 'le'] },
            { type: 'type', nl: 'het raam', target: 'la fenêtre', accept: ['fenêtre', 'La fenêtre', 'la fenetre', 'fenetre'] },
            { type: 'select', prompt: 'Ma cuisine est petite.', speak: 'Ma cuisine est petite.', options: ['Mijn keuken is klein.', 'Mijn slaapkamer is klein.', 'Mijn keuken is groot.'], correct: 0 },
            { type: 'fill', before: "J'habite dans", after: ' grande maison.', nl: 'Ik woon in een groot huis.', options: ['une', 'un', 'la'], correct: 0 },
            { type: 'type', nl: 'de deur', target: 'la porte', accept: ['porte', 'La porte'] },
            { type: 'wordbank', nl: 'Het brood ligt op tafel.', target: 'Le pain est sur la table', distractors: ['dans', 'chaise', 'une'] },
          ],
        },
      ],
    },
    {
      id: 'fr-u8',
      title: 'Werk & school',
      icon: '💼',
      lessons: [
        {
          id: 'fr-u8-l1',
          title: 'Op het werk',
          exercises: [
            { type: 'new', word: 'le travail', nl: 'het werk', example: 'Mon travail est intéressant.', exampleNl: 'Mijn werk is interessant.' },
            { type: 'new', word: 'je travaille', nl: 'ik werk', example: 'Je travaille à Paris.', exampleNl: 'Ik werk in Parijs.' },
            { type: 'new', word: 'le bureau', nl: 'het kantoor', example: 'Le bureau est dans la ville.', exampleNl: 'Het kantoor is in de stad.' },
            { type: 'new', word: 'le médecin', nl: 'de dokter', example: 'Ma mère est médecin.', exampleNl: 'Mijn moeder is dokter.' },
            { type: 'select', prompt: 'het werk', options: ['le bureau', 'le travail', 'le médecin'], correct: 1 },
            { type: 'select', prompt: 'je travaille', speak: 'je travaille', options: ['ik woon', 'ik koop', 'ik werk'], correct: 2 },
            { type: 'listen', target: 'le bureau', options: ['le bureau', 'le travail', 'le métro'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'het werk', target: 'le travail' },
                { nl: 'ik werk', target: 'je travaille' },
                { nl: 'het kantoor', target: 'le bureau' },
                { nl: 'de dokter', target: 'le médecin' },
              ],
            },
            { type: 'fill', before: 'Je', after: ' le soir.', nl: "Ik werk 's avonds.", options: ['travaille', 'travailles', 'travaillez'], correct: 0 },
            { type: 'wordbank', nl: 'Ik werk op een kantoor in Parijs.', target: 'Je travaille dans un bureau à Paris', distractors: ['le', 'au', 'maison'] },
            { type: 'type', nl: 'de dokter', target: 'le médecin', accept: ['médecin', 'Le médecin', 'le medecin', 'medecin'] },
            { type: 'listen', target: 'je travaille', options: ['je travaille', "j'habite", 'je voudrais'], correct: 0 },
          ],
        },
        {
          id: 'fr-u8-l2',
          title: 'Naar school',
          exercises: [
            { type: 'new', word: "l'école", nl: 'de school', example: "L'école est à gauche.", exampleNl: 'De school is links.' },
            { type: 'new', word: 'le professeur', nl: 'de leraar', example: 'Mon père est professeur.', exampleNl: 'Mijn vader is leraar.' },
            { type: 'new', word: 'le livre', nl: 'het boek', example: 'Le livre est sur la table.', exampleNl: 'Het boek ligt op tafel.' },
            { type: 'new', word: "j'étudie", nl: 'ik studeer', example: "J'étudie le français.", exampleNl: 'Ik studeer Frans.' },
            { type: 'select', prompt: 'de school', options: ["l'école", 'le bureau', 'le livre'], correct: 0 },
            { type: 'select', prompt: 'le livre', speak: 'le livre', options: ['de leraar', 'het boek', 'de school'], correct: 1 },
            { type: 'listen', target: "l'école", options: ["l'école", "l'eau", "l'heure"], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'de school', target: "l'école" },
                { nl: 'de leraar', target: 'le professeur' },
                { nl: 'het boek', target: 'le livre' },
                { nl: 'ik studeer', target: "j'étudie" },
              ],
            },
            { type: 'fill', before: "J'étudie", after: ' français.', nl: 'Ik studeer Frans.', options: ['le', 'la', 'un'], correct: 0 },
            { type: 'wordbank', nl: 'Ik studeer Frans op school.', target: "J'étudie le français à l'école", distractors: ['la', 'au', 'livre'] },
            { type: 'type', nl: 'het boek', target: 'le livre', accept: ['livre', 'Le livre'] },
            { type: 'listen', target: 'le professeur', options: ['le professeur', 'le médecin', 'le père'], correct: 0 },
          ],
        },
        {
          id: 'fr-u8-l3',
          title: 'Herhaling: een drukke week',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'het werk', target: 'le travail' },
                { nl: 'het kantoor', target: 'le bureau' },
                { nl: 'de dokter', target: 'le médecin' },
                { nl: 'de school', target: "l'école" },
                { nl: 'het boek', target: 'le livre' },
              ],
            },
            { type: 'type', nl: 'ik werk', target: 'je travaille', accept: ['Je travaille'] },
            { type: 'wordbank', nl: "'s Ochtends werk ik op kantoor.", target: 'Le matin je travaille au bureau', distractors: ['soir', 'école', 'la'] },
            { type: 'type', nl: 'ik studeer', target: "j'étudie", accept: ["J'étudie", 'j etudie', "j'etudie"] },
            { type: 'fill', before: 'Ma sœur', after: ' médecin.', nl: 'Mijn zus is dokter.', options: ['est', 'es', 'et'], correct: 0 },
            { type: 'listen', target: "j'étudie le français", options: ["j'étudie le français", 'je travaille à Paris', 'le professeur'], correct: 0 },
            { type: 'select', prompt: 'Mon frère travaille à la gare.', speak: 'Mon frère travaille à la gare.', options: ['Mijn broer werkt op het station.', 'Mijn broer woont bij het station.', 'Mijn vader werkt op het station.'], correct: 0 },
            { type: 'wordbank', nl: 'De leraar heeft tien boeken.', target: 'Le professeur a dix livres', distractors: ['deux', 'est', 'livre'] },
            { type: 'type', nl: 'het kantoor', target: 'le bureau', accept: ['bureau', 'Le bureau'] },
            { type: 'fill', before: 'Je travaille', after: ' bureau.', nl: 'Ik werk op kantoor.', options: ['au', 'à la', 'le'], correct: 0 },
            { type: 'type', nl: 'de school', target: "l'école", accept: ['école', "L'école", 'ecole', 'l ecole'] },
            { type: 'wordbank', nl: 'Ik studeer Frans en ik werk in Parijs.', target: "J'étudie le français et je travaille à Paris", distractors: ['habite', 'la', 'au'] },
          ],
        },
      ],
    },
    {
      id: 'fr-u9',
      title: 'Gesprekken voeren',
      icon: '💬',
      lessons: [
        {
          id: 'fr-u9-l1',
          title: 'Een praatje maken',
          exercises: [
            { type: 'new', word: "aujourd'hui", nl: 'vandaag', example: "Aujourd'hui, je travaille.", exampleNl: 'Vandaag werk ik.' },
            { type: 'new', word: 'demain', nl: 'morgen', example: "Demain, j'étudie à la maison.", exampleNl: 'Morgen studeer ik thuis.' },
            { type: 'new', word: 'je parle', nl: 'ik spreek', example: 'Je parle français et néerlandais.', exampleNl: 'Ik spreek Frans en Nederlands.' },
            { type: 'new', word: 'aussi', nl: 'ook', example: 'Ma sœur parle aussi français.', exampleNl: 'Mijn zus spreekt ook Frans.' },
            { type: 'select', prompt: 'vandaag', options: ['demain', "aujourd'hui", 'le matin'], correct: 1 },
            { type: 'select', prompt: 'Je parle français.', speak: 'Je parle français.', options: ['Ik studeer Frans.', 'Ik spreek Frans.', 'Ik hou van Frans.'], correct: 1 },
            { type: 'listen', target: 'demain', options: ['demain', 'le matin', 'combien'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'vandaag', target: "aujourd'hui" },
                { nl: 'morgen', target: 'demain' },
                { nl: 'ik spreek', target: 'je parle' },
                { nl: 'ook', target: 'aussi' },
              ],
            },
            { type: 'wordbank', nl: 'Vandaag werk ik op kantoor.', target: "Aujourd'hui je travaille au bureau", distractors: ['demain', 'école', 'le'] },
            { type: 'fill', before: 'Je', after: ' français et néerlandais.', nl: 'Ik spreek Frans en Nederlands.', options: ['parle', 'parles', 'parlez'], correct: 0 },
            { type: 'type', nl: 'morgen', target: 'demain', accept: ['Demain'] },
            { type: 'wordbank', nl: 'Mijn broer spreekt ook Frans.', target: 'Mon frère parle aussi français', distractors: ['ma', 'sœur', 'et'] },
          ],
        },
        {
          id: 'fr-u9-l2',
          title: 'Vragen stellen',
          exercises: [
            { type: 'new', word: 'pourquoi', nl: 'waarom', example: 'Pourquoi tu travailles le soir ?', exampleNl: "Waarom werk je 's avonds?" },
            { type: 'new', word: 'parce que', nl: 'omdat', example: 'Parce que le café est bon !', exampleNl: 'Omdat de koffie lekker is!' },
            { type: 'new', word: 'quand', nl: 'wanneer', example: 'Tu travailles quand ?', exampleNl: 'Wanneer werk je?' },
            { type: 'new', word: 'avec', nl: 'met', example: 'Je travaille avec ma sœur.', exampleNl: 'Ik werk met mijn zus.' },
            { type: 'select', prompt: 'waarom', options: ['quand', 'pourquoi', 'combien'], correct: 1 },
            { type: 'select', prompt: 'avec', speak: 'avec', options: ['met', 'ook', 'omdat'], correct: 0 },
            { type: 'listen', target: 'pourquoi', options: ['pourquoi', 'quand', 'combien'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'waarom', target: 'pourquoi' },
                { nl: 'omdat', target: 'parce que' },
                { nl: 'wanneer', target: 'quand' },
                { nl: 'met', target: 'avec' },
              ],
            },
            { type: 'wordbank', nl: 'Wanneer werk je?', target: 'Tu travailles quand', distractors: ['pourquoi', 'je', 'où'] },
            { type: 'fill', before: 'Je prends un café', after: ' mon ami.', nl: 'Ik drink een koffie met mijn vriend.', options: ['avec', 'et', 'aussi'], correct: 0 },
            { type: 'type', nl: 'waarom', target: 'pourquoi', accept: ['Pourquoi'] },
            { type: 'wordbank', nl: 'Omdat het brood lekker is!', target: 'Parce que le pain est bon', distractors: ['bien', 'cher', 'la'] },
          ],
        },
        {
          id: 'fr-u9-l3',
          title: 'Herhaling: alles door elkaar',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'vandaag', target: "aujourd'hui" },
                { nl: 'morgen', target: 'demain' },
                { nl: 'waarom', target: 'pourquoi' },
                { nl: 'wanneer', target: 'quand' },
                { nl: 'met', target: 'avec' },
              ],
            },
            { type: 'type', nl: 'ook', target: 'aussi', accept: ['Aussi'] },
            { type: 'wordbank', nl: 'Vandaag koop ik fruit op de markt.', target: "Aujourd'hui j'achète des fruits au marché", distractors: ['demain', 'légumes', 'le'] },
            { type: 'type', nl: 'ik spreek', target: 'je parle', accept: ['Je parle'] },
            { type: 'fill', before: 'Pourquoi tu', after: ' le soir ?', nl: "Waarom werk je 's avonds?", options: ['travailles', 'travaille', 'travaillez'], correct: 0 },
            { type: 'listen', target: 'je parle français', options: ['je parle français', "j'étudie le français", 'je travaille demain'], correct: 0 },
            { type: 'select', prompt: 'Demain, je travaille avec ma mère.', speak: 'Demain, je travaille avec ma mère.', options: ['Morgen werk ik met mijn moeder.', 'Vandaag werk ik met mijn moeder.', 'Morgen woon ik bij mijn moeder.'], correct: 0 },
            { type: 'wordbank', nl: 'Het boek kost tien euro.', target: 'Le livre coûte dix euros', distractors: ['cher', 'deux', 'combien'] },
            { type: 'type', nl: 'wanneer', target: 'quand', accept: ['Quand'] },
            { type: 'fill', before: "J'habite", after: ' ma famille.', nl: 'Ik woon met mijn familie.', options: ['avec', 'et', 'à'], correct: 0 },
            { type: 'wordbank', nl: "'s Avonds spreek ik Frans met mijn vriend.", target: 'Le soir je parle français avec mon ami', distractors: ['matin', 'aussi', 'ma'] },
            { type: 'type', nl: 'vandaag', target: "aujourd'hui", accept: ["Aujourd'hui", 'aujourd hui', 'aujourdhui'] },
            { type: 'wordbank', nl: 'Waarom is de wijn duur?', target: 'Pourquoi le vin est cher', distractors: ['trop', 'combien', 'la'] },
          ],
        },
      ],
    },
  ],
}
