import type { Section } from '../../types'

export const section: Section = {
  title: 'Sectie 3 · Op weg naar A2',
  cefr: 'A2',
  units: [
    {
      id: 'fr-u10',
      title: 'Reizen & vervoer',
      icon: '✈️',
      lessons: [
        {
          id: 'fr-u10-l1',
          title: 'Op reis',
          exercises: [
            { type: 'new', word: 'le train', nl: 'de trein', example: 'Le train pour Lyon part à dix heures.', exampleNl: 'De trein naar Lyon vertrekt om tien uur.' },
            { type: 'new', word: 'le billet', nl: 'het kaartje', example: 'Je voudrais un billet pour Paris.', exampleNl: 'Ik wil graag een kaartje naar Parijs.' },
            { type: 'new', word: 'le voyage', nl: 'de reis', example: 'Le voyage à Paris est long.', exampleNl: 'De reis naar Parijs is lang.' },
            { type: 'new', word: 'la valise', nl: 'de koffer', example: 'Ma valise est dans le train.', exampleNl: 'Mijn koffer is in de trein.' },
            { type: 'select', prompt: 'het kaartje', options: ['le voyage', 'le billet', 'le train'], correct: 1 },
            { type: 'select', prompt: 'la valise', speak: 'la valise', options: ['de reis', 'de trein', 'de koffer'], correct: 2 },
            { type: 'listen', target: 'le train', options: ['le train', 'le voyage', 'la ville'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'de trein', target: 'le train' },
                { nl: 'het kaartje', target: 'le billet' },
                { nl: 'de reis', target: 'le voyage' },
                { nl: 'de koffer', target: 'la valise' },
              ],
            },
            { type: 'fill', before: 'Je voudrais un billet', after: ' Lyon.', nl: 'Ik wil graag een kaartje naar Lyon.', options: ['pour', 'à', 'de'], correct: 0 },
            { type: 'wordbank', nl: 'De reis naar Parijs is lang.', target: 'Le voyage à Paris est long', distractors: ['train', 'longue', 'la'] },
            { type: 'type', nl: 'de trein', target: 'le train', accept: ['train', 'Le train'] },
            { type: 'listen', target: 'le billet', options: ['la valise', 'le billet', 'le voyage'], correct: 1 },
          ],
        },
        {
          id: 'fr-u10-l2',
          title: 'Vertrek en aankomst',
          exercises: [
            { type: 'new', word: "l'avion", nl: 'het vliegtuig', example: "L'avion arrive à Paris.", exampleNl: 'Het vliegtuig komt aan in Parijs.' },
            { type: 'new', word: "l'aéroport", nl: 'het vliegveld', example: "L'aéroport est loin de la ville.", exampleNl: 'Het vliegveld is ver van de stad.' },
            { type: 'new', word: 'partir', nl: 'vertrekken', example: 'Le train part à neuf heures.', exampleNl: 'De trein vertrekt om negen uur.' },
            { type: 'new', word: 'arriver', nl: 'aankomen', example: 'Nous arrivons à la gare.', exampleNl: 'Wij komen aan op het station.' },
            { type: 'select', prompt: 'het vliegtuig', options: ["l'aéroport", "l'avion", 'le train'], correct: 1 },
            { type: 'select', prompt: "l'aéroport", speak: "l'aéroport", options: ['het station', 'het vliegveld', 'het vliegtuig'], correct: 1 },
            { type: 'listen', target: "l'avion", options: ["l'avion", "l'aéroport", 'le billet'], correct: 0 },
            { type: 'fill', before: 'Le train', after: ' à neuf heures.', nl: 'De trein vertrekt om negen uur.', options: ['part', 'pars', 'partez'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'het vliegtuig', target: "l'avion" },
                { nl: 'het vliegveld', target: "l'aéroport" },
                { nl: 'vertrekken', target: 'partir' },
                { nl: 'aankomen', target: 'arriver' },
              ],
            },
            { type: 'wordbank', nl: 'Het vliegtuig vertrekt om tien uur.', target: "L'avion part à dix heures", distractors: ['arrive', 'le', 'gare'] },
            { type: 'type', nl: 'het vliegveld', target: "l'aéroport", accept: ['aéroport', "L'aéroport", 'aeroport', 'l aeroport'] },
            { type: 'fill', before: 'Nous', after: ' à la gare.', nl: 'Wij komen aan op het station.', options: ['arrivons', 'arrive', 'arrivez'], correct: 0 },
          ],
        },
        {
          id: 'fr-u10-l3',
          title: 'Herhaling: onderweg',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'de trein', target: 'le train' },
                { nl: 'het kaartje', target: 'le billet' },
                { nl: 'het vliegtuig', target: "l'avion" },
                { nl: 'de koffer', target: 'la valise' },
                { nl: 'het vliegveld', target: "l'aéroport" },
              ],
            },
            { type: 'type', nl: 'het kaartje', target: 'le billet', accept: ['billet', 'Le billet'] },
            { type: 'wordbank', nl: 'Ik wil graag een kaartje naar Nice.', target: 'Je voudrais un billet pour Nice', distractors: ['train', 'le', 'à'] },
            { type: 'type', nl: 'de koffer', target: 'la valise', accept: ['valise', 'La valise'] },
            { type: 'listen', target: 'le voyage', options: ['le voyage', 'la valise', 'le billet'], correct: 0 },
            { type: 'select', prompt: "L'avion part à dix heures.", speak: "L'avion part à dix heures.", options: ['Het vliegtuig komt om tien uur aan.', 'Het vliegtuig vertrekt om tien uur.', 'De trein vertrekt om tien uur.'], correct: 1 },
            { type: 'wordbank', nl: 'Waar is het vliegveld?', target: "Où est l'aéroport", distractors: ['gare', 'la', 'avion'] },
            { type: 'type', nl: 'het vliegtuig', target: "l'avion", accept: ['avion', "L'avion", 'l avion'] },
            { type: 'fill', before: "L'avion arrive", after: ' Paris.', nl: 'Het vliegtuig komt aan in Parijs.', options: ['à', 'en', 'au'], correct: 0 },
            { type: 'type', nl: 'vertrekken', target: 'partir', accept: ['Partir'] },
            { type: 'wordbank', nl: 'Mijn koffer is op het station.', target: 'Ma valise est à la gare', distractors: ['mon', 'le', 'train'] },
            { type: 'type', nl: 'de reis', target: 'le voyage', accept: ['voyage', 'Le voyage'] },
          ],
        },
      ],
    },
    {
      id: 'fr-u11',
      title: 'Gezondheid & lichaam',
      icon: '🌿',
      lessons: [
        {
          id: 'fr-u11-l1',
          title: 'Het lichaam',
          exercises: [
            { type: 'new', word: 'la tête', nl: 'het hoofd', example: "J'ai mal à la tête.", exampleNl: 'Ik heb hoofdpijn.' },
            { type: 'new', word: 'la main', nl: 'de hand', example: 'Il écrit avec la main gauche.', exampleNl: 'Hij schrijft met zijn linkerhand.' },
            { type: 'new', word: 'le ventre', nl: 'de buik', example: "J'ai mal au ventre.", exampleNl: 'Ik heb buikpijn.' },
            { type: 'new', word: 'la jambe', nl: 'het been', example: 'Ma jambe me fait mal.', exampleNl: 'Mijn been doet pijn.' },
            { type: 'select', prompt: 'het hoofd', options: ['la main', 'la jambe', 'la tête'], correct: 2 },
            { type: 'select', prompt: 'le ventre', speak: 'le ventre', options: ['de buik', 'het been', 'de hand'], correct: 0 },
            { type: 'listen', target: 'la jambe', options: ['la jambe', 'la main', 'la tête'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'het hoofd', target: 'la tête' },
                { nl: 'de hand', target: 'la main' },
                { nl: 'de buik', target: 'le ventre' },
                { nl: 'het been', target: 'la jambe' },
              ],
            },
            { type: 'fill', before: "J'ai mal", after: ' la tête.', nl: 'Ik heb hoofdpijn.', options: ['à', 'au', 'aux'], correct: 0 },
            { type: 'fill', before: "J'ai mal", after: ' ventre.', nl: 'Ik heb buikpijn.', options: ['à', 'au', 'à la'], correct: 1 },
            { type: 'wordbank', nl: 'Mijn been doet pijn.', target: 'Ma jambe me fait mal', distractors: ['tête', 'le', 'bien'] },
            { type: 'type', nl: 'de hand', target: 'la main', accept: ['main', 'La main'] },
          ],
        },
        {
          id: 'fr-u11-l2',
          title: 'Bij de dokter',
          exercises: [
            { type: 'new', word: 'le médecin', nl: 'de dokter', example: 'Je vais chez le médecin.', exampleNl: 'Ik ga naar de dokter.' },
            { type: 'new', word: 'malade', nl: 'ziek', example: 'Ma sœur est malade.', exampleNl: 'Mijn zus is ziek.' },
            { type: 'new', word: 'la pharmacie', nl: 'de apotheek', example: 'La pharmacie est à gauche.', exampleNl: 'De apotheek is links.' },
            { type: 'new', word: 'fatigué', nl: 'moe', example: 'Je suis fatigué ce soir.', exampleNl: 'Ik ben moe vanavond.' },
            { type: 'select', prompt: 'ziek', options: ['fatigué', 'malade', 'bien'], correct: 1 },
            { type: 'select', prompt: 'le médecin', speak: 'le médecin', options: ['de apotheek', 'de dokter', 'de buik'], correct: 1 },
            { type: 'listen', target: 'la pharmacie', options: ['la pharmacie', 'le médecin', 'la famille'], correct: 0 },
            { type: 'fill', before: 'Je vais', after: ' le médecin.', nl: 'Ik ga naar de dokter.', options: ['chez', 'à', 'dans'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'de dokter', target: 'le médecin' },
                { nl: 'ziek', target: 'malade' },
                { nl: 'de apotheek', target: 'la pharmacie' },
                { nl: 'moe', target: 'fatigué' },
              ],
            },
            { type: 'wordbank', nl: 'Mijn broer is ziek.', target: 'Mon frère est malade', distractors: ['ma', 'fatigué', 'sœur'] },
            { type: 'type', nl: 'moe', target: 'fatigué', accept: ['Fatigué', 'fatigue', 'fatiguée'] },
            { type: 'fill', before: 'Ma mère est', after: " aujourd'hui.", nl: 'Mijn moeder is moe vandaag.', options: ['fatigué', 'fatiguée', 'fatigués'], correct: 1 },
          ],
        },
        {
          id: 'fr-u11-l3',
          title: 'Herhaling: in vorm blijven',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'het hoofd', target: 'la tête' },
                { nl: 'de buik', target: 'le ventre' },
                { nl: 'het been', target: 'la jambe' },
                { nl: 'de dokter', target: 'le médecin' },
                { nl: 'de apotheek', target: 'la pharmacie' },
              ],
            },
            { type: 'type', nl: 'ziek', target: 'malade', accept: ['Malade'] },
            { type: 'wordbank', nl: 'Ik heb hoofdpijn en ik ben moe.', target: "J'ai mal à la tête et je suis fatigué", distractors: ['ventre', 'au', 'malade'] },
            { type: 'type', nl: 'de dokter', target: 'le médecin', accept: ['médecin', 'Le médecin', 'le medecin', 'medecin'] },
            { type: 'listen', target: "j'ai mal à la tête", options: ["j'ai mal à la tête", "j'ai mal au ventre", 'je suis malade'], correct: 0 },
            { type: 'select', prompt: 'La pharmacie est à droite.', speak: 'La pharmacie est à droite.', options: ['De apotheek is links.', 'De dokter is rechts.', 'De apotheek is rechts.'], correct: 2 },
            { type: 'type', nl: 'de apotheek', target: 'la pharmacie', accept: ['pharmacie', 'La pharmacie'] },
            { type: 'fill', before: "J'ai mal", after: ' jambes.', nl: 'Ik heb pijn aan mijn benen.', options: ['à la', 'au', 'aux'], correct: 2 },
            { type: 'wordbank', nl: 'Ik ben ziek en ik ga naar de dokter.', target: 'Je suis malade et je vais chez le médecin', distractors: ['fatigué', 'à', 'la'] },
            { type: 'type', nl: 'het been', target: 'la jambe', accept: ['jambe', 'La jambe'] },
            { type: 'listen', target: 'je suis fatigué', options: ['je suis fatigué', 'je suis malade', 'je vais bien'], correct: 0 },
            { type: 'wordbank', nl: 'Waar is de apotheek?', target: 'Où est la pharmacie', distractors: ['médecin', 'le', 'chez'] },
          ],
        },
      ],
    },
    {
      id: 'fr-u12',
      title: 'Weer & seizoenen',
      icon: '🌦️',
      lessons: [
        {
          id: 'fr-u12-l1',
          title: 'Wat voor weer is het?',
          exercises: [
            { type: 'new', word: 'il pleut', nl: 'het regent', example: "Il pleut à Paris aujourd'hui.", exampleNl: 'Het regent vandaag in Parijs.' },
            { type: 'new', word: 'il fait beau', nl: 'het is mooi weer', example: 'Il fait beau ce matin.', exampleNl: 'Het is mooi weer vanochtend.' },
            { type: 'new', word: 'le soleil', nl: 'de zon', example: 'Le soleil brille.', exampleNl: 'De zon schijnt.' },
            { type: 'new', word: 'froid', nl: 'koud', example: 'Il fait froid ce soir.', exampleNl: 'Het is koud vanavond.' },
            { type: 'select', prompt: 'het regent', options: ['il fait beau', 'il pleut', 'il fait froid'], correct: 1 },
            { type: 'select', prompt: 'le soleil', speak: 'le soleil', options: ['de regen', 'de zon', 'de sneeuw'], correct: 1 },
            { type: 'listen', target: 'il pleut', options: ['il pleut', 'il fait beau', 'le soleil'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'het regent', target: 'il pleut' },
                { nl: 'het is mooi weer', target: 'il fait beau' },
                { nl: 'de zon', target: 'le soleil' },
                { nl: 'koud', target: 'froid' },
              ],
            },
            { type: 'fill', before: 'Il', after: ' froid ce soir.', nl: 'Het is koud vanavond.', options: ['fait', 'est', 'a'], correct: 0 },
            { type: 'wordbank', nl: 'Het is mooi weer vandaag.', target: "Il fait beau aujourd'hui", distractors: ['pleut', 'froid', 'le'] },
            { type: 'type', nl: 'de zon', target: 'le soleil', accept: ['soleil', 'Le soleil'] },
            { type: 'listen', target: 'il fait froid', options: ['il fait beau', 'il fait froid', 'il pleut'], correct: 1 },
          ],
        },
        {
          id: 'fr-u12-l2',
          title: 'De seizoenen',
          exercises: [
            { type: 'new', word: "l'été", nl: 'de zomer', example: 'En été, je voyage avec ma famille.', exampleNl: 'In de zomer reis ik met mijn familie.' },
            { type: 'new', word: "l'hiver", nl: 'de winter', example: 'En hiver, il fait froid.', exampleNl: 'In de winter is het koud.' },
            { type: 'new', word: 'chaud', nl: 'warm', example: 'Il fait chaud en été.', exampleNl: 'Het is warm in de zomer.' },
            { type: 'new', word: 'la neige', nl: 'de sneeuw', example: 'La neige est belle en hiver.', exampleNl: 'De sneeuw is mooi in de winter.' },
            { type: 'select', prompt: 'de winter', options: ["l'été", "l'hiver", 'la neige'], correct: 1 },
            { type: 'select', prompt: 'chaud', speak: 'chaud', options: ['koud', 'warm', 'mooi'], correct: 1 },
            { type: 'listen', target: 'la neige', options: ['la neige', 'la jambe', 'la ville'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'de zomer', target: "l'été" },
                { nl: 'de winter', target: "l'hiver" },
                { nl: 'warm', target: 'chaud' },
                { nl: 'de sneeuw', target: 'la neige' },
              ],
            },
            { type: 'fill', before: 'En', after: ', il fait chaud.', nl: 'In de zomer is het warm.', options: ['été', 'hiver', 'soleil'], correct: 0 },
            { type: 'wordbank', nl: 'In de winter is het koud.', target: 'En hiver il fait froid', distractors: ['été', 'chaud', 'beau'] },
            { type: 'type', nl: 'de zomer', target: "l'été", accept: ['été', "L'été", 'ete', 'l ete'] },
            { type: 'select', prompt: 'Il fait chaud en été.', speak: 'Il fait chaud en été.', options: ['Het is koud in de winter.', 'Het is warm in de zomer.', 'Het regent in de zomer.'], correct: 1 },
          ],
        },
        {
          id: 'fr-u12-l3',
          title: 'Herhaling: het weerbericht',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'het regent', target: 'il pleut' },
                { nl: 'de zon', target: 'le soleil' },
                { nl: 'de sneeuw', target: 'la neige' },
                { nl: 'warm', target: 'chaud' },
                { nl: 'koud', target: 'froid' },
              ],
            },
            { type: 'type', nl: 'de winter', target: "l'hiver", accept: ['hiver', "L'hiver", 'l hiver'] },
            { type: 'wordbank', nl: 'Vandaag schijnt de zon.', target: "Aujourd'hui le soleil brille", distractors: ['pleut', 'la', 'neige'] },
            { type: 'type', nl: 'warm', target: 'chaud', accept: ['Chaud'] },
            { type: 'listen', target: 'il fait beau', options: ['il fait beau', 'il fait chaud', 'il fait froid'], correct: 0 },
            { type: 'select', prompt: 'Il pleut à Paris.', speak: 'Il pleut à Paris.', options: ['Het sneeuwt in Parijs.', 'Het regent in Parijs.', 'De zon schijnt in Parijs.'], correct: 1 },
            { type: 'wordbank', nl: 'Het is mooi weer en het is warm.', target: 'Il fait beau et il fait chaud', distractors: ['froid', 'pleut', 'le'] },
            { type: 'fill', before: 'En hiver, il fait', after: '.', nl: 'In de winter is het koud.', options: ['chaud', 'froid', 'beau'], correct: 1 },
            { type: 'type', nl: 'de sneeuw', target: 'la neige', accept: ['neige', 'La neige'] },
            { type: 'type', nl: 'het regent', target: 'il pleut', accept: ['Il pleut', 'pleut'] },
            { type: 'wordbank', nl: 'In de zomer reis ik met mijn familie.', target: 'En été je voyage avec ma famille', distractors: ['hiver', 'la', 'mon'] },
            { type: 'fill', before: 'Le soleil', after: ' ce matin.', nl: 'De zon schijnt vanochtend.', options: ['brille', 'brilles', 'brillez'], correct: 0 },
          ],
        },
      ],
    },
    {
      id: 'fr-u13',
      title: 'Uitgaan & cultuur',
      icon: '🎭',
      lessons: [
        {
          id: 'fr-u13-l1',
          title: 'Naar de film',
          exercises: [
            { type: 'new', word: 'le cinéma', nl: 'de bioscoop', example: 'On va au cinéma ce soir ?', exampleNl: 'Gaan we vanavond naar de bioscoop?' },
            { type: 'new', word: 'le film', nl: 'de film', example: 'Le film commence à huit heures.', exampleNl: 'De film begint om acht uur.' },
            { type: 'new', word: 'le théâtre', nl: 'het theater', example: 'Le théâtre est près du musée.', exampleNl: 'Het theater is bij het museum.' },
            { type: 'new', word: 'la musique', nl: 'de muziek', example: "J'aime la musique française.", exampleNl: 'Ik hou van Franse muziek.' },
            { type: 'select', prompt: 'de bioscoop', options: ['le théâtre', 'le cinéma', 'le film'], correct: 1 },
            { type: 'select', prompt: 'la musique', speak: 'la musique', options: ['de muziek', 'de film', 'het theater'], correct: 0 },
            { type: 'listen', target: 'le cinéma', options: ['le cinéma', 'le théâtre', 'la musique'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'de bioscoop', target: 'le cinéma' },
                { nl: 'de film', target: 'le film' },
                { nl: 'het theater', target: 'le théâtre' },
                { nl: 'de muziek', target: 'la musique' },
              ],
            },
            { type: 'fill', before: 'On va', after: ' cinéma ce soir.', nl: 'We gaan vanavond naar de bioscoop.', options: ['au', 'à la', 'chez'], correct: 0 },
            { type: 'wordbank', nl: 'De film begint om acht uur.', target: 'Le film commence à huit heures', distractors: ['cinéma', 'le', 'part'] },
            { type: 'type', nl: 'de film', target: 'le film', accept: ['film', 'Le film'] },
            { type: 'listen', target: 'le théâtre', options: ['le métro', 'le théâtre', 'le musée'], correct: 1 },
          ],
        },
        {
          id: 'fr-u13-l2',
          title: 'Een avondje uit',
          exercises: [
            { type: 'new', word: 'le restaurant', nl: 'het restaurant', example: 'Le restaurant est ouvert ce soir.', exampleNl: 'Het restaurant is vanavond open.' },
            { type: 'new', word: 'le concert', nl: 'het concert', example: 'Le concert commence à neuf heures.', exampleNl: 'Het concert begint om negen uur.' },
            { type: 'new', word: 'danser', nl: 'dansen', example: "J'aime danser avec mes amis.", exampleNl: 'Ik dans graag met mijn vrienden.' },
            { type: 'new', word: 'chanter', nl: 'zingen', example: 'Elle chante très bien.', exampleNl: 'Zij zingt heel goed.' },
            { type: 'select', prompt: 'dansen', options: ['chanter', 'danser', 'commencer'], correct: 1 },
            { type: 'select', prompt: 'le concert', speak: 'le concert', options: ['het restaurant', 'de bioscoop', 'het concert'], correct: 2 },
            { type: 'listen', target: 'danser', options: ['danser', 'chanter', 'manger'], correct: 0 },
            { type: 'fill', before: 'Elle', after: ' très bien.', nl: 'Zij zingt heel goed.', options: ['chante', 'chantes', 'chantez'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'het restaurant', target: 'le restaurant' },
                { nl: 'het concert', target: 'le concert' },
                { nl: 'dansen', target: 'danser' },
                { nl: 'zingen', target: 'chanter' },
              ],
            },
            { type: 'wordbank', nl: 'Ik dans graag met mijn vrienden.', target: "J'aime danser avec mes amis", distractors: ['chante', 'mon', 'le'] },
            { type: 'type', nl: 'zingen', target: 'chanter', accept: ['Chanter'] },
            { type: 'fill', before: 'Le restaurant est', after: ' du théâtre.', nl: 'Het restaurant is bij het theater.', options: ['près', 'chez', 'sur'], correct: 0 },
          ],
        },
        {
          id: 'fr-u13-l3',
          title: 'Herhaling: een avond uit',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'de bioscoop', target: 'le cinéma' },
                { nl: 'het theater', target: 'le théâtre' },
                { nl: 'de muziek', target: 'la musique' },
                { nl: 'het concert', target: 'le concert' },
                { nl: 'het restaurant', target: 'le restaurant' },
              ],
            },
            { type: 'type', nl: 'de bioscoop', target: 'le cinéma', accept: ['cinéma', 'Le cinéma', 'cinema', 'le cinema'] },
            { type: 'wordbank', nl: 'Gaan we vanavond naar de bioscoop?', target: 'On va au cinéma ce soir', distractors: ['théâtre', 'le', 'demain'] },
            { type: 'type', nl: 'de muziek', target: 'la musique', accept: ['musique', 'La musique'] },
            { type: 'listen', target: 'le concert commence', options: ['le concert commence', 'le film commence', 'le concert est bon'], correct: 0 },
            { type: 'select', prompt: "J'aime la musique française.", speak: "J'aime la musique française.", options: ['Ik hou van Franse films.', 'Ik hou van Franse muziek.', 'Ik hou van het Franse theater.'], correct: 1 },
            { type: 'wordbank', nl: 'Het concert begint om negen uur.', target: 'Le concert commence à neuf heures', distractors: ['huit', 'film', 'part'] },
            { type: 'type', nl: 'dansen', target: 'danser', accept: ['Danser'] },
            { type: 'fill', before: "J'aime", after: ' avec mes amis.', nl: 'Ik zing graag met mijn vrienden.', options: ['chanter', 'chante', 'chantez'], correct: 0 },
            { type: 'type', nl: 'het theater', target: 'le théâtre', accept: ['théâtre', 'Le théâtre', 'theatre', 'le theatre'] },
            { type: 'wordbank', nl: 'Het restaurant is bij het museum.', target: 'Le restaurant est près du musée', distractors: ['théâtre', 'au', 'la'] },
            { type: 'listen', target: 'la musique', options: ['la musique', 'le musée', 'la ville'], correct: 0 },
          ],
        },
      ],
    },
    {
      id: 'fr-u14',
      title: 'De grote herhaling',
      icon: '🏆',
      lessons: [
        {
          id: 'fr-u14-l1',
          title: 'Terug naar het begin',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'goedendag', target: 'bonjour' },
                { nl: 'dank je wel', target: 'merci' },
                { nl: 'de trein', target: 'le train' },
                { nl: 'het station', target: 'la gare' },
                { nl: 'de dokter', target: 'le médecin' },
              ],
            },
            { type: 'type', nl: 'ik wil graag', target: 'je voudrais', accept: ['Je voudrais'] },
            { type: 'wordbank', nl: 'Goedendag, ik wil graag een kaartje naar Parijs.', target: 'Bonjour je voudrais un billet pour Paris', distractors: ['merci', 'train', 'le'] },
            { type: 'select', prompt: 'Où est la gare ?', speak: 'Où est la gare ?', options: ['Waar is het vliegveld?', 'Waar is het station?', 'Waar is de apotheek?'], correct: 1 },
            { type: 'type', nl: 'een koffie', target: 'un café', accept: ['café', 'Un café', 'un cafe', 'cafe'] },
            { type: 'listen', target: 'je voudrais un café', options: ['je voudrais un café', 'je voudrais un thé', 'un café et un croissant'], correct: 0 },
            { type: 'wordbank', nl: 'Mijn zus is ziek en ik ga naar de apotheek.', target: 'Ma sœur est malade et je vais à la pharmacie', distractors: ['chez', 'mon', 'médecin'] },
            { type: 'fill', before: 'Où', after: " l'aéroport ?", nl: 'Waar is het vliegveld?', options: ['est', 'es', 'et'], correct: 0 },
            { type: 'type', nl: 'tot ziens', target: 'au revoir', accept: ['Au revoir'] },
            { type: 'wordbank', nl: 'De metro is links en het museum is rechts.', target: 'Le métro est à gauche et le musée est à droite', distractors: ['la', 'gare', 'où'] },
            { type: 'select', prompt: 'de kaas', options: ['le pain', 'le fromage', 'le vin'], correct: 1 },
            { type: 'type', nl: 'het water', target: "l'eau", accept: ['eau', "L'eau", 'l eau'] },
          ],
        },
        {
          id: 'fr-u14-l2',
          title: 'Alles door elkaar',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'het vliegtuig', target: "l'avion" },
                { nl: 'de zon', target: 'le soleil' },
                { nl: 'de film', target: 'le film' },
                { nl: 'de buik', target: 'le ventre' },
                { nl: 'de winter', target: "l'hiver" },
              ],
            },
            { type: 'wordbank', nl: 'Het regent en ik neem de metro.', target: 'Il pleut et je prends le métro', distractors: ['fait', 'beau', 'la'] },
            { type: 'type', nl: 'het is mooi weer', target: 'il fait beau', accept: ['Il fait beau'] },
            { type: 'listen', target: 'le train part à dix heures', options: ['le train part à dix heures', 'le film commence à dix heures', 'le train arrive à dix heures'], correct: 0 },
            { type: 'select', prompt: 'Je suis fatigué et je vais chez le médecin.', speak: 'Je suis fatigué et je vais chez le médecin.', options: ['Ik ben ziek en ik ga naar de apotheek.', 'Ik ben moe en ik ga naar de dokter.', 'Ik ben moe en ik blijf thuis.'], correct: 1 },
            { type: 'fill', before: "L'avion", after: ' à Nice en été.', nl: 'Het vliegtuig komt in de zomer in Nice aan.', options: ['arrive', 'arrives', 'arrivez'], correct: 0 },
            { type: 'wordbank', nl: 'In de winter gaan we naar het theater.', target: 'En hiver on va au théâtre', distractors: ['été', 'cinéma', 'la'] },
            { type: 'type', nl: 'warm', target: 'chaud', accept: ['Chaud'] },
            { type: 'select', prompt: 'de koffer', options: ['le billet', 'la valise', 'le voyage'], correct: 1 },
            { type: 'wordbank', nl: 'Ik hou van muziek en ik zing heel goed.', target: "J'aime la musique et je chante très bien", distractors: ['danse', 'le', 'mal'] },
            { type: 'fill', before: "J'ai mal", after: ' la tête.', nl: 'Ik heb hoofdpijn.', options: ['à', 'au', 'aux'], correct: 0 },
            { type: 'listen', target: 'il fait chaud en été', options: ['il fait chaud en été', 'il fait froid en hiver', 'il fait beau ce matin'], correct: 0 },
          ],
        },
        {
          id: 'fr-u14-l3',
          title: 'De grote finale',
          exercises: [
            { type: 'type', nl: 'Het vliegtuig vertrekt om tien uur.', target: "L'avion part à dix heures", accept: ["l'avion part à dix heures", 'L avion part a dix heures'] },
            { type: 'wordbank', nl: 'Goedendag, ik wil graag een thee en een croissant.', target: 'Bonjour je voudrais un thé et un croissant', distractors: ['café', 'merci', 'le'] },
            { type: 'type', nl: 'Ik ben ziek.', target: 'Je suis malade', accept: ['je suis malade', 'Je suis malade.'] },
            { type: 'wordbank', nl: 'In de winter is het koud en in de zomer is het warm.', target: 'En hiver il fait froid et en été il fait chaud', distractors: ['beau', 'pleut', 'le'] },
            { type: 'type', nl: 'Waar is het theater?', target: 'Où est le théâtre', accept: ['où est le théâtre', 'Où est le théâtre ?', 'Ou est le theatre'] },
            { type: 'wordbank', nl: 'Mijn moeder gaat naar de dokter.', target: 'Ma mère va chez le médecin', distractors: ['mon', 'à', 'pharmacie'] },
            {
              type: 'match',
              pairs: [
                { nl: 'de moeder', target: 'la mère' },
                { nl: 'de broer', target: 'le frère' },
                { nl: 'moe', target: 'fatigué' },
                { nl: 'de sneeuw', target: 'la neige' },
                { nl: 'het kaartje', target: 'le billet' },
              ],
            },
            { type: 'type', nl: 'De film begint om acht uur.', target: 'Le film commence à huit heures', accept: ['le film commence à huit heures', 'Le film commence a huit heures'] },
            { type: 'wordbank', nl: 'Wij komen aan op het station en wij nemen de metro.', target: 'Nous arrivons à la gare et nous prenons le métro', distractors: ['part', 'du', 'chez'] },
            { type: 'type', nl: 'Het regent vandaag.', target: "Il pleut aujourd'hui", accept: ["il pleut aujourd'hui", 'Il pleut aujourd hui'] },
            { type: 'wordbank', nl: 'Ik hou van dansen en van Franse muziek.', target: "J'aime danser et la musique française", distractors: ['chanter', 'le', 'très'] },
            { type: 'listen', target: 'au revoir et merci beaucoup', options: ['au revoir et merci beaucoup', 'bonjour et merci beaucoup', 'au revoir madame'], correct: 0 },
          ],
        },
      ],
    },
  ],
}
