import type { Course } from '../../types'

export const course: Course = {
  id: 'fr',
  name: 'Frans',
  flag: '🇫🇷',
  tagline: 'Elegantie in elke zin',
  ttsLang: 'fr-FR',
  sections: [
    {
      title: 'Sectie 1 · Eerste stappen',
      cefr: 'A1',
      units: [
        {
          id: 'fr-u1',
          title: 'Begroetingen & basis',
          icon: '👋',
          lessons: [
            {
              id: 'fr-u1-l1',
              title: 'Hallo zeggen',
              exercises: [
                { type: 'new', word: 'bonjour', nl: 'goedendag', example: 'Bonjour, madame !', exampleNl: 'Goedendag, mevrouw!' },
                { type: 'new', word: 'salut', nl: 'hoi', example: 'Salut, Marie !', exampleNl: 'Hoi, Marie!' },
                { type: 'new', word: 'au revoir', nl: 'tot ziens', example: 'Au revoir, monsieur !', exampleNl: 'Tot ziens, meneer!' },
                { type: 'new', word: 'merci', nl: 'dank je wel', example: 'Merci beaucoup !', exampleNl: 'Heel erg bedankt!' },
                { type: 'select', prompt: 'goedendag', options: ['au revoir', 'bonjour', 'salut'], correct: 1 },
                { type: 'select', prompt: 'merci', speak: 'merci', options: ['tot ziens', 'hoi', 'dank je wel'], correct: 2 },
                { type: 'listen', target: 'bonjour', options: ['bonjour', 'au revoir', 'salut'], correct: 0 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'goedendag', target: 'bonjour' },
                    { nl: 'hoi', target: 'salut' },
                    { nl: 'tot ziens', target: 'au revoir' },
                    { nl: 'dank je wel', target: 'merci' },
                  ],
                },
                { type: 'select', prompt: 'au revoir', speak: 'au revoir', options: ['goedendag', 'tot ziens', 'dank je wel'], correct: 1 },
                { type: 'wordbank', nl: 'Goedendag, mevrouw!', target: 'Bonjour madame', distractors: ['salut', 'merci', 'monsieur'] },
                { type: 'type', nl: 'hoi', target: 'salut', accept: ['Salut', 'salut !'] },
                { type: 'listen', target: 'merci', options: ['salut', 'merci', 'madame'], correct: 1 },
              ],
            },
            {
              id: 'fr-u1-l2',
              title: 'Hoe gaat het?',
              exercises: [
                { type: 'new', word: 'ça va', nl: 'het gaat', example: 'Salut, ça va ?', exampleNl: 'Hoi, gaat het?' },
                { type: 'new', word: 'bien', nl: 'goed', example: 'Ça va bien.', exampleNl: 'Het gaat goed.' },
                { type: 'new', word: 'oui', nl: 'ja', example: 'Oui, merci.', exampleNl: 'Ja, dank je.' },
                { type: 'new', word: 'non', nl: 'nee', example: 'Non, merci.', exampleNl: 'Nee, dank je.' },
                { type: 'select', prompt: 'ja', options: ['non', 'bien', 'oui'], correct: 2 },
                { type: 'select', prompt: 'bien', speak: 'bien', options: ['goed', 'ja', 'nee'], correct: 0 },
                { type: 'listen', target: 'ça va', options: ['ça va', 'oui', 'au revoir'], correct: 0 },
                { type: 'fill', before: 'Ça va', after: ', merci.', nl: 'Het gaat goed, dank je.', options: ['oui', 'bien', 'bon'], correct: 1 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'ja', target: 'oui' },
                    { nl: 'nee', target: 'non' },
                    { nl: 'goed', target: 'bien' },
                    { nl: 'het gaat', target: 'ça va' },
                  ],
                },
                { type: 'wordbank', nl: 'Het gaat goed, dank je.', target: 'Ça va bien merci', distractors: ['non', 'salut', 'oui'] },
                { type: 'type', nl: 'ja', target: 'oui', accept: ['Oui', 'oui.'] },
                { type: 'select', prompt: 'Non, merci.', speak: 'Non, merci.', options: ['Ja, dank je.', 'Nee, dank je.', 'Tot ziens.'], correct: 1 },
              ],
            },
            {
              id: 'fr-u1-l3',
              title: 'Herhaling: eerste woorden',
              exercises: [
                {
                  type: 'match',
                  pairs: [
                    { nl: 'goedendag', target: 'bonjour' },
                    { nl: 'dank je wel', target: 'merci' },
                    { nl: 'ja', target: 'oui' },
                    { nl: 'nee', target: 'non' },
                    { nl: 'tot ziens', target: 'au revoir' },
                  ],
                },
                { type: 'type', nl: 'goedendag', target: 'bonjour', accept: ['Bonjour', 'bonjour !'] },
                { type: 'wordbank', nl: 'Hoi, gaat het?', target: 'Salut ça va', distractors: ['bien', 'non', 'merci'] },
                { type: 'type', nl: 'tot ziens', target: 'au revoir', accept: ['Au revoir'] },
                { type: 'listen', target: 'oui', options: ['non', 'au revoir', 'oui'], correct: 2 },
                { type: 'wordbank', nl: 'Ja, het gaat goed, dank je.', target: 'Oui ça va bien merci', distractors: ['non', 'salut', 'madame'] },
                { type: 'select', prompt: 'Bonjour, madame !', speak: 'Bonjour, madame !', options: ['Tot ziens, mevrouw!', 'Goedendag, mevrouw!', 'Dank u wel, mevrouw!'], correct: 1 },
                { type: 'type', nl: 'nee', target: 'non', accept: ['Non'] },
                { type: 'fill', before: 'Bonjour, ça va', after: ' ?', nl: 'Goedendag, gaat het goed?', options: ['bien', 'merci', 'salut'], correct: 0 },
                { type: 'type', nl: 'dank je wel', target: 'merci', accept: ['Merci', 'merci beaucoup'] },
                { type: 'wordbank', nl: 'Tot ziens, mevrouw!', target: 'Au revoir madame', distractors: ['salut', 'monsieur', 'merci'] },
                { type: 'listen', target: 'ça va bien', options: ['ça va bien', 'oui merci', 'au revoir'], correct: 0 },
              ],
            },
          ],
        },
        {
          id: 'fr-u2',
          title: 'Eten & drinken',
          icon: '☕',
          lessons: [
            {
              id: 'fr-u2-l1',
              title: 'In het café',
              exercises: [
                { type: 'new', word: 'un café', nl: 'een koffie', example: "Un café, s'il vous plaît.", exampleNl: 'Een koffie, alstublieft.' },
                { type: 'new', word: 'un thé', nl: 'een thee', example: 'Un thé, madame ?', exampleNl: 'Een thee, mevrouw?' },
                { type: 'new', word: 'un croissant', nl: 'een croissant', example: 'Le croissant est bon.', exampleNl: 'De croissant is lekker.' },
                { type: 'new', word: "l'eau", nl: 'het water', example: "L'eau, s'il vous plaît.", exampleNl: 'Water, alstublieft.' },
                { type: 'select', prompt: 'een koffie', options: ['un thé', 'un café', 'un croissant'], correct: 1 },
                { type: 'select', prompt: "l'eau", speak: "l'eau", options: ['het water', 'de koffie', 'de thee'], correct: 0 },
                { type: 'listen', target: 'un croissant', options: ['un croissant', 'un café', 'un thé'], correct: 0 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'een koffie', target: 'un café' },
                    { nl: 'een thee', target: 'un thé' },
                    { nl: 'het water', target: "l'eau" },
                    { nl: 'een croissant', target: 'un croissant' },
                  ],
                },
                { type: 'fill', before: 'Bonjour,', after: " café, s'il vous plaît.", nl: 'Goedendag, een koffie, alstublieft.', options: ['une', 'un', 'le'], correct: 1 },
                { type: 'wordbank', nl: 'Een thee, alstublieft.', target: "Un thé s'il vous plaît", distractors: ['café', 'merci', 'une'] },
                { type: 'type', nl: 'een koffie', target: 'un café', accept: ['Un café', 'café', 'un cafe'] },
                { type: 'listen', target: 'un thé', options: ["l'eau", 'un thé', 'un café'], correct: 1 },
              ],
            },
            {
              id: 'fr-u2-l2',
              title: 'Bestellen',
              exercises: [
                { type: 'new', word: 'je voudrais', nl: 'ik wil graag', example: 'Je voudrais un café.', exampleNl: 'Ik wil graag een koffie.' },
                { type: 'new', word: 'le pain', nl: 'het brood', example: 'Le pain est bon.', exampleNl: 'Het brood is lekker.' },
                { type: 'new', word: 'le fromage', nl: 'de kaas', example: 'Je voudrais du fromage.', exampleNl: 'Ik wil graag kaas.' },
                { type: 'new', word: 'le vin', nl: 'de wijn', example: 'Le vin est très bon.', exampleNl: 'De wijn is erg lekker.' },
                { type: 'select', prompt: 'het brood', options: ['le vin', 'le fromage', 'le pain'], correct: 2 },
                { type: 'select', prompt: 'le fromage', speak: 'le fromage', options: ['het brood', 'de kaas', 'de wijn'], correct: 1 },
                { type: 'wordbank', nl: 'Ik wil graag een koffie.', target: 'Je voudrais un café', distractors: ['thé', 'merci', 'le'] },
                { type: 'fill', before: 'Je', after: ' un croissant.', nl: 'Ik wil graag een croissant.', options: ['voudrais', 'voulez', 'voudra'], correct: 0 },
                { type: 'listen', target: 'le vin', options: ['le pain', 'le vin', 'le fromage'], correct: 1 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'het brood', target: 'le pain' },
                    { nl: 'de wijn', target: 'le vin' },
                    { nl: 'de kaas', target: 'le fromage' },
                    { nl: 'ik wil graag', target: 'je voudrais' },
                  ],
                },
                { type: 'type', nl: 'de wijn', target: 'le vin', accept: ['Le vin', 'vin'] },
                { type: 'wordbank', nl: 'Ik wil graag water, alstublieft.', target: "Je voudrais de l'eau s'il vous plaît", distractors: ['vin', 'un', 'merci'] },
              ],
            },
            {
              id: 'fr-u2-l3',
              title: 'Herhaling: op het terras',
              exercises: [
                {
                  type: 'match',
                  pairs: [
                    { nl: 'een koffie', target: 'un café' },
                    { nl: 'het brood', target: 'le pain' },
                    { nl: 'het water', target: "l'eau" },
                    { nl: 'de kaas', target: 'le fromage' },
                    { nl: 'de wijn', target: 'le vin' },
                  ],
                },
                { type: 'type', nl: 'een thee', target: 'un thé', accept: ['Un thé', 'thé', 'un the'] },
                { type: 'wordbank', nl: 'Ik wil graag een croissant, alstublieft.', target: "Je voudrais un croissant s'il vous plaît", distractors: ['le', 'une', 'merci'] },
                { type: 'fill', before: 'Je voudrais', after: ' pain.', nl: 'Ik wil graag brood.', options: ['du', 'de la', 'le'], correct: 0 },
                { type: 'type', nl: 'het brood', target: 'le pain', accept: ['pain', 'Le pain'] },
                { type: 'listen', target: "s'il vous plaît", options: ['je voudrais', "s'il vous plaît", 'merci beaucoup'], correct: 1 },
                { type: 'wordbank', nl: 'De koffie is lekker.', target: 'Le café est bon', distractors: ['bien', 'un', 'vin'] },
                { type: 'select', prompt: 'Je voudrais du vin.', speak: 'Je voudrais du vin.', options: ['Ik wil graag water.', 'Ik wil graag brood.', 'Ik wil graag wijn.'], correct: 2 },
                { type: 'type', nl: 'ik wil graag', target: 'je voudrais', accept: ['Je voudrais'] },
                { type: 'fill', before: 'Le pain est', after: '.', nl: 'Het brood is lekker.', options: ['bonne', 'bien', 'bon'], correct: 2 },
                { type: 'wordbank', nl: 'Een koffie en een croissant, alstublieft.', target: "Un café et un croissant s'il vous plaît", distractors: ['une', 'le', 'merci'] },
                { type: 'type', nl: 'het water', target: "l'eau", accept: ['eau', "L'eau", 'l eau'] },
              ],
            },
          ],
        },
        {
          id: 'fr-u3',
          title: 'Mensen & familie',
          icon: '💛',
          lessons: [
            {
              id: 'fr-u3-l1',
              title: 'De familie',
              exercises: [
                { type: 'new', word: 'la mère', nl: 'de moeder', example: "Ma mère s'appelle Marie.", exampleNl: 'Mijn moeder heet Marie.' },
                { type: 'new', word: 'le père', nl: 'de vader', example: 'Voici mon père.', exampleNl: 'Dit is mijn vader.' },
                { type: 'new', word: 'le frère', nl: 'de broer', example: "J'ai un frère.", exampleNl: 'Ik heb een broer.' },
                { type: 'new', word: 'la sœur', nl: 'de zus', example: "Ma sœur s'appelle Emma.", exampleNl: 'Mijn zus heet Emma.' },
                { type: 'select', prompt: 'de moeder', options: ['la sœur', 'la mère', 'le père'], correct: 1 },
                { type: 'select', prompt: 'le frère', speak: 'le frère', options: ['de vader', 'de zus', 'de broer'], correct: 2 },
                { type: 'listen', target: 'la sœur', options: ['la sœur', 'la mère', 'le frère'], correct: 0 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de moeder', target: 'la mère' },
                    { nl: 'de vader', target: 'le père' },
                    { nl: 'de broer', target: 'le frère' },
                    { nl: 'de zus', target: 'la sœur' },
                  ],
                },
                { type: 'fill', before: 'Voici', after: ' mère.', nl: 'Dit is mijn moeder.', options: ['mon', 'ma', 'mes'], correct: 1 },
                { type: 'wordbank', nl: 'Ik heb een broer.', target: "J'ai un frère", distractors: ['une', 'sœur', 'ma'] },
                { type: 'type', nl: 'de vader', target: 'le père', accept: ['père', 'Le père', 'le pere'] },
                { type: 'listen', target: 'la mère', options: ['le frère', 'la mère', 'la sœur'], correct: 1 },
              ],
            },
            {
              id: 'fr-u3-l2',
              title: 'Over jezelf',
              exercises: [
                { type: 'new', word: "je m'appelle", nl: 'ik heet', example: "Bonjour, je m'appelle Léa.", exampleNl: 'Goedendag, ik heet Léa.' },
                { type: 'new', word: 'la famille', nl: 'de familie', example: 'Ma famille est grande.', exampleNl: 'Mijn familie is groot.' },
                { type: 'new', word: "l'ami", nl: 'de vriend', example: "C'est mon ami.", exampleNl: 'Dat is mijn vriend.' },
                { type: 'new', word: 'et', nl: 'en', example: 'Mon frère et ma sœur.', exampleNl: 'Mijn broer en mijn zus.' },
                { type: 'select', prompt: 'ik heet', options: ["je m'appelle", 'je voudrais', "j'ai"], correct: 0 },
                { type: 'select', prompt: 'la famille', speak: 'la famille', options: ['de vriend', 'de moeder', 'de familie'], correct: 2 },
                { type: 'wordbank', nl: 'Ik heet Paul.', target: "Je m'appelle Paul", distractors: ['suis', 'ai', 'le'] },
                { type: 'fill', before: "C'est", after: ' amie Marie.', nl: 'Dat is mijn vriendin Marie.', options: ['ma', 'mon', 'le'], correct: 1 },
                { type: 'listen', target: "je m'appelle", options: ["j'ai", "je m'appelle", 'je voudrais'], correct: 1 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de vriend', target: "l'ami" },
                    { nl: 'de familie', target: 'la famille' },
                    { nl: 'en', target: 'et' },
                    { nl: 'ik heet', target: "je m'appelle" },
                  ],
                },
                { type: 'type', nl: 'en', target: 'et', accept: ['Et'] },
                { type: 'wordbank', nl: 'Mijn vader en mijn moeder.', target: 'Mon père et ma mère', distractors: ['la', 'frère', 'mes'] },
              ],
            },
            {
              id: 'fr-u3-l3',
              title: 'Herhaling: mijn familie',
              exercises: [
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de moeder', target: 'la mère' },
                    { nl: 'de broer', target: 'le frère' },
                    { nl: 'de zus', target: 'la sœur' },
                    { nl: 'de vriend', target: "l'ami" },
                    { nl: 'de familie', target: 'la famille' },
                  ],
                },
                { type: 'type', nl: 'de zus', target: 'la sœur', accept: ['sœur', 'La sœur', 'la soeur', 'soeur'] },
                { type: 'wordbank', nl: 'Ik heet Emma en ik heb een broer.', target: "Je m'appelle Emma et j'ai un frère", distractors: ['une', 'sœur', 'ma'] },
                { type: 'fill', before: 'Voici', after: ' père.', nl: 'Dit is mijn vader.', options: ['ma', 'mes', 'mon'], correct: 2 },
                { type: 'type', nl: 'de familie', target: 'la famille', accept: ['famille', 'La famille'] },
                { type: 'listen', target: "j'ai un frère", options: ["j'ai un frère", "j'ai une sœur", 'ma famille'], correct: 0 },
                { type: 'select', prompt: "Ma sœur s'appelle Julie.", speak: "Ma sœur s'appelle Julie.", options: ['Mijn moeder heet Julie.', 'Mijn zus heet Julie.', 'Mijn vriendin heet Julie.'], correct: 1 },
                { type: 'type', nl: 'ik heet', target: "je m'appelle", accept: ["Je m'appelle", 'je m appelle'] },
                { type: 'wordbank', nl: 'Dat is mijn vriend Marc.', target: "C'est mon ami Marc", distractors: ['ma', 'amie', 'et'] },
                { type: 'fill', before: "J'ai", after: ' sœur.', nl: 'Ik heb een zus.', options: ['un', 'le', 'une'], correct: 2 },
                { type: 'type', nl: 'de broer', target: 'le frère', accept: ['frère', 'Le frère', 'le frere'] },
                { type: 'wordbank', nl: 'Mijn familie is groot.', target: 'Ma famille est grande', distractors: ['grand', 'mon', 'petite'] },
              ],
            },
          ],
        },
        {
          id: 'fr-u4',
          title: 'Onderweg in de stad',
          icon: '🧭',
          lessons: [
            {
              id: 'fr-u4-l1',
              title: 'Plekken in de stad',
              exercises: [
                { type: 'new', word: 'la ville', nl: 'de stad', example: 'Paris est une belle ville.', exampleNl: 'Parijs is een mooie stad.' },
                { type: 'new', word: 'la gare', nl: 'het station', example: 'Le train est à la gare.', exampleNl: 'De trein is op het station.' },
                { type: 'new', word: 'la rue', nl: 'de straat', example: "J'habite rue Victor Hugo.", exampleNl: 'Ik woon in de rue Victor Hugo.' },
                { type: 'new', word: 'le musée', nl: 'het museum', example: 'Le musée du Louvre est à Paris.', exampleNl: 'Het Louvre is in Parijs.' },
                { type: 'select', prompt: 'de stad', options: ['la rue', 'la gare', 'la ville'], correct: 2 },
                { type: 'select', prompt: 'le musée', speak: 'le musée', options: ['het museum', 'de straat', 'het station'], correct: 0 },
                { type: 'listen', target: 'la gare', options: ['la gare', 'la rue', 'la ville'], correct: 0 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de stad', target: 'la ville' },
                    { nl: 'het station', target: 'la gare' },
                    { nl: 'de straat', target: 'la rue' },
                    { nl: 'het museum', target: 'le musée' },
                  ],
                },
                { type: 'fill', before: 'Le musée est', after: ' Paris.', nl: 'Het museum is in Parijs.', options: ['en', 'à', 'de'], correct: 1 },
                { type: 'wordbank', nl: 'Het station is groot.', target: 'La gare est grande', distractors: ['grand', 'le', 'rue'] },
                { type: 'type', nl: 'de straat', target: 'la rue', accept: ['rue', 'La rue'] },
                { type: 'listen', target: 'la ville', options: ['la rue', 'le musée', 'la ville'], correct: 2 },
              ],
            },
            {
              id: 'fr-u4-l2',
              title: 'De weg vragen',
              exercises: [
                { type: 'new', word: 'où', nl: 'waar', example: 'Où est la gare ?', exampleNl: 'Waar is het station?' },
                { type: 'new', word: 'à gauche', nl: 'links', example: 'La rue est à gauche.', exampleNl: 'De straat is links.' },
                { type: 'new', word: 'à droite', nl: 'rechts', example: 'Le musée est à droite.', exampleNl: 'Het museum is rechts.' },
                { type: 'new', word: 'le métro', nl: 'de metro', example: 'Je prends le métro.', exampleNl: 'Ik neem de metro.' },
                { type: 'select', prompt: 'waar', options: ['ou', 'où', 'oui'], correct: 1 },
                { type: 'select', prompt: 'à gauche', speak: 'à gauche', options: ['rechts', 'rechtdoor', 'links'], correct: 2 },
                { type: 'listen', target: 'à droite', options: ['à droite', 'à gauche', 'le métro'], correct: 0 },
                { type: 'wordbank', nl: 'Waar is het station?', target: 'Où est la gare', distractors: ['le', 'rue', 'à'] },
                { type: 'fill', before: 'Où', after: ' le musée ?', nl: 'Waar is het museum?', options: ['et', 'es', 'est'], correct: 2 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'waar', target: 'où' },
                    { nl: 'links', target: 'à gauche' },
                    { nl: 'rechts', target: 'à droite' },
                    { nl: 'de metro', target: 'le métro' },
                  ],
                },
                { type: 'type', nl: 'de metro', target: 'le métro', accept: ['métro', 'Le métro', 'le metro', 'metro'] },
                { type: 'wordbank', nl: 'De metro is rechts.', target: 'Le métro est à droite', distractors: ['gauche', 'la', 'où'] },
              ],
            },
            {
              id: 'fr-u4-l3',
              title: 'Herhaling: door Parijs',
              exercises: [
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de stad', target: 'la ville' },
                    { nl: 'het station', target: 'la gare' },
                    { nl: 'de metro', target: 'le métro' },
                    { nl: 'links', target: 'à gauche' },
                    { nl: 'rechts', target: 'à droite' },
                  ],
                },
                { type: 'type', nl: 'waar', target: 'où', accept: ['Où', 'ou'] },
                { type: 'wordbank', nl: 'Waar is de metro, alstublieft?', target: "Où est le métro s'il vous plaît", distractors: ['la', 'gare', 'à'] },
                { type: 'fill', before: 'La gare est', after: ' gauche.', nl: 'Het station is links.', options: ['au', 'à', 'en'], correct: 1 },
                { type: 'type', nl: 'het museum', target: 'le musée', accept: ['musée', 'Le musée', 'le musee', 'musee'] },
                { type: 'listen', target: 'à gauche', options: ['à droite', 'à gauche', 'la gare'], correct: 1 },
                { type: 'select', prompt: 'La rue est à droite.', speak: 'La rue est à droite.', options: ['De straat is links.', 'Het station is rechts.', 'De straat is rechts.'], correct: 2 },
                { type: 'type', nl: 'het station', target: 'la gare', accept: ['gare', 'La gare'] },
                { type: 'wordbank', nl: 'Ik neem de metro.', target: 'Je prends le métro', distractors: ['voudrais', 'la', 'à'] },
                { type: 'fill', before: 'Où', after: ' la rue Victor Hugo ?', nl: 'Waar is de rue Victor Hugo?', options: ['est', 'es', 'et'], correct: 0 },
                { type: 'type', nl: 'de stad', target: 'la ville', accept: ['ville', 'La ville'] },
                { type: 'wordbank', nl: 'Het station is links en het museum is rechts.', target: 'La gare est à gauche et le musée est à droite', distractors: ['rue', 'ville', 'où'] },
              ],
            },
          ],
        },
      ],
    },
  ],
}
