import type { Section } from '../../types'

export const section: Section = {
  title: 'Sectie 2 · Dagelijks leven',
  cefr: 'A1+',
  units: [
    {
      id: 'it-u5',
      title: 'Getallen & tijd',
      icon: '🕰️',
      lessons: [
        {
          id: 'it-u5-l1',
          title: 'Tellen tot tien',
          exercises: [
            { type: 'new', word: 'due', nl: 'twee', example: 'Due caffè, per favore.', exampleNl: 'Twee koffie, alsjeblieft.' },
            { type: 'new', word: 'tre', nl: 'drie', example: 'Ho tre fratelli.', exampleNl: 'Ik heb drie broers.' },
            { type: 'new', word: 'cinque', nl: 'vijf', example: 'Il treno parte tra cinque minuti.', exampleNl: 'De trein vertrekt over vijf minuten.' },
            { type: 'new', word: 'dieci', nl: 'tien', example: 'Il museo apre alle dieci.', exampleNl: 'Het museum opent om tien uur.' },
            { type: 'select', prompt: 'twee', options: ['tre', 'due', 'dieci'], correct: 1 },
            { type: 'select', prompt: 'cinque', speak: 'cinque', options: ['vijf', 'tien', 'drie'], correct: 0 },
            { type: 'listen', target: 'dieci', options: ['dieci', 'due', 'tre'], correct: 0 },
            { type: 'fill', before: 'Il museo apre', after: 'dieci.', nl: 'Het museum opent om tien uur.', options: ['alle', 'a', 'al'], correct: 0 },
            { type: 'wordbank', nl: 'Twee koffie, alsjeblieft.', target: 'Due caffè, per favore.', distractors: ['tre', 'dieci', 'vino'] },
            {
              type: 'match',
              pairs: [
                { nl: 'twee', target: 'due' },
                { nl: 'drie', target: 'tre' },
                { nl: 'vijf', target: 'cinque' },
                { nl: 'tien', target: 'dieci' },
              ],
            },
            { type: 'type', nl: 'drie', target: 'tre', accept: ['Tre'] },
            { type: 'select', prompt: 'due', speak: 'due', options: ['tien', 'twee', 'vijf'], correct: 1 },
          ],
        },
        {
          id: 'it-u5-l2',
          title: 'Hoe laat is het?',
          exercises: [
            { type: 'new', word: 'che ore sono?', nl: 'hoe laat is het?', example: 'Che ore sono? — Sono le dieci.', exampleNl: 'Hoe laat is het? — Het is tien uur.' },
            { type: 'new', word: 'sono le due', nl: 'het is twee uur', example: 'Sono le due e il treno parte.', exampleNl: 'Het is twee uur en de trein vertrekt.' },
            { type: 'new', word: 'oggi', nl: 'vandaag', example: 'Oggi sono a Roma.', exampleNl: 'Vandaag ben ik in Rome.' },
            { type: 'new', word: 'domani', nl: 'morgen', example: 'Il treno per Roma parte domani.', exampleNl: 'De trein naar Rome vertrekt morgen.' },
            { type: 'select', prompt: 'vandaag', options: ['domani', 'oggi', 'ora'], correct: 1 },
            { type: 'select', prompt: 'domani', speak: 'domani', options: ['vandaag', 'morgen', 'gisteren'], correct: 1 },
            { type: 'listen', target: 'che ore sono?', options: ['che ore sono?', 'sono le due', 'come stai?'], correct: 0 },
            { type: 'fill', before: 'Sono', after: 'tre.', nl: 'Het is drie uur.', options: ['le', 'la', 'il'], correct: 0 },
            { type: 'wordbank', nl: 'Hoe laat is het? Het is twee uur.', target: 'Che ore sono? Sono le due.', distractors: ['domani', 'dieci', 'adesso'] },
            {
              type: 'match',
              pairs: [
                { nl: 'vandaag', target: 'oggi' },
                { nl: 'morgen', target: 'domani' },
                { nl: 'hoe laat is het?', target: 'che ore sono?' },
                { nl: 'het is twee uur', target: 'sono le due' },
              ],
            },
            { type: 'type', nl: 'vandaag', target: 'oggi', accept: ['Oggi'] },
            { type: 'listen', target: 'oggi', options: ['oggi', 'domani', 'dove'], correct: 0 },
          ],
        },
        {
          id: 'it-u5-l3',
          title: 'Herhaling: getallen & tijd',
          exercises: [
            { type: 'type', nl: 'morgen', target: 'domani', accept: ['Domani'] },
            { type: 'wordbank', nl: 'Het museum opent vandaag om tien uur.', target: 'Il museo apre oggi alle dieci.', distractors: ['domani', 'due', 'sono'] },
            { type: 'select', prompt: 'tien', options: ['due', 'dieci', 'tre'], correct: 1 },
            { type: 'listen', target: 'sono le due', options: ['sono le due', 'sono le tre', 'che ore sono?'], correct: 0 },
            { type: 'type', nl: 'Het is twee uur.', target: 'Sono le due.', accept: ['sono le due', 'Sono le due', 'sono le due.'] },
            { type: 'fill', before: 'Il treno parte', after: 'cinque.', nl: 'De trein vertrekt om vijf uur.', options: ['alle', 'a', 'in'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'twee', target: 'due' },
                { nl: 'vijf', target: 'cinque' },
                { nl: 'vandaag', target: 'oggi' },
                { nl: 'tien', target: 'dieci' },
                { nl: 'morgen', target: 'domani' },
              ],
            },
            { type: 'wordbank', nl: 'De trein naar Rome vertrekt morgen.', target: 'Il treno per Roma parte domani.', distractors: ['oggi', 'alle', 'stazione'] },
            { type: 'type', nl: 'vijf', target: 'cinque', accept: ['Cinque'] },
            { type: 'select', prompt: 'sono le due', speak: 'sono le due', options: ['het is twee uur', 'het is tien uur', 'hoe laat is het?'], correct: 0 },
            { type: 'listen', target: 'tre', options: ['tre', 'due', 'dieci'], correct: 0 },
            { type: 'wordbank', nl: 'Hoe laat is het? Het is tien uur.', target: 'Che ore sono? Sono le dieci.', distractors: ['due', 'oggi', 'alle'] },
          ],
        },
      ],
    },
    {
      id: 'it-u6',
      title: 'Boodschappen & geld',
      icon: '🛍️',
      lessons: [
        {
          id: 'it-u6-l1',
          title: 'Op de markt',
          exercises: [
            { type: 'new', word: 'il mercato', nl: 'de markt', example: 'Il mercato è in piazza.', exampleNl: 'De markt is op het plein.' },
            { type: 'new', word: 'il pane', nl: 'het brood', example: 'Il pane fresco è buonissimo.', exampleNl: 'Het verse brood is heerlijk.' },
            { type: 'new', word: 'la frutta', nl: 'het fruit', example: 'Vorrei della frutta fresca.', exampleNl: 'Ik wil graag wat vers fruit.' },
            { type: 'new', word: 'il formaggio', nl: 'de kaas', example: 'Il formaggio italiano è famoso.', exampleNl: 'De Italiaanse kaas is beroemd.' },
            { type: 'select', prompt: 'het brood', options: ['il pane', 'il vino', 'il formaggio'], correct: 0 },
            { type: 'select', prompt: 'il mercato', speak: 'il mercato', options: ['het museum', 'de markt', 'de winkel'], correct: 1 },
            { type: 'listen', target: 'il formaggio', options: ['il formaggio', 'la frutta', 'il mercato'], correct: 0 },
            { type: 'fill', before: 'Vorrei', after: 'pane, per favore.', nl: 'Ik wil graag het brood, alsjeblieft.', options: ['il', 'la', 'lo'], correct: 0 },
            { type: 'wordbank', nl: 'De markt is op het plein.', target: 'Il mercato è in piazza.', distractors: ['la', 'stazione', 'pane'] },
            {
              type: 'match',
              pairs: [
                { nl: 'de markt', target: 'il mercato' },
                { nl: 'het brood', target: 'il pane' },
                { nl: 'het fruit', target: 'la frutta' },
                { nl: 'de kaas', target: 'il formaggio' },
              ],
            },
            { type: 'type', nl: 'de kaas', target: 'il formaggio', accept: ['formaggio', 'Formaggio', 'Il formaggio'] },
            { type: 'listen', target: 'il pane', options: ['il pane', 'il vino', 'il conto'], correct: 0 },
          ],
        },
        {
          id: 'it-u6-l2',
          title: 'Betalen',
          exercises: [
            { type: 'new', word: 'quanto costa?', nl: 'hoeveel kost het?', example: 'Quanto costa il formaggio?', exampleNl: 'Hoeveel kost de kaas?' },
            { type: 'new', word: "l'euro", nl: 'de euro', example: 'Il caffè costa un euro.', exampleNl: 'De koffie kost één euro.' },
            { type: 'new', word: 'caro', nl: 'duur', example: 'Questo vino è troppo caro.', exampleNl: 'Deze wijn is te duur.' },
            { type: 'new', word: 'compro', nl: 'ik koop', example: 'Compro il pane al mercato.', exampleNl: 'Ik koop het brood op de markt.' },
            { type: 'select', prompt: 'duur', options: ['caro', 'euro', 'fresco'], correct: 0 },
            { type: 'select', prompt: 'quanto costa?', speak: 'quanto costa?', options: ['hoeveel kost het?', 'waar is het?', 'hoe laat is het?'], correct: 0 },
            { type: 'listen', target: "l'euro", options: ["l'euro", "l'acqua", "l'uomo"], correct: 0 },
            { type: 'fill', before: 'Quanto', after: 'la pizza?', nl: 'Hoeveel kost de pizza?', options: ['costa', 'costo', 'costano'], correct: 0 },
            { type: 'wordbank', nl: 'Ik koop het fruit op de markt.', target: 'Compro la frutta al mercato.', distractors: ['il', 'pane', 'costa'] },
            {
              type: 'match',
              pairs: [
                { nl: 'hoeveel kost het?', target: 'quanto costa?' },
                { nl: 'de euro', target: "l'euro" },
                { nl: 'duur', target: 'caro' },
                { nl: 'ik koop', target: 'compro' },
              ],
            },
            { type: 'type', nl: 'ik koop', target: 'compro', accept: ['Compro'] },
            { type: 'fill', before: 'Il formaggio costa dieci', after: '.', nl: 'De kaas kost tien euro.', options: ['euro', 'euri', 'euros'], correct: 0 },
          ],
        },
        {
          id: 'it-u6-l3',
          title: 'Herhaling: boodschappen & geld',
          exercises: [
            { type: 'type', nl: 'het brood', target: 'il pane', accept: ['pane', 'Pane', 'Il pane'] },
            { type: 'wordbank', nl: 'Hoeveel kost het brood?', target: 'Quanto costa il pane?', distractors: ['la', 'frutta', 'euro'] },
            { type: 'select', prompt: 'het fruit', options: ['il formaggio', 'la frutta', 'il pane'], correct: 1 },
            { type: 'listen', target: 'quanto costa?', options: ['quanto costa?', 'che ore sono?', 'come stai?'], correct: 0 },
            { type: 'type', nl: 'Hoeveel kost de koffie?', target: 'Quanto costa il caffè?', accept: ['quanto costa il caffè', 'Quanto costa il caffè', 'quanto costa il caffe?', 'Quanto costa il caffe?'] },
            { type: 'fill', before: 'Compro il pane', after: 'mercato.', nl: 'Ik koop het brood op de markt.', options: ['al', 'il', 'a'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'de markt', target: 'il mercato' },
                { nl: 'duur', target: 'caro' },
                { nl: 'de euro', target: "l'euro" },
                { nl: 'de kaas', target: 'il formaggio' },
                { nl: 'ik koop', target: 'compro' },
              ],
            },
            { type: 'wordbank', nl: 'De wijn is te duur.', target: 'Il vino è troppo caro.', distractors: ['costa', 'molto', 'la'] },
            { type: 'type', nl: 'duur', target: 'caro', accept: ['Caro'] },
            { type: 'select', prompt: 'compro', speak: 'compro', options: ['ik koop', 'ik betaal', 'ik eet'], correct: 0 },
            { type: 'listen', target: 'caro', options: ['caro', 'euro', 'ciao'], correct: 0 },
            { type: 'wordbank', nl: 'Ik koop de kaas en het brood.', target: 'Compro il formaggio e il pane.', distractors: ['la', 'frutta', 'costa'] },
          ],
        },
      ],
    },
    {
      id: 'it-u7',
      title: 'Huis & wonen',
      icon: '🏠',
      lessons: [
        {
          id: 'it-u7-l1',
          title: 'Mijn huis',
          exercises: [
            { type: 'new', word: 'la casa', nl: 'het huis', example: 'La casa di Marco è grande.', exampleNl: 'Het huis van Marco is groot.' },
            { type: 'new', word: 'la cucina', nl: 'de keuken', example: 'La cucina è piccola ma bella.', exampleNl: 'De keuken is klein maar mooi.' },
            { type: 'new', word: 'la camera', nl: 'de slaapkamer', example: 'La camera è al primo piano.', exampleNl: 'De slaapkamer is op de eerste verdieping.' },
            { type: 'new', word: 'il bagno', nl: 'de badkamer', example: 'Il bagno è a destra.', exampleNl: 'De badkamer is aan de rechterkant.' },
            { type: 'select', prompt: 'het huis', options: ['la casa', 'la camera', 'la cucina'], correct: 0 },
            { type: 'select', prompt: 'il bagno', speak: 'il bagno', options: ['de keuken', 'de badkamer', 'de slaapkamer'], correct: 1 },
            { type: 'listen', target: 'la cucina', options: ['la cucina', 'la camera', 'la casa'], correct: 0 },
            { type: 'fill', before: 'La camera è', after: 'destra.', nl: 'De slaapkamer is aan de rechterkant.', options: ['a', 'in', 'di'], correct: 0 },
            { type: 'wordbank', nl: 'Het huis van Anna is groot.', target: 'La casa di Anna è grande.', distractors: ['cucina', 'il', 'piccola'] },
            {
              type: 'match',
              pairs: [
                { nl: 'het huis', target: 'la casa' },
                { nl: 'de keuken', target: 'la cucina' },
                { nl: 'de slaapkamer', target: 'la camera' },
                { nl: 'de badkamer', target: 'il bagno' },
              ],
            },
            { type: 'type', nl: 'de keuken', target: 'la cucina', accept: ['cucina', 'Cucina', 'La cucina'] },
            { type: 'listen', target: 'il bagno', options: ['il bagno', 'il pane', 'la casa'], correct: 0 },
          ],
        },
        {
          id: 'it-u7-l2',
          title: 'Waar ik woon',
          exercises: [
            { type: 'new', word: 'abito', nl: 'ik woon', example: 'Abito a Milano con la mia famiglia.', exampleNl: 'Ik woon in Milaan met mijn familie.' },
            { type: 'new', word: 'il tavolo', nl: 'de tafel', example: 'Il tavolo è in cucina.', exampleNl: 'De tafel staat in de keuken.' },
            { type: 'new', word: 'la porta', nl: 'de deur', example: 'La porta della casa è verde.', exampleNl: 'De deur van het huis is groen.' },
            { type: 'new', word: 'la finestra', nl: 'het raam', example: 'La camera ha una finestra grande.', exampleNl: 'De slaapkamer heeft een groot raam.' },
            { type: 'select', prompt: 'de deur', options: ['la finestra', 'la porta', 'il tavolo'], correct: 1 },
            { type: 'select', prompt: 'abito', speak: 'abito', options: ['ik woon', 'ik koop', 'ik werk'], correct: 0 },
            { type: 'listen', target: 'la finestra', options: ['la finestra', 'la porta', 'la sedia'], correct: 0 },
            { type: 'fill', before: 'Abito', after: 'Roma.', nl: 'Ik woon in Rome.', options: ['a', 'in', 'di'], correct: 0 },
            { type: 'wordbank', nl: 'Ik woon in Milaan met mijn familie.', target: 'Abito a Milano con la mia famiglia.', distractors: ['casa', 'in', 'abita'] },
            {
              type: 'match',
              pairs: [
                { nl: 'ik woon', target: 'abito' },
                { nl: 'de tafel', target: 'il tavolo' },
                { nl: 'de deur', target: 'la porta' },
                { nl: 'het raam', target: 'la finestra' },
                { nl: 'het huis', target: 'la casa' },
              ],
            },
            { type: 'type', nl: 'het raam', target: 'la finestra', accept: ['finestra', 'Finestra', 'La finestra'] },
            { type: 'fill', before: 'Il tavolo è', after: 'cucina.', nl: 'De tafel staat in de keuken.', options: ['in', 'a', 'su'], correct: 0 },
          ],
        },
        {
          id: 'it-u7-l3',
          title: 'Herhaling: huis & wonen',
          exercises: [
            { type: 'type', nl: 'het huis', target: 'la casa', accept: ['casa', 'Casa', 'La casa'] },
            { type: 'wordbank', nl: 'De badkamer is aan de linkerkant.', target: 'Il bagno è a sinistra.', distractors: ['destra', 'la', 'camera'] },
            { type: 'select', prompt: 'de tafel', options: ['la porta', 'il tavolo', 'il bagno'], correct: 1 },
            { type: 'listen', target: 'abito', options: ['abito', 'abita', 'tavolo'], correct: 0 },
            { type: 'type', nl: 'Ik woon in Rome.', target: 'Abito a Roma.', accept: ['abito a roma', 'abito a Roma', 'Abito a Roma'] },
            { type: 'fill', before: 'La finestra', after: 'camera è grande.', nl: 'Het raam van de slaapkamer is groot.', options: ['della', 'del', 'di'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'de slaapkamer', target: 'la camera' },
                { nl: 'de deur', target: 'la porta' },
                { nl: 'de keuken', target: 'la cucina' },
                { nl: 'ik woon', target: 'abito' },
              ],
            },
            { type: 'wordbank', nl: 'De keuken heeft een grote tafel.', target: 'La cucina ha un tavolo grande.', distractors: ['la', 'porta', 'finestra'] },
            { type: 'type', nl: 'de deur', target: 'la porta', accept: ['porta', 'Porta', 'La porta'] },
            { type: 'select', prompt: 'la camera', speak: 'la camera', options: ['de keuken', 'de badkamer', 'de slaapkamer'], correct: 2 },
            { type: 'listen', target: 'la casa', options: ['la casa', 'la cosa', 'la cucina'], correct: 0 },
            { type: 'wordbank', nl: 'Ik woon in een groot huis.', target: 'Abito in una casa grande.', distractors: ['la', 'tavolo', 'a'] },
          ],
        },
      ],
    },
    {
      id: 'it-u8',
      title: 'Werk & school',
      icon: '💼',
      lessons: [
        {
          id: 'it-u8-l1',
          title: 'Op het werk',
          exercises: [
            { type: 'new', word: 'il lavoro', nl: 'het werk', example: 'Il mio lavoro è interessante.', exampleNl: 'Mijn werk is interessant.' },
            { type: 'new', word: "l'ufficio", nl: 'het kantoor', example: "L'ufficio è in centro.", exampleNl: 'Het kantoor is in het centrum.' },
            { type: 'new', word: 'il medico', nl: 'de arts', example: 'Mia sorella è medico.', exampleNl: 'Mijn zus is arts.' },
            { type: 'new', word: "l'insegnante", nl: 'de leraar', example: 'Mio padre è insegnante.', exampleNl: 'Mijn vader is leraar.' },
            { type: 'select', prompt: 'het kantoor', options: ["l'ufficio", 'il lavoro', 'la scuola'], correct: 0 },
            { type: 'select', prompt: 'il medico', speak: 'il medico', options: ['de leraar', 'de arts', 'de student'], correct: 1 },
            { type: 'listen', target: 'il lavoro', options: ['il lavoro', 'il tavolo', "l'ufficio"], correct: 0 },
            { type: 'fill', before: 'Mia madre', after: 'medico.', nl: 'Mijn moeder is arts.', options: ['è', 'e', 'ha'], correct: 0 },
            { type: 'wordbank', nl: 'Mijn vader is leraar.', target: 'Mio padre è insegnante.', distractors: ['medico', 'la', 'lavoro'] },
            {
              type: 'match',
              pairs: [
                { nl: 'het werk', target: 'il lavoro' },
                { nl: 'het kantoor', target: "l'ufficio" },
                { nl: 'de arts', target: 'il medico' },
                { nl: 'de leraar', target: "l'insegnante" },
              ],
            },
            { type: 'type', nl: 'het werk', target: 'il lavoro', accept: ['lavoro', 'Lavoro', 'Il lavoro'] },
            { type: 'listen', target: "l'insegnante", options: ["l'insegnante", 'il medico', "l'ufficio"], correct: 0 },
          ],
        },
        {
          id: 'it-u8-l2',
          title: 'Naar school',
          exercises: [
            { type: 'new', word: 'la scuola', nl: 'de school', example: 'La scuola è vicino alla stazione.', exampleNl: 'De school is dicht bij het station.' },
            { type: 'new', word: 'lo studente', nl: 'de student', example: 'Lo studente studia italiano.', exampleNl: 'De student studeert Italiaans.' },
            { type: 'new', word: 'il libro', nl: 'het boek', example: 'Il libro è sul tavolo.', exampleNl: 'Het boek ligt op de tafel.' },
            { type: 'new', word: 'studio', nl: 'ik studeer', example: 'Studio italiano a scuola.', exampleNl: 'Ik studeer Italiaans op school.' },
            { type: 'select', prompt: 'het boek', options: ['il libro', 'la scuola', 'il lavoro'], correct: 0 },
            { type: 'select', prompt: 'lo studente', speak: 'lo studente', options: ['de leraar', 'de school', 'de student'], correct: 2 },
            { type: 'listen', target: 'la scuola', options: ['la scuola', 'lo studente', 'la sorella'], correct: 0 },
            { type: 'fill', before: 'Il libro è', after: 'tavolo.', nl: 'Het boek ligt op de tafel.', options: ['sul', 'nel', 'al'], correct: 0 },
            { type: 'wordbank', nl: 'Ik studeer Italiaans op school.', target: 'Studio italiano a scuola.', distractors: ['la', 'studia', 'libro'] },
            {
              type: 'match',
              pairs: [
                { nl: 'de school', target: 'la scuola' },
                { nl: 'de student', target: 'lo studente' },
                { nl: 'het boek', target: 'il libro' },
                { nl: 'ik studeer', target: 'studio' },
                { nl: 'het kantoor', target: "l'ufficio" },
              ],
            },
            { type: 'type', nl: 'de school', target: 'la scuola', accept: ['scuola', 'Scuola', 'La scuola'] },
            { type: 'fill', before: 'Lo studente', after: 'italiano.', nl: 'De student studeert Italiaans.', options: ['studia', 'studio', 'studi'], correct: 0 },
          ],
        },
        {
          id: 'it-u8-l3',
          title: 'Herhaling: werk & school',
          exercises: [
            { type: 'type', nl: 'de arts', target: 'il medico', accept: ['medico', 'Medico', 'Il medico'] },
            { type: 'wordbank', nl: 'Mijn zus is arts en mijn broer is leraar.', target: 'Mia sorella è medico e mio fratello è insegnante.', distractors: ['la', 'studente', 'lavoro'] },
            { type: 'select', prompt: 'de student', options: ["l'insegnante", 'lo studente', 'il medico'], correct: 1 },
            { type: 'listen', target: 'studio', options: ['studio', 'studia', 'scuola'], correct: 0 },
            { type: 'type', nl: 'het boek', target: 'il libro', accept: ['libro', 'Libro', 'Il libro'] },
            { type: 'fill', before: 'La scuola è', after: 'centro.', nl: 'De school is in het centrum.', options: ['in', 'a', 'di'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'het werk', target: 'il lavoro' },
                { nl: 'de school', target: 'la scuola' },
                { nl: 'het boek', target: 'il libro' },
                { nl: 'de leraar', target: "l'insegnante" },
              ],
            },
            { type: 'wordbank', nl: 'Het kantoor is dicht bij het station.', target: "L'ufficio è vicino alla stazione.", distractors: ['scuola', 'il', 'lavoro'] },
            { type: 'type', nl: 'ik studeer', target: 'studio', accept: ['Studio'] },
            { type: 'select', prompt: 'il lavoro', speak: 'il lavoro', options: ['het boek', 'het werk', 'het kantoor'], correct: 1 },
            { type: 'listen', target: 'il libro', options: ['il libro', 'il lavoro', 'il vino'], correct: 0 },
            { type: 'wordbank', nl: 'Het boek van de leraar ligt op de tafel.', target: "Il libro dell'insegnante è sul tavolo.", distractors: ['della', 'la', 'scuola'] },
          ],
        },
      ],
    },
    {
      id: 'it-u9',
      title: 'Gesprekken voeren',
      icon: '💬',
      lessons: [
        {
          id: 'it-u9-l1',
          title: 'Vragen stellen',
          exercises: [
            { type: 'new', word: 'chi', nl: 'wie', example: 'Chi è quella donna?', exampleNl: 'Wie is die vrouw?' },
            { type: 'new', word: 'come', nl: 'hoe', example: 'Come stai oggi?', exampleNl: 'Hoe gaat het vandaag met je?' },
            { type: 'new', word: 'quando', nl: 'wanneer', example: 'Quando parte il treno?', exampleNl: 'Wanneer vertrekt de trein?' },
            { type: 'new', word: 'perché', nl: 'waarom', example: 'Perché studi italiano?', exampleNl: 'Waarom studeer je Italiaans?' },
            { type: 'select', prompt: 'wanneer', options: ['quando', 'dove', 'chi'], correct: 0 },
            { type: 'select', prompt: 'perché', speak: 'perché', options: ['waarom', 'wanneer', 'wie'], correct: 0 },
            { type: 'listen', target: 'quando', options: ['quando', 'quanto', 'chi'], correct: 0 },
            { type: 'fill', before: 'Come si', after: 'tua madre?', nl: 'Hoe heet jouw moeder?', options: ['chiama', 'chiamo', 'chiami'], correct: 0 },
            { type: 'wordbank', nl: 'Wanneer vertrekt de trein naar Rome?', target: 'Quando parte il treno per Roma?', distractors: ['dove', 'alle', 'biglietto'] },
            {
              type: 'match',
              pairs: [
                { nl: 'wie', target: 'chi' },
                { nl: 'hoe', target: 'come' },
                { nl: 'wanneer', target: 'quando' },
                { nl: 'waarom', target: 'perché' },
                { nl: 'waar', target: 'dove' },
              ],
            },
            { type: 'type', nl: 'waarom', target: 'perché', accept: ['Perché', 'perche', 'Perche'] },
            { type: 'listen', target: 'chi', options: ['chi', 'che', 'ciao'], correct: 0 },
          ],
        },
        {
          id: 'it-u9-l2',
          title: 'Over jezelf vertellen',
          exercises: [
            { type: 'new', word: 'parlo', nl: 'ik spreek', example: 'Parlo italiano e olandese.', exampleNl: 'Ik spreek Italiaans en Nederlands.' },
            { type: 'new', word: "un po'", nl: 'een beetje', example: "Parlo un po' di italiano.", exampleNl: 'Ik spreek een beetje Italiaans.' },
            { type: 'new', word: 'bene', nl: 'goed', example: 'Oggi sto bene, grazie.', exampleNl: 'Vandaag gaat het goed met me, dank je.' },
            { type: 'new', word: 'anche', nl: 'ook', example: 'Anche mia sorella studia italiano.', exampleNl: 'Mijn zus studeert ook Italiaans.' },
            { type: 'select', prompt: 'ook', options: ['anche', 'bene', 'ancora'], correct: 0 },
            { type: 'select', prompt: 'bene', speak: 'bene', options: ['goed', 'ook', 'een beetje'], correct: 0 },
            { type: 'listen', target: "un po'", options: ["un po'", 'anche', 'bene'], correct: 0 },
            { type: 'fill', before: 'Parlo', after: "po' di italiano.", nl: 'Ik spreek een beetje Italiaans.', options: ['un', 'uno', 'una'], correct: 0 },
            { type: 'wordbank', nl: 'Ik spreek ook een beetje Italiaans.', target: "Parlo anche un po' di italiano.", distractors: ['bene', 'studio', 'molto'] },
            {
              type: 'match',
              pairs: [
                { nl: 'ik spreek', target: 'parlo' },
                { nl: 'een beetje', target: "un po'" },
                { nl: 'goed', target: 'bene' },
                { nl: 'ook', target: 'anche' },
              ],
            },
            { type: 'type', nl: 'ik spreek', target: 'parlo', accept: ['Parlo'] },
            { type: 'select', prompt: 'Come stai? — Sto bene, grazie.', speak: 'Come stai? — Sto bene, grazie.', options: ['Hoe gaat het? — Goed, dank je.', 'Hoe laat is het? — Het is twee uur.', 'Waar woon je? — Ik woon in Rome.'], correct: 0 },
          ],
        },
        {
          id: 'it-u9-l3',
          title: 'Herhaling: dagelijks leven',
          exercises: [
            { type: 'wordbank', nl: 'Hoeveel kost het boek?', target: 'Quanto costa il libro?', distractors: ['quando', 'la', 'euro'] },
            { type: 'type', nl: 'Ik spreek een beetje Italiaans.', target: "Parlo un po' di italiano.", accept: ["parlo un po' di italiano", 'Parlo un po di italiano', 'parlo un po di italiano'] },
            { type: 'select', prompt: 'Quando apre il museo?', speak: 'Quando apre il museo?', options: ['Wanneer opent het museum?', 'Waar is het museum?', 'Hoeveel kost het museum?'], correct: 0 },
            { type: 'listen', target: 'perché', options: ['perché', 'prego', 'piacere'], correct: 0 },
            { type: 'wordbank', nl: 'Ik woon in Milaan en ik studeer Italiaans.', target: 'Abito a Milano e studio italiano.', distractors: ['in', 'parlo', 'scuola'] },
            { type: 'fill', before: 'Anche mio fratello', after: 'a Roma.', nl: 'Mijn broer woont ook in Rome.', options: ['abita', 'abito', 'abiti'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'wanneer', target: 'quando' },
                { nl: 'ik koop', target: 'compro' },
                { nl: 'het is twee uur', target: 'sono le due' },
                { nl: 'de school', target: 'la scuola' },
                { nl: 'duur', target: 'caro' },
              ],
            },
            { type: 'type', nl: 'Wanneer vertrekt de trein?', target: 'Quando parte il treno?', accept: ['quando parte il treno', 'Quando parte il treno', 'quando parte il treno?'] },
            { type: 'listen', target: 'anche', options: ['anche', 'bene', 'oggi'], correct: 0 },
            { type: 'wordbank', nl: 'Vandaag koop ik brood en kaas op de markt.', target: 'Oggi compro il pane e il formaggio al mercato.', distractors: ['domani', 'la', 'costa'] },
            { type: 'fill', before: 'Il bagno è', after: 'sinistra, la cucina è a destra.', nl: 'De badkamer is links, de keuken is rechts.', options: ['a', 'in', 'di'], correct: 0 },
            { type: 'type', nl: 'Vandaag gaat het goed met me.', target: 'Oggi sto bene.', accept: ['oggi sto bene', 'Oggi sto bene', 'oggi sto bene.'] },
          ],
        },
      ],
    },
  ],
}
