import type { Section } from '../../types'

export const section: Section = {
  title: 'Sectie 3 · Op weg naar A2',
  cefr: 'A2',
  units: [
    {
      id: 'it-u10',
      title: 'Reizen & vervoer',
      icon: '✈️',
      lessons: [
        {
          id: 'it-u10-l1',
          title: 'Op het vliegveld',
          exercises: [
            { type: 'new', word: "l'aereo", nl: 'het vliegtuig', example: "L'aereo per Milano parte alle sette.", exampleNl: 'Het vliegtuig naar Milaan vertrekt om zeven uur.' },
            { type: 'new', word: "l'aeroporto", nl: 'het vliegveld', example: "L'aeroporto di Roma è molto grande.", exampleNl: 'Het vliegveld van Rome is erg groot.' },
            { type: 'new', word: 'la valigia', nl: 'de koffer', example: 'La mia valigia è pesante.', exampleNl: 'Mijn koffer is zwaar.' },
            { type: 'new', word: 'il passaporto', nl: 'het paspoort', example: 'Ecco il mio passaporto.', exampleNl: 'Hier is mijn paspoort.' },
            { type: 'select', prompt: 'het vliegtuig', options: ["l'aeroporto", "l'aereo", 'la valigia'], correct: 1 },
            { type: 'select', prompt: 'il passaporto', speak: 'il passaporto', options: ['de koffer', 'het kaartje', 'het paspoort'], correct: 2 },
            { type: 'listen', target: 'la valigia', options: ['la valigia', 'la famiglia', 'la stazione'], correct: 0 },
            { type: 'fill', before: 'Vorrei', after: 'biglietto per Milano.', nl: 'Ik wil graag een kaartje naar Milaan.', options: ['un', 'una', "un'"], correct: 0 },
            { type: 'wordbank', nl: 'Het vliegtuig naar Rome vertrekt om negen uur.', target: "L'aereo per Roma parte alle nove.", distractors: ['treno', 'aeroporto', 'alla'] },
            {
              type: 'match',
              pairs: [
                { nl: 'het vliegtuig', target: "l'aereo" },
                { nl: 'het vliegveld', target: "l'aeroporto" },
                { nl: 'de koffer', target: 'la valigia' },
                { nl: 'het paspoort', target: 'il passaporto' },
              ],
            },
            { type: 'type', nl: 'de koffer', target: 'la valigia', accept: ['valigia', 'Valigia', 'La valigia'] },
            { type: 'listen', target: "l'aereo", options: ["l'aereo", "l'aeroporto", 'il treno'], correct: 0 },
          ],
        },
        {
          id: 'it-u10-l2',
          title: 'Onderweg',
          exercises: [
            { type: 'new', word: "l'autobus", nl: 'de bus', example: "Prendo l'autobus per andare in centro.", exampleNl: 'Ik neem de bus om naar het centrum te gaan.' },
            { type: 'new', word: 'la macchina', nl: 'de auto', example: 'La macchina è parcheggiata in piazza.', exampleNl: 'De auto staat geparkeerd op het plein.' },
            { type: 'new', word: 'prenotare', nl: 'reserveren', example: 'Vorrei prenotare una camera per due notti.', exampleNl: 'Ik wil graag een kamer voor twee nachten reserveren.' },
            { type: 'new', word: 'il viaggio', nl: 'de reis', example: 'Buon viaggio!', exampleNl: 'Goede reis!' },
            { type: 'select', prompt: 'de auto', options: ["l'autobus", 'la macchina', 'il treno'], correct: 1 },
            { type: 'select', prompt: 'il viaggio', speak: 'il viaggio', options: ['de reis', 'het vliegveld', 'de bus'], correct: 0 },
            { type: 'listen', target: "l'autobus", options: ["l'autobus", "l'aereo", 'la macchina'], correct: 0 },
            { type: 'fill', before: 'Vorrei prenotare', after: 'tavolo per due.', nl: 'Ik wil graag een tafel voor twee reserveren.', options: ['un', 'una', 'uno'], correct: 0 },
            { type: 'wordbank', nl: 'Ik neem de bus naar het vliegveld.', target: "Prendo l'autobus per l'aeroporto.", distractors: ['il', 'treno', 'macchina'] },
            {
              type: 'match',
              pairs: [
                { nl: 'de bus', target: "l'autobus" },
                { nl: 'de auto', target: 'la macchina' },
                { nl: 'de reis', target: 'il viaggio' },
                { nl: 'de trein', target: 'il treno' },
                { nl: 'het kaartje', target: 'il biglietto' },
              ],
            },
            { type: 'type', nl: 'de reis', target: 'il viaggio', accept: ['viaggio', 'Viaggio', 'Il viaggio'] },
            { type: 'fill', before: 'Andiamo a Firenze', after: 'macchina.', nl: 'We gaan met de auto naar Florence.', options: ['in', 'a', 'con'], correct: 0 },
          ],
        },
        {
          id: 'it-u10-l3',
          title: 'Herhaling: reizen & vervoer',
          exercises: [
            { type: 'type', nl: 'het vliegtuig', target: "l'aereo", accept: ['aereo', 'Aereo', "L'aereo"] },
            { type: 'wordbank', nl: 'Mijn koffer is op het vliegveld.', target: "La mia valigia è all'aeroporto.", distractors: ['aereo', 'stazione', 'nella'] },
            { type: 'select', prompt: 'het paspoort', options: ['il biglietto', 'il passaporto', 'il viaggio'], correct: 1 },
            { type: 'listen', target: 'la macchina', options: ['la macchina', 'la valigia', 'la piazza'], correct: 0 },
            { type: 'type', nl: 'de bus', target: "l'autobus", accept: ['autobus', 'Autobus', "L'autobus"] },
            { type: 'fill', before: "L'aereo", after: 'Napoli parte alle sei.', nl: 'Het vliegtuig naar Napels vertrekt om zes uur.', options: ['per', 'a', 'di'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'het vliegveld', target: "l'aeroporto" },
                { nl: 'het paspoort', target: 'il passaporto' },
                { nl: 'de auto', target: 'la macchina' },
                { nl: 'de reis', target: 'il viaggio' },
                { nl: 'de koffer', target: 'la valigia' },
              ],
            },
            { type: 'wordbank', nl: 'Ik wil graag twee kaartjes naar Venetië reserveren.', target: 'Vorrei prenotare due biglietti per Venezia.', distractors: ['treni', 'valigia', 'alla'] },
            { type: 'type', nl: 'Goede reis!', target: 'Buon viaggio!', accept: ['buon viaggio', 'Buon viaggio', 'buon viaggio!'] },
            { type: 'select', prompt: 'prenotare', speak: 'prenotare', options: ['betalen', 'reserveren', 'vertrekken'], correct: 1 },
            { type: 'listen', target: 'il passaporto', options: ['il passaporto', 'il biglietto', "l'aeroporto"], correct: 0 },
            { type: 'wordbank', nl: 'Waar is de bus naar het station?', target: "Dov'è l'autobus per la stazione?", distractors: ['treno', 'macchina', 'a'] },
          ],
        },
      ],
    },
    {
      id: 'it-u11',
      title: 'Gezondheid & lichaam',
      icon: '🌿',
      lessons: [
        {
          id: 'it-u11-l1',
          title: 'Bij de dokter',
          exercises: [
            { type: 'new', word: 'il medico', nl: 'de dokter', example: 'Devo andare dal medico.', exampleNl: 'Ik moet naar de dokter.' },
            { type: 'new', word: 'la testa', nl: 'het hoofd', example: 'Ho mal di testa.', exampleNl: 'Ik heb hoofdpijn.' },
            { type: 'new', word: 'la febbre', nl: 'de koorts', example: 'Il bambino ha la febbre.', exampleNl: 'Het kind heeft koorts.' },
            { type: 'new', word: 'mi fa male', nl: 'het doet me pijn', example: 'Mi fa male la testa.', exampleNl: 'Mijn hoofd doet pijn.' },
            { type: 'select', prompt: 'de dokter', options: ['la febbre', 'il medico', 'la testa'], correct: 1 },
            { type: 'select', prompt: 'la febbre', speak: 'la febbre', options: ['de koorts', 'het hoofd', 'de pijn'], correct: 0 },
            { type: 'listen', target: 'la testa', options: ['la testa', 'la festa', 'la pasta'], correct: 0 },
            { type: 'fill', before: 'Ho mal', after: 'testa.', nl: 'Ik heb hoofdpijn.', options: ['di', 'a', 'da'], correct: 0 },
            { type: 'wordbank', nl: 'Ik moet naar de dokter.', target: 'Devo andare dal medico.', distractors: ['il', 'alla', 'febbre'] },
            {
              type: 'match',
              pairs: [
                { nl: 'de dokter', target: 'il medico' },
                { nl: 'het hoofd', target: 'la testa' },
                { nl: 'de koorts', target: 'la febbre' },
                { nl: 'het doet me pijn', target: 'mi fa male' },
              ],
            },
            { type: 'type', nl: 'het hoofd', target: 'la testa', accept: ['testa', 'Testa', 'La testa'] },
            { type: 'listen', target: 'mi fa male', options: ['mi fa male', 'mi chiamo', 'la febbre'], correct: 0 },
          ],
        },
        {
          id: 'it-u11-l2',
          title: 'Het lichaam',
          exercises: [
            { type: 'new', word: 'la mano', nl: 'de hand', example: 'Scrivo con la mano destra.', exampleNl: 'Ik schrijf met mijn rechterhand.' },
            { type: 'new', word: 'la gamba', nl: 'het been', example: 'Mi fa male la gamba.', exampleNl: 'Mijn been doet pijn.' },
            { type: 'new', word: 'lo stomaco', nl: 'de maag', example: 'Ho mal di stomaco.', exampleNl: 'Ik heb maagpijn.' },
            { type: 'new', word: 'la farmacia', nl: 'de apotheek', example: 'La farmacia è aperta fino alle otto.', exampleNl: 'De apotheek is open tot acht uur.' },
            { type: 'select', prompt: 'het been', options: ['la mano', 'la gamba', 'lo stomaco'], correct: 1 },
            { type: 'select', prompt: 'la farmacia', speak: 'la farmacia', options: ['de dokter', 'het ziekenhuis', 'de apotheek'], correct: 2 },
            { type: 'listen', target: 'lo stomaco', options: ['lo stomaco', 'la stazione', 'la gamba'], correct: 0 },
            { type: 'fill', before: 'Mi fa male', after: 'stomaco.', nl: 'Mijn maag doet pijn.', options: ['lo', 'la', 'il'], correct: 0 },
            { type: 'wordbank', nl: 'Waar is de apotheek?', target: "Dov'è la farmacia?", distractors: ['medico', 'il', 'dove'] },
            {
              type: 'match',
              pairs: [
                { nl: 'de hand', target: 'la mano' },
                { nl: 'het been', target: 'la gamba' },
                { nl: 'de maag', target: 'lo stomaco' },
                { nl: 'de apotheek', target: 'la farmacia' },
                { nl: 'de dokter', target: 'il medico' },
              ],
            },
            { type: 'type', nl: 'de hand', target: 'la mano', accept: ['mano', 'Mano', 'La mano'] },
            { type: 'wordbank', nl: 'Mijn been doet pijn.', target: 'Mi fa male la gamba.', distractors: ['testa', 'lo', 'febbre'] },
          ],
        },
        {
          id: 'it-u11-l3',
          title: 'Herhaling: gezondheid',
          exercises: [
            { type: 'type', nl: 'de koorts', target: 'la febbre', accept: ['febbre', 'Febbre', 'La febbre'] },
            { type: 'wordbank', nl: 'Ik heb koorts en hoofdpijn.', target: 'Ho la febbre e mal di testa.', distractors: ['stomaco', 'gamba', 'il'] },
            { type: 'select', prompt: 'de maag', options: ['la gamba', 'lo stomaco', 'la mano'], correct: 1 },
            { type: 'listen', target: 'la farmacia', options: ['la farmacia', 'la famiglia', 'la febbre'], correct: 0 },
            { type: 'type', nl: 'de dokter', target: 'il medico', accept: ['medico', 'Medico', 'Il medico'] },
            { type: 'fill', before: 'Devo andare', after: 'medico.', nl: 'Ik moet naar de dokter.', options: ['dal', 'al', 'del'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'de koorts', target: 'la febbre' },
                { nl: 'de hand', target: 'la mano' },
                { nl: 'de apotheek', target: 'la farmacia' },
                { nl: 'het hoofd', target: 'la testa' },
              ],
            },
            { type: 'wordbank', nl: 'De apotheek is dicht bij het station.', target: 'La farmacia è vicino alla stazione.', distractors: ['medico', 'destra', 'il'] },
            { type: 'type', nl: 'Mijn hoofd doet pijn.', target: 'Mi fa male la testa.', accept: ['mi fa male la testa', 'Mi fa male la testa'] },
            { type: 'select', prompt: 'la gamba', speak: 'la gamba', options: ['de arm', 'het been', 'de hand'], correct: 1 },
            { type: 'listen', target: 'la febbre', options: ['la febbre', 'la farmacia', 'mi fa male'], correct: 0 },
            { type: 'wordbank', nl: 'Ik heb maagpijn, waar is de apotheek?', target: "Ho mal di stomaco, dov'è la farmacia?", distractors: ['testa', 'medico', 'il'] },
          ],
        },
      ],
    },
    {
      id: 'it-u12',
      title: 'Weer & seizoenen',
      icon: '🌦️',
      lessons: [
        {
          id: 'it-u12-l1',
          title: 'Wat voor weer is het?',
          exercises: [
            { type: 'new', word: 'il sole', nl: 'de zon', example: "Oggi c'è il sole.", exampleNl: 'Vandaag schijnt de zon.' },
            { type: 'new', word: 'la pioggia', nl: 'de regen', example: 'Non mi piace la pioggia.', exampleNl: 'Ik hou niet van regen.' },
            { type: 'new', word: 'fa caldo', nl: 'het is warm', example: 'In agosto fa molto caldo.', exampleNl: 'In augustus is het erg warm.' },
            { type: 'new', word: 'fa freddo', nl: 'het is koud', example: 'In montagna fa freddo.', exampleNl: 'In de bergen is het koud.' },
            { type: 'select', prompt: 'de zon', options: ['la pioggia', 'il sole', 'il cielo'], correct: 1 },
            { type: 'select', prompt: 'fa caldo', speak: 'fa caldo', options: ['het is koud', 'het is warm', 'het regent'], correct: 1 },
            { type: 'listen', target: 'la pioggia', options: ['la pioggia', 'la piazza', 'la spiaggia'], correct: 0 },
            { type: 'fill', before: 'Oggi', after: 'caldo.', nl: 'Vandaag is het warm.', options: ['fa', 'è', 'ha'], correct: 0 },
            { type: 'wordbank', nl: 'Vandaag schijnt de zon.', target: "Oggi c'è il sole.", distractors: ['pioggia', 'fa', 'caldo'] },
            {
              type: 'match',
              pairs: [
                { nl: 'de zon', target: 'il sole' },
                { nl: 'de regen', target: 'la pioggia' },
                { nl: 'het is warm', target: 'fa caldo' },
                { nl: 'het is koud', target: 'fa freddo' },
              ],
            },
            { type: 'type', nl: 'de zon', target: 'il sole', accept: ['sole', 'Sole', 'Il sole'] },
            { type: 'listen', target: 'fa freddo', options: ['fa freddo', 'fa caldo', 'il sole'], correct: 0 },
          ],
        },
        {
          id: 'it-u12-l2',
          title: 'De seizoenen',
          exercises: [
            { type: 'new', word: "l'estate", nl: 'de zomer', example: 'In estate andiamo al mare.', exampleNl: 'In de zomer gaan we naar zee.' },
            { type: 'new', word: "l'inverno", nl: 'de winter', example: 'In inverno nevica in montagna.', exampleNl: 'In de winter sneeuwt het in de bergen.' },
            { type: 'new', word: 'la primavera', nl: 'de lente', example: 'La primavera è la mia stagione preferita.', exampleNl: 'De lente is mijn favoriete seizoen.' },
            { type: 'new', word: "l'autunno", nl: 'de herfst', example: 'In autunno piove spesso.', exampleNl: 'In de herfst regent het vaak.' },
            { type: 'select', prompt: 'de winter', options: ["l'estate", "l'inverno", "l'autunno"], correct: 1 },
            { type: 'select', prompt: 'la primavera', speak: 'la primavera', options: ['de herfst', 'de zomer', 'de lente'], correct: 2 },
            { type: 'listen', target: "l'estate", options: ["l'estate", "l'autunno", "l'inverno"], correct: 0 },
            { type: 'fill', before: 'In inverno', after: 'freddo.', nl: 'In de winter is het koud.', options: ['fa', 'è', "c'è"], correct: 0 },
            { type: 'wordbank', nl: 'In de zomer is het erg warm.', target: 'In estate fa molto caldo.', distractors: ['inverno', 'freddo', 'sole'] },
            {
              type: 'match',
              pairs: [
                { nl: 'de zomer', target: "l'estate" },
                { nl: 'de winter', target: "l'inverno" },
                { nl: 'de lente', target: 'la primavera' },
                { nl: 'de herfst', target: "l'autunno" },
                { nl: 'de regen', target: 'la pioggia' },
              ],
            },
            { type: 'type', nl: 'de zomer', target: "l'estate", accept: ['estate', 'Estate', "L'estate"] },
            { type: 'wordbank', nl: 'In de herfst regent het vaak.', target: 'In autunno piove spesso.', distractors: ['estate', 'caldo', 'sole'] },
          ],
        },
        {
          id: 'it-u12-l3',
          title: 'Herhaling: weer & seizoenen',
          exercises: [
            { type: 'type', nl: 'de regen', target: 'la pioggia', accept: ['pioggia', 'Pioggia', 'La pioggia'] },
            { type: 'wordbank', nl: 'In de winter is het koud in de bergen.', target: 'In inverno fa freddo in montagna.', distractors: ['estate', 'caldo', 'sole'] },
            { type: 'select', prompt: 'de herfst', options: ["l'inverno", "l'autunno", 'la primavera'], correct: 1 },
            { type: 'listen', target: 'la primavera', options: ['la primavera', "l'estate", 'la pioggia'], correct: 0 },
            { type: 'type', nl: 'het is warm', target: 'fa caldo', accept: ['Fa caldo', 'fa caldo.'] },
            { type: 'fill', before: 'Oggi', after: 'il sole.', nl: 'Vandaag schijnt de zon.', options: ["c'è", 'fa', 'è'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'het is koud', target: 'fa freddo' },
                { nl: 'de lente', target: 'la primavera' },
                { nl: 'de zon', target: 'il sole' },
                { nl: 'de herfst', target: "l'autunno" },
              ],
            },
            { type: 'wordbank', nl: 'Vandaag regent het en is het koud.', target: 'Oggi piove e fa freddo.', distractors: ['caldo', 'sole', "c'è"] },
            { type: 'type', nl: 'de winter', target: "l'inverno", accept: ['inverno', 'Inverno', "L'inverno"] },
            { type: 'select', prompt: "l'estate", speak: "l'estate", options: ['de lente', 'de zomer', 'de winter'], correct: 1 },
            { type: 'listen', target: 'fa caldo', options: ['fa caldo', 'fa freddo', 'la pioggia'], correct: 0 },
            { type: 'wordbank', nl: 'De lente in Italië is prachtig.', target: 'La primavera in Italia è bellissima.', distractors: ["l'estate", 'caldo', 'sole'] },
          ],
        },
      ],
    },
    {
      id: 'it-u13',
      title: 'Uitgaan & cultuur',
      icon: '🎭',
      lessons: [
        {
          id: 'it-u13-l1',
          title: 'Naar de film',
          exercises: [
            { type: 'new', word: 'il cinema', nl: 'de bioscoop', example: 'Stasera andiamo al cinema.', exampleNl: 'Vanavond gaan we naar de bioscoop.' },
            { type: 'new', word: 'il film', nl: 'de film', example: 'Il film comincia alle nove.', exampleNl: 'De film begint om negen uur.' },
            { type: 'new', word: 'il teatro', nl: 'het theater', example: 'Il teatro è in centro.', exampleNl: 'Het theater is in het centrum.' },
            { type: 'new', word: 'stasera', nl: 'vanavond', example: 'Cosa facciamo stasera?', exampleNl: 'Wat doen we vanavond?' },
            { type: 'select', prompt: 'de bioscoop', options: ['il teatro', 'il cinema', 'il film'], correct: 1 },
            { type: 'select', prompt: 'stasera', speak: 'stasera', options: ['vanmorgen', 'vanavond', 'morgen'], correct: 1 },
            { type: 'listen', target: 'il teatro', options: ['il teatro', 'il treno', 'il cinema'], correct: 0 },
            { type: 'fill', before: 'Stasera andiamo', after: 'cinema.', nl: 'Vanavond gaan we naar de bioscoop.', options: ['al', 'in', 'a'], correct: 0 },
            { type: 'wordbank', nl: 'De film begint om negen uur.', target: 'Il film comincia alle nove.', distractors: ['teatro', 'stasera', 'cinema'] },
            {
              type: 'match',
              pairs: [
                { nl: 'de bioscoop', target: 'il cinema' },
                { nl: 'de film', target: 'il film' },
                { nl: 'het theater', target: 'il teatro' },
                { nl: 'vanavond', target: 'stasera' },
              ],
            },
            { type: 'type', nl: 'de film', target: 'il film', accept: ['film', 'Film', 'Il film'] },
            { type: 'listen', target: 'stasera', options: ['stasera', 'la sera', 'la stazione'], correct: 0 },
          ],
        },
        {
          id: 'it-u13-l2',
          title: 'Muziek & feest',
          exercises: [
            { type: 'new', word: 'la musica', nl: 'de muziek', example: 'Mi piace la musica italiana.', exampleNl: 'Ik hou van Italiaanse muziek.' },
            { type: 'new', word: 'il concerto', nl: 'het concert', example: 'Il concerto è in piazza.', exampleNl: 'Het concert is op het plein.' },
            { type: 'new', word: 'la festa', nl: 'het feest', example: "Sabato c'è una festa a casa di Giulia.", exampleNl: 'Zaterdag is er een feest bij Giulia thuis.' },
            { type: 'new', word: 'ballare', nl: 'dansen', example: 'Mi piace ballare con gli amici.', exampleNl: 'Ik dans graag met vrienden.' },
            { type: 'select', prompt: 'het feest', options: ['la musica', 'la festa', 'il concerto'], correct: 1 },
            { type: 'select', prompt: 'ballare', speak: 'ballare', options: ['zingen', 'dansen', 'luisteren'], correct: 1 },
            { type: 'listen', target: 'la musica', options: ['la musica', 'la macchina', 'la festa'], correct: 0 },
            { type: 'fill', before: 'Il concerto è', after: 'piazza.', nl: 'Het concert is op het plein.', options: ['in', 'a', 'su'], correct: 0 },
            { type: 'wordbank', nl: 'Vanavond is er een concert op het plein.', target: "Stasera c'è un concerto in piazza.", distractors: ['festa', 'musica', 'il'] },
            {
              type: 'match',
              pairs: [
                { nl: 'de muziek', target: 'la musica' },
                { nl: 'het concert', target: 'il concerto' },
                { nl: 'het feest', target: 'la festa' },
                { nl: 'dansen', target: 'ballare' },
                { nl: 'de bioscoop', target: 'il cinema' },
              ],
            },
            { type: 'type', nl: 'het feest', target: 'la festa', accept: ['festa', 'Festa', 'La festa'] },
            { type: 'wordbank', nl: 'Ik dans graag op het feest.', target: 'Mi piace ballare alla festa.', distractors: ['musica', 'concerto', 'il'] },
          ],
        },
        {
          id: 'it-u13-l3',
          title: 'Herhaling: uitgaan',
          exercises: [
            { type: 'type', nl: 'het theater', target: 'il teatro', accept: ['teatro', 'Teatro', 'Il teatro'] },
            { type: 'wordbank', nl: 'Gaan we vanavond naar de bioscoop?', target: 'Andiamo al cinema stasera?', distractors: ['teatro', 'festa', 'il'] },
            { type: 'select', prompt: 'het concert', options: ['la festa', 'il concerto', 'la musica'], correct: 1 },
            { type: 'listen', target: 'ballare', options: ['ballare', 'parlare', 'la festa'], correct: 0 },
            { type: 'type', nl: 'de muziek', target: 'la musica', accept: ['musica', 'Musica', 'La musica'] },
            { type: 'fill', before: 'Andiamo', after: 'teatro stasera.', nl: 'We gaan vanavond naar het theater.', options: ['al', 'dal', 'del'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'vanavond', target: 'stasera' },
                { nl: 'dansen', target: 'ballare' },
                { nl: 'de film', target: 'il film' },
                { nl: 'het concert', target: 'il concerto' },
              ],
            },
            { type: 'wordbank', nl: 'Het feest van Giulia is zaterdag.', target: 'La festa di Giulia è sabato.', distractors: ['concerto', 'stasera', 'il'] },
            { type: 'type', nl: 'vanavond', target: 'stasera', accept: ['Stasera'] },
            { type: 'select', prompt: 'il cinema', speak: 'il cinema', options: ['het theater', 'de bioscoop', 'het concert'], correct: 1 },
            { type: 'listen', target: 'il concerto', options: ['il concerto', 'il conto', 'il cinema'], correct: 0 },
            { type: 'wordbank', nl: 'Ik hou van Italiaanse muziek.', target: 'Mi piace la musica italiana.', distractors: ['ballare', 'festa', 'il'] },
          ],
        },
      ],
    },
    {
      id: 'it-u14',
      title: 'De grote herhaling',
      icon: '🏆',
      lessons: [
        {
          id: 'it-u14-l1',
          title: 'Herhaling: op reis',
          exercises: [
            { type: 'wordbank', nl: 'Een kaartje naar Rome, alsjeblieft.', target: 'Un biglietto per Roma, per favore.', distractors: ['treno', 'la', 'grazie'] },
            { type: 'select', prompt: 'de koffer', options: ['la valigia', 'la macchina', 'la gamba'], correct: 0 },
            { type: 'type', nl: 'het vliegveld', target: "l'aeroporto", accept: ['aeroporto', 'Aeroporto', "L'aeroporto"] },
            { type: 'listen', target: 'il medico', options: ['il medico', 'il museo', 'la musica'], correct: 0 },
            { type: 'fill', before: 'Il treno', after: 'Milano parte alle otto.', nl: 'De trein naar Milaan vertrekt om acht uur.', options: ['per', 'a', 'da'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'de trein', target: 'il treno' },
                { nl: 'het vliegtuig', target: "l'aereo" },
                { nl: 'de dokter', target: 'il medico' },
                { nl: 'de apotheek', target: 'la farmacia' },
                { nl: 'het kaartje', target: 'il biglietto' },
              ],
            },
            { type: 'wordbank', nl: 'Mijn hoofd doet pijn, ik moet naar de dokter.', target: 'Mi fa male la testa, devo andare dal medico.', distractors: ['febbre', 'farmacia', 'al'] },
            { type: 'select', prompt: 'la stazione', speak: 'la stazione', options: ['het station', 'het vliegveld', 'het plein'], correct: 0 },
            { type: 'type', nl: 'Waar is het station?', target: "Dov'è la stazione?", accept: ["dov'è la stazione", "Dov'è la stazione", 'Dove è la stazione?'] },
            { type: 'listen', target: 'la valigia', options: ['la valigia', 'la famiglia', 'la farmacia'], correct: 0 },
            { type: 'wordbank', nl: 'Ik wil graag een koffie en een water, alsjeblieft.', target: "Vorrei un caffè e un'acqua, per favore.", distractors: ['vino', 'il', 'conto'] },
            { type: 'fill', before: 'Ho mal', after: 'stomaco.', nl: 'Ik heb maagpijn.', options: ['di', 'a', 'del'], correct: 0 },
          ],
        },
        {
          id: 'it-u14-l2',
          title: 'Herhaling: weer & uitgaan',
          exercises: [
            { type: 'select', prompt: 'het is koud', options: ['fa caldo', 'fa freddo', "c'è il sole"], correct: 1 },
            { type: 'wordbank', nl: 'Vanavond gaan we naar het theater.', target: 'Stasera andiamo al teatro.', distractors: ['cinema', 'in', 'festa'] },
            { type: 'type', nl: 'de zomer', target: "l'estate", accept: ['estate', 'Estate', "L'estate"] },
            { type: 'listen', target: 'la festa', options: ['la festa', 'la testa', 'la pasta'], correct: 0 },
            { type: 'fill', before: 'In estate', after: 'molto caldo.', nl: 'In de zomer is het erg warm.', options: ['fa', 'è', 'ha'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'de regen', target: 'la pioggia' },
                { nl: 'het feest', target: 'la festa' },
                { nl: 'de winter', target: "l'inverno" },
                { nl: 'de muziek', target: 'la musica' },
                { nl: 'de wijn', target: 'il vino' },
              ],
            },
            { type: 'wordbank', nl: 'Vandaag schijnt de zon op het plein.', target: "Oggi c'è il sole in piazza.", distractors: ['pioggia', 'fa', 'la'] },
            { type: 'select', prompt: 'il concerto', speak: 'il concerto', options: ['de rekening', 'het concert', 'de bioscoop'], correct: 1 },
            { type: 'type', nl: 'het regent', target: 'piove', accept: ['Piove', 'piove.'] },
            { type: 'listen', target: "l'inverno", options: ["l'inverno", "l'estate", "l'uomo"], correct: 0 },
            { type: 'wordbank', nl: 'De pizza en de wijn zijn heerlijk.', target: 'La pizza e il vino sono buonissimi.', distractors: ['pasta', 'conto', 'la'] },
            { type: 'fill', before: 'Andiamo', after: 'cinema?', nl: 'Gaan we naar de bioscoop?', options: ['al', 'a', 'dal'], correct: 0 },
          ],
        },
        {
          id: 'it-u14-l3',
          title: 'De grote finale',
          exercises: [
            { type: 'type', nl: 'Goede reis!', target: 'Buon viaggio!', accept: ['buon viaggio', 'Buon viaggio', 'buon viaggio!'] },
            { type: 'wordbank', nl: 'Goedenavond, ik wil graag een tafel voor twee reserveren.', target: 'Buonasera, vorrei prenotare un tavolo per due.', distractors: ['grazie', 'biglietto', 'la'] },
            { type: 'select', prompt: 'de apotheek', options: ['la farmacia', 'la famiglia', 'la stazione'], correct: 0 },
            { type: 'listen', target: 'buon viaggio', options: ['buon viaggio', 'buongiorno', 'buonasera'], correct: 0 },
            { type: 'type', nl: 'Vanavond is er een feest.', target: "Stasera c'è una festa.", accept: ["stasera c'è una festa", "Stasera c'è una festa"] },
            { type: 'fill', before: 'Mia sorella', after: 'chiama Sara.', nl: 'Mijn zus heet Sara.', options: ['si', 'mi', 'ti'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'graag gedaan', target: 'prego' },
                { nl: 'de koorts', target: 'la febbre' },
                { nl: 'de herfst', target: "l'autunno" },
                { nl: 'de koffer', target: 'la valigia' },
                { nl: 'dansen', target: 'ballare' },
              ],
            },
            { type: 'wordbank', nl: 'In de winter gaan we niet naar zee.', target: 'In inverno non andiamo al mare.', distractors: ['estate', 'sole', 'la'] },
            { type: 'type', nl: 'de rekening', target: 'il conto', accept: ['conto', 'Conto', 'Il conto'] },
            { type: 'select', prompt: 'mi fa male la gamba', speak: 'mi fa male la gamba', options: ['Mijn been doet pijn', 'Mijn hand doet pijn', 'Ik heb koorts'], correct: 0 },
            { type: 'listen', target: 'arrivederci', options: ['arrivederci', 'buonasera', 'a destra'], correct: 0 },
            { type: 'wordbank', nl: 'Tot ziens en goede reis!', target: 'Arrivederci e buon viaggio!', distractors: ['grazie', 'ciao', 'prego'] },
            { type: 'type', nl: 'Ik wil graag twee kaartjes voor het concert.', target: 'Vorrei due biglietti per il concerto.', accept: ['vorrei due biglietti per il concerto'] },
          ],
        },
      ],
    },
  ],
}
