import type { Course } from '../../types'

export const course: Course = {
  id: 'it',
  name: 'Italiaans',
  flag: '🇮🇹',
  tagline: 'La dolce vita, in woorden',
  ttsLang: 'it-IT',
  sections: [
    {
      title: 'Sectie 1 · Eerste stappen',
      cefr: 'A1',
      units: [
        {
          id: 'it-u1',
          title: 'Begroetingen & basis',
          icon: '👋',
          lessons: [
            {
              id: 'it-u1-l1',
              title: 'Hallo zeggen',
              exercises: [
                { type: 'new', word: 'ciao', nl: 'hallo', example: 'Ciao, come stai?', exampleNl: 'Hallo, hoe gaat het?' },
                { type: 'new', word: 'buongiorno', nl: 'goedemorgen', example: 'Buongiorno, signora Rossi!', exampleNl: 'Goedemorgen, mevrouw Rossi!' },
                { type: 'new', word: 'grazie', nl: 'dank je', example: 'Grazie mille!', exampleNl: 'Heel erg bedankt!' },
                { type: 'new', word: 'prego', nl: 'graag gedaan', example: 'Grazie! — Prego.', exampleNl: 'Dank je! — Graag gedaan.' },
                { type: 'select', prompt: 'hallo', options: ['grazie', 'ciao', 'prego'], correct: 1 },
                { type: 'select', prompt: 'buongiorno', speak: 'buongiorno', options: ['graag gedaan', 'goedemorgen', 'goedenavond'], correct: 1 },
                { type: 'listen', target: 'grazie', options: ['prego', 'grazie', 'ciao'], correct: 1 },
                { type: 'select', prompt: 'graag gedaan', options: ['grazie', 'buongiorno', 'prego'], correct: 2 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'hallo', target: 'ciao' },
                    { nl: 'goedemorgen', target: 'buongiorno' },
                    { nl: 'dank je', target: 'grazie' },
                    { nl: 'graag gedaan', target: 'prego' },
                  ],
                },
                { type: 'type', nl: 'dank je', target: 'grazie', accept: ['Grazie', 'grazie!', 'Grazie!'] },
                { type: 'listen', target: 'ciao', options: ['ciao', 'prego', 'buongiorno'], correct: 0 },
                { type: 'select', prompt: 'grazie', speak: 'grazie', options: ['hallo', 'tot ziens', 'dank je'], correct: 2 },
              ],
            },
            {
              id: 'it-u1-l2',
              title: 'Kennismaken',
              exercises: [
                { type: 'new', word: 'buonasera', nl: 'goedenavond', example: 'Buonasera, signor Bruni.', exampleNl: 'Goedenavond, meneer Bruni.' },
                { type: 'new', word: 'arrivederci', nl: 'tot ziens', example: 'Arrivederci, a domani!', exampleNl: 'Tot ziens, tot morgen!' },
                { type: 'new', word: 'mi chiamo', nl: 'ik heet', example: 'Mi chiamo Luca.', exampleNl: 'Ik heet Luca.' },
                { type: 'new', word: 'piacere', nl: 'aangenaam', example: 'Piacere, io sono Giulia.', exampleNl: 'Aangenaam, ik ben Giulia.' },
                { type: 'select', prompt: 'goedenavond', options: ['buongiorno', 'buonasera', 'arrivederci'], correct: 1 },
                { type: 'select', prompt: 'arrivederci', speak: 'arrivederci', options: ['aangenaam', 'goedenavond', 'tot ziens'], correct: 2 },
                { type: 'fill', before: 'Mi', after: 'Marco.', nl: 'Ik heet Marco.', options: ['chiama', 'chiamo', 'chiami'], correct: 1 },
                { type: 'listen', target: 'buonasera', options: ['buongiorno', 'arrivederci', 'buonasera'], correct: 2 },
                { type: 'wordbank', nl: 'Ik heet Anna, aangenaam!', target: 'Mi chiamo Anna, piacere!', distractors: ['sono', 'ciao', 'grazie'] },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'goedenavond', target: 'buonasera' },
                    { nl: 'tot ziens', target: 'arrivederci' },
                    { nl: 'aangenaam', target: 'piacere' },
                    { nl: 'dank je', target: 'grazie' },
                    { nl: 'hallo', target: 'ciao' },
                  ],
                },
                { type: 'type', nl: 'tot ziens', target: 'arrivederci', accept: ['Arrivederci', 'arrivederci!', 'Arrivederci!'] },
                { type: 'select', prompt: 'piacere', speak: 'piacere', options: ['tot ziens', 'aangenaam', 'graag gedaan'], correct: 1 },
              ],
            },
            {
              id: 'it-u1-l3',
              title: 'Herhaling: begroetingen',
              exercises: [
                { type: 'select', prompt: 'goedemorgen', options: ['buonasera', 'arrivederci', 'buongiorno'], correct: 2 },
                { type: 'type', nl: 'hallo', target: 'ciao', accept: ['Ciao', 'ciao!', 'Ciao!'] },
                { type: 'wordbank', nl: 'Goedemorgen! Ik heet Sofia.', target: 'Buongiorno! Mi chiamo Sofia.', distractors: ['piacere', 'ciao', 'sono', 'grazie'] },
                { type: 'listen', target: 'arrivederci', options: ['arrivederci', 'buonasera', 'piacere'], correct: 0 },
                { type: 'type', nl: 'goedenavond', target: 'buonasera', accept: ['Buonasera', 'buonasera!', 'Buonasera!'] },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'hallo', target: 'ciao' },
                    { nl: 'graag gedaan', target: 'prego' },
                    { nl: 'aangenaam', target: 'piacere' },
                    { nl: 'goedemorgen', target: 'buongiorno' },
                  ],
                },
                { type: 'fill', before: 'Grazie mille! —', after: '!', nl: 'Heel erg bedankt! — Graag gedaan!', options: ['Piacere', 'Prego', 'Arrivederci'], correct: 1 },
                { type: 'wordbank', nl: 'Tot ziens en dank je!', target: 'Arrivederci e grazie!', distractors: ['prego', 'ciao', 'buonasera'] },
                { type: 'type', nl: 'aangenaam', target: 'piacere', accept: ['Piacere', 'piacere!', 'Piacere!'] },
                { type: 'select', prompt: 'buongiorno', speak: 'buongiorno', options: ['goedemorgen', 'goedenavond', 'tot ziens'], correct: 0 },
                { type: 'listen', target: 'prego', options: ['piacere', 'grazie', 'prego'], correct: 2 },
                { type: 'wordbank', nl: 'Goedenavond, ik heet Paolo.', target: 'Buonasera, mi chiamo Paolo.', distractors: ['buongiorno', 'piacere', 'arrivederci'] },
              ],
            },
          ],
        },
        {
          id: 'it-u2',
          title: 'Eten & drinken',
          icon: '☕',
          lessons: [
            {
              id: 'it-u2-l1',
              title: 'In de bar',
              exercises: [
                { type: 'new', word: 'il caffè', nl: 'de koffie', example: 'Un caffè al banco, per favore.', exampleNl: 'Een koffie aan de bar, alsjeblieft.' },
                { type: 'new', word: "l'acqua", nl: 'het water', example: "Un'acqua naturale, per favore.", exampleNl: 'Een plat water, alsjeblieft.' },
                { type: 'new', word: 'vorrei', nl: 'ik wil graag', example: 'Vorrei un cappuccino.', exampleNl: 'Ik wil graag een cappuccino.' },
                { type: 'new', word: 'per favore', nl: 'alsjeblieft', example: 'Due caffè, per favore.', exampleNl: 'Twee koffie, alsjeblieft.' },
                { type: 'select', prompt: 'de koffie', options: ['il caffè', "l'acqua", 'il tè'], correct: 0 },
                { type: 'select', prompt: "l'acqua", speak: "l'acqua", options: ['de wijn', 'het water', 'de koffie'], correct: 1 },
                { type: 'listen', target: 'vorrei', options: ['per favore', 'vorrei', 'grazie'], correct: 1 },
                { type: 'fill', before: 'Vorrei', after: 'caffè, per favore.', nl: 'Ik wil graag een koffie, alsjeblieft.', options: ['una', 'uno', 'un'], correct: 2 },
                { type: 'wordbank', nl: 'Een koffie, alsjeblieft.', target: 'Un caffè, per favore.', distractors: ['vorrei', 'grazie', 'acqua'] },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de koffie', target: 'il caffè' },
                    { nl: 'het water', target: "l'acqua" },
                    { nl: 'alsjeblieft', target: 'per favore' },
                    { nl: 'ik wil graag', target: 'vorrei' },
                  ],
                },
                { type: 'type', nl: 'de koffie', target: 'il caffè', accept: ['caffè', 'caffe', 'Il caffè', 'il caffe'] },
                { type: 'listen', target: 'il caffè', options: ['il caffè', 'il tè', "l'acqua"], correct: 0 },
              ],
            },
            {
              id: 'it-u2-l2',
              title: 'Op restaurant',
              exercises: [
                { type: 'new', word: 'la pizza', nl: 'de pizza', example: 'La pizza margherita è buonissima.', exampleNl: 'De pizza margherita is heerlijk.' },
                { type: 'new', word: 'la pasta', nl: 'de pasta', example: 'La pasta al pomodoro, per favore.', exampleNl: 'De pasta met tomatensaus, alsjeblieft.' },
                { type: 'new', word: 'il vino', nl: 'de wijn', example: 'Un bicchiere di vino rosso.', exampleNl: 'Een glas rode wijn.' },
                { type: 'new', word: 'il conto', nl: 'de rekening', example: 'Il conto, per favore!', exampleNl: 'De rekening, alsjeblieft!' },
                { type: 'select', prompt: 'de wijn', options: ["l'acqua", 'il vino', 'il caffè'], correct: 1 },
                { type: 'select', prompt: 'il conto', speak: 'il conto', options: ['de rekening', 'de wijn', 'de pizza'], correct: 0 },
                { type: 'listen', target: 'la pasta', options: ['la pizza', 'la pasta', 'il pane'], correct: 1 },
                { type: 'fill', before: 'Vorrei', after: 'pizza margherita.', nl: 'Ik wil graag de pizza margherita.', options: ['il', 'la', 'lo'], correct: 1 },
                { type: 'wordbank', nl: 'De rekening, alsjeblieft.', target: 'Il conto, per favore.', distractors: ['vino', 'la', 'grazie'] },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de pizza', target: 'la pizza' },
                    { nl: 'de wijn', target: 'il vino' },
                    { nl: 'de rekening', target: 'il conto' },
                    { nl: 'de pasta', target: 'la pasta' },
                    { nl: 'het water', target: "l'acqua" },
                  ],
                },
                { type: 'type', nl: 'de wijn', target: 'il vino', accept: ['vino', 'Vino', 'Il vino'] },
                { type: 'wordbank', nl: 'De pizza en de wijn, alsjeblieft.', target: 'La pizza e il vino, per favore.', distractors: ['pasta', 'conto', 'vorrei', 'grazie'] },
              ],
            },
            {
              id: 'it-u2-l3',
              title: 'Herhaling: eten & drinken',
              exercises: [
                { type: 'type', nl: 'de rekening', target: 'il conto', accept: ['conto', 'Conto', 'Il conto'] },
                { type: 'select', prompt: 'het water', options: ['il vino', "l'acqua", 'il caffè'], correct: 1 },
                { type: 'wordbank', nl: 'Ik wil graag pizza en water.', target: "Vorrei la pizza e l'acqua.", distractors: ['il', 'vino', 'conto', 'per'] },
                { type: 'listen', target: 'il vino', options: ['il vino', 'il conto', 'vorrei'], correct: 0 },
                { type: 'fill', before: 'Un bicchiere', after: 'vino, per favore.', nl: 'Een glas wijn, alsjeblieft.', options: ['da', 'del', 'di'], correct: 2 },
                { type: 'type', nl: 'ik wil graag', target: 'vorrei', accept: ['Vorrei'] },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de koffie', target: 'il caffè' },
                    { nl: 'de pasta', target: 'la pasta' },
                    { nl: 'de rekening', target: 'il conto' },
                    { nl: 'alsjeblieft', target: 'per favore' },
                  ],
                },
                { type: 'wordbank', nl: 'De rekening, alsjeblieft. Dank je!', target: 'Il conto, per favore. Grazie!', distractors: ['vorrei', 'prego', 'vino'] },
                { type: 'select', prompt: 'la pizza', speak: 'la pizza', options: ['de pasta', 'het brood', 'de pizza'], correct: 2 },
                { type: 'listen', target: "l'acqua", options: ["l'acqua", 'la pasta', 'il vino'], correct: 0 },
                { type: 'type', nl: 'Een koffie, alsjeblieft.', target: 'Un caffè, per favore.', accept: ['Un caffè per favore', 'un caffè per favore', 'Un caffe, per favore.', 'un caffe per favore'] },
                { type: 'fill', before: 'Vorrei', after: 'acqua naturale.', nl: 'Ik wil graag een plat water.', options: ['un', 'una', "un'"], correct: 2 },
              ],
            },
          ],
        },
        {
          id: 'it-u3',
          title: 'Mensen & familie',
          icon: '💛',
          lessons: [
            {
              id: 'it-u3-l1',
              title: 'De familie',
              exercises: [
                { type: 'new', word: 'la madre', nl: 'de moeder', example: 'Mia madre si chiama Elena.', exampleNl: 'Mijn moeder heet Elena.' },
                { type: 'new', word: 'il padre', nl: 'de vader', example: 'Mio padre è di Roma.', exampleNl: 'Mijn vader komt uit Rome.' },
                { type: 'new', word: 'il fratello', nl: 'de broer', example: 'Ho un fratello.', exampleNl: 'Ik heb een broer.' },
                { type: 'new', word: 'la sorella', nl: 'de zus', example: 'Mia sorella si chiama Sara.', exampleNl: 'Mijn zus heet Sara.' },
                { type: 'select', prompt: 'de moeder', options: ['la sorella', 'la madre', 'il padre'], correct: 1 },
                { type: 'select', prompt: 'il fratello', speak: 'il fratello', options: ['de broer', 'de zus', 'de vader'], correct: 0 },
                { type: 'listen', target: 'la sorella', options: ['la madre', 'la sorella', 'il fratello'], correct: 1 },
                { type: 'fill', before: 'Ho', after: 'fratello.', nl: 'Ik heb een broer.', options: ['una', 'un', 'uno'], correct: 1 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de moeder', target: 'la madre' },
                    { nl: 'de vader', target: 'il padre' },
                    { nl: 'de broer', target: 'il fratello' },
                    { nl: 'de zus', target: 'la sorella' },
                  ],
                },
                { type: 'wordbank', nl: 'Mijn moeder heet Elena.', target: 'Mia madre si chiama Elena.', distractors: ['padre', 'sorella', 'mio'] },
                { type: 'type', nl: 'de vader', target: 'il padre', accept: ['padre', 'Padre', 'Il padre'] },
                { type: 'select', prompt: 'de zus', options: ['la sorella', 'la madre', 'la nonna'], correct: 0 },
              ],
            },
            {
              id: 'it-u3-l2',
              title: 'Vrienden & mensen',
              exercises: [
                { type: 'new', word: "l'amico", nl: 'de vriend', example: 'Marco è il mio migliore amico.', exampleNl: 'Marco is mijn beste vriend.' },
                { type: 'new', word: 'la famiglia', nl: 'de familie', example: 'La famiglia è importante in Italia.', exampleNl: 'Familie is belangrijk in Italië.' },
                { type: 'new', word: 'la donna', nl: 'de vrouw', example: 'Quella donna è mia madre.', exampleNl: 'Die vrouw is mijn moeder.' },
                { type: 'new', word: "l'uomo", nl: 'de man', example: "L'uomo si chiama Paolo.", exampleNl: 'De man heet Paolo.' },
                { type: 'select', prompt: 'de vriend', options: ["l'uomo", "l'amico", 'il fratello'], correct: 1 },
                { type: 'select', prompt: 'la famiglia', speak: 'la famiglia', options: ['de vrouw', 'de vriendin', 'de familie'], correct: 2 },
                { type: 'listen', target: 'la donna', options: ['la donna', 'la madre', 'la nonna'], correct: 0 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de vriend', target: "l'amico" },
                    { nl: 'de familie', target: 'la famiglia' },
                    { nl: 'de vrouw', target: 'la donna' },
                    { nl: 'de man', target: "l'uomo" },
                  ],
                },
                { type: 'fill', before: 'Paolo è', after: 'amico di Marco.', nl: 'Paolo is een vriend van Marco.', options: ['un', 'una', "un'"], correct: 0 },
                { type: 'wordbank', nl: 'De familie van Marco is groot.', target: 'La famiglia di Marco è grande.', distractors: ['amico', 'madre', 'il'] },
                { type: 'type', nl: 'de vrouw', target: 'la donna', accept: ['donna', 'Donna', 'La donna'] },
                { type: 'listen', target: "l'uomo", options: ["l'amico", "l'uomo", 'la donna'], correct: 1 },
              ],
            },
            {
              id: 'it-u3-l3',
              title: 'Herhaling: mensen & familie',
              exercises: [
                { type: 'type', nl: 'de broer', target: 'il fratello', accept: ['fratello', 'Fratello', 'Il fratello'] },
                { type: 'wordbank', nl: 'Mijn zus heet Sara.', target: 'Mia sorella si chiama Sara.', distractors: ['madre', 'mio', 'donna'] },
                { type: 'select', prompt: 'de man', options: ["l'amico", 'il padre', "l'uomo"], correct: 2 },
                { type: 'listen', target: 'la famiglia', options: ['la famiglia', 'la sorella', 'la donna'], correct: 0 },
                { type: 'type', nl: 'de familie', target: 'la famiglia', accept: ['famiglia', 'Famiglia', 'La famiglia'] },
                { type: 'fill', before: 'Mia madre e', after: 'padre sono di Napoli.', nl: 'Mijn moeder en mijn vader komen uit Napels.', options: ['mia', 'mio', 'miei'], correct: 1 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de zus', target: 'la sorella' },
                    { nl: 'de man', target: "l'uomo" },
                    { nl: 'de vriend', target: "l'amico" },
                    { nl: 'de moeder', target: 'la madre' },
                    { nl: 'de vrouw', target: 'la donna' },
                  ],
                },
                { type: 'wordbank', nl: 'Ik heb een broer en een zus.', target: 'Ho un fratello e una sorella.', distractors: ['la', 'madre', 'il', 'amico'] },
                { type: 'type', nl: 'de moeder', target: 'la madre', accept: ['madre', 'Madre', 'La madre'] },
                { type: 'select', prompt: 'la sorella', speak: 'la sorella', options: ['de zus', 'de broer', 'de dochter'], correct: 0 },
                { type: 'listen', target: 'il padre', options: ['il fratello', 'il padre', 'la madre'], correct: 1 },
                { type: 'wordbank', nl: 'De man is een vriend van mijn vader.', target: "L'uomo è un amico di mio padre.", distractors: ['donna', 'fratello', 'una'] },
              ],
            },
          ],
        },
        {
          id: 'it-u4',
          title: 'Onderweg in de stad',
          icon: '🧭',
          lessons: [
            {
              id: 'it-u4-l1',
              title: 'De weg vragen',
              exercises: [
                { type: 'new', word: 'dove', nl: 'waar', example: "Dov'è la stazione?", exampleNl: 'Waar is het station?' },
                { type: 'new', word: 'la stazione', nl: 'het station', example: 'La stazione è in centro.', exampleNl: 'Het station is in het centrum.' },
                { type: 'new', word: 'a destra', nl: 'naar rechts', example: 'Il bar è a destra.', exampleNl: 'De bar is aan de rechterkant.' },
                { type: 'new', word: 'a sinistra', nl: 'naar links', example: 'Il museo è a sinistra.', exampleNl: 'Het museum is aan de linkerkant.' },
                { type: 'select', prompt: 'waar', options: ['destra', 'qui', 'dove'], correct: 2 },
                { type: 'select', prompt: 'la stazione', speak: 'la stazione', options: ['het station', 'het plein', 'de straat'], correct: 0 },
                { type: 'listen', target: 'a destra', options: ['a sinistra', 'a destra', 'la strada'], correct: 1 },
                { type: 'wordbank', nl: 'Waar is het station?', target: "Dov'è la stazione?", distractors: ['dove', 'destra', 'il'] },
                { type: 'fill', before: "Dov'è", after: 'stazione?', nl: 'Waar is het station?', options: ['la', 'il', 'lo'], correct: 0 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'waar', target: 'dove' },
                    { nl: 'het station', target: 'la stazione' },
                    { nl: 'naar rechts', target: 'a destra' },
                    { nl: 'naar links', target: 'a sinistra' },
                  ],
                },
                { type: 'type', nl: 'naar links', target: 'a sinistra', accept: ['sinistra', 'Sinistra', 'A sinistra'] },
                { type: 'listen', target: 'a sinistra', options: ['a sinistra', 'a destra', 'la stazione'], correct: 0 },
              ],
            },
            {
              id: 'it-u4-l2',
              title: 'Met de trein',
              exercises: [
                { type: 'new', word: 'il treno', nl: 'de trein', example: 'Il treno per Firenze parte alle nove.', exampleNl: 'De trein naar Florence vertrekt om negen uur.' },
                { type: 'new', word: 'il biglietto', nl: 'het kaartje', example: 'Un biglietto per Roma, per favore.', exampleNl: 'Een kaartje naar Rome, alsjeblieft.' },
                { type: 'new', word: 'la piazza', nl: 'het plein', example: 'La piazza è bellissima.', exampleNl: 'Het plein is prachtig.' },
                { type: 'new', word: 'il museo', nl: 'het museum', example: 'Il museo apre alle dieci.', exampleNl: 'Het museum opent om tien uur.' },
                { type: 'select', prompt: 'de trein', options: ['il biglietto', 'il treno', 'il museo'], correct: 1 },
                { type: 'select', prompt: 'la piazza', speak: 'la piazza', options: ['het museum', 'het plein', 'het station'], correct: 1 },
                { type: 'listen', target: 'il biglietto', options: ['il biglietto', 'il treno', 'la piazza'], correct: 0 },
                { type: 'wordbank', nl: 'Een kaartje naar Rome, alsjeblieft.', target: 'Un biglietto per Roma, per favore.', distractors: ['treno', 'il', 'la'] },
                { type: 'fill', before: 'Un biglietto', after: 'Firenze, per favore.', nl: 'Een kaartje naar Florence, alsjeblieft.', options: ['a', 'per', 'di'], correct: 1 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de trein', target: 'il treno' },
                    { nl: 'het kaartje', target: 'il biglietto' },
                    { nl: 'het plein', target: 'la piazza' },
                    { nl: 'het museum', target: 'il museo' },
                    { nl: 'het station', target: 'la stazione' },
                  ],
                },
                { type: 'type', nl: 'het museum', target: 'il museo', accept: ['museo', 'Museo', 'Il museo'] },
                { type: 'wordbank', nl: 'Waar is het museum?', target: "Dov'è il museo?", distractors: ['la', 'piazza', 'destra'] },
              ],
            },
            {
              id: 'it-u4-l3',
              title: 'Herhaling: in de stad',
              exercises: [
                { type: 'type', nl: 'de trein', target: 'il treno', accept: ['treno', 'Treno', 'Il treno'] },
                { type: 'wordbank', nl: 'Het museum is aan de rechterkant.', target: 'Il museo è a destra.', distractors: ['sinistra', 'la', 'piazza'] },
                { type: 'select', prompt: 'het kaartje', options: ['il treno', 'il conto', 'il biglietto'], correct: 2 },
                { type: 'listen', target: 'la piazza', options: ['la piazza', 'la stazione', 'a destra'], correct: 0 },
                { type: 'type', nl: 'waar', target: 'dove', accept: ['Dove', 'dove?', 'Dove?'] },
                { type: 'fill', before: 'Il treno', after: 'Roma parte alle otto.', nl: 'De trein naar Rome vertrekt om acht uur.', options: ['di', 'per', 'in'], correct: 1 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'waar', target: 'dove' },
                    { nl: 'naar links', target: 'a sinistra' },
                    { nl: 'het plein', target: 'la piazza' },
                    { nl: 'het kaartje', target: 'il biglietto' },
                  ],
                },
                { type: 'wordbank', nl: 'Waar is het plein?', target: "Dov'è la piazza?", distractors: ['museo', 'il', 'destra'] },
                { type: 'type', nl: 'het station', target: 'la stazione', accept: ['stazione', 'Stazione', 'La stazione'] },
                { type: 'select', prompt: 'a destra', speak: 'a destra', options: ['naar links', 'rechtdoor', 'naar rechts'], correct: 2 },
                { type: 'listen', target: 'il museo', options: ['il museo', 'il treno', 'il biglietto'], correct: 0 },
                { type: 'wordbank', nl: 'Het station is aan de linkerkant.', target: 'La stazione è a sinistra.', distractors: ['destra', 'il', 'museo', 'dove'] },
              ],
            },
          ],
        },
      ],
    },
  ],
}
