import type { Section } from '../../types'

export const section: Section = {
  title: 'Sectie 2 · Dagelijks leven',
  cefr: 'A1+',
  units: [
    {
      id: 'pt-u5',
      title: 'Getallen & tijd',
      icon: '🕰️',
      lessons: [
        {
          id: 'pt-u5-l1',
          title: 'Tellen tot tien',
          exercises: [
            { type: 'new', word: 'dois', nl: 'twee', example: 'Dois cafés, por favor.', exampleNl: 'Twee koffies, alsjeblieft.' },
            { type: 'new', word: 'três', nl: 'drie', example: 'Quero três pastéis de nata.', exampleNl: 'Ik wil drie pastéis de nata.' },
            { type: 'new', word: 'cinco', nl: 'vijf', example: 'Quero cinco bilhetes para o Porto.', exampleNl: 'Ik wil vijf kaartjes naar Porto.' },
            { type: 'new', word: 'dez', nl: 'tien', example: 'O meu irmão tem dez anos.', exampleNl: 'Mijn broer is tien jaar.' },
            { type: 'select', prompt: 'twee', options: ['três', 'dois', 'dez'], correct: 1 },
            { type: 'select', prompt: 'cinco', speak: 'cinco', options: ['vijf', 'drie', 'tien'], correct: 0 },
            { type: 'listen', target: 'três', options: ['três', 'dez', 'dois'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'twee', target: 'dois' },
                { nl: 'drie', target: 'três' },
                { nl: 'vijf', target: 'cinco' },
                { nl: 'tien', target: 'dez' },
              ],
            },
            { type: 'wordbank', nl: 'Twee koffies, alsjeblieft.', target: 'Dois cafés, por favor.', distractors: ['três', 'um', 'conta'] },
            { type: 'fill', before: 'Dois cafés', after: 'um pastel de nata, por favor.', nl: 'Twee koffies en een pastel de nata, alsjeblieft.', options: ['e', 'com', 'para'], correct: 0 },
            { type: 'type', nl: 'tien', target: 'dez', accept: ['Dez'] },
            { type: 'select', prompt: 'dez', speak: 'dez', options: ['twee', 'tien', 'vijf'], correct: 1 },
          ],
        },
        {
          id: 'pt-u5-l2',
          title: 'Hoe laat is het?',
          exercises: [
            { type: 'new', word: 'a hora', nl: 'het uur', example: 'É uma hora.', exampleNl: 'Het is één uur.' },
            { type: 'new', word: 'que horas são?', nl: 'hoe laat is het?', example: 'Que horas são, por favor?', exampleNl: 'Hoe laat is het, alsjeblieft?' },
            { type: 'new', word: 'o dia', nl: 'de dag', example: 'O dia está bonito.', exampleNl: 'De dag is mooi.' },
            { type: 'new', word: 'a noite', nl: 'de avond', example: 'Boa noite!', exampleNl: 'Goedenavond!' },
            { type: 'select', prompt: 'hoe laat is het?', options: ['que horas são?', 'onde é a estação?', 'tudo bem?'], correct: 0 },
            { type: 'select', prompt: 'a noite', speak: 'a noite', options: ['de dag', 'de avond', 'het uur'], correct: 1 },
            { type: 'listen', target: 'que horas são?', options: ['que horas são?', 'são dez horas', 'é uma hora'], correct: 0 },
            { type: 'fill', before: 'São dez', after: '.', nl: 'Het is tien uur.', options: ['horas', 'hora', 'dias'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'het uur', target: 'a hora' },
                { nl: 'de dag', target: 'o dia' },
                { nl: 'de avond', target: 'a noite' },
                { nl: 'tien', target: 'dez' },
                { nl: 'twee', target: 'dois' },
              ],
            },
            { type: 'wordbank', nl: 'Goedenavond, hoe laat is het?', target: 'Boa noite, que horas são?', distractors: ['bom', 'dia', 'é'] },
            { type: 'type', nl: 'de dag', target: 'o dia', accept: ['dia', 'O dia'] },
            { type: 'fill', before: 'É uma', after: '.', nl: 'Het is één uur.', options: ['hora', 'horas', 'noite'], correct: 0 },
          ],
        },
        {
          id: 'pt-u5-l3',
          title: 'Herhaling: getallen & tijd',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'twee', target: 'dois' },
                { nl: 'vijf', target: 'cinco' },
                { nl: 'tien', target: 'dez' },
                { nl: 'het uur', target: 'a hora' },
                { nl: 'de avond', target: 'a noite' },
              ],
            },
            { type: 'type', nl: 'Hoe laat is het?', target: 'Que horas são?', accept: ['que horas são', 'Que horas sao?', 'que horas sao'] },
            { type: 'wordbank', nl: 'Het is tien uur.', target: 'São dez horas.', distractors: ['é', 'uma', 'dia'] },
            { type: 'listen', target: 'são cinco horas', options: ['são cinco horas', 'são dez horas', 'é uma hora'], correct: 0 },
            { type: 'type', nl: 'twee', target: 'dois', accept: ['Dois', 'duas', 'Duas'] },
            { type: 'fill', before: 'O comboio para o Porto é', after: 'dez horas.', nl: 'De trein naar Porto is om tien uur.', options: ['às', 'a', 'em'], correct: 0 },
            { type: 'wordbank', nl: 'Goedenavond, twee koffies, alsjeblieft.', target: 'Boa noite, dois cafés, por favor.', distractors: ['dia', 'três', 'horas'] },
            { type: 'type', nl: 'de avond', target: 'a noite', accept: ['noite', 'A noite'] },
            { type: 'select', prompt: 'São dez horas.', speak: 'São dez horas.', options: ['Het is tien uur.', 'Het is twee uur.', 'Het is één uur.'], correct: 0 },
            { type: 'type', nl: 'vijf', target: 'cinco', accept: ['Cinco'] },
            { type: 'wordbank', nl: 'Hoe laat is het? Het is één uur.', target: 'Que horas são? É uma hora.', distractors: ['dia', 'dez', 'noite'] },
            { type: 'type', nl: 'Het is vijf uur.', target: 'São cinco horas.', accept: ['são cinco horas', 'Sao cinco horas.', 'sao cinco horas'] },
          ],
        },
      ],
    },
    {
      id: 'pt-u6',
      title: 'Boodschappen & geld',
      icon: '🛍️',
      lessons: [
        {
          id: 'pt-u6-l1',
          title: 'In de winkel',
          exercises: [
            { type: 'new', word: 'a loja', nl: 'de winkel', example: 'A loja é grande.', exampleNl: 'De winkel is groot.' },
            { type: 'new', word: 'quanto custa?', nl: 'hoeveel kost het?', example: 'Quanto custa o pão?', exampleNl: 'Hoeveel kost het brood?' },
            { type: 'new', word: 'o dinheiro', nl: 'het geld', example: 'Não tenho dinheiro.', exampleNl: 'Ik heb geen geld.' },
            { type: 'new', word: 'o euro', nl: 'de euro', example: 'O café custa um euro.', exampleNl: 'De koffie kost één euro.' },
            { type: 'select', prompt: 'de winkel', options: ['a loja', 'a rua', 'a estação'], correct: 0 },
            { type: 'select', prompt: 'quanto custa?', speak: 'quanto custa?', options: ['hoe laat is het?', 'hoeveel kost het?', 'waar is het?'], correct: 1 },
            { type: 'listen', target: 'quanto custa o pão?', options: ['quanto custa o pão?', 'quanto custa o café?', 'onde é a loja?'], correct: 0 },
            { type: 'fill', before: 'O pastel de nata custa dois', after: '.', nl: 'De pastel de nata kost twee euro.', options: ['euros', 'euro', 'o euro'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'de winkel', target: 'a loja' },
                { nl: 'het geld', target: 'o dinheiro' },
                { nl: 'de euro', target: 'o euro' },
                { nl: 'hoeveel kost het?', target: 'quanto custa?' },
              ],
            },
            { type: 'wordbank', nl: 'Hoeveel kost de koffie?', target: 'Quanto custa o café?', distractors: ['a', 'loja', 'euros'] },
            { type: 'type', nl: 'het geld', target: 'o dinheiro', accept: ['dinheiro', 'O dinheiro'] },
            { type: 'fill', before: 'A loja é', after: 'esquerda.', nl: 'De winkel is links.', options: ['à', 'a', 'o'], correct: 0 },
          ],
        },
        {
          id: 'pt-u6-l2',
          title: 'Op de markt',
          exercises: [
            { type: 'new', word: 'o mercado', nl: 'de markt', example: 'O mercado é à direita.', exampleNl: 'De markt is rechts.' },
            { type: 'new', word: 'a fruta', nl: 'het fruit', example: 'A fruta do mercado é boa.', exampleNl: 'Het fruit van de markt is lekker.' },
            { type: 'new', word: 'barato', nl: 'goedkoop', example: 'O pão é barato.', exampleNl: 'Het brood is goedkoop.' },
            { type: 'new', word: 'caro', nl: 'duur', example: 'O vinho é caro.', exampleNl: 'De wijn is duur.' },
            { type: 'select', prompt: 'duur', options: ['barato', 'caro', 'grande'], correct: 1 },
            { type: 'select', prompt: 'a fruta', speak: 'a fruta', options: ['het fruit', 'het brood', 'de markt'], correct: 0 },
            { type: 'listen', target: 'o mercado é barato', options: ['o mercado é barato', 'o mercado é caro', 'a loja é barata'], correct: 0 },
            { type: 'fill', before: 'A fruta é', after: '.', nl: 'Het fruit is goedkoop.', options: ['barata', 'barato', 'baratos'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'de markt', target: 'o mercado' },
                { nl: 'het fruit', target: 'a fruta' },
                { nl: 'goedkoop', target: 'barato' },
                { nl: 'duur', target: 'caro' },
                { nl: 'de euro', target: 'o euro' },
              ],
            },
            { type: 'wordbank', nl: 'Het fruit van de markt is goedkoop.', target: 'A fruta do mercado é barata.', distractors: ['o', 'caro', 'loja'] },
            { type: 'type', nl: 'de markt', target: 'o mercado', accept: ['mercado', 'O mercado'] },
            { type: 'fill', before: 'Quanto custa a fruta', after: 'mercado?', nl: 'Hoeveel kost het fruit op de markt?', options: ['no', 'na', 'em'], correct: 0 },
            { type: 'type', nl: 'De wijn is duur.', target: 'O vinho é caro.', accept: ['o vinho é caro', 'O vinho e caro.', 'o vinho e caro'] },
          ],
        },
        {
          id: 'pt-u6-l3',
          title: 'Herhaling: boodschappen',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'de winkel', target: 'a loja' },
                { nl: 'het geld', target: 'o dinheiro' },
                { nl: 'de markt', target: 'o mercado' },
                { nl: 'goedkoop', target: 'barato' },
                { nl: 'duur', target: 'caro' },
              ],
            },
            { type: 'type', nl: 'Hoeveel kost het?', target: 'Quanto custa?', accept: ['quanto custa', 'Quanto custa?'] },
            { type: 'wordbank', nl: 'Hoeveel kost het kaartje naar Lissabon?', target: 'Quanto custa o bilhete para Lisboa?', distractors: ['a', 'euros', 'mercado'] },
            { type: 'listen', target: 'a loja é cara', options: ['a loja é cara', 'a loja é barata', 'a fruta é cara'], correct: 0 },
            { type: 'type', nl: 'goedkoop', target: 'barato', accept: ['Barato', 'barata', 'Barata'] },
            { type: 'fill', before: 'O pão', after: 'dois euros.', nl: 'Het brood kost twee euro.', options: ['custa', 'custas', 'custam'], correct: 0 },
            { type: 'wordbank', nl: 'Ik wil fruit van de markt.', target: 'Quero fruta do mercado.', distractors: ['a', 'caro', 'loja'] },
            { type: 'type', nl: 'De koffie kost één euro.', target: 'O café custa um euro.', accept: ['o café custa um euro', 'O cafe custa um euro.', 'o cafe custa um euro'] },
            { type: 'select', prompt: 'O mercado é caro.', speak: 'O mercado é caro.', options: ['De markt is duur.', 'De markt is goedkoop.', 'De winkel is duur.'], correct: 0 },
            { type: 'type', nl: 'de euro', target: 'o euro', accept: ['euro', 'O euro'] },
            { type: 'fill', before: 'Eu não', after: 'dinheiro.', nl: 'Ik heb geen geld.', options: ['tenho', 'tem', 'tens'], correct: 0 },
            { type: 'wordbank', nl: 'Het fruit is goedkoop en het brood is lekker.', target: 'A fruta é barata e o pão é bom.', distractors: ['caro', 'barato', 'custa'] },
          ],
        },
      ],
    },
    {
      id: 'pt-u7',
      title: 'Huis & wonen',
      icon: '🏠',
      lessons: [
        {
          id: 'pt-u7-l1',
          title: 'Mijn huis',
          exercises: [
            { type: 'new', word: 'a casa', nl: 'het huis', example: 'A casa é grande.', exampleNl: 'Het huis is groot.' },
            { type: 'new', word: 'moro', nl: 'ik woon', example: 'Moro em Lisboa.', exampleNl: 'Ik woon in Lissabon.' },
            { type: 'new', word: 'o quarto', nl: 'de slaapkamer', example: 'O quarto é pequeno.', exampleNl: 'De slaapkamer is klein.' },
            { type: 'new', word: 'a cozinha', nl: 'de keuken', example: 'A minha mãe está na cozinha.', exampleNl: 'Mijn moeder is in de keuken.' },
            { type: 'select', prompt: 'het huis', options: ['a casa', 'a loja', 'a rua'], correct: 0 },
            { type: 'select', prompt: 'moro', speak: 'moro', options: ['ik wil', 'ik woon', 'ik heb'], correct: 1 },
            { type: 'listen', target: 'moro em Lisboa', options: ['moro em Lisboa', 'moro no Porto', 'a casa é grande'], correct: 0 },
            { type: 'fill', before: 'Moro', after: 'Lisboa.', nl: 'Ik woon in Lissabon.', options: ['em', 'no', 'para'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'het huis', target: 'a casa' },
                { nl: 'de slaapkamer', target: 'o quarto' },
                { nl: 'de keuken', target: 'a cozinha' },
                { nl: 'ik woon', target: 'moro' },
              ],
            },
            { type: 'wordbank', nl: 'Het huis is groot en mooi.', target: 'A casa é grande e bonita.', distractors: ['o', 'quarto', 'pequena'] },
            { type: 'type', nl: 'de keuken', target: 'a cozinha', accept: ['cozinha', 'A cozinha'] },
            { type: 'fill', before: 'A minha irmã está', after: 'cozinha.', nl: 'Mijn zus is in de keuken.', options: ['na', 'no', 'em'], correct: 0 },
          ],
        },
        {
          id: 'pt-u7-l2',
          title: 'In huis',
          exercises: [
            { type: 'new', word: 'a mesa', nl: 'de tafel', example: 'O pão está na mesa.', exampleNl: 'Het brood staat op tafel.' },
            { type: 'new', word: 'a cadeira', nl: 'de stoel', example: 'A cadeira é confortável.', exampleNl: 'De stoel is comfortabel.' },
            { type: 'new', word: 'a porta', nl: 'de deur', example: 'A porta está à direita.', exampleNl: 'De deur is rechts.' },
            { type: 'new', word: 'a janela', nl: 'het raam', example: 'A janela do quarto é grande.', exampleNl: 'Het raam van de slaapkamer is groot.' },
            { type: 'select', prompt: 'de tafel', options: ['a cadeira', 'a mesa', 'a porta'], correct: 1 },
            { type: 'select', prompt: 'a janela', speak: 'a janela', options: ['de deur', 'de tafel', 'het raam'], correct: 2 },
            { type: 'listen', target: 'a porta está à esquerda', options: ['a porta está à esquerda', 'a porta está à direita', 'a janela está à esquerda'], correct: 0 },
            { type: 'fill', before: 'O café está', after: 'mesa.', nl: 'De koffie staat op tafel.', options: ['na', 'no', 'à'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'de tafel', target: 'a mesa' },
                { nl: 'de stoel', target: 'a cadeira' },
                { nl: 'de deur', target: 'a porta' },
                { nl: 'het raam', target: 'a janela' },
              ],
            },
            { type: 'wordbank', nl: 'Het brood staat op tafel.', target: 'O pão está na mesa.', distractors: ['a', 'porta', 'é'] },
            { type: 'type', nl: 'de deur', target: 'a porta', accept: ['porta', 'A porta'] },
            { type: 'fill', before: 'A janela do quarto', after: 'grande.', nl: 'Het raam van de slaapkamer is groot.', options: ['é', 'está', 'são'], correct: 0 },
          ],
        },
        {
          id: 'pt-u7-l3',
          title: 'Herhaling: huis',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'het huis', target: 'a casa' },
                { nl: 'de slaapkamer', target: 'o quarto' },
                { nl: 'de keuken', target: 'a cozinha' },
                { nl: 'de tafel', target: 'a mesa' },
                { nl: 'het raam', target: 'a janela' },
              ],
            },
            { type: 'type', nl: 'Ik woon in Lissabon.', target: 'Moro em Lisboa.', accept: ['moro em lisboa', 'Moro em Lisboa', 'Eu moro em Lisboa.', 'eu moro em Lisboa'] },
            { type: 'wordbank', nl: 'De keuken is klein en mooi.', target: 'A cozinha é pequena e bonita.', distractors: ['o', 'grande', 'casa'] },
            { type: 'listen', target: 'a casa tem dois quartos', options: ['a casa tem dois quartos', 'a casa tem três quartos', 'o quarto é grande'], correct: 0 },
            { type: 'type', nl: 'de stoel', target: 'a cadeira', accept: ['cadeira', 'A cadeira'] },
            { type: 'fill', before: 'A mesa', after: 'na cozinha.', nl: 'De tafel staat in de keuken.', options: ['está', 'é', 'são'], correct: 0 },
            { type: 'wordbank', nl: 'Het huis heeft twee slaapkamers.', target: 'A casa tem dois quartos.', distractors: ['três', 'é', 'cozinha'] },
            { type: 'type', nl: 'het raam', target: 'a janela', accept: ['janela', 'A janela'] },
            { type: 'select', prompt: 'A porta da cozinha está à direita.', speak: 'A porta da cozinha está à direita.', options: ['De keukendeur is rechts.', 'De keukendeur is links.', 'Het keukenraam is rechts.'], correct: 0 },
            { type: 'type', nl: 'Het huis is groot.', target: 'A casa é grande.', accept: ['a casa é grande', 'A casa e grande.', 'a casa e grande'] },
            { type: 'fill', before: 'O meu irmão mora', after: 'Porto.', nl: 'Mijn broer woont in Porto.', options: ['no', 'na', 'em'], correct: 0 },
            { type: 'wordbank', nl: 'Ik woon in Lissabon met mijn familie.', target: 'Moro em Lisboa com a minha família.', distractors: ['casa', 'o', 'meu'] },
          ],
        },
      ],
    },
    {
      id: 'pt-u8',
      title: 'Werk & school',
      icon: '💼',
      lessons: [
        {
          id: 'pt-u8-l1',
          title: 'Op het werk',
          exercises: [
            { type: 'new', word: 'o trabalho', nl: 'het werk', example: 'O trabalho é interessante.', exampleNl: 'Het werk is interessant.' },
            { type: 'new', word: 'trabalhar', nl: 'werken', example: 'Trabalho em Lisboa.', exampleNl: 'Ik werk in Lissabon.' },
            { type: 'new', word: 'o médico', nl: 'de arts', example: 'O meu pai é médico.', exampleNl: 'Mijn vader is arts.' },
            { type: 'new', word: 'a professora', nl: 'de lerares', example: 'A professora é simpática.', exampleNl: 'De lerares is aardig.' },
            { type: 'select', prompt: 'het werk', options: ['o trabalho', 'a loja', 'a escola'], correct: 0 },
            { type: 'select', prompt: 'o médico', speak: 'o médico', options: ['de lerares', 'de arts', 'de man'], correct: 1 },
            { type: 'listen', target: 'trabalho em Lisboa', options: ['trabalho em Lisboa', 'trabalho no Porto', 'moro em Lisboa'], correct: 0 },
            { type: 'fill', before: 'A minha mãe', after: 'professora.', nl: 'Mijn moeder is lerares.', options: ['é', 'está', 'sou'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'het werk', target: 'o trabalho' },
                { nl: 'werken', target: 'trabalhar' },
                { nl: 'de arts', target: 'o médico' },
                { nl: 'de lerares', target: 'a professora' },
              ],
            },
            { type: 'wordbank', nl: 'Mijn vader is arts.', target: 'O meu pai é médico.', distractors: ['a', 'professora', 'trabalho'] },
            { type: 'type', nl: 'de lerares', target: 'a professora', accept: ['professora', 'A professora'] },
            { type: 'fill', before: 'Eu', after: 'em Lisboa.', nl: 'Ik werk in Lissabon.', options: ['trabalho', 'trabalha', 'trabalhas'], correct: 0 },
          ],
        },
        {
          id: 'pt-u8-l2',
          title: 'Naar school',
          exercises: [
            { type: 'new', word: 'a escola', nl: 'de school', example: 'A escola é grande.', exampleNl: 'De school is groot.' },
            { type: 'new', word: 'o livro', nl: 'het boek', example: 'O livro está na mesa.', exampleNl: 'Het boek ligt op tafel.' },
            { type: 'new', word: 'aprender', nl: 'leren', example: 'Quero aprender português.', exampleNl: 'Ik wil Portugees leren.' },
            { type: 'new', word: 'falar', nl: 'spreken', example: 'A professora fala português.', exampleNl: 'De lerares spreekt Portugees.' },
            { type: 'select', prompt: 'de school', options: ['a escola', 'a loja', 'a casa'], correct: 0 },
            { type: 'select', prompt: 'o livro', speak: 'o livro', options: ['het boek', 'het werk', 'de tafel'], correct: 0 },
            { type: 'listen', target: 'quero aprender português', options: ['quero aprender português', 'quero falar português', 'aprendo na escola'], correct: 0 },
            { type: 'fill', before: 'A professora', after: 'português.', nl: 'De lerares spreekt Portugees.', options: ['fala', 'falo', 'falas'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'de school', target: 'a escola' },
                { nl: 'het boek', target: 'o livro' },
                { nl: 'leren', target: 'aprender' },
                { nl: 'spreken', target: 'falar' },
              ],
            },
            { type: 'wordbank', nl: 'Ik wil Portugees leren.', target: 'Quero aprender português.', distractors: ['falo', 'escola', 'o'] },
            { type: 'type', nl: 'het boek', target: 'o livro', accept: ['livro', 'O livro'] },
            { type: 'fill', before: 'O livro está', after: 'mesa.', nl: 'Het boek ligt op tafel.', options: ['na', 'no', 'à'], correct: 0 },
          ],
        },
        {
          id: 'pt-u8-l3',
          title: 'Herhaling: werk & school',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'het werk', target: 'o trabalho' },
                { nl: 'de arts', target: 'o médico' },
                { nl: 'de school', target: 'a escola' },
                { nl: 'het boek', target: 'o livro' },
                { nl: 'spreken', target: 'falar' },
              ],
            },
            { type: 'type', nl: 'Ik werk in Lissabon.', target: 'Trabalho em Lisboa.', accept: ['trabalho em lisboa', 'Eu trabalho em Lisboa.', 'eu trabalho em Lisboa'] },
            { type: 'wordbank', nl: 'De lerares werkt op de school.', target: 'A professora trabalha na escola.', distractors: ['o', 'médico', 'em'] },
            { type: 'listen', target: 'o meu irmão é médico', options: ['o meu irmão é médico', 'o meu pai é médico', 'o meu irmão é professor'], correct: 0 },
            { type: 'type', nl: 'Ik wil Portugees leren.', target: 'Quero aprender português.', accept: ['quero aprender português', 'Quero aprender portugues.', 'quero aprender portugues'] },
            { type: 'fill', before: 'Eu', after: 'português.', nl: 'Ik spreek Portugees.', options: ['falo', 'fala', 'falas'], correct: 0 },
            { type: 'wordbank', nl: 'Het boek van de lerares ligt op tafel.', target: 'O livro da professora está na mesa.', distractors: ['do', 'é', 'escola'] },
            { type: 'type', nl: 'de school', target: 'a escola', accept: ['escola', 'A escola'] },
            { type: 'select', prompt: 'A minha irmã trabalha no mercado.', speak: 'A minha irmã trabalha no mercado.', options: ['Mijn zus werkt op de markt.', 'Mijn zus werkt in de winkel.', 'Mijn broer werkt op de markt.'], correct: 0 },
            { type: 'type', nl: 'de arts', target: 'o médico', accept: ['médico', 'medico', 'O médico', 'o medico'] },
            { type: 'fill', before: 'Quero', after: 'português na escola.', nl: 'Ik wil Portugees leren op school.', options: ['aprender', 'aprendo', 'aprende'], correct: 0 },
            { type: 'wordbank', nl: 'Ik spreek Portugees op het werk.', target: 'Falo português no trabalho.', distractors: ['em', 'escola', 'livro'] },
          ],
        },
      ],
    },
    {
      id: 'pt-u9',
      title: 'Gesprekken voeren',
      icon: '💬',
      lessons: [
        {
          id: 'pt-u9-l1',
          title: 'Een gesprek beginnen',
          exercises: [
            { type: 'new', word: 'chamo-me', nl: 'ik heet', example: 'Olá, chamo-me Ana.', exampleNl: 'Hallo, ik heet Ana.' },
            { type: 'new', word: 'desculpe', nl: 'pardon', example: 'Desculpe, onde é o mercado?', exampleNl: 'Pardon, waar is de markt?' },
            { type: 'new', word: 'gosto de', nl: 'ik houd van', example: 'Gosto de café.', exampleNl: 'Ik houd van koffie.' },
            { type: 'new', word: 'também', nl: 'ook', example: 'Eu também gosto de vinho.', exampleNl: 'Ik houd ook van wijn.' },
            { type: 'select', prompt: 'ik heet', options: ['chamo-me', 'gosto de', 'quero'], correct: 0 },
            { type: 'select', prompt: 'desculpe', speak: 'desculpe', options: ['pardon', 'dank je', 'tot ziens'], correct: 0 },
            { type: 'listen', target: 'gosto de café', options: ['gosto de café', 'gosto de vinho', 'também gosto de café'], correct: 0 },
            { type: 'fill', before: 'Gosto', after: 'pastéis de nata.', nl: 'Ik houd van pastéis de nata.', options: ['de', 'em', 'com'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'ik heet', target: 'chamo-me' },
                { nl: 'pardon', target: 'desculpe' },
                { nl: 'ik houd van', target: 'gosto de' },
                { nl: 'ook', target: 'também' },
              ],
            },
            { type: 'wordbank', nl: 'Hallo, ik heet Ana.', target: 'Olá, chamo-me Ana.', distractors: ['gosto', 'sou', 'também'] },
            { type: 'type', nl: 'ook', target: 'também', accept: ['tambem', 'Também', 'Tambem'] },
            { type: 'wordbank', nl: 'Pardon, hoe laat is het?', target: 'Desculpe, que horas são?', distractors: ['quanto', 'custa', 'é'] },
          ],
        },
        {
          id: 'pt-u9-l2',
          title: 'Vragen stellen',
          exercises: [
            { type: 'new', word: 'como', nl: 'hoe', example: 'Como está?', exampleNl: 'Hoe gaat het met u?' },
            { type: 'new', word: 'quando', nl: 'wanneer', example: 'Quando é o comboio para o Porto?', exampleNl: 'Wanneer gaat de trein naar Porto?' },
            { type: 'new', word: 'hoje', nl: 'vandaag', example: 'Hoje trabalho em casa.', exampleNl: 'Vandaag werk ik thuis.' },
            { type: 'new', word: 'amanhã', nl: 'morgen', example: 'Até amanhã!', exampleNl: 'Tot morgen!' },
            { type: 'select', prompt: 'wanneer', options: ['como', 'quando', 'onde'], correct: 1 },
            { type: 'select', prompt: 'hoje', speak: 'hoje', options: ['morgen', 'vandaag', 'vanavond'], correct: 1 },
            { type: 'listen', target: 'até amanhã', options: ['até amanhã', 'até hoje', 'boa noite'], correct: 0 },
            { type: 'fill', before: 'Quando', after: 'o comboio para Lisboa?', nl: 'Wanneer gaat de trein naar Lissabon?', options: ['é', 'são', 'está'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'hoe', target: 'como' },
                { nl: 'wanneer', target: 'quando' },
                { nl: 'vandaag', target: 'hoje' },
                { nl: 'morgen', target: 'amanhã' },
              ],
            },
            { type: 'wordbank', nl: 'Wanneer gaat de bus naar Belém?', target: 'Quando é o autocarro para Belém?', distractors: ['como', 'hoje', 'comboio'] },
            { type: 'type', nl: 'vandaag', target: 'hoje', accept: ['Hoje'] },
            { type: 'type', nl: 'Tot morgen!', target: 'Até amanhã!', accept: ['até amanhã', 'ate amanha', 'Ate amanha!', 'até amanhã!'] },
          ],
        },
        {
          id: 'pt-u9-l3',
          title: 'Herhaling: gesprekken',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'pardon', target: 'desculpe' },
                { nl: 'ook', target: 'também' },
                { nl: 'vandaag', target: 'hoje' },
                { nl: 'morgen', target: 'amanhã' },
                { nl: 'wanneer', target: 'quando' },
              ],
            },
            { type: 'type', nl: 'Ik heet Pedro.', target: 'Chamo-me Pedro.', accept: ['chamo-me pedro', 'Chamo me Pedro.', 'Eu chamo-me Pedro.', 'eu chamo-me Pedro'] },
            { type: 'wordbank', nl: 'Pardon, hoeveel kost het fruit?', target: 'Desculpe, quanto custa a fruta?', distractors: ['que', 'horas', 'mercado'] },
            { type: 'listen', target: 'hoje trabalho em casa', options: ['hoje trabalho em casa', 'amanhã trabalho em casa', 'hoje trabalho na escola'], correct: 0 },
            { type: 'type', nl: 'Ik houd van koffie.', target: 'Gosto de café.', accept: ['gosto de café', 'Gosto de cafe.', 'gosto de cafe', 'Eu gosto de café.'] },
            { type: 'fill', before: 'Eu também', after: 'de vinho.', nl: 'Ik houd ook van wijn.', options: ['gosto', 'gosta', 'gostas'], correct: 0 },
            { type: 'wordbank', nl: 'Vandaag wil ik fruit van de markt.', target: 'Hoje quero fruta do mercado.', distractors: ['amanhã', 'loja', 'custa'] },
            { type: 'type', nl: 'wanneer', target: 'quando', accept: ['Quando'] },
            { type: 'select', prompt: 'Desculpe, onde é a escola?', speak: 'Desculpe, onde é a escola?', options: ['Pardon, waar is de school?', 'Pardon, waar is de winkel?', 'Pardon, wanneer is de school?'], correct: 0 },
            { type: 'wordbank', nl: 'Morgen werk ik op school.', target: 'Amanhã trabalho na escola.', distractors: ['hoje', 'em', 'casa'] },
            { type: 'type', nl: 'Pardon, hoe laat is het?', target: 'Desculpe, que horas são?', accept: ['desculpe, que horas são', 'Desculpe que horas sao?', 'desculpe que horas sao'] },
            { type: 'fill', before: 'Gosto', after: 'aprender português.', nl: 'Ik houd ervan om Portugees te leren.', options: ['de', 'a', 'em'], correct: 0 },
            { type: 'wordbank', nl: 'Tot morgen, en dank je wel!', target: 'Até amanhã, e muito obrigado!', distractors: ['hoje', 'adeus', 'boa'] },
          ],
        },
      ],
    },
  ],
}
