import type { Section } from '../../types'

export const section: Section = {
  title: 'Sectie 3 · Op weg naar A2',
  cefr: 'A2',
  units: [
    {
      id: 'pt-u10',
      title: 'Reizen & vervoer',
      icon: '✈️',
      lessons: [
        {
          id: 'pt-u10-l1',
          title: 'Op reis',
          exercises: [
            { type: 'new', word: 'a viagem', nl: 'de reis', example: 'A viagem para o Porto é longa.', exampleNl: 'De reis naar Porto is lang.' },
            { type: 'new', word: 'o avião', nl: 'het vliegtuig', example: 'O avião parte às dez.', exampleNl: 'Het vliegtuig vertrekt om tien uur.' },
            { type: 'new', word: 'o aeroporto', nl: 'het vliegveld', example: 'Onde é o aeroporto?', exampleNl: 'Waar is het vliegveld?' },
            { type: 'new', word: 'a mala', nl: 'de koffer', example: 'A minha mala está no comboio.', exampleNl: 'Mijn koffer is in de trein.' },
            { type: 'select', prompt: 'het vliegtuig', options: ['o aeroporto', 'o avião', 'a mala'], correct: 1 },
            { type: 'select', prompt: 'a viagem', speak: 'a viagem', options: ['de reis', 'de koffer', 'het vliegveld'], correct: 0 },
            { type: 'listen', target: 'o avião', options: ['o aeroporto', 'o avião', 'a viagem'], correct: 1 },
            { type: 'fill', before: 'O avião parte', after: 'dez.', nl: 'Het vliegtuig vertrekt om tien uur.', options: ['às', 'a', 'no'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'de reis', target: 'a viagem' },
                { nl: 'het vliegtuig', target: 'o avião' },
                { nl: 'het vliegveld', target: 'o aeroporto' },
                { nl: 'de koffer', target: 'a mala' },
              ],
            },
            { type: 'wordbank', nl: 'Mijn koffer is in de trein.', target: 'A minha mala está no comboio.', distractors: ['avião', 'o', 'aeroporto'] },
            { type: 'type', nl: 'het vliegveld', target: 'o aeroporto', accept: ['aeroporto', 'O aeroporto'] },
            { type: 'select', prompt: 'de koffer', options: ['a viagem', 'o bilhete', 'a mala'], correct: 2 },
          ],
        },
        {
          id: 'pt-u10-l2',
          title: 'In het hotel',
          exercises: [
            { type: 'new', word: 'o hotel', nl: 'het hotel', example: 'O hotel é perto da estação.', exampleNl: 'Het hotel is dicht bij het station.' },
            { type: 'new', word: 'o quarto', nl: 'de kamer', example: 'Quero um quarto para duas noites.', exampleNl: 'Ik wil een kamer voor twee nachten.' },
            { type: 'new', word: 'a praia', nl: 'het strand', example: 'A praia de Cascais é bonita.', exampleNl: 'Het strand van Cascais is mooi.' },
            { type: 'new', word: 'a chave', nl: 'de sleutel', example: 'A chave do quarto, se faz favor.', exampleNl: 'De sleutel van de kamer, alsjeblieft.' },
            { type: 'select', prompt: 'de kamer', options: ['a chave', 'o quarto', 'o hotel'], correct: 1 },
            { type: 'select', prompt: 'a praia', speak: 'a praia', options: ['het strand', 'de sleutel', 'de kamer'], correct: 0 },
            { type: 'listen', target: 'a chave do quarto', options: ['a chave do hotel', 'o quarto do hotel', 'a chave do quarto'], correct: 2 },
            { type: 'fill', before: 'O hotel é', after: 'da estação.', nl: 'Het hotel is dicht bij het station.', options: ['perto', 'longe', 'dentro'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'het hotel', target: 'o hotel' },
                { nl: 'de kamer', target: 'o quarto' },
                { nl: 'het strand', target: 'a praia' },
                { nl: 'de sleutel', target: 'a chave' },
              ],
            },
            { type: 'wordbank', nl: 'Ik wil een kamer voor twee nachten.', target: 'Quero um quarto para duas noites.', distractors: ['chave', 'a', 'praia'] },
            { type: 'type', nl: 'de sleutel', target: 'a chave', accept: ['chave', 'A chave'] },
            { type: 'fill', before: 'A mala está', after: 'quarto.', nl: 'De koffer is in de kamer.', options: ['no', 'na', 'ao'], correct: 0 },
          ],
        },
        {
          id: 'pt-u10-l3',
          title: 'Herhaling: op reis',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'de reis', target: 'a viagem' },
                { nl: 'het vliegtuig', target: 'o avião' },
                { nl: 'de koffer', target: 'a mala' },
                { nl: 'de trein', target: 'o comboio' },
                { nl: 'het kaartje', target: 'o bilhete' },
              ],
            },
            { type: 'type', nl: 'de reis', target: 'a viagem', accept: ['viagem', 'A viagem'] },
            { type: 'wordbank', nl: 'Het vliegtuig naar Lissabon vertrekt om tien uur.', target: 'O avião para Lisboa parte às dez.', distractors: ['comboio', 'na', 'mala'] },
            { type: 'listen', target: 'a mala está no quarto', options: ['a mala está no comboio', 'a mala está no quarto', 'a chave está no quarto'], correct: 1 },
            { type: 'type', nl: 'Waar is het vliegveld?', target: 'Onde é o aeroporto?', accept: ['onde é o aeroporto', 'Onde e o aeroporto?', 'onde e o aeroporto'] },
            { type: 'fill', before: 'Quero um bilhete', after: 'o Porto.', nl: 'Ik wil een kaartje naar Porto.', options: ['para', 'de', 'em'], correct: 0 },
            { type: 'wordbank', nl: 'Het hotel is dicht bij het strand.', target: 'O hotel é perto da praia.', distractors: ['longe', 'na', 'estação'] },
            { type: 'select', prompt: 'o quarto', speak: 'o quarto', options: ['de sleutel', 'de kamer', 'het strand'], correct: 1 },
            { type: 'type', nl: 'de koffer', target: 'a mala', accept: ['mala', 'A mala'] },
            { type: 'fill', before: 'A viagem', after: 'comboio é longa.', nl: 'De reis met de trein is lang.', options: ['de', 'com', 'para'], correct: 0 },
            { type: 'wordbank', nl: 'De sleutel van de kamer, alsjeblieft.', target: 'A chave do quarto, se faz favor.', distractors: ['da', 'hotel', 'bilhete'] },
            { type: 'type', nl: 'Ik wil een kamer, alsjeblieft.', target: 'Quero um quarto, por favor.', accept: ['quero um quarto por favor', 'Quero um quarto, se faz favor.', 'quero um quarto, por favor'] },
          ],
        },
      ],
    },
    {
      id: 'pt-u11',
      title: 'Gezondheid & lichaam',
      icon: '🌿',
      lessons: [
        {
          id: 'pt-u11-l1',
          title: 'Hoe voel je je?',
          exercises: [
            { type: 'new', word: 'doente', nl: 'ziek', example: 'Hoje estou doente.', exampleNl: 'Vandaag ben ik ziek.' },
            { type: 'new', word: 'o médico', nl: 'de dokter', example: 'Preciso de um médico.', exampleNl: 'Ik heb een dokter nodig.' },
            { type: 'new', word: 'a cabeça', nl: 'het hoofd', example: 'Dói-me a cabeça.', exampleNl: 'Ik heb hoofdpijn.' },
            { type: 'new', word: 'a barriga', nl: 'de buik', example: 'Dói-me a barriga.', exampleNl: 'Ik heb buikpijn.' },
            { type: 'select', prompt: 'ziek', options: ['o médico', 'doente', 'a cabeça'], correct: 1 },
            { type: 'select', prompt: 'a cabeça', speak: 'a cabeça', options: ['de buik', 'het hoofd', 'de dokter'], correct: 1 },
            { type: 'listen', target: 'dói-me a cabeça', options: ['dói-me a barriga', 'dói-me a cabeça', 'estou doente'], correct: 1 },
            { type: 'fill', before: 'Dói-me', after: 'barriga.', nl: 'Ik heb buikpijn.', options: ['a', 'o', 'à'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'ziek', target: 'doente' },
                { nl: 'de dokter', target: 'o médico' },
                { nl: 'het hoofd', target: 'a cabeça' },
                { nl: 'de buik', target: 'a barriga' },
              ],
            },
            { type: 'wordbank', nl: 'Vandaag ben ik ziek.', target: 'Hoje estou doente.', distractors: ['sou', 'médico', 'cabeça'] },
            { type: 'type', nl: 'de dokter', target: 'o médico', accept: ['médico', 'medico', 'o medico', 'O médico'] },
            { type: 'fill', before: 'Eu', after: 'doente.', nl: 'Ik ben ziek. (nu, tijdelijk)', options: ['estou', 'sou', 'é'], correct: 0 },
          ],
        },
        {
          id: 'pt-u11-l2',
          title: 'Bij de apotheek',
          exercises: [
            { type: 'new', word: 'a farmácia', nl: 'de apotheek', example: 'A farmácia é à direita da estação.', exampleNl: 'De apotheek is rechts van het station.' },
            { type: 'new', word: 'o remédio', nl: 'het medicijn', example: 'Preciso de um remédio.', exampleNl: 'Ik heb een medicijn nodig.' },
            { type: 'new', word: 'cansado', nl: 'moe', example: 'Estou muito cansado.', exampleNl: 'Ik ben erg moe.' },
            { type: 'new', word: 'dormir', nl: 'slapen', example: 'Preciso de dormir mais.', exampleNl: 'Ik moet meer slapen.' },
            { type: 'select', prompt: 'moe', options: ['doente', 'cansado', 'quente'], correct: 1 },
            { type: 'select', prompt: 'a farmácia', speak: 'a farmácia', options: ['de apotheek', 'de dokter', 'het medicijn'], correct: 0 },
            { type: 'listen', target: 'preciso de um remédio', options: ['preciso de um médico', 'quero um remédio', 'preciso de um remédio'], correct: 2 },
            { type: 'fill', before: 'Preciso', after: 'dormir mais.', nl: 'Ik moet meer slapen.', options: ['de', 'a', 'para'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'de apotheek', target: 'a farmácia' },
                { nl: 'het medicijn', target: 'o remédio' },
                { nl: 'moe', target: 'cansado' },
                { nl: 'slapen', target: 'dormir' },
              ],
            },
            { type: 'wordbank', nl: 'De apotheek is rechts.', target: 'A farmácia é à direita.', distractors: ['esquerda', 'o', 'remédio'] },
            { type: 'type', nl: 'het medicijn', target: 'o remédio', accept: ['remédio', 'remedio', 'o remedio', 'O remédio'] },
            { type: 'fill', before: 'A minha mãe está', after: '.', nl: 'Mijn moeder is moe.', options: ['cansada', 'cansado', 'doente'], correct: 0 },
          ],
        },
        {
          id: 'pt-u11-l3',
          title: 'Herhaling: gezondheid',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'ziek', target: 'doente' },
                { nl: 'de dokter', target: 'o médico' },
                { nl: 'de apotheek', target: 'a farmácia' },
                { nl: 'het medicijn', target: 'o remédio' },
                { nl: 'slapen', target: 'dormir' },
              ],
            },
            { type: 'type', nl: 'Ik heb hoofdpijn.', target: 'Dói-me a cabeça.', accept: ['dói-me a cabeça', 'Doi-me a cabeca.', 'doi-me a cabeca'] },
            { type: 'wordbank', nl: 'Ik ben ziek en ik heb een dokter nodig.', target: 'Estou doente e preciso de um médico.', distractors: ['sou', 'remédio', 'farmácia'] },
            { type: 'listen', target: 'estou muito cansado', options: ['estou muito doente', 'estou muito cansado', 'preciso de dormir'], correct: 1 },
            { type: 'type', nl: 'moe', target: 'cansado', accept: ['Cansado', 'cansada', 'Cansada'] },
            { type: 'fill', before: 'Dói-me a', after: '.', nl: 'Ik heb buikpijn.', options: ['barriga', 'cabeça', 'farmácia'], correct: 0 },
            { type: 'wordbank', nl: 'Waar is de apotheek?', target: 'Onde é a farmácia?', distractors: ['médico', 'o', 'remédio'] },
            { type: 'select', prompt: 'o remédio', speak: 'o remédio', options: ['de dokter', 'het medicijn', 'de apotheek'], correct: 1 },
            { type: 'type', nl: 'slapen', target: 'dormir', accept: ['Dormir'] },
            { type: 'fill', before: 'O meu pai', after: 'doente.', nl: 'Mijn vader is ziek.', options: ['está', 'é', 'sou'], correct: 0 },
            { type: 'wordbank', nl: 'Ik ben moe en ik moet slapen.', target: 'Estou cansado e preciso de dormir.', distractors: ['doente', 'remédio', 'sou'] },
            { type: 'type', nl: 'Ik heb een medicijn nodig.', target: 'Preciso de um remédio.', accept: ['preciso de um remédio', 'Preciso de um remedio.', 'preciso de um remedio'] },
          ],
        },
      ],
    },
    {
      id: 'pt-u12',
      title: 'Weer & seizoenen',
      icon: '🌦️',
      lessons: [
        {
          id: 'pt-u12-l1',
          title: 'Wat voor weer is het?',
          exercises: [
            { type: 'new', word: 'o tempo', nl: 'het weer', example: 'O tempo hoje está bom.', exampleNl: 'Het weer is vandaag goed.' },
            { type: 'new', word: 'o sol', nl: 'de zon', example: 'Está sol em Lisboa.', exampleNl: 'Het is zonnig in Lissabon.' },
            { type: 'new', word: 'a chuva', nl: 'de regen', example: 'Não gosto de chuva.', exampleNl: 'Ik houd niet van regen.' },
            { type: 'new', word: 'o vento', nl: 'de wind', example: 'Hoje está muito vento.', exampleNl: 'Het is vandaag erg winderig.' },
            { type: 'select', prompt: 'de zon', options: ['o vento', 'a chuva', 'o sol'], correct: 2 },
            { type: 'select', prompt: 'a chuva', speak: 'a chuva', options: ['de regen', 'de wind', 'de zon'], correct: 0 },
            { type: 'listen', target: 'está muito vento', options: ['está muito sol', 'está muito vento', 'está muito frio'], correct: 1 },
            { type: 'fill', before: 'O tempo hoje', after: 'bom.', nl: 'Het weer is vandaag goed.', options: ['está', 'são', 'sou'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'het weer', target: 'o tempo' },
                { nl: 'de zon', target: 'o sol' },
                { nl: 'de regen', target: 'a chuva' },
                { nl: 'de wind', target: 'o vento' },
              ],
            },
            { type: 'wordbank', nl: 'Het is zonnig in Lissabon.', target: 'Está sol em Lisboa.', distractors: ['chuva', 'o', 'vento'] },
            { type: 'type', nl: 'de regen', target: 'a chuva', accept: ['chuva', 'A chuva'] },
            { type: 'fill', before: 'Não gosto', after: 'chuva.', nl: 'Ik houd niet van regen.', options: ['de', 'em', 'para'], correct: 0 },
          ],
        },
        {
          id: 'pt-u12-l2',
          title: 'De seizoenen',
          exercises: [
            { type: 'new', word: 'o verão', nl: 'de zomer', example: 'No verão vamos à praia.', exampleNl: 'In de zomer gaan we naar het strand.' },
            { type: 'new', word: 'o inverno', nl: 'de winter', example: 'Não gosto do inverno.', exampleNl: 'Ik houd niet van de winter.' },
            { type: 'new', word: 'quente', nl: 'warm', example: 'Hoje está muito quente.', exampleNl: 'Het is vandaag erg warm.' },
            { type: 'new', word: 'frio', nl: 'koud', example: 'Está frio em dezembro.', exampleNl: 'Het is koud in december.' },
            { type: 'select', prompt: 'warm', options: ['frio', 'quente', 'cansado'], correct: 1 },
            { type: 'select', prompt: 'o inverno', speak: 'o inverno', options: ['de zomer', 'de winter', 'de wind'], correct: 1 },
            { type: 'listen', target: 'no verão está quente', options: ['no inverno está frio', 'no verão está frio', 'no verão está quente'], correct: 2 },
            { type: 'fill', before: 'No inverno', after: 'frio.', nl: 'In de winter is het koud.', options: ['está', 'são', 'tenho'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'de zomer', target: 'o verão' },
                { nl: 'de winter', target: 'o inverno' },
                { nl: 'warm', target: 'quente' },
                { nl: 'koud', target: 'frio' },
              ],
            },
            { type: 'wordbank', nl: 'In de zomer gaan we naar het strand.', target: 'No verão vamos à praia.', distractors: ['inverno', 'na', 'frio'] },
            { type: 'type', nl: 'koud', target: 'frio', accept: ['Frio'] },
            { type: 'fill', before: 'Vamos', after: 'praia.', nl: 'We gaan naar het strand.', options: ['à', 'ao', 'no'], correct: 0 },
          ],
        },
        {
          id: 'pt-u12-l3',
          title: 'Herhaling: het weer',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'het weer', target: 'o tempo' },
                { nl: 'de zon', target: 'o sol' },
                { nl: 'de regen', target: 'a chuva' },
                { nl: 'de zomer', target: 'o verão' },
                { nl: 'koud', target: 'frio' },
              ],
            },
            { type: 'type', nl: 'de zomer', target: 'o verão', accept: ['verão', 'verao', 'o verao', 'O verão'] },
            { type: 'wordbank', nl: 'Het weer in Portugal is goed.', target: 'O tempo em Portugal é bom.', distractors: ['chuva', 'no', 'vento'] },
            { type: 'listen', target: 'está sol e está quente', options: ['está frio e está vento', 'está sol e está quente', 'está sol e está frio'], correct: 1 },
            { type: 'type', nl: 'Het is koud vandaag.', target: 'Hoje está frio.', accept: ['hoje está frio', 'Está frio hoje.', 'esta frio hoje', 'hoje esta frio'] },
            { type: 'fill', before: 'No verão', after: 'muito quente.', nl: 'In de zomer is het erg warm.', options: ['está', 'são', 'sou'], correct: 0 },
            { type: 'wordbank', nl: 'Ik houd niet van regen en wind.', target: 'Não gosto de chuva e vento.', distractors: ['sol', 'da', 'quente'] },
            { type: 'select', prompt: 'o vento', speak: 'o vento', options: ['de wind', 'de regen', 'de zon'], correct: 0 },
            { type: 'type', nl: 'de winter', target: 'o inverno', accept: ['inverno', 'O inverno'] },
            { type: 'fill', before: 'Está sol', after: 'Lisboa.', nl: 'Het is zonnig in Lissabon.', options: ['em', 'a', 'de'], correct: 0 },
            { type: 'wordbank', nl: 'In de winter is het koud in Lissabon.', target: 'No inverno está frio em Lisboa.', distractors: ['verão', 'quente', 'no'] },
            { type: 'type', nl: 'het weer', target: 'o tempo', accept: ['tempo', 'O tempo'] },
          ],
        },
      ],
    },
    {
      id: 'pt-u13',
      title: 'Uitgaan & cultuur',
      icon: '🎭',
      lessons: [
        {
          id: 'pt-u13-l1',
          title: 'Muziek en fado',
          exercises: [
            { type: 'new', word: 'a música', nl: 'de muziek', example: 'Gosto de música portuguesa.', exampleNl: 'Ik houd van Portugese muziek.' },
            { type: 'new', word: 'o fado', nl: 'de fado', example: 'O fado é a música de Lisboa.', exampleNl: 'De fado is de muziek van Lissabon.' },
            { type: 'new', word: 'cantar', nl: 'zingen', example: 'A Amália canta muito bem.', exampleNl: 'Amália zingt heel goed.' },
            { type: 'new', word: 'o concerto', nl: 'het concert', example: 'O concerto começa às nove.', exampleNl: 'Het concert begint om negen uur.' },
            { type: 'select', prompt: 'de muziek', options: ['o fado', 'a música', 'o concerto'], correct: 1 },
            { type: 'select', prompt: 'o concerto', speak: 'o concerto', options: ['het concert', 'de muziek', 'het lied'], correct: 0 },
            { type: 'listen', target: 'gosto de fado', options: ['gosto de fado', 'gosto de música', 'canto fado'], correct: 0 },
            { type: 'fill', before: 'O concerto começa', after: 'nove.', nl: 'Het concert begint om negen uur.', options: ['às', 'a', 'em'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'de muziek', target: 'a música' },
                { nl: 'de fado', target: 'o fado' },
                { nl: 'zingen', target: 'cantar' },
                { nl: 'het concert', target: 'o concerto' },
              ],
            },
            { type: 'wordbank', nl: 'Ik houd van Portugese muziek.', target: 'Gosto de música portuguesa.', distractors: ['fado', 'a', 'concerto'] },
            { type: 'type', nl: 'zingen', target: 'cantar', accept: ['Cantar'] },
            { type: 'fill', before: 'A minha irmã canta', after: 'bem.', nl: 'Mijn zus zingt heel goed.', options: ['muito', 'muita', 'mais'], correct: 0 },
          ],
        },
        {
          id: 'pt-u13-l2',
          title: 'Een avondje uit',
          exercises: [
            { type: 'new', word: 'o cinema', nl: 'de bioscoop', example: 'Vamos ao cinema hoje à noite?', exampleNl: 'Gaan we vanavond naar de bioscoop?' },
            { type: 'new', word: 'o filme', nl: 'de film', example: 'O filme começa às oito.', exampleNl: 'De film begint om acht uur.' },
            { type: 'new', word: 'o restaurante', nl: 'het restaurant', example: 'O restaurante é perto do cinema.', exampleNl: 'Het restaurant is dicht bij de bioscoop.' },
            { type: 'new', word: 'dançar', nl: 'dansen', example: 'Gosto de dançar com os meus amigos.', exampleNl: 'Ik dans graag met mijn vrienden.' },
            { type: 'select', prompt: 'de film', options: ['o cinema', 'o filme', 'o fado'], correct: 1 },
            { type: 'select', prompt: 'o restaurante', speak: 'o restaurante', options: ['de bioscoop', 'het restaurant', 'het concert'], correct: 1 },
            { type: 'listen', target: 'vamos ao cinema', options: ['vamos ao concerto', 'vamos ao restaurante', 'vamos ao cinema'], correct: 2 },
            { type: 'fill', before: 'Vamos', after: 'cinema?', nl: 'Gaan we naar de bioscoop?', options: ['ao', 'à', 'no'], correct: 0 },
            {
              type: 'match',
              pairs: [
                { nl: 'de bioscoop', target: 'o cinema' },
                { nl: 'de film', target: 'o filme' },
                { nl: 'het restaurant', target: 'o restaurante' },
                { nl: 'dansen', target: 'dançar' },
              ],
            },
            { type: 'wordbank', nl: 'De film begint om acht uur.', target: 'O filme começa às oito.', distractors: ['cinema', 'a', 'nove'] },
            { type: 'type', nl: 'dansen', target: 'dançar', accept: ['dancar', 'Dançar'] },
            { type: 'fill', before: 'O restaurante é perto', after: 'cinema.', nl: 'Het restaurant is dicht bij de bioscoop.', options: ['do', 'da', 'de'], correct: 0 },
          ],
        },
        {
          id: 'pt-u13-l3',
          title: 'Herhaling: uitgaan',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'de muziek', target: 'a música' },
                { nl: 'zingen', target: 'cantar' },
                { nl: 'de bioscoop', target: 'o cinema' },
                { nl: 'de film', target: 'o filme' },
                { nl: 'het restaurant', target: 'o restaurante' },
              ],
            },
            { type: 'type', nl: 'de bioscoop', target: 'o cinema', accept: ['cinema', 'O cinema'] },
            { type: 'wordbank', nl: 'Gaan we vanavond naar de bioscoop?', target: 'Vamos ao cinema hoje à noite?', distractors: ['filme', 'na', 'concerto'] },
            { type: 'listen', target: 'o concerto de fado começa às nove', options: ['o filme começa às nove', 'o concerto de fado começa às nove', 'o concerto de fado começa às oito'], correct: 1 },
            { type: 'type', nl: 'Ik houd van fado.', target: 'Gosto de fado.', accept: ['gosto de fado', 'Gosto de fado', 'gosto de fado.'] },
            { type: 'fill', before: 'Gosto de dançar', after: 'os meus amigos.', nl: 'Ik dans graag met mijn vrienden.', options: ['com', 'de', 'para'], correct: 0 },
            { type: 'wordbank', nl: 'Het restaurant is dicht bij het station.', target: 'O restaurante é perto da estação.', distractors: ['do', 'cinema', 'longe'] },
            { type: 'select', prompt: 'o filme', speak: 'o filme', options: ['de bioscoop', 'de muziek', 'de film'], correct: 2 },
            { type: 'type', nl: 'het concert', target: 'o concerto', accept: ['concerto', 'O concerto'] },
            { type: 'fill', before: 'A mulher canta fado', after: 'restaurante.', nl: 'De vrouw zingt fado in het restaurant.', options: ['no', 'na', 'ao'], correct: 0 },
            { type: 'wordbank', nl: 'Ik houd van muziek en dansen.', target: 'Gosto de música e de dançar.', distractors: ['fado', 'com', 'a'] },
            { type: 'type', nl: 'Gaan we naar het restaurant?', target: 'Vamos ao restaurante?', accept: ['vamos ao restaurante', 'Vamos ao restaurante', 'vamos ao restaurante?'] },
          ],
        },
      ],
    },
    {
      id: 'pt-u14',
      title: 'De grote herhaling',
      icon: '🏆',
      lessons: [
        {
          id: 'pt-u14-l1',
          title: 'Alles door elkaar',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'de reis', target: 'a viagem' },
                { nl: 'de dokter', target: 'o médico' },
                { nl: 'de zomer', target: 'o verão' },
                { nl: 'de film', target: 'o filme' },
                { nl: 'de sleutel', target: 'a chave' },
              ],
            },
            { type: 'type', nl: 'Ik wil een kamer voor twee nachten.', target: 'Quero um quarto para duas noites.', accept: ['quero um quarto para duas noites', 'Quero um quarto para duas noites', 'quero um quarto para duas noites.'] },
            { type: 'select', prompt: 'Está muito frio hoje.', speak: 'Está muito frio hoje.', options: ['Het is vandaag erg koud.', 'Het is vandaag erg warm.', 'Het is vandaag erg winderig.'], correct: 0 },
            { type: 'wordbank', nl: 'In de zomer gaan we naar het strand van Cascais.', target: 'No verão vamos à praia de Cascais.', distractors: ['inverno', 'na', 'chuva'] },
            { type: 'listen', target: 'dói-me a cabeça e estou cansado', options: ['dói-me a cabeça e estou cansado', 'dói-me a barriga e estou doente', 'dói-me a cabeça e estou doente'], correct: 0 },
            { type: 'fill', before: 'O avião', after: 'às dez.', nl: 'Het vliegtuig vertrekt om tien uur.', options: ['parte', 'partem', 'parto'], correct: 0 },
            { type: 'type', nl: 'Het concert begint om negen uur.', target: 'O concerto começa às nove.', accept: ['o concerto começa às nove', 'O concerto comeca as nove.', 'o concerto comeca as nove'] },
            { type: 'wordbank', nl: 'Ik ben ziek en het is koud.', target: 'Estou doente e está frio.', distractors: ['sou', 'quente', 'cansado'] },
            { type: 'select', prompt: 'het medicijn', options: ['a farmácia', 'o remédio', 'o médico'], correct: 1 },
            { type: 'fill', before: 'Vamos', after: 'restaurante hoje à noite.', nl: 'We gaan vanavond naar het restaurant.', options: ['ao', 'à', 'em'], correct: 0 },
            { type: 'type', nl: 'de regen', target: 'a chuva', accept: ['chuva', 'A chuva'] },
            { type: 'wordbank', nl: 'De film begint om acht uur in de bioscoop.', target: 'O filme começa às oito no cinema.', distractors: ['concerto', 'na', 'nove'] },
          ],
        },
        {
          id: 'pt-u14-l2',
          title: 'Terug naar het begin',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'de koffie', target: 'o café' },
                { nl: 'de rekening', target: 'a conta' },
                { nl: 'de trein', target: 'o comboio' },
                { nl: 'de zus', target: 'a irmã' },
                { nl: 'het brood', target: 'o pão' },
              ],
            },
            { type: 'type', nl: 'Een koffie en een pastel de nata, alsjeblieft.', target: 'Um café e um pastel de nata, por favor.', accept: ['um café e um pastel de nata por favor', 'Um cafe e um pastel de nata, por favor.', 'um café e um pastel de nata, se faz favor'] },
            { type: 'wordbank', nl: 'Ik wil een kaartje naar Lissabon.', target: 'Quero um bilhete para Lisboa.', distractors: ['mala', 'à', 'viagem'] },
            { type: 'select', prompt: 'a estação', speak: 'a estação', options: ['het station', 'het strand', 'de straat'], correct: 0 },
            { type: 'listen', target: 'onde é a farmácia', options: ['onde é a estação', 'onde é a farmácia', 'onde é a praia'], correct: 1 },
            { type: 'fill', before: 'A minha mãe', after: 'doente.', nl: 'Mijn moeder is ziek.', options: ['está', 'é', 'estou'], correct: 0 },
            { type: 'type', nl: 'De rekening, alsjeblieft.', target: 'A conta, por favor.', accept: ['a conta por favor', 'A conta, se faz favor.', 'a conta, se faz favor'] },
            { type: 'wordbank', nl: 'Mijn broer houdt van rode wijn.', target: 'O meu irmão gosta de vinho tinto.', distractors: ['irmã', 'a', 'leite'] },
            { type: 'select', prompt: 'de melk', options: ['o vinho', 'a água', 'o leite'], correct: 2 },
            { type: 'fill', before: 'O comboio para o Porto é', after: '.', nl: 'De trein naar Porto is snel.', options: ['rápido', 'rápida', 'lento'], correct: 0 },
            { type: 'type', nl: 'Waar is het station?', target: 'Onde é a estação?', accept: ['onde é a estação', 'Onde e a estacao?', 'onde e a estacao'] },
            { type: 'wordbank', nl: 'Hallo, alles goed? Ik ben moe.', target: 'Olá, tudo bem? Estou cansado.', distractors: ['sou', 'doente', 'adeus'] },
          ],
        },
        {
          id: 'pt-u14-l3',
          title: 'De grote finale',
          exercises: [
            {
              type: 'match',
              pairs: [
                { nl: 'het weer', target: 'o tempo' },
                { nl: 'de koffer', target: 'a mala' },
                { nl: 'het medicijn', target: 'o remédio' },
                { nl: 'zingen', target: 'cantar' },
                { nl: 'de kamer', target: 'o quarto' },
              ],
            },
            { type: 'type', nl: 'Ik dans graag.', target: 'Gosto de dançar.', accept: ['gosto de dançar', 'Gosto de dancar.', 'gosto de dancar'] },
            { type: 'wordbank', nl: 'De reis is lang en ik ben moe.', target: 'A viagem é longa e estou cansado.', distractors: ['sou', 'curta', 'doente'] },
            { type: 'listen', target: 'quero um quarto perto da praia', options: ['quero um quarto perto da estação', 'quero uma mala perto da praia', 'quero um quarto perto da praia'], correct: 2 },
            { type: 'fill', before: 'No inverno não', after: 'à praia.', nl: 'In de winter gaan we niet naar het strand.', options: ['vamos', 'vou', 'vais'], correct: 0 },
            { type: 'type', nl: 'Het is zonnig en warm.', target: 'Está sol e está quente.', accept: ['esta sol e esta quente', 'Está sol e quente.', 'está sol e quente', 'esta sol e quente.'] },
            { type: 'wordbank', nl: 'Vanavond gaan we naar een fadoconcert.', target: 'Hoje à noite vamos a um concerto de fado.', distractors: ['ao', 'cinema', 'música'] },
            { type: 'select', prompt: 'Preciso de dormir.', speak: 'Preciso de dormir.', options: ['Ik moet slapen.', 'Ik wil dansen.', 'Ik ben moe.'], correct: 0 },
            { type: 'type', nl: 'de apotheek', target: 'a farmácia', accept: ['farmácia', 'farmacia', 'a farmacia', 'A farmácia'] },
            { type: 'fill', before: 'A chave', after: 'quarto está na mala.', nl: 'De sleutel van de kamer zit in de koffer.', options: ['do', 'da', 'de'], correct: 0 },
            { type: 'wordbank', nl: 'Goedemorgen! Het weer is vandaag goed.', target: 'Bom dia! O tempo hoje está bom.', distractors: ['olá', 'chuva', 'frio'] },
            { type: 'type', nl: 'Tot ziens, tot morgen!', target: 'Adeus, até amanhã!', accept: ['adeus, até amanhã', 'Adeus, ate amanha!', 'adeus até amanhã'] },
          ],
        },
      ],
    },
  ],
}
