import type { Course } from '../../types'

export const course: Course = {
  id: 'pt',
  name: 'Portugees',
  flag: '🇵🇹',
  tagline: 'Van Lissabon tot Rio',
  ttsLang: 'pt-PT',
  sections: [
    {
      title: 'Sectie 1 · Eerste stappen',
      cefr: 'A1',
      units: [
        {
          id: 'pt-u1',
          title: 'Begroetingen & basis',
          icon: '👋',
          lessons: [
            {
              id: 'pt-u1-l1',
              title: 'Hallo en tot ziens',
              exercises: [
                { type: 'new', word: 'olá', nl: 'hallo', example: 'Olá, tudo bem?', exampleNl: 'Hallo, alles goed?' },
                { type: 'new', word: 'bom dia', nl: 'goedemorgen', example: 'Bom dia, senhor Silva!', exampleNl: 'Goedemorgen, meneer Silva!' },
                { type: 'new', word: 'adeus', nl: 'tot ziens', example: 'Adeus, até amanhã!', exampleNl: 'Tot ziens, tot morgen!' },
                { type: 'new', word: 'obrigado', nl: 'dank je', example: 'Muito obrigado!', exampleNl: 'Dank je wel!' },
                { type: 'select', prompt: 'hallo', options: ['adeus', 'olá', 'bom dia'], correct: 1 },
                { type: 'select', prompt: 'bom dia', speak: 'bom dia', options: ['goedemorgen', 'tot ziens', 'dank je'], correct: 0 },
                { type: 'listen', target: 'olá', options: ['olá', 'adeus', 'obrigado'], correct: 0 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'hallo', target: 'olá' },
                    { nl: 'goedemorgen', target: 'bom dia' },
                    { nl: 'tot ziens', target: 'adeus' },
                    { nl: 'dank je', target: 'obrigado' },
                  ],
                },
                { type: 'select', prompt: 'tot ziens', options: ['obrigado', 'olá', 'adeus'], correct: 2 },
                { type: 'wordbank', nl: 'Hallo, goedemorgen!', target: 'Olá, bom dia!', distractors: ['adeus', 'obrigado', 'noite'] },
                { type: 'type', nl: 'dank je wel', target: 'obrigado', accept: ['Obrigado', 'obrigada', 'Obrigada', 'obrigado!'] },
                { type: 'listen', target: 'adeus', options: ['bom dia', 'adeus', 'olá'], correct: 1 },
              ],
            },
            {
              id: 'pt-u1-l2',
              title: 'Alles goed?',
              exercises: [
                { type: 'new', word: 'tudo bem?', nl: 'alles goed?', example: 'Olá, tudo bem?', exampleNl: 'Hallo, alles goed?' },
                { type: 'new', word: 'sim', nl: 'ja', example: 'Sim, tudo bem.', exampleNl: 'Ja, alles goed.' },
                { type: 'new', word: 'não', nl: 'nee', example: 'Não, obrigado.', exampleNl: 'Nee, dank je.' },
                { type: 'new', word: 'por favor', nl: 'alsjeblieft', example: 'Um café, por favor.', exampleNl: 'Een koffie, alsjeblieft.' },
                { type: 'select', prompt: 'ja', options: ['sim', 'não', 'por favor'], correct: 0 },
                { type: 'select', prompt: 'não', speak: 'não', options: ['ja', 'nee', 'alsjeblieft'], correct: 1 },
                { type: 'listen', target: 'tudo bem?', options: ['tudo bem?', 'bom dia', 'por favor'], correct: 0 },
                { type: 'fill', before: 'Muito', after: '!', nl: 'Dank je wel! (een vrouw zegt dit)', options: ['obrigada', 'obrigado', 'obrigadas'], correct: 0 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'ja', target: 'sim' },
                    { nl: 'nee', target: 'não' },
                    { nl: 'alsjeblieft', target: 'por favor' },
                    { nl: 'alles goed', target: 'tudo bem' },
                  ],
                },
                { type: 'wordbank', nl: 'Ja, alles goed, dank je.', target: 'Sim, tudo bem, obrigado.', distractors: ['não', 'adeus', 'favor'] },
                { type: 'type', nl: 'nee', target: 'não', accept: ['Não', 'nao', 'Nao'] },
                { type: 'select', prompt: 'alsjeblieft', options: ['tudo bem', 'obrigado', 'por favor'], correct: 2 },
                { type: 'type', nl: 'ja', target: 'sim', accept: ['Sim'] },
              ],
            },
            {
              id: 'pt-u1-l3',
              title: 'Herhaling: begroetingen',
              exercises: [
                { type: 'select', prompt: 'olá', speak: 'olá', options: ['tot ziens', 'hallo', 'dank je'], correct: 1 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'hallo', target: 'olá' },
                    { nl: 'tot ziens', target: 'adeus' },
                    { nl: 'ja', target: 'sim' },
                    { nl: 'nee', target: 'não' },
                    { nl: 'dank je', target: 'obrigado' },
                  ],
                },
                { type: 'type', nl: 'goedemorgen', target: 'bom dia', accept: ['Bom dia', 'bom dia!'] },
                { type: 'wordbank', nl: 'Goedemorgen, alles goed?', target: 'Bom dia, tudo bem?', distractors: ['olá', 'adeus', 'sim', 'não'] },
                { type: 'listen', target: 'por favor', options: ['por favor', 'tudo bem', 'bom dia'], correct: 0 },
                { type: 'type', nl: 'tot ziens', target: 'adeus', accept: ['Adeus', 'adeus!', 'até logo', 'Até logo'] },
                { type: 'fill', before: 'Olá, tudo', after: '?', nl: 'Hallo, alles goed?', options: ['bom', 'bem', 'boa'], correct: 1 },
                { type: 'wordbank', nl: 'Nee, dank je.', target: 'Não, obrigado.', distractors: ['sim', 'por', 'favor'] },
                { type: 'type', nl: 'alsjeblieft', target: 'por favor', accept: ['Por favor', 'se faz favor', 'Se faz favor'] },
                { type: 'select', prompt: 'alles goed?', options: ['por favor', 'tudo bem?', 'bom dia'], correct: 1 },
                { type: 'type', nl: 'Hallo, alles goed?', target: 'Olá, tudo bem?', accept: ['olá tudo bem', 'Olá tudo bem', 'Ola, tudo bem?', 'olá, tudo bem'] },
                { type: 'wordbank', nl: 'Goedemorgen, dank je wel!', target: 'Bom dia, muito obrigado!', distractors: ['adeus', 'não', 'favor'] },
              ],
            },
          ],
        },
        {
          id: 'pt-u2',
          title: 'Eten & drinken',
          icon: '☕',
          lessons: [
            {
              id: 'pt-u2-l1',
              title: 'In het café',
              exercises: [
                { type: 'new', word: 'o café', nl: 'de koffie', example: 'Um café, se faz favor.', exampleNl: 'Een koffie, alsjeblieft.' },
                { type: 'new', word: 'a água', nl: 'het water', example: 'Uma água, por favor.', exampleNl: 'Een water, alsjeblieft.' },
                { type: 'new', word: 'o pão', nl: 'het brood', example: 'O pão é fresco.', exampleNl: 'Het brood is vers.' },
                { type: 'new', word: 'o pastel de nata', nl: 'het custardgebakje', example: 'Um pastel de nata, por favor.', exampleNl: 'Een pastel de nata, alsjeblieft.' },
                { type: 'select', prompt: 'de koffie', options: ['a água', 'o café', 'o pão'], correct: 1 },
                { type: 'select', prompt: 'a água', speak: 'a água', options: ['het water', 'de koffie', 'het brood'], correct: 0 },
                { type: 'listen', target: 'um café', options: ['um café', 'uma água', 'um pão'], correct: 0 },
                { type: 'fill', before: 'Um café e', after: 'água, por favor.', nl: 'Een koffie en een water, alsjeblieft.', options: ['um', 'uma', 'o'], correct: 1 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de koffie', target: 'o café' },
                    { nl: 'het water', target: 'a água' },
                    { nl: 'het brood', target: 'o pão' },
                    { nl: 'het custardgebakje', target: 'o pastel de nata' },
                  ],
                },
                { type: 'wordbank', nl: 'Een koffie, alsjeblieft.', target: 'Um café, por favor.', distractors: ['uma', 'água', 'pão'] },
                { type: 'type', nl: 'het brood', target: 'o pão', accept: ['pão', 'O pão', 'pao', 'o pao'] },
                { type: 'select', prompt: 'het custardgebakje', options: ['o pão', 'o café', 'o pastel de nata'], correct: 2 },
              ],
            },
            {
              id: 'pt-u2-l2',
              title: 'Bestellen',
              exercises: [
                { type: 'new', word: 'quero', nl: 'ik wil', example: 'Quero um sumo de laranja.', exampleNl: 'Ik wil een sinaasappelsap.' },
                { type: 'new', word: 'o leite', nl: 'de melk', example: 'O café com leite é bom.', exampleNl: 'De koffie met melk is lekker.' },
                { type: 'new', word: 'o vinho', nl: 'de wijn', example: 'O vinho tinto é de Portugal.', exampleNl: 'De rode wijn komt uit Portugal.' },
                { type: 'new', word: 'a conta', nl: 'de rekening', example: 'A conta, se faz favor!', exampleNl: 'De rekening, alsjeblieft!' },
                { type: 'select', prompt: 'ik wil', options: ['quero', 'tenho', 'sou'], correct: 0 },
                { type: 'select', prompt: 'o vinho', speak: 'o vinho', options: ['de melk', 'de wijn', 'de rekening'], correct: 1 },
                { type: 'listen', target: 'a conta, por favor', options: ['a conta, por favor', 'o café, por favor', 'a água, por favor'], correct: 0 },
                { type: 'fill', before: 'Um café', after: 'leite, por favor.', nl: 'Een koffie met melk, alsjeblieft.', options: ['de', 'em', 'com'], correct: 2 },
                { type: 'wordbank', nl: 'Ik wil een koffie met melk.', target: 'Quero um café com leite.', distractors: ['vinho', 'a', 'conta'] },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'ik wil', target: 'quero' },
                    { nl: 'de melk', target: 'o leite' },
                    { nl: 'de wijn', target: 'o vinho' },
                    { nl: 'de rekening', target: 'a conta' },
                  ],
                },
                { type: 'type', nl: 'de rekening', target: 'a conta', accept: ['conta', 'A conta'] },
                { type: 'fill', before: 'Quero', after: 'água, por favor.', nl: 'Ik wil een water, alsjeblieft.', options: ['uma', 'um', 'o'], correct: 0 },
                { type: 'type', nl: 'Ik wil een koffie.', target: 'Quero um café.', accept: ['quero um café', 'Quero um cafe', 'quero um cafe'] },
              ],
            },
            {
              id: 'pt-u2-l3',
              title: 'Herhaling: eten & drinken',
              exercises: [
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de koffie', target: 'o café' },
                    { nl: 'het brood', target: 'o pão' },
                    { nl: 'de wijn', target: 'o vinho' },
                    { nl: 'de melk', target: 'o leite' },
                    { nl: 'de rekening', target: 'a conta' },
                  ],
                },
                { type: 'type', nl: 'het water', target: 'a água', accept: ['água', 'agua', 'a agua', 'A água'] },
                { type: 'wordbank', nl: 'Ik wil een pastel de nata en een koffie.', target: 'Quero um pastel de nata e um café.', distractors: ['uma', 'água', 'com', 'vinho'] },
                { type: 'listen', target: 'quero a conta', options: ['quero a conta', 'quero um café', 'quero o pão'], correct: 0 },
                { type: 'select', prompt: 'o leite', speak: 'o leite', options: ['de wijn', 'het water', 'de melk'], correct: 2 },
                { type: 'fill', before: 'Quero', after: 'vinho tinto.', nl: 'Ik wil een rode wijn.', options: ['uma', 'um', 'a'], correct: 1 },
                { type: 'type', nl: 'Een koffie, alsjeblieft.', target: 'Um café, por favor.', accept: ['um café por favor', 'Um café, se faz favor.', 'um cafe por favor', 'Um cafe, por favor.'] },
                { type: 'wordbank', nl: 'De rekening, alsjeblieft.', target: 'A conta, se faz favor.', distractors: ['um', 'vinho', 'obrigado'] },
                { type: 'type', nl: 'ik wil', target: 'quero', accept: ['Quero', 'eu quero', 'Eu quero'] },
                { type: 'select', prompt: 'de melk', options: ['o leite', 'o vinho', 'a água'], correct: 0 },
                { type: 'fill', before: 'O café', after: 'leite é bom.', nl: 'De koffie met melk is lekker.', options: ['com', 'de', 'para'], correct: 0 },
                { type: 'type', nl: 'Ik wil een water.', target: 'Quero uma água.', accept: ['quero uma água', 'Quero uma agua', 'quero uma agua'] },
              ],
            },
          ],
        },
        {
          id: 'pt-u3',
          title: 'Mensen & familie',
          icon: '💛',
          lessons: [
            {
              id: 'pt-u3-l1',
              title: 'Mijn familie',
              exercises: [
                { type: 'new', word: 'a mãe', nl: 'de moeder', example: 'A minha mãe é simpática.', exampleNl: 'Mijn moeder is aardig.' },
                { type: 'new', word: 'o pai', nl: 'de vader', example: 'O meu pai é de Lisboa.', exampleNl: 'Mijn vader komt uit Lissabon.' },
                { type: 'new', word: 'o irmão', nl: 'de broer', example: 'O meu irmão é alto.', exampleNl: 'Mijn broer is groot.' },
                { type: 'new', word: 'a irmã', nl: 'de zus', example: 'A minha irmã tem dez anos.', exampleNl: 'Mijn zus is tien jaar.' },
                { type: 'select', prompt: 'de moeder', options: ['a irmã', 'a mãe', 'o pai'], correct: 1 },
                { type: 'select', prompt: 'o irmão', speak: 'o irmão', options: ['de broer', 'de zus', 'de vader'], correct: 0 },
                { type: 'listen', target: 'a mãe', options: ['a mãe', 'o pai', 'a irmã'], correct: 0 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de moeder', target: 'a mãe' },
                    { nl: 'de vader', target: 'o pai' },
                    { nl: 'de broer', target: 'o irmão' },
                    { nl: 'de zus', target: 'a irmã' },
                  ],
                },
                { type: 'fill', before: 'A minha', after: 'é simpática.', nl: 'Mijn zus is aardig.', options: ['irmão', 'pai', 'irmã'], correct: 2 },
                { type: 'wordbank', nl: 'Mijn vader komt uit Lissabon.', target: 'O meu pai é de Lisboa.', distractors: ['a', 'mãe', 'em'] },
                { type: 'type', nl: 'de zus', target: 'a irmã', accept: ['irmã', 'irma', 'a irma', 'A irmã'] },
                { type: 'select', prompt: 'de vader', options: ['o pai', 'o irmão', 'a mãe'], correct: 0 },
              ],
            },
            {
              id: 'pt-u3-l2',
              title: 'Mensen om je heen',
              exercises: [
                { type: 'new', word: 'o homem', nl: 'de man', example: 'O homem fala português.', exampleNl: 'De man spreekt Portugees.' },
                { type: 'new', word: 'a mulher', nl: 'de vrouw', example: 'A mulher é de Lisboa.', exampleNl: 'De vrouw komt uit Lissabon.' },
                { type: 'new', word: 'o amigo', nl: 'de vriend', example: 'O Pedro é o meu amigo.', exampleNl: 'Pedro is mijn vriend.' },
                { type: 'new', word: 'a família', nl: 'de familie', example: 'A família é grande.', exampleNl: 'De familie is groot.' },
                { type: 'select', prompt: 'de man', options: ['o homem', 'a mulher', 'o amigo'], correct: 0 },
                { type: 'select', prompt: 'a família', speak: 'a família', options: ['de vriendin', 'de familie', 'de vrouw'], correct: 1 },
                { type: 'listen', target: 'a mulher', options: ['a mulher', 'a mãe', 'a família'], correct: 0 },
                { type: 'fill', before: 'O', after: 'é o meu amigo.', nl: 'De man is mijn vriend.', options: ['homem', 'mulher', 'irmã'], correct: 0 },
                { type: 'fill', before: 'A Ana é a minha', after: '.', nl: 'Ana is mijn vriendin.', options: ['amigo', 'amiga', 'pai'], correct: 1 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de man', target: 'o homem' },
                    { nl: 'de vrouw', target: 'a mulher' },
                    { nl: 'de vriend', target: 'o amigo' },
                    { nl: 'de familie', target: 'a família' },
                  ],
                },
                { type: 'wordbank', nl: 'De familie is groot.', target: 'A família é grande.', distractors: ['o', 'homem', 'pequena'] },
                { type: 'type', nl: 'de vrouw', target: 'a mulher', accept: ['mulher', 'A mulher'] },
                { type: 'wordbank', nl: 'De man is mijn vader.', target: 'O homem é o meu pai.', distractors: ['a', 'mãe', 'minha'] },
              ],
            },
            {
              id: 'pt-u3-l3',
              title: 'Herhaling: familie',
              exercises: [
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de moeder', target: 'a mãe' },
                    { nl: 'de vader', target: 'o pai' },
                    { nl: 'de broer', target: 'o irmão' },
                    { nl: 'de vrouw', target: 'a mulher' },
                    { nl: 'de familie', target: 'a família' },
                  ],
                },
                { type: 'type', nl: 'de broer', target: 'o irmão', accept: ['irmão', 'irmao', 'o irmao', 'O irmão'] },
                { type: 'wordbank', nl: 'Mijn moeder is aardig.', target: 'A minha mãe é simpática.', distractors: ['o', 'pai', 'grande'] },
                { type: 'listen', target: 'o meu irmão', options: ['o meu irmão', 'a minha irmã', 'o meu pai'], correct: 0 },
                { type: 'fill', before: 'Onde está', after: 'irmã?', nl: 'Waar is de zus?', options: ['o', 'a', 'um'], correct: 1 },
                { type: 'type', nl: 'de familie', target: 'a família', accept: ['família', 'familia', 'a familia', 'A família'] },
                { type: 'select', prompt: 'o pai', speak: 'o pai', options: ['de broer', 'de man', 'de vader'], correct: 2 },
                { type: 'wordbank', nl: 'De vrouw is mijn moeder.', target: 'A mulher é a minha mãe.', distractors: ['o', 'pai', 'meu'] },
                { type: 'type', nl: 'de man', target: 'o homem', accept: ['homem', 'O homem'] },
                { type: 'fill', before: 'Eu', after: 'o irmão do Pedro.', nl: 'Ik ben de broer van Pedro.', options: ['sou', 'é', 'és'], correct: 0 },
                { type: 'type', nl: 'mijn vriend', target: 'o meu amigo', accept: ['meu amigo', 'O meu amigo', 'amigo'] },
                { type: 'wordbank', nl: 'Mijn zus is mijn vriendin.', target: 'A minha irmã é a minha amiga.', distractors: ['o', 'irmão', 'amigo'] },
              ],
            },
          ],
        },
        {
          id: 'pt-u4',
          title: 'Onderweg in de stad',
          icon: '🧭',
          lessons: [
            {
              id: 'pt-u4-l1',
              title: 'De weg vragen',
              exercises: [
                { type: 'new', word: 'onde', nl: 'waar', example: 'Onde é a estação?', exampleNl: 'Waar is het station?' },
                { type: 'new', word: 'a rua', nl: 'de straat', example: 'A rua é bonita.', exampleNl: 'De straat is mooi.' },
                { type: 'new', word: 'à esquerda', nl: 'links', example: 'A estação é à esquerda.', exampleNl: 'Het station is links.' },
                { type: 'new', word: 'à direita', nl: 'rechts', example: 'O café é à direita.', exampleNl: 'Het café is rechts.' },
                { type: 'select', prompt: 'waar', options: ['quando', 'onde', 'como'], correct: 1 },
                { type: 'select', prompt: 'a rua', speak: 'a rua', options: ['de straat', 'het plein', 'het station'], correct: 0 },
                { type: 'listen', target: 'à esquerda', options: ['à esquerda', 'à direita', 'a rua'], correct: 0 },
                { type: 'fill', before: 'A estação é', after: 'esquerda.', nl: 'Het station is links.', options: ['o', 'à', 'em'], correct: 1 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'waar', target: 'onde' },
                    { nl: 'de straat', target: 'a rua' },
                    { nl: 'links', target: 'à esquerda' },
                    { nl: 'rechts', target: 'à direita' },
                  ],
                },
                { type: 'wordbank', nl: 'Waar is de straat?', target: 'Onde é a rua?', distractors: ['esquerda', 'o', 'café'] },
                { type: 'type', nl: 'rechts', target: 'à direita', accept: ['direita', 'a direita', 'A direita'] },
                { type: 'select', prompt: 'links', options: ['à direita', 'a rua', 'à esquerda'], correct: 2 },
              ],
            },
            {
              id: 'pt-u4-l2',
              title: 'Bus en trein',
              exercises: [
                { type: 'new', word: 'o comboio', nl: 'de trein', example: 'O comboio para Lisboa é rápido.', exampleNl: 'De trein naar Lissabon is snel.' },
                { type: 'new', word: 'o autocarro', nl: 'de bus', example: 'Onde é o autocarro para Belém?', exampleNl: 'Waar is de bus naar Belém?' },
                { type: 'new', word: 'a estação', nl: 'het station', example: 'A estação é à direita.', exampleNl: 'Het station is rechts.' },
                { type: 'new', word: 'o bilhete', nl: 'het kaartje', example: 'Quero um bilhete para o Porto.', exampleNl: 'Ik wil een kaartje naar Porto.' },
                { type: 'select', prompt: 'de trein', options: ['o autocarro', 'o comboio', 'o bilhete'], correct: 1 },
                { type: 'select', prompt: 'o bilhete', speak: 'o bilhete', options: ['het kaartje', 'het station', 'de bus'], correct: 0 },
                { type: 'listen', target: 'o comboio para Lisboa', options: ['o comboio para Lisboa', 'o autocarro para Lisboa', 'o comboio para o Porto'], correct: 0 },
                { type: 'fill', before: 'Quero um bilhete', after: 'Lisboa.', nl: 'Ik wil een kaartje naar Lissabon.', options: ['de', 'para', 'em'], correct: 1 },
                {
                  type: 'match',
                  pairs: [
                    { nl: 'de trein', target: 'o comboio' },
                    { nl: 'de bus', target: 'o autocarro' },
                    { nl: 'het station', target: 'a estação' },
                    { nl: 'het kaartje', target: 'o bilhete' },
                  ],
                },
                { type: 'wordbank', nl: 'Waar is het station?', target: 'Onde é a estação?', distractors: ['o', 'comboio', 'rua'] },
                { type: 'type', nl: 'de bus', target: 'o autocarro', accept: ['autocarro', 'O autocarro'] },
                { type: 'fill', before: 'Onde é', after: 'estação?', nl: 'Waar is het station?', options: ['a', 'o', 'um'], correct: 0 },
                { type: 'type', nl: 'Ik wil een kaartje.', target: 'Quero um bilhete.', accept: ['quero um bilhete', 'Quero um bilhete', 'quero um bilhete.'] },
              ],
            },
            {
              id: 'pt-u4-l3',
              title: 'Herhaling: in de stad',
              exercises: [
                {
                  type: 'match',
                  pairs: [
                    { nl: 'waar', target: 'onde' },
                    { nl: 'de straat', target: 'a rua' },
                    { nl: 'de trein', target: 'o comboio' },
                    { nl: 'het station', target: 'a estação' },
                    { nl: 'het kaartje', target: 'o bilhete' },
                  ],
                },
                { type: 'type', nl: 'de trein', target: 'o comboio', accept: ['comboio', 'O comboio'] },
                { type: 'wordbank', nl: 'Het station is links.', target: 'A estação é à esquerda.', distractors: ['direita', 'o', 'comboio'] },
                { type: 'listen', target: 'à direita', options: ['à direita', 'à esquerda', 'a rua'], correct: 0 },
                { type: 'type', nl: 'Waar is de bus?', target: 'Onde é o autocarro?', accept: ['onde é o autocarro', 'Onde e o autocarro?', 'onde e o autocarro'] },
                { type: 'fill', before: 'O comboio', after: 'o Porto é rápido.', nl: 'De trein naar Porto is snel.', options: ['para', 'de', 'com'], correct: 0 },
                { type: 'wordbank', nl: 'Ik wil een kaartje naar Lissabon, alsjeblieft.', target: 'Quero um bilhete para Lisboa, por favor.', distractors: ['uma', 'comboio', 'à', 'estação'] },
                { type: 'select', prompt: 'a estação', speak: 'a estação', options: ['de straat', 'het station', 'het kaartje'], correct: 1 },
                { type: 'type', nl: 'links', target: 'à esquerda', accept: ['esquerda', 'a esquerda', 'A esquerda'] },
                { type: 'fill', before: 'Onde', after: 'a rua?', nl: 'Waar is de straat?', options: ['sou', 'és', 'é'], correct: 2 },
                { type: 'wordbank', nl: 'De bus naar Belém is rechts.', target: 'O autocarro para Belém é à direita.', distractors: ['esquerda', 'comboio', 'a'] },
                { type: 'type', nl: 'het kaartje', target: 'o bilhete', accept: ['bilhete', 'O bilhete'] },
                { type: 'select', prompt: 'Onde é a estação?', speak: 'Onde é a estação?', options: ['Waar is de straat?', 'Waar is de bus?', 'Waar is het station?'], correct: 2 },
              ],
            },
          ],
        },
      ],
    },
  ],
}
