import type { CourseId } from '../types'

/**
 * De Woordenstamboom: families van woorden die over de talen heen dezelfde
 * stam delen. Wie in het Spaans "amigo" leert, herkent daarna moeiteloos
 * ami, amico en amigo. Dat is het idee: één woord leren opent er vijf.
 */
export interface FamilieLid {
  /** het woord in die taal, precies zoals het in de cursus staat */
  woord: string
  /** de Nederlandse betekenis */
  nl: string
}

export interface WoordFamilie {
  /** unieke sleutel, kleine letters, bv. 'amicus' */
  id: string
  /** de stam waar alles vandaan komt, bv. 'amicus' */
  stam: string
  /** waar de stam vandaan komt */
  herkomst: 'Latijn' | 'Germaans' | 'Grieks' | 'Arabisch' | 'Frankisch'
  /** wat de stam letterlijk betekende, in het Nederlands */
  stamBetekenis: string
  /** één zin die dit leuk of memorabel maakt, in het Nederlands, zonder middenstreepjes */
  weetje: string
  /** per taal het familielid; een taal mag ontbreken */
  leden: Partial<Record<CourseId, FamilieLid>>
}

export const FAMILIES: WoordFamilie[] = [
  // ─── Mensen en familie ───────────────────────────────────────────────
  {
    id: 'amicus',
    stam: 'amicus',
    herkomst: 'Latijn',
    stamBetekenis: 'vriend',
    weetje: 'De Romeinen zeiden amicus voor vriend, en na tweeduizend jaar hoor je dat nog in vier talen terug.',
    leden: {
      es: { woord: 'amigo', nl: 'vriend' },
      fr: { woord: 'ami', nl: 'vriend' },
      it: { woord: 'amico', nl: 'vriend' },
      pt: { woord: 'amigo', nl: 'vriend' },
      en: { woord: 'amicable', nl: 'vriendschappelijk' },
    },
  },
  {
    id: 'pater',
    stam: 'pater',
    herkomst: 'Latijn',
    stamBetekenis: 'vader',
    weetje: 'Papa mag dan kindertaal zijn, pater zit stiekem in padre, in père en in de paters van het klooster.',
    leden: {
      es: { woord: 'padre', nl: 'vader' },
      fr: { woord: 'père', nl: 'vader' },
      it: { woord: 'padre', nl: 'vader' },
      pt: { woord: 'pai', nl: 'vader' },
      en: { woord: 'paternal', nl: 'vaderlijk' },
    },
  },
  {
    id: 'mater',
    stam: 'mater',
    herkomst: 'Latijn',
    stamBetekenis: 'moeder',
    weetje: 'Uit mater groeide niet alleen madre maar ook materiaal, want moeder aarde levert de stof.',
    leden: {
      es: { woord: 'madre', nl: 'moeder' },
      fr: { woord: 'mère', nl: 'moeder' },
      it: { woord: 'madre', nl: 'moeder' },
      pt: { woord: 'mãe', nl: 'moeder' },
      en: { woord: 'maternal', nl: 'moederlijk' },
    },
  },
  {
    id: 'filius',
    stam: 'filius',
    herkomst: 'Latijn',
    stamBetekenis: 'zoon',
    weetje: 'Een filiaal is letterlijk een dochterbedrijf, precies zoals filius zoon betekende.',
    leden: {
      es: { woord: 'hijo', nl: 'zoon' },
      fr: { woord: 'fils', nl: 'zoon' },
      it: { woord: 'figlio', nl: 'zoon' },
      pt: { woord: 'filho', nl: 'zoon' },
      en: { woord: 'filial', nl: 'van kind tot ouder' },
    },
  },
  {
    id: 'frater',
    stam: 'frater',
    herkomst: 'Latijn',
    stamBetekenis: 'broer',
    weetje: 'Broederschap heet in het Frans fraternité, en dat woord staat nog op elk Frans gemeentehuis.',
    leden: {
      fr: { woord: 'frère', nl: 'broer' },
      it: { woord: 'fratello', nl: 'broer' },
      es: { woord: 'fraternal', nl: 'broederlijk' },
      pt: { woord: 'fraterno', nl: 'broederlijk' },
      en: { woord: 'fraternal', nl: 'broederlijk' },
    },
  },
  {
    id: 'familia',
    stam: 'familia',
    herkomst: 'Latijn',
    stamBetekenis: 'huishouden met alles erop en eraan',
    weetje: 'Bij de Romeinen hoorden ook de bedienden bij de familia, dus het woord was ooit veel ruimer dan nu.',
    leden: {
      es: { woord: 'familia', nl: 'familie' },
      fr: { woord: 'famille', nl: 'familie' },
      it: { woord: 'famiglia', nl: 'familie' },
      pt: { woord: 'família', nl: 'familie' },
      en: { woord: 'family', nl: 'familie' },
      de: { woord: 'Familie', nl: 'familie' },
    },
  },
  {
    id: 'homo',
    stam: 'homo',
    herkomst: 'Latijn',
    stamBetekenis: 'mens',
    weetje: 'Hombre, homme en uomo zijn drie jassen om precies dezelfde Latijnse mens.',
    leden: {
      es: { woord: 'hombre', nl: 'man' },
      fr: { woord: 'homme', nl: 'man' },
      it: { woord: 'uomo', nl: 'man' },
      pt: { woord: 'homem', nl: 'man' },
      en: { woord: 'human', nl: 'menselijk, mens' },
    },
  },
  {
    id: 'infans',
    stam: 'infans',
    herkomst: 'Latijn',
    stamBetekenis: 'iemand die nog niet spreekt',
    weetje: 'Een baby heette bij de Romeinen infans, letterlijk iemand die nog niet praat.',
    leden: {
      fr: { woord: 'enfant', nl: 'kind' },
      es: { woord: 'infancia', nl: 'kindertijd' },
      it: { woord: 'infanzia', nl: 'kindertijd' },
      pt: { woord: 'infância', nl: 'kindertijd' },
      en: { woord: 'infant', nl: 'zuigeling' },
    },
  },
  {
    id: 'persona',
    stam: 'persona',
    herkomst: 'Latijn',
    stamBetekenis: 'toneelmasker',
    weetje: 'Een persoon was ooit het masker dat een acteur voorhield, dus iedereen speelt nog altijd een rol.',
    leden: {
      es: { woord: 'persona', nl: 'persoon' },
      fr: { woord: 'personne', nl: 'persoon, niemand' },
      it: { woord: 'persona', nl: 'persoon' },
      pt: { woord: 'pessoa', nl: 'persoon' },
      en: { woord: 'person', nl: 'persoon' },
      de: { woord: 'Person', nl: 'persoon' },
    },
  },

  // ─── Huis en stad ────────────────────────────────────────────────────
  {
    id: 'casa',
    stam: 'casa',
    herkomst: 'Latijn',
    stamBetekenis: 'hut',
    weetje: 'Het Franse chez betekent bij, en het komt van casa, dus chez moi is eigenlijk in mijn huisje.',
    leden: {
      es: { woord: 'casa', nl: 'huis' },
      it: { woord: 'casa', nl: 'huis' },
      pt: { woord: 'casa', nl: 'huis' },
      fr: { woord: 'chez', nl: 'bij, ten huize van' },
    },
  },
  {
    id: 'porta',
    stam: 'porta',
    herkomst: 'Latijn',
    stamBetekenis: 'doorgang',
    weetje: 'Puerta, porte en porta staan alle drie nog open, en het Duitse Pforte klinkt precies als onze poort.',
    leden: {
      es: { woord: 'puerta', nl: 'deur' },
      fr: { woord: 'porte', nl: 'deur' },
      it: { woord: 'porta', nl: 'deur' },
      pt: { woord: 'porta', nl: 'deur' },
      en: { woord: 'portal', nl: 'portaal, toegangspoort' },
      de: { woord: 'Pforte', nl: 'poort' },
    },
  },
  {
    id: 'fenestra',
    stam: 'fenestra',
    herkomst: 'Latijn',
    stamBetekenis: 'raam',
    weetje: 'Het Engels bewaarde fenestra alleen in defenestration, het uit het raam gooien van iemand.',
    leden: {
      fr: { woord: 'fenêtre', nl: 'raam' },
      it: { woord: 'finestra', nl: 'raam' },
      de: { woord: 'Fenster', nl: 'raam' },
      en: { woord: 'defenestration', nl: 'het uit het raam werpen' },
    },
  },
  {
    id: 'camera',
    stam: 'camera',
    herkomst: 'Latijn',
    stamBetekenis: 'gewelfde kamer',
    weetje: 'Je fototoestel heet camera omdat de allereerste toestellen letterlijk een donkere kamer waren.',
    leden: {
      it: { woord: 'camera', nl: 'kamer' },
      es: { woord: 'cámara', nl: 'kamer, camera' },
      fr: { woord: 'chambre', nl: 'slaapkamer' },
      pt: { woord: 'câmara', nl: 'kamer, camera' },
      en: { woord: 'chamber', nl: 'kamer, zaal' },
      de: { woord: 'Kammer', nl: 'kamertje' },
    },
  },
  {
    id: 'civitas',
    stam: 'civitas',
    herkomst: 'Latijn',
    stamBetekenis: 'burgerij',
    weetje: 'Een stad was voor de Romeinen vooral een verzameling burgers, en dat zit nog in ciudad en in city.',
    leden: {
      es: { woord: 'ciudad', nl: 'stad' },
      fr: { woord: 'cité', nl: 'binnenstad' },
      it: { woord: 'città', nl: 'stad' },
      pt: { woord: 'cidade', nl: 'stad' },
      en: { woord: 'city', nl: 'stad' },
    },
  },
  {
    id: 'mercatus',
    stam: 'mercatus',
    herkomst: 'Latijn',
    stamBetekenis: 'handel, marktplaats',
    weetje: 'Mercado, marché en market komen allemaal uit de Romeinse handel, en het Duitse Markt lijkt op onze markt als twee druppels water.',
    leden: {
      es: { woord: 'mercado', nl: 'markt' },
      fr: { woord: 'marché', nl: 'markt' },
      it: { woord: 'mercato', nl: 'markt' },
      pt: { woord: 'mercado', nl: 'markt' },
      en: { woord: 'market', nl: 'markt' },
      de: { woord: 'Markt', nl: 'markt' },
    },
  },
  {
    id: 'strata',
    stam: 'via strata',
    herkomst: 'Latijn',
    stamBetekenis: 'geplaveide weg',
    weetje: 'Via strata betekende geplaveide weg, en daar rijden onze straat, de Straße en de strada nog altijd overheen.',
    leden: {
      it: { woord: 'strada', nl: 'straat, weg' },
      pt: { woord: 'estrada', nl: 'weg' },
      en: { woord: 'street', nl: 'straat' },
      de: { woord: 'Straße', nl: 'straat' },
    },
  },
  {
    id: 'hospitalis',
    stam: 'hospitalis',
    herkomst: 'Latijn',
    stamBetekenis: 'gastvrij',
    weetje: 'Hotel en hospitaal komen van hetzelfde woord voor gastvrij, want allebei vingen ze ooit reizigers op.',
    leden: {
      fr: { woord: 'hôpital', nl: 'ziekenhuis' },
      es: { woord: 'hospital', nl: 'ziekenhuis' },
      it: { woord: 'ospedale', nl: 'ziekenhuis' },
      pt: { woord: 'hospital', nl: 'ziekenhuis' },
      en: { woord: 'hospital', nl: 'ziekenhuis' },
    },
  },

  // ─── Eten en drinken ─────────────────────────────────────────────────
  {
    id: 'panis',
    stam: 'panis',
    herkomst: 'Latijn',
    stamBetekenis: 'brood',
    weetje: 'Een companion is letterlijk iemand met wie je je brood deelt.',
    leden: {
      es: { woord: 'pan', nl: 'brood' },
      fr: { woord: 'pain', nl: 'brood' },
      it: { woord: 'pane', nl: 'brood' },
      pt: { woord: 'pão', nl: 'brood' },
      en: { woord: 'companion', nl: 'metgezel' },
    },
  },
  {
    id: 'aqua',
    stam: 'aqua',
    herkomst: 'Latijn',
    stamBetekenis: 'water',
    weetje: 'Van aqua naar eau lijkt een enorme sprong, maar de Fransen sleten er in duizend jaar simpelweg alle medeklinkers af.',
    leden: {
      es: { woord: 'agua', nl: 'water' },
      fr: { woord: 'eau', nl: 'water' },
      it: { woord: 'acqua', nl: 'water' },
      pt: { woord: 'água', nl: 'water' },
      en: { woord: 'aquarium', nl: 'aquarium' },
    },
  },
  {
    id: 'vinum',
    stam: 'vinum',
    herkomst: 'Latijn',
    stamBetekenis: 'wijn',
    weetje: 'Wijn reisde met de Romeinen mee naar het noorden, en het woord ging vrolijk mee in de kar.',
    leden: {
      es: { woord: 'vino', nl: 'wijn' },
      fr: { woord: 'vin', nl: 'wijn' },
      it: { woord: 'vino', nl: 'wijn' },
      pt: { woord: 'vinho', nl: 'wijn' },
      en: { woord: 'wine', nl: 'wijn' },
      de: { woord: 'Wein', nl: 'wijn' },
    },
  },
  {
    id: 'lac',
    stam: 'lac',
    herkomst: 'Latijn',
    stamBetekenis: 'melk',
    weetje: 'De lactose op je yoghurtpak verraadt dat leche, lait en latte gewoon melk zijn.',
    leden: {
      es: { woord: 'leche', nl: 'melk' },
      fr: { woord: 'lait', nl: 'melk' },
      it: { woord: 'latte', nl: 'melk' },
      pt: { woord: 'leite', nl: 'melk' },
      en: { woord: 'lactose', nl: 'melksuiker' },
    },
  },
  {
    id: 'caseus',
    stam: 'caseus',
    herkomst: 'Latijn',
    stamBetekenis: 'kaas',
    weetje: 'Kaas, Käse, cheese en queso komen allemaal uit caseus, want de Romeinen leerden half Europa kazen.',
    leden: {
      es: { woord: 'queso', nl: 'kaas' },
      pt: { woord: 'queijo', nl: 'kaas' },
      en: { woord: 'cheese', nl: 'kaas' },
      de: { woord: 'Käse', nl: 'kaas' },
    },
  },
  {
    id: 'sal',
    stam: 'sal',
    herkomst: 'Latijn',
    stamBetekenis: 'zout',
    weetje: 'Romeinse soldaten kregen zoutgeld, en daarom heet jouw loon nog altijd salaris.',
    leden: {
      es: { woord: 'sal', nl: 'zout' },
      fr: { woord: 'sel', nl: 'zout' },
      it: { woord: 'sale', nl: 'zout' },
      pt: { woord: 'sal', nl: 'zout' },
      en: { woord: 'salt', nl: 'zout' },
      de: { woord: 'Salz', nl: 'zout' },
    },
  },
  {
    id: 'fructus',
    stam: 'fructus',
    herkomst: 'Latijn',
    stamBetekenis: 'opbrengst',
    weetje: 'Fruit was voor de Romeinen simpelweg alles wat het land opbracht.',
    leden: {
      es: { woord: 'fruta', nl: 'fruit' },
      fr: { woord: 'fruit', nl: 'fruit' },
      it: { woord: 'frutta', nl: 'fruit' },
      pt: { woord: 'fruta', nl: 'fruit' },
      en: { woord: 'fruit', nl: 'fruit' },
      de: { woord: 'Frucht', nl: 'vrucht' },
    },
  },
  {
    id: 'ovum',
    stam: 'ovum',
    herkomst: 'Latijn',
    stamBetekenis: 'ei',
    weetje: 'Ovaal betekent eivormig, dus wie een ovaal gezicht heeft loopt met een eitje rond.',
    leden: {
      es: { woord: 'huevo', nl: 'ei' },
      fr: { woord: 'œuf', nl: 'ei' },
      it: { woord: 'uovo', nl: 'ei' },
      pt: { woord: 'ovo', nl: 'ei' },
      en: { woord: 'oval', nl: 'ovaal, eivormig' },
    },
  },
  {
    id: 'bibere',
    stam: 'bibere',
    herkomst: 'Latijn',
    stamBetekenis: 'drinken',
    weetje: 'Een beverage is niets anders dan iets te drinken, en dat hoor je terug in beber en boire.',
    leden: {
      es: { woord: 'beber', nl: 'drinken' },
      fr: { woord: 'boire', nl: 'drinken' },
      it: { woord: 'bere', nl: 'drinken' },
      pt: { woord: 'beber', nl: 'drinken' },
      en: { woord: 'beverage', nl: 'drank' },
    },
  },

  // ─── Dieren ──────────────────────────────────────────────────────────
  {
    id: 'cattus',
    stam: 'cattus',
    herkomst: 'Latijn',
    stamBetekenis: 'kat',
    weetje: 'Bijna heel Europa zegt iets met kat, want het beestje kwam met naam en al uit het zuiden aanlopen.',
    leden: {
      es: { woord: 'gato', nl: 'kat' },
      fr: { woord: 'chat', nl: 'kat' },
      it: { woord: 'gatto', nl: 'kat' },
      pt: { woord: 'gato', nl: 'kat' },
      en: { woord: 'cat', nl: 'kat' },
      de: { woord: 'Katze', nl: 'kat' },
    },
  },
  {
    id: 'canis',
    stam: 'canis',
    herkomst: 'Latijn',
    stamBetekenis: 'hond',
    weetje: 'Je hoektanden heten canine tanden omdat ze op de tanden van een hond lijken.',
    leden: {
      fr: { woord: 'chien', nl: 'hond' },
      it: { woord: 'cane', nl: 'hond' },
      pt: { woord: 'cão', nl: 'hond' },
      es: { woord: 'canino', nl: 'hondachtig, hoektand' },
      en: { woord: 'canine', nl: 'hondachtig' },
    },
  },
  {
    id: 'caballus',
    stam: 'caballus',
    herkomst: 'Latijn',
    stamBetekenis: 'werkpaard',
    weetje: 'Een cavalier was gewoon iemand te paard, en aan die ruiters hielden we het woord ridderlijk over.',
    leden: {
      es: { woord: 'caballo', nl: 'paard' },
      fr: { woord: 'cheval', nl: 'paard' },
      it: { woord: 'cavallo', nl: 'paard' },
      pt: { woord: 'cavalo', nl: 'paard' },
      en: { woord: 'cavalry', nl: 'cavalerie, ruiterij' },
    },
  },
  {
    id: 'vacca',
    stam: 'vacca',
    herkomst: 'Latijn',
    stamBetekenis: 'koe',
    weetje: 'Het woord vaccin komt van vacca, want de allereerste inenting kwam uit koeienpokken.',
    leden: {
      es: { woord: 'vaca', nl: 'koe' },
      fr: { woord: 'vache', nl: 'koe' },
      it: { woord: 'vacca', nl: 'koe' },
      pt: { woord: 'vaca', nl: 'koe' },
      en: { woord: 'vaccine', nl: 'vaccin' },
    },
  },
  {
    id: 'avis',
    stam: 'avis',
    herkomst: 'Latijn',
    stamBetekenis: 'vogel',
    weetje: 'Oiseau en uccello klinken totaal verschillend, maar het zijn allebei verkleinwoorden van dezelfde Latijnse vogel.',
    leden: {
      es: { woord: 'ave', nl: 'vogel' },
      pt: { woord: 'ave', nl: 'vogel' },
      fr: { woord: 'oiseau', nl: 'vogel' },
      it: { woord: 'uccello', nl: 'vogel' },
      en: { woord: 'aviation', nl: 'luchtvaart' },
    },
  },
  {
    id: 'piscis',
    stam: 'piscis',
    herkomst: 'Latijn',
    stamBetekenis: 'vis',
    weetje: 'Pesce, peixe en poisson zijn onderling familie, en het Engelse fish komt uit diezelfde oeroude wortel.',
    leden: {
      es: { woord: 'pez', nl: 'vis' },
      fr: { woord: 'poisson', nl: 'vis' },
      it: { woord: 'pesce', nl: 'vis' },
      pt: { woord: 'peixe', nl: 'vis' },
    },
  },

  // ─── Kleuren en getallen ─────────────────────────────────────────────
  {
    id: 'viridis',
    stam: 'viridis',
    herkomst: 'Latijn',
    stamBetekenis: 'groen, fris',
    weetje: 'Verde schrijf je in drie talen precies hetzelfde, dus die kleur krijg je bijna cadeau.',
    leden: {
      es: { woord: 'verde', nl: 'groen' },
      it: { woord: 'verde', nl: 'groen' },
      pt: { woord: 'verde', nl: 'groen' },
      fr: { woord: 'vert', nl: 'groen' },
      en: { woord: 'verdant', nl: 'groen begroeid' },
    },
  },
  {
    id: 'ruber',
    stam: 'ruber',
    herkomst: 'Latijn',
    stamBetekenis: 'rood',
    weetje: 'Rouge, rojo en rosso komen uit hetzelfde rode Latijn, net als de robijn aan een ring.',
    leden: {
      es: { woord: 'rojo', nl: 'rood' },
      fr: { woord: 'rouge', nl: 'rood' },
      it: { woord: 'rosso', nl: 'rood' },
      en: { woord: 'ruby', nl: 'robijn' },
    },
  },
  {
    id: 'unus',
    stam: 'unus',
    herkomst: 'Latijn',
    stamBetekenis: 'één',
    weetje: 'Uno, un en um zijn hetzelfde getal in vier verschillende jasjes.',
    leden: {
      es: { woord: 'uno', nl: 'één' },
      fr: { woord: 'un', nl: 'één' },
      it: { woord: 'uno', nl: 'één' },
      pt: { woord: 'um', nl: 'één' },
      en: { woord: 'unit', nl: 'eenheid' },
    },
  },
  {
    id: 'duo',
    stam: 'duo',
    herkomst: 'Latijn',
    stamBetekenis: 'twee',
    weetje: 'Een duo is twee, en dat getal reist bijna onherkenbaar mee in deux en in dois.',
    leden: {
      es: { woord: 'dos', nl: 'twee' },
      fr: { woord: 'deux', nl: 'twee' },
      it: { woord: 'due', nl: 'twee' },
      pt: { woord: 'dois', nl: 'twee' },
      en: { woord: 'duo', nl: 'tweetal' },
    },
  },
  {
    id: 'tres',
    stam: 'tres',
    herkomst: 'Latijn',
    stamBetekenis: 'drie',
    weetje: 'Tres, trois en três lijken op ons drie omdat dit getal ouder is dan al die talen bij elkaar.',
    leden: {
      es: { woord: 'tres', nl: 'drie' },
      fr: { woord: 'trois', nl: 'drie' },
      it: { woord: 'tre', nl: 'drie' },
      pt: { woord: 'três', nl: 'drie' },
      en: { woord: 'trio', nl: 'drietal' },
    },
  },
  {
    id: 'mille',
    stam: 'mille',
    herkomst: 'Latijn',
    stamBetekenis: 'duizend',
    weetje: 'Een Engelse mile was ooit duizend Romeinse dubbelpassen, dus je loopt nog steeds op Latijnse voeten.',
    leden: {
      es: { woord: 'mil', nl: 'duizend' },
      fr: { woord: 'mille', nl: 'duizend' },
      it: { woord: 'mille', nl: 'duizend' },
      pt: { woord: 'mil', nl: 'duizend' },
      en: { woord: 'mile', nl: 'mijl' },
    },
  },

  // ─── Tijd en weer ────────────────────────────────────────────────────
  {
    id: 'dies',
    stam: 'dies',
    herkomst: 'Latijn',
    stamBetekenis: 'dag',
    weetje: 'Jour en giorno komen van het Latijnse woord voor dagelijks, terwijl día het korte origineel bewaarde.',
    leden: {
      es: { woord: 'día', nl: 'dag' },
      pt: { woord: 'dia', nl: 'dag' },
      it: { woord: 'giorno', nl: 'dag' },
      fr: { woord: 'jour', nl: 'dag' },
      en: { woord: 'journal', nl: 'dagboek, krant' },
    },
  },
  {
    id: 'nox',
    stam: 'nox',
    herkomst: 'Latijn',
    stamBetekenis: 'nacht',
    weetje: 'Nacht, night en notte gaan terug op dezelfde oeroude wortel, want donker was overal donker.',
    leden: {
      es: { woord: 'noche', nl: 'nacht' },
      fr: { woord: 'nuit', nl: 'nacht' },
      it: { woord: 'notte', nl: 'nacht' },
      pt: { woord: 'noite', nl: 'nacht' },
      en: { woord: 'night', nl: 'nacht' },
      de: { woord: 'Nacht', nl: 'nacht' },
    },
  },
  {
    id: 'hora',
    stam: 'hora',
    herkomst: 'Latijn',
    stamBetekenis: 'uur',
    weetje: 'Het Duitse Uhr is gewoon het Latijnse hora dat onderweg zijn eerste letters kwijtraakte.',
    leden: {
      es: { woord: 'hora', nl: 'uur' },
      fr: { woord: 'heure', nl: 'uur' },
      it: { woord: 'ora', nl: 'uur' },
      pt: { woord: 'hora', nl: 'uur' },
      en: { woord: 'hour', nl: 'uur' },
      de: { woord: 'Uhr', nl: 'uur, klok' },
    },
  },
  {
    id: 'tempus',
    stam: 'tempus',
    herkomst: 'Latijn',
    stamBetekenis: 'tijd',
    weetje: 'Het tempo van een liedje is letterlijk zijn tijd.',
    leden: {
      es: { woord: 'tiempo', nl: 'tijd, weer' },
      fr: { woord: 'temps', nl: 'tijd, weer' },
      it: { woord: 'tempo', nl: 'tijd, weer' },
      pt: { woord: 'tempo', nl: 'tijd, weer' },
      en: { woord: 'temporary', nl: 'tijdelijk' },
    },
  },
  {
    id: 'annus',
    stam: 'annus',
    herkomst: 'Latijn',
    stamBetekenis: 'jaar',
    weetje: 'Een jubileum heet anniversary omdat het jaar zich netjes weer omdraait.',
    leden: {
      es: { woord: 'año', nl: 'jaar' },
      fr: { woord: 'an', nl: 'jaar' },
      it: { woord: 'anno', nl: 'jaar' },
      pt: { woord: 'ano', nl: 'jaar' },
      en: { woord: 'annual', nl: 'jaarlijks' },
    },
  },
  {
    id: 'septimana',
    stam: 'septimana',
    herkomst: 'Latijn',
    stamBetekenis: 'periode van zeven',
    weetje: 'Semana, semaine en settimana tellen alle drie gewoon tot zeven.',
    leden: {
      es: { woord: 'semana', nl: 'week' },
      fr: { woord: 'semaine', nl: 'week' },
      it: { woord: 'settimana', nl: 'week' },
      pt: { woord: 'semana', nl: 'week' },
    },
  },
  {
    id: 'sol',
    stam: 'sol',
    herkomst: 'Latijn',
    stamBetekenis: 'zon',
    weetje: 'Soleil is een verkleinwoord, dus de Fransen zeggen elke ochtend zonnetje, en het Duitse Sonne komt uit dezelfde oeroude wortel.',
    leden: {
      es: { woord: 'sol', nl: 'zon' },
      it: { woord: 'sole', nl: 'zon' },
      pt: { woord: 'sol', nl: 'zon' },
      fr: { woord: 'soleil', nl: 'zon' },
      en: { woord: 'solar', nl: 'van de zon' },
      de: { woord: 'Sonne', nl: 'zon' },
    },
  },
  {
    id: 'luna',
    stam: 'luna',
    herkomst: 'Latijn',
    stamBetekenis: 'maan',
    weetje: 'Wie maangek was heette lunatic, want de maan zou je hoofd op hol brengen.',
    leden: {
      es: { woord: 'luna', nl: 'maan' },
      it: { woord: 'luna', nl: 'maan' },
      pt: { woord: 'lua', nl: 'maan' },
      fr: { woord: 'lune', nl: 'maan' },
      en: { woord: 'lunar', nl: 'van de maan' },
    },
  },
  {
    id: 'ventus',
    stam: 'ventus',
    herkomst: 'Latijn',
    stamBetekenis: 'wind',
    weetje: 'Je ventilator maakt letterlijk wind, precies wat viento en vent beloven.',
    leden: {
      es: { woord: 'viento', nl: 'wind' },
      fr: { woord: 'vent', nl: 'wind' },
      it: { woord: 'vento', nl: 'wind' },
      pt: { woord: 'vento', nl: 'wind' },
      en: { woord: 'ventilation', nl: 'ventilatie' },
    },
  },
  {
    id: 'pluvia',
    stam: 'pluvia',
    herkomst: 'Latijn',
    stamBetekenis: 'regen',
    weetje: 'De pl van pluvia werd in Spanje ll, in Italië pi en in Portugal ch, dus één bui gaf drie woorden.',
    leden: {
      es: { woord: 'lluvia', nl: 'regen' },
      fr: { woord: 'pluie', nl: 'regen' },
      it: { woord: 'pioggia', nl: 'regen' },
      pt: { woord: 'chuva', nl: 'regen' },
    },
  },
  {
    id: 'calidus',
    stam: 'calidus',
    herkomst: 'Latijn',
    stamBetekenis: 'warm',
    weetje: 'Een calorie is een hoeveelheid warmte, en dat is precies wat caliente en chaud beloven.',
    leden: {
      es: { woord: 'caliente', nl: 'warm, heet' },
      fr: { woord: 'chaud', nl: 'warm' },
      it: { woord: 'caldo', nl: 'warm' },
      pt: { woord: 'cálido', nl: 'warm' },
      en: { woord: 'calorie', nl: 'calorie, eenheid van warmte' },
    },
  },
  {
    id: 'frigidus',
    stam: 'frigidus',
    herkomst: 'Latijn',
    stamBetekenis: 'koud',
    weetje: 'In je koelkast staat het Latijn nog fier overeind, want een refrigerator maakt alles weer koud.',
    leden: {
      es: { woord: 'frío', nl: 'koud' },
      fr: { woord: 'froid', nl: 'koud' },
      it: { woord: 'freddo', nl: 'koud' },
      pt: { woord: 'frio', nl: 'koud' },
      en: { woord: 'refrigerator', nl: 'koelkast' },
    },
  },

  // ─── Lichaam ─────────────────────────────────────────────────────────
  {
    id: 'manus',
    stam: 'manus',
    herkomst: 'Latijn',
    stamBetekenis: 'hand',
    weetje: 'Een manicure is letterlijk handverzorging, en handwerk heet nog altijd manueel.',
    leden: {
      es: { woord: 'mano', nl: 'hand' },
      fr: { woord: 'main', nl: 'hand' },
      it: { woord: 'mano', nl: 'hand' },
      pt: { woord: 'mão', nl: 'hand' },
      en: { woord: 'manual', nl: 'handmatig, handleiding' },
    },
  },
  {
    id: 'cor',
    stam: 'cor',
    herkomst: 'Latijn',
    stamBetekenis: 'hart',
    weetje: 'Courage komt van hart, want moed zat voor de Romeinen niet in je hoofd.',
    leden: {
      es: { woord: 'corazón', nl: 'hart' },
      fr: { woord: 'cœur', nl: 'hart' },
      it: { woord: 'cuore', nl: 'hart' },
      pt: { woord: 'coração', nl: 'hart' },
      en: { woord: 'courage', nl: 'moed' },
    },
  },
  {
    id: 'caput',
    stam: 'caput',
    herkomst: 'Latijn',
    stamBetekenis: 'hoofd',
    weetje: 'Een chef is letterlijk het hoofd van de zaak, en een kapitein het hoofd van het schip.',
    leden: {
      es: { woord: 'cabeza', nl: 'hoofd' },
      it: { woord: 'capo', nl: 'hoofd, baas' },
      pt: { woord: 'cabeça', nl: 'hoofd' },
      fr: { woord: 'chef', nl: 'hoofd, baas' },
      en: { woord: 'captain', nl: 'kapitein' },
    },
  },
  {
    id: 'oculus',
    stam: 'oculus',
    herkomst: 'Latijn',
    stamBetekenis: 'oog',
    weetje: 'Een monocle is één oog, en een oculist kijkt er beroepshalve in.',
    leden: {
      es: { woord: 'ojo', nl: 'oog' },
      fr: { woord: 'œil', nl: 'oog' },
      it: { woord: 'occhio', nl: 'oog' },
      pt: { woord: 'olho', nl: 'oog' },
      en: { woord: 'ocular', nl: 'van het oog' },
    },
  },
  {
    id: 'dens',
    stam: 'dens',
    herkomst: 'Latijn',
    stamBetekenis: 'tand',
    weetje: 'De tandarts heet overal naar dens, dus dental, diente en dente zijn dezelfde kies.',
    leden: {
      es: { woord: 'diente', nl: 'tand' },
      fr: { woord: 'dent', nl: 'tand' },
      it: { woord: 'dente', nl: 'tand' },
      pt: { woord: 'dente', nl: 'tand' },
      en: { woord: 'dental', nl: 'tandheelkundig' },
    },
  },
  {
    id: 'pes',
    stam: 'pes',
    herkomst: 'Latijn',
    stamBetekenis: 'voet',
    weetje: 'Een pedaal trap je met je voet, en een voetganger heet daarom pedestrian.',
    leden: {
      es: { woord: 'pie', nl: 'voet' },
      fr: { woord: 'pied', nl: 'voet' },
      it: { woord: 'piede', nl: 'voet' },
      pt: { woord: 'pé', nl: 'voet' },
      en: { woord: 'pedal', nl: 'pedaal' },
    },
  },

  // ─── Werkwoorden ─────────────────────────────────────────────────────
  {
    id: 'esse',
    stam: 'esse',
    herkomst: 'Latijn',
    stamBetekenis: 'zijn',
    weetje: 'Ser, essere en être zijn hetzelfde rommelige werkwoord dat in elke taal onregelmatig bleef.',
    leden: {
      es: { woord: 'ser', nl: 'zijn' },
      fr: { woord: 'être', nl: 'zijn' },
      it: { woord: 'essere', nl: 'zijn' },
      pt: { woord: 'ser', nl: 'zijn' },
      en: { woord: 'essence', nl: 'wezen, kern' },
    },
  },
  {
    id: 'habere',
    stam: 'habere',
    herkomst: 'Latijn',
    stamBetekenis: 'hebben, vasthouden',
    weetje: 'Een gewoonte heet habit omdat je haar hebt en maar niet loslaat.',
    leden: {
      es: { woord: 'haber', nl: 'hebben, er zijn' },
      fr: { woord: 'avoir', nl: 'hebben' },
      it: { woord: 'avere', nl: 'hebben' },
      pt: { woord: 'haver', nl: 'hebben, er zijn' },
      en: { woord: 'habit', nl: 'gewoonte' },
    },
  },
  {
    id: 'venire',
    stam: 'venire',
    herkomst: 'Latijn',
    stamBetekenis: 'komen',
    weetje: 'De advent is de komst, en dat is exact wat venir betekent.',
    leden: {
      es: { woord: 'venir', nl: 'komen' },
      fr: { woord: 'venir', nl: 'komen' },
      it: { woord: 'venire', nl: 'komen' },
      pt: { woord: 'vir', nl: 'komen' },
      en: { woord: 'advent', nl: 'komst, aankomst' },
    },
  },
  {
    id: 'partire',
    stam: 'partire',
    herkomst: 'Latijn',
    stamBetekenis: 'vertrekken, verdelen',
    weetje: 'Vertrekken is in vier talen hetzelfde woord, dus wie partir kent kan overal weg.',
    leden: {
      es: { woord: 'partir', nl: 'vertrekken' },
      fr: { woord: 'partir', nl: 'vertrekken' },
      it: { woord: 'partire', nl: 'vertrekken' },
      pt: { woord: 'partir', nl: 'vertrekken' },
      en: { woord: 'depart', nl: 'vertrekken' },
    },
  },
  {
    id: 'videre',
    stam: 'videre',
    herkomst: 'Latijn',
    stamBetekenis: 'zien',
    weetje: 'Video betekent letterlijk ik zie.',
    leden: {
      es: { woord: 'ver', nl: 'zien' },
      fr: { woord: 'voir', nl: 'zien' },
      it: { woord: 'vedere', nl: 'zien' },
      pt: { woord: 'ver', nl: 'zien' },
      en: { woord: 'video', nl: 'video, beeld' },
    },
  },
  {
    id: 'dicere',
    stam: 'dicere',
    herkomst: 'Latijn',
    stamBetekenis: 'zeggen',
    weetje: 'Een woordenboek heet dictionary omdat het opsomt hoe je alles zegt.',
    leden: {
      es: { woord: 'decir', nl: 'zeggen' },
      fr: { woord: 'dire', nl: 'zeggen' },
      it: { woord: 'dire', nl: 'zeggen' },
      pt: { woord: 'dizer', nl: 'zeggen' },
      en: { woord: 'dictionary', nl: 'woordenboek' },
    },
  },
  {
    id: 'facere',
    stam: 'facere',
    herkomst: 'Latijn',
    stamBetekenis: 'doen, maken',
    weetje: 'Het Spaanse hacer begint met een h omdat de f daar ooit wegzakte tot een zuchtje.',
    leden: {
      es: { woord: 'hacer', nl: 'doen, maken' },
      fr: { woord: 'faire', nl: 'doen, maken' },
      it: { woord: 'fare', nl: 'doen, maken' },
      pt: { woord: 'fazer', nl: 'doen, maken' },
      en: { woord: 'factory', nl: 'fabriek' },
    },
  },
  {
    id: 'amare',
    stam: 'amare',
    herkomst: 'Latijn',
    stamBetekenis: 'liefhebben',
    weetje: 'Een amateur doet iets uit pure liefde en niet voor het geld.',
    leden: {
      es: { woord: 'amar', nl: 'liefhebben' },
      fr: { woord: 'aimer', nl: 'houden van' },
      it: { woord: 'amare', nl: 'liefhebben' },
      pt: { woord: 'amar', nl: 'liefhebben' },
      en: { woord: 'amateur', nl: 'liefhebber' },
    },
  },
  {
    id: 'dormire',
    stam: 'dormire',
    herkomst: 'Latijn',
    stamBetekenis: 'slapen',
    weetje: 'Een dormitory is een slaapzaal, dus dormir slaapt in het Engels gewoon door.',
    leden: {
      es: { woord: 'dormir', nl: 'slapen' },
      fr: { woord: 'dormir', nl: 'slapen' },
      it: { woord: 'dormire', nl: 'slapen' },
      pt: { woord: 'dormir', nl: 'slapen' },
      en: { woord: 'dormitory', nl: 'slaapzaal' },
    },
  },
  {
    id: 'tripalium',
    stam: 'tripalium',
    herkomst: 'Latijn',
    stamBetekenis: 'martelwerktuig van drie palen',
    weetje: 'Werken heet in het Spaans en het Frans naar een Romeins martelwerktuig, dus dat gevoel op maandag is niet nieuw.',
    leden: {
      es: { woord: 'trabajo', nl: 'werk' },
      fr: { woord: 'travail', nl: 'werk' },
      pt: { woord: 'trabalho', nl: 'werk' },
      it: { woord: 'travaglio', nl: 'gezwoeg, kwelling' },
      en: { woord: 'travail', nl: 'zwaar gezwoeg' },
    },
  },

  // ─── Taal, school en reizen ──────────────────────────────────────────
  {
    id: 'lingua',
    stam: 'lingua',
    herkomst: 'Latijn',
    stamBetekenis: 'tong',
    weetje: 'Taal en tong zijn hetzelfde woord, want je spreekt met wat er in je mond ligt.',
    leden: {
      es: { woord: 'lengua', nl: 'tong, taal' },
      fr: { woord: 'langue', nl: 'tong, taal' },
      it: { woord: 'lingua', nl: 'tong, taal' },
      pt: { woord: 'língua', nl: 'tong, taal' },
      en: { woord: 'language', nl: 'taal' },
    },
  },
  {
    id: 'nomen',
    stam: 'nomen',
    herkomst: 'Latijn',
    stamBetekenis: 'naam',
    weetje: 'Naam, name en nome lijken op elkaar omdat het woord ouder is dan Latijn en Germaans samen.',
    leden: {
      es: { woord: 'nombre', nl: 'naam' },
      fr: { woord: 'nom', nl: 'naam' },
      it: { woord: 'nome', nl: 'naam' },
      pt: { woord: 'nome', nl: 'naam' },
      en: { woord: 'name', nl: 'naam' },
      de: { woord: 'Name', nl: 'naam' },
    },
  },
  {
    id: 'liber',
    stam: 'liber',
    herkomst: 'Latijn',
    stamBetekenis: 'boombast waarop men schreef',
    weetje: 'Een libro was oorspronkelijk de bast van een boom, want daar krabbelde men de eerste teksten op.',
    leden: {
      es: { woord: 'libro', nl: 'boek' },
      fr: { woord: 'livre', nl: 'boek' },
      it: { woord: 'libro', nl: 'boek' },
      pt: { woord: 'livro', nl: 'boek' },
      en: { woord: 'library', nl: 'bibliotheek' },
    },
  },
  {
    id: 'libertas',
    stam: 'liber',
    herkomst: 'Latijn',
    stamBetekenis: 'vrij',
    weetje: 'Libre en livre schelen maar één letter, dus vrijheid en een boek liggen in het Frans dicht bij elkaar.',
    leden: {
      es: { woord: 'libre', nl: 'vrij' },
      fr: { woord: 'libre', nl: 'vrij' },
      it: { woord: 'libero', nl: 'vrij' },
      pt: { woord: 'livre', nl: 'vrij' },
      en: { woord: 'liberty', nl: 'vrijheid' },
    },
  },
  {
    id: 'mare',
    stam: 'mare',
    herkomst: 'Latijn',
    stamBetekenis: 'zee',
    weetje: 'Alles wat met de zee te maken heeft heet maritiem, van mar tot mer.',
    leden: {
      es: { woord: 'mar', nl: 'zee' },
      fr: { woord: 'mer', nl: 'zee' },
      it: { woord: 'mare', nl: 'zee' },
      pt: { woord: 'mar', nl: 'zee' },
      en: { woord: 'marine', nl: 'van de zee' },
    },
  },
  {
    id: 'terra',
    stam: 'terra',
    herkomst: 'Latijn',
    stamBetekenis: 'aarde, land',
    weetje: 'Terras, terrein en territorium zijn stuk voor stuk gewoon stukjes grond.',
    leden: {
      es: { woord: 'tierra', nl: 'aarde, land' },
      fr: { woord: 'terre', nl: 'aarde, land' },
      it: { woord: 'terra', nl: 'aarde, land' },
      pt: { woord: 'terra', nl: 'aarde, land' },
      en: { woord: 'terrain', nl: 'terrein' },
    },
  },
  {
    id: 'insula',
    stam: 'insula',
    herkomst: 'Latijn',
    stamBetekenis: 'eiland',
    weetje: 'Het dakje op île staat precies op de plek waar ooit een s stond, zoals je die in isla nog gewoon ziet.',
    leden: {
      es: { woord: 'isla', nl: 'eiland' },
      fr: { woord: 'île', nl: 'eiland' },
      it: { woord: 'isola', nl: 'eiland' },
      pt: { woord: 'ilha', nl: 'eiland' },
      en: { woord: 'peninsula', nl: 'schiereiland' },
    },
  },
  {
    id: 'montanea',
    stam: 'montanea',
    herkomst: 'Latijn',
    stamBetekenis: 'bergachtig gebied',
    weetje: 'Montagne, montaña en mountain zijn dezelfde berg met een ander accent.',
    leden: {
      es: { woord: 'montaña', nl: 'berg' },
      fr: { woord: 'montagne', nl: 'berg' },
      it: { woord: 'montagna', nl: 'berg' },
      pt: { woord: 'montanha', nl: 'berg' },
      en: { woord: 'mountain', nl: 'berg' },
    },
  },
  {
    id: 'viaticum',
    stam: 'viaticum',
    herkomst: 'Latijn',
    stamBetekenis: 'reisgeld voor onderweg',
    weetje: 'Een voyage was ooit het geld dat je voor onderweg meekreeg, en pas later de reis zelf.',
    leden: {
      es: { woord: 'viaje', nl: 'reis' },
      fr: { woord: 'voyage', nl: 'reis' },
      it: { woord: 'viaggio', nl: 'reis' },
      pt: { woord: 'viagem', nl: 'reis' },
      en: { woord: 'voyage', nl: 'zeereis' },
    },
  },
  {
    id: 'trahere',
    stam: 'trahere',
    herkomst: 'Latijn',
    stamBetekenis: 'trekken',
    weetje: 'Een trein heet naar trekken, want de locomotief sleept de rest gewoon achter zich aan.',
    leden: {
      fr: { woord: 'train', nl: 'trein' },
      es: { woord: 'tren', nl: 'trein' },
      it: { woord: 'treno', nl: 'trein' },
      pt: { woord: 'trem', nl: 'trein' },
      en: { woord: 'train', nl: 'trein' },
    },
  },

  // ─── Beleefdheid en begroetingen ─────────────────────────────────────
  {
    id: 'salus',
    stam: 'salus',
    herkomst: 'Latijn',
    stamBetekenis: 'gezondheid, heil',
    weetje: 'Iemand groeten was bij de Romeinen niets anders dan hem gezondheid toewensen.',
    leden: {
      fr: { woord: 'salut', nl: 'hoi, groet' },
      it: { woord: 'salve', nl: 'hallo' },
      es: { woord: 'salud', nl: 'gezondheid, proost' },
      pt: { woord: 'saúde', nl: 'gezondheid, proost' },
      en: { woord: 'salute', nl: 'groeten, saluut' },
    },
  },
  {
    id: 'gratia',
    stam: 'gratia',
    herkomst: 'Latijn',
    stamBetekenis: 'gunst, dank',
    weetje: 'Gracias en grazie vragen eigenlijk om genade, en gratis betekent uit pure goedheid.',
    leden: {
      es: { woord: 'gracias', nl: 'dank je' },
      it: { woord: 'grazie', nl: 'dank je' },
      pt: { woord: 'graças', nl: 'dankzij, dank' },
      fr: { woord: 'grâce', nl: 'gratie, genade' },
      en: { woord: 'gratitude', nl: 'dankbaarheid' },
    },
  },
  {
    id: 'bonus',
    stam: 'bonus',
    herkomst: 'Latijn',
    stamBetekenis: 'goed',
    weetje: 'Een bonus is letterlijk iets goeds, net als bueno en buono.',
    leden: {
      es: { woord: 'bueno', nl: 'goed' },
      fr: { woord: 'bon', nl: 'goed' },
      it: { woord: 'buono', nl: 'goed' },
      pt: { woord: 'bom', nl: 'goed' },
      en: { woord: 'bonus', nl: 'bonus, iets goeds' },
    },
  },
  {
    id: 'malus',
    stam: 'malus',
    herkomst: 'Latijn',
    stamBetekenis: 'slecht',
    weetje: 'Malaria betekent slechte lucht, want men dacht dat je ziek werd van de moeraslucht.',
    leden: {
      es: { woord: 'malo', nl: 'slecht' },
      fr: { woord: 'mal', nl: 'slecht, pijn' },
      it: { woord: 'male', nl: 'slecht, pijn' },
      pt: { woord: 'mau', nl: 'slecht' },
      en: { woord: 'malicious', nl: 'kwaadaardig' },
    },
  },
  {
    id: 'placere',
    stam: 'placere',
    herkomst: 'Latijn',
    stamBetekenis: 'behagen, bevallen',
    weetje: 'Het Franse plaît betekent behaagt, dus alstublieft is eigenlijk als het u bevalt.',
    leden: {
      fr: { woord: 'plaît', nl: 'behaagt, in alstublieft' },
      en: { woord: 'please', nl: 'alsjeblieft' },
      it: { woord: 'piacere', nl: 'plezier, aangenaam' },
      es: { woord: 'placer', nl: 'genot, plezier' },
      pt: { woord: 'prazer', nl: 'genot, aangenaam' },
    },
  },
  {
    id: 'favor',
    stam: 'favor',
    herkomst: 'Latijn',
    stamBetekenis: 'gunst',
    weetje: 'Por favor en per favore vragen letterlijk om een gunst, precies zoals wij alsjeblieft bedoelen.',
    leden: {
      es: { woord: 'por favor', nl: 'alsjeblieft' },
      pt: { woord: 'por favor', nl: 'alsjeblieft' },
      it: { woord: 'per favore', nl: 'alsjeblieft' },
      fr: { woord: 'faveur', nl: 'gunst' },
      en: { woord: 'favour', nl: 'gunst' },
    },
  },
  {
    id: 'sclavus',
    stam: 'sclavus',
    herkomst: 'Latijn',
    stamBetekenis: 'slaaf',
    weetje: 'Ciao komt van een oud Venetiaans zinnetje waarin je jezelf iemands slaaf noemde.',
    leden: {
      it: { woord: 'ciao', nl: 'hoi, doei' },
      es: { woord: 'esclavo', nl: 'slaaf' },
      fr: { woord: 'esclave', nl: 'slaaf' },
      pt: { woord: 'escravo', nl: 'slaaf' },
      en: { woord: 'slave', nl: 'slaaf' },
      de: { woord: 'Sklave', nl: 'slaaf' },
    },
  },

  // ─── Grieks ──────────────────────────────────────────────────────────
  {
    id: 'schola',
    stam: 'skholē',
    herkomst: 'Grieks',
    stamBetekenis: 'vrije tijd om te studeren',
    weetje: 'School betekende bij de Grieken vrije tijd, want alleen wie tijd over had kon nadenken.',
    leden: {
      es: { woord: 'escuela', nl: 'school' },
      fr: { woord: 'école', nl: 'school' },
      it: { woord: 'scuola', nl: 'school' },
      pt: { woord: 'escola', nl: 'school' },
      en: { woord: 'school', nl: 'school' },
      de: { woord: 'Schule', nl: 'school' },
    },
  },
  {
    id: 'musica',
    stam: 'mousikē',
    herkomst: 'Grieks',
    stamBetekenis: 'kunst van de muzen',
    weetje: 'Muziek is de kunst van de muzen, negen Griekse dames met opvallend veel talent.',
    leden: {
      es: { woord: 'música', nl: 'muziek' },
      fr: { woord: 'musique', nl: 'muziek' },
      it: { woord: 'musica', nl: 'muziek' },
      pt: { woord: 'música', nl: 'muziek' },
      en: { woord: 'music', nl: 'muziek' },
      de: { woord: 'Musik', nl: 'muziek' },
    },
  },
  {
    id: 'charta',
    stam: 'khartēs',
    herkomst: 'Grieks',
    stamBetekenis: 'blad papyrus',
    weetje: 'Kaart, carta en Karte waren ooit gewoon een vel papier zonder iets erop.',
    leden: {
      es: { woord: 'carta', nl: 'brief, kaart' },
      it: { woord: 'carta', nl: 'papier, kaart' },
      fr: { woord: 'carte', nl: 'kaart' },
      pt: { woord: 'carta', nl: 'brief' },
      en: { woord: 'card', nl: 'kaart' },
      de: { woord: 'Karte', nl: 'kaart' },
    },
  },
  {
    id: 'ekklesia',
    stam: 'ekklēsia',
    herkomst: 'Grieks',
    stamBetekenis: 'bijeenkomst van het volk',
    weetje: 'Een kerk heette in het Grieks de bijeenkomst, dus het gebouw kwam pas veel later.',
    leden: {
      es: { woord: 'iglesia', nl: 'kerk' },
      fr: { woord: 'église', nl: 'kerk' },
      it: { woord: 'chiesa', nl: 'kerk' },
      pt: { woord: 'igreja', nl: 'kerk' },
      en: { woord: 'ecclesiastical', nl: 'kerkelijk' },
    },
  },
  {
    id: 'oryza',
    stam: 'oryza',
    herkomst: 'Grieks',
    stamBetekenis: 'rijst',
    weetje: 'Rijst reisde via het Arabische ar ruzz naar Spanje en werd daar arroz, inclusief het Arabische lidwoord.',
    leden: {
      es: { woord: 'arroz', nl: 'rijst' },
      pt: { woord: 'arroz', nl: 'rijst' },
      it: { woord: 'riso', nl: 'rijst' },
      fr: { woord: 'riz', nl: 'rijst' },
      en: { woord: 'rice', nl: 'rijst' },
      de: { woord: 'Reis', nl: 'rijst' },
    },
  },
  {
    id: 'pharmakon',
    stam: 'pharmakon',
    herkomst: 'Grieks',
    stamBetekenis: 'kruid, middel',
    weetje: 'Pharmakon betekende zowel medicijn als gif, dus alleen de dosis maakte het verschil.',
    leden: {
      es: { woord: 'farmacia', nl: 'apotheek' },
      fr: { woord: 'pharmacie', nl: 'apotheek' },
      it: { woord: 'farmacia', nl: 'apotheek' },
      pt: { woord: 'farmácia', nl: 'apotheek' },
      en: { woord: 'pharmacy', nl: 'apotheek' },
    },
  },

  // ─── Germaans: waar Nederlands, Duits en Engels samenvallen ──────────
  {
    id: 'watar',
    stam: 'watar',
    herkomst: 'Germaans',
    stamBetekenis: 'water',
    weetje: 'Water, Wasser en water zijn hetzelfde woord, dus wie Nederlands kent heeft hier niets te leren.',
    leden: {
      de: { woord: 'Wasser', nl: 'water' },
      en: { woord: 'water', nl: 'water' },
    },
  },
  {
    id: 'husa',
    stam: 'husa',
    herkomst: 'Germaans',
    stamBetekenis: 'huis',
    weetje: 'Huis, Haus en house klinken bijna gelijk omdat ze nooit uit elkaar zijn gegroeid.',
    leden: {
      de: { woord: 'Haus', nl: 'huis' },
      en: { woord: 'house', nl: 'huis' },
    },
  },
  {
    id: 'bokiz',
    stam: 'bōks',
    herkomst: 'Germaans',
    stamBetekenis: 'beukenhouten schrijfplankje',
    weetje: 'Boek, Buch en book gaan terug op de beuk, want in beukenhout kerfde men de eerste letters.',
    leden: {
      de: { woord: 'Buch', nl: 'boek' },
      en: { woord: 'book', nl: 'boek' },
    },
  },
  {
    id: 'meluk',
    stam: 'meluk',
    herkomst: 'Germaans',
    stamBetekenis: 'melk',
    weetje: 'Melk, Milch en milk verraden dat de koe al bij onze verste voorouders in de wei stond.',
    leden: {
      de: { woord: 'Milch', nl: 'melk' },
      en: { woord: 'milk', nl: 'melk' },
    },
  },
  {
    id: 'brauda',
    stam: 'brauda',
    herkomst: 'Germaans',
    stamBetekenis: 'brood',
    weetje: 'Brood, Brot en bread komen alle drie uit hetzelfde deeg.',
    leden: {
      de: { woord: 'Brot', nl: 'brood' },
      en: { woord: 'bread', nl: 'brood' },
    },
  },
  {
    id: 'handuz',
    stam: 'handuz',
    herkomst: 'Germaans',
    stamBetekenis: 'hand',
    weetje: 'Hand, Hand en hand zijn in drie talen precies hetzelfde, en zo makkelijk is het zelden.',
    leden: {
      de: { woord: 'Hand', nl: 'hand' },
      en: { woord: 'hand', nl: 'hand' },
    },
  },

  // ─── Germaanse en Frankische woorden die de Romaanse talen binnendrongen ──
  {
    id: 'werra',
    stam: 'werra',
    herkomst: 'Frankisch',
    stamBetekenis: 'strijd, verwarring',
    weetje: 'Guerre en guerra komen uit een Frankisch woord voor herrie, want oorlog is vooral chaos.',
    leden: {
      fr: { woord: 'guerre', nl: 'oorlog' },
      es: { woord: 'guerra', nl: 'oorlog' },
      it: { woord: 'guerra', nl: 'oorlog' },
      pt: { woord: 'guerra', nl: 'oorlog' },
      en: { woord: 'war', nl: 'oorlog' },
    },
  },
  {
    id: 'blank',
    stam: 'blank',
    herkomst: 'Frankisch',
    stamBetekenis: 'blinkend, wit',
    weetje: 'Blanc, blanco en bianco komen van ons blank, want blinkend en wit waren voor Germanen hetzelfde idee.',
    leden: {
      fr: { woord: 'blanc', nl: 'wit' },
      es: { woord: 'blanco', nl: 'wit' },
      it: { woord: 'bianco', nl: 'wit' },
      pt: { woord: 'branco', nl: 'wit' },
      en: { woord: 'blank', nl: 'blanco, leeg' },
      de: { woord: 'blank', nl: 'blinkend' },
    },
  },
  {
    id: 'gardo',
    stam: 'gardo',
    herkomst: 'Frankisch',
    stamBetekenis: 'omheind stuk grond',
    weetje: 'Tuin, Garten, garden en jardin komen alle vier uit hetzelfde Germaanse hek.',
    leden: {
      fr: { woord: 'jardin', nl: 'tuin' },
      es: { woord: 'jardín', nl: 'tuin' },
      it: { woord: 'giardino', nl: 'tuin' },
      pt: { woord: 'jardim', nl: 'tuin' },
      en: { woord: 'garden', nl: 'tuin' },
      de: { woord: 'Garten', nl: 'tuin' },
    },
  },
  {
    id: 'grisi',
    stam: 'grīs',
    herkomst: 'Frankisch',
    stamBetekenis: 'grijs',
    weetje: 'Gris en grigio zijn Germaanse verstekelingen in Romaanse talen, want grijs bleek een Germaanse kleur.',
    leden: {
      fr: { woord: 'gris', nl: 'grijs' },
      es: { woord: 'gris', nl: 'grijs' },
      it: { woord: 'grigio', nl: 'grijs' },
      en: { woord: 'grey', nl: 'grijs' },
      de: { woord: 'grau', nl: 'grijs' },
    },
  },
  {
    id: 'blao',
    stam: 'blao',
    herkomst: 'Frankisch',
    stamBetekenis: 'blauw',
    weetje: 'Bleu is gewoon ons blauw dat ooit de Franse grens over wandelde.',
    leden: {
      fr: { woord: 'bleu', nl: 'blauw' },
      it: { woord: 'blu', nl: 'blauw' },
      en: { woord: 'blue', nl: 'blauw' },
      de: { woord: 'blau', nl: 'blauw' },
    },
  },
  {
    id: 'riki',
    stam: 'rīki',
    herkomst: 'Germaans',
    stamBetekenis: 'machtig',
    weetje: 'Rijk betekende eerst machtig en pas later vol met geld.',
    leden: {
      fr: { woord: 'riche', nl: 'rijk' },
      es: { woord: 'rico', nl: 'rijk, lekker' },
      it: { woord: 'ricco', nl: 'rijk' },
      pt: { woord: 'rico', nl: 'rijk' },
      en: { woord: 'rich', nl: 'rijk' },
      de: { woord: 'reich', nl: 'rijk' },
    },
  },
  {
    id: 'banki',
    stam: 'banki',
    herkomst: 'Germaans',
    stamBetekenis: 'bank, plank',
    weetje: 'De bank waar je geld staat heet naar de plank waarop geldwisselaars hun munten uitstalden.',
    leden: {
      fr: { woord: 'banque', nl: 'bank' },
      es: { woord: 'banco', nl: 'bank' },
      it: { woord: 'banca', nl: 'bank' },
      pt: { woord: 'banco', nl: 'bank' },
      en: { woord: 'bank', nl: 'bank' },
      de: { woord: 'Bank', nl: 'bank' },
    },
  },
  {
    id: 'suppa',
    stam: 'suppa',
    herkomst: 'Germaans',
    stamBetekenis: 'ingedoopt brood',
    weetje: 'Soep heet naar het brood dat je erin soopte, en zo kwam het woord in half Europa op tafel.',
    leden: {
      fr: { woord: 'soupe', nl: 'soep' },
      es: { woord: 'sopa', nl: 'soep' },
      it: { woord: 'zuppa', nl: 'soep' },
      pt: { woord: 'sopa', nl: 'soep' },
      en: { woord: 'soup', nl: 'soep' },
      de: { woord: 'Suppe', nl: 'soep' },
    },
  },
  {
    id: 'nord',
    stam: 'nord',
    herkomst: 'Germaans',
    stamBetekenis: 'noord',
    weetje: 'De windstreken zijn Germaans, dus zelfs de Italianen wijzen met een Noord Europees woord naar boven.',
    leden: {
      fr: { woord: 'nord', nl: 'noorden' },
      es: { woord: 'norte', nl: 'noorden' },
      it: { woord: 'nord', nl: 'noorden' },
      pt: { woord: 'norte', nl: 'noorden' },
      en: { woord: 'north', nl: 'noorden' },
      de: { woord: 'Norden', nl: 'noorden' },
    },
  },

  // ─── Arabisch ────────────────────────────────────────────────────────
  {
    id: 'sukkar',
    stam: 'sukkar',
    herkomst: 'Arabisch',
    stamBetekenis: 'suiker',
    weetje: 'Suiker kwam met Arabische handelaren naar Europa en nam zijn naam gewoon mee.',
    leden: {
      es: { woord: 'azúcar', nl: 'suiker' },
      fr: { woord: 'sucre', nl: 'suiker' },
      it: { woord: 'zucchero', nl: 'suiker' },
      pt: { woord: 'açúcar', nl: 'suiker' },
      en: { woord: 'sugar', nl: 'suiker' },
      de: { woord: 'Zucker', nl: 'suiker' },
    },
  },
  {
    id: 'azzayt',
    stam: 'az-zayt',
    herkomst: 'Arabisch',
    stamBetekenis: 'de olijfolie',
    weetje: 'In aceite en azeite zit het Arabische lidwoord al nog altijd vastgeplakt aan het woord.',
    leden: {
      es: { woord: 'aceite', nl: 'olie' },
      pt: { woord: 'azeite', nl: 'olijfolie' },
    },
  },
  {
    id: 'aljabr',
    stam: 'al-jabr',
    herkomst: 'Arabisch',
    stamBetekenis: 'het samenvoegen van gebroken delen',
    weetje: 'Algebra dankt zijn naam aan een boek van de geleerde al Chwarizmi, wiens naam ook in algoritme zit.',
    leden: {
      es: { woord: 'álgebra', nl: 'algebra' },
      fr: { woord: 'algèbre', nl: 'algebra' },
      it: { woord: 'algebra', nl: 'algebra' },
      pt: { woord: 'álgebra', nl: 'algebra' },
      en: { woord: 'algebra', nl: 'algebra' },
      de: { woord: 'Algebra', nl: 'algebra' },
    },
  },
  {
    id: 'naranj',
    stam: 'nāranj',
    herkomst: 'Arabisch',
    stamBetekenis: 'sinaasappel',
    weetje: 'In het Frans schoof de n van naranja stiekem naar het lidwoord, en zo werd het une orange.',
    leden: {
      es: { woord: 'naranja', nl: 'sinaasappel' },
      fr: { woord: 'orange', nl: 'sinaasappel, oranje' },
      it: { woord: 'arancia', nl: 'sinaasappel' },
      pt: { woord: 'laranja', nl: 'sinaasappel' },
      en: { woord: 'orange', nl: 'sinaasappel, oranje' },
      de: { woord: 'Orange', nl: 'sinaasappel' },
    },
  },
  {
    id: 'alkuhl',
    stam: 'al-kuhl',
    herkomst: 'Arabisch',
    stamBetekenis: 'fijn poeder voor de ogen',
    weetje: 'Alcohol betekende eerst fijn oogpoeder en pas eeuwen later de sterke drank.',
    leden: {
      es: { woord: 'alcohol', nl: 'alcohol' },
      fr: { woord: 'alcool', nl: 'alcohol' },
      it: { woord: 'alcol', nl: 'alcohol' },
      pt: { woord: 'álcool', nl: 'alcohol' },
      en: { woord: 'alcohol', nl: 'alcohol' },
      de: { woord: 'Alkohol', nl: 'alcohol' },
    },
  },
  {
    id: 'qahwa',
    stam: 'qahwa',
    herkomst: 'Arabisch',
    stamBetekenis: 'koffie',
    weetje: 'Koffie ging van het Arabische qahwa via het Turkse kahve heel Europa door.',
    leden: {
      es: { woord: 'café', nl: 'koffie, café' },
      fr: { woord: 'café', nl: 'koffie, café' },
      it: { woord: 'caffè', nl: 'koffie, café' },
      pt: { woord: 'café', nl: 'koffie, café' },
      en: { woord: 'coffee', nl: 'koffie' },
      de: { woord: 'Kaffee', nl: 'koffie' },
    },
  },
  {
    id: 'laymun',
    stam: 'laymūn',
    herkomst: 'Arabisch',
    stamBetekenis: 'citroen',
    weetje: 'De citroen kwam met Arabische tuinbouw naar Europa, en zijn naam reisde vrolijk mee.',
    leden: {
      es: { woord: 'limón', nl: 'citroen' },
      it: { woord: 'limone', nl: 'citroen' },
      pt: { woord: 'limão', nl: 'citroen' },
      en: { woord: 'lemon', nl: 'citroen' },
      de: { woord: 'Limone', nl: 'citroen' },
    },
  },
  {
    id: 'alqutn',
    stam: 'al-qutn',
    herkomst: 'Arabisch',
    stamBetekenis: 'de katoen',
    weetje: 'Katoen heet in het Spaans algodón, met het Arabische lidwoord er nog stevig aan vast.',
    leden: {
      es: { woord: 'algodón', nl: 'katoen' },
      pt: { woord: 'algodão', nl: 'katoen' },
      fr: { woord: 'coton', nl: 'katoen' },
      it: { woord: 'cotone', nl: 'katoen' },
      en: { woord: 'cotton', nl: 'katoen' },
    },
  },
  {
    id: 'lazaward',
    stam: 'lāzaward',
    herkomst: 'Arabisch',
    stamBetekenis: 'lapis lazuli, blauwe steen',
    weetje: 'Azul komt van een blauwe edelsteen, en het Franse azur is dezelfde kleur uit dezelfde mijn.',
    leden: {
      es: { woord: 'azul', nl: 'blauw' },
      pt: { woord: 'azul', nl: 'blauw' },
      it: { woord: 'azzurro', nl: 'azuurblauw' },
      fr: { woord: 'azur', nl: 'azuurblauw' },
      en: { woord: 'azure', nl: 'azuurblauw' },
    },
  },

  // ─── Vragen, dagen en kleine woordjes uit de eerste les ──────────────
  {
    id: 'hodie',
    stam: 'hodie',
    herkomst: 'Latijn',
    stamBetekenis: 'op deze dag',
    weetje: 'Hodie betekende op deze dag, en het Franse aujourd hui draagt dat stukje hui nog altijd met zich mee.',
    leden: {
      es: { woord: 'hoy', nl: 'vandaag' },
      it: { woord: 'oggi', nl: 'vandaag' },
      pt: { woord: 'hoje', nl: 'vandaag' },
      fr: { woord: 'aujourd\'hui', nl: 'vandaag' },
    },
  },
  {
    id: 'demane',
    stam: 'de mane',
    herkomst: 'Latijn',
    stamBetekenis: 'in de vroege ochtend',
    weetje: 'Morgen betekende letterlijk in de vroegte, want wie morgen zei bedoelde de volgende ochtend.',
    leden: {
      es: { woord: 'mañana', nl: 'morgen, ochtend' },
      fr: { woord: 'demain', nl: 'morgen' },
      it: { woord: 'domani', nl: 'morgen' },
      pt: { woord: 'amanhã', nl: 'morgen' },
    },
  },
  {
    id: 'quando',
    stam: 'quando',
    herkomst: 'Latijn',
    stamBetekenis: 'wanneer',
    weetje: 'Quando, quand en quando zijn in tweeduizend jaar nauwelijks van hun plek gekomen.',
    leden: {
      es: { woord: 'cuándo', nl: 'wanneer' },
      fr: { woord: 'quand', nl: 'wanneer' },
      it: { woord: 'quando', nl: 'wanneer' },
      pt: { woord: 'quando', nl: 'wanneer' },
    },
  },
  {
    id: 'ubi',
    stam: 'ubi',
    herkomst: 'Latijn',
    stamBetekenis: 'waar',
    weetje: 'Où, dove en onde vragen alle drie waar, en dat piepkleine woordje veranderde nauwelijks.',
    leden: {
      fr: { woord: 'où', nl: 'waar' },
      it: { woord: 'dove', nl: 'waar' },
      pt: { woord: 'onde', nl: 'waar' },
      es: { woord: 'dónde', nl: 'waar' },
    },
  },
  {
    id: 'quomodo',
    stam: 'quomodo',
    herkomst: 'Latijn',
    stamBetekenis: 'op welke manier',
    weetje: 'Como, come en comment vragen letterlijk op welke manier iets gaat.',
    leden: {
      es: { woord: 'cómo', nl: 'hoe' },
      fr: { woord: 'comment', nl: 'hoe' },
      it: { woord: 'come', nl: 'hoe, zoals' },
      pt: { woord: 'como', nl: 'hoe' },
    },
  },
  {
    id: 'non',
    stam: 'non',
    herkomst: 'Latijn',
    stamBetekenis: 'niet',
    weetje: 'Nee is in vier talen nog steeds hetzelfde Latijnse woordje, dus dat leer je maar één keer.',
    leden: {
      es: { woord: 'no', nl: 'nee, niet' },
      fr: { woord: 'non', nl: 'nee' },
      it: { woord: 'no', nl: 'nee' },
      pt: { woord: 'não', nl: 'nee, niet' },
    },
  },
  {
    id: 'addeum',
    stam: 'ad deum',
    herkomst: 'Latijn',
    stamBetekenis: 'aan God',
    weetje: 'Adiós en adieu bevelen je bij het afscheid aan bij God, wat een zware zin is voor gewoon doei.',
    leden: {
      es: { woord: 'adiós', nl: 'dag, tot ziens' },
      fr: { woord: 'adieu', nl: 'vaarwel' },
      it: { woord: 'addio', nl: 'vaarwel' },
      pt: { woord: 'adeus', nl: 'tot ziens' },
    },
  },
  {
    id: 'merces',
    stam: 'merces',
    herkomst: 'Latijn',
    stamBetekenis: 'loon, gunst',
    weetje: 'Merci vraagt eigenlijk om genade, want het woord ging van loon via gunst naar dank.',
    leden: {
      fr: { woord: 'merci', nl: 'dank je wel' },
      es: { woord: 'merced', nl: 'gunst, genade' },
      it: { woord: 'mercé', nl: 'genade' },
      pt: { woord: 'mercê', nl: 'gunst, genade' },
      en: { woord: 'mercy', nl: 'genade' },
    },
  },
  {
    id: 'perdonare',
    stam: 'perdonare',
    herkomst: 'Latijn',
    stamBetekenis: 'volledig kwijtschelden',
    weetje: 'Pardon vragen is letterlijk vragen of iemand het je helemaal weggeeft.',
    leden: {
      es: { woord: 'perdona', nl: 'sorry, pardon' },
      fr: { woord: 'pardon', nl: 'pardon, sorry' },
      it: { woord: 'perdono', nl: 'vergiffenis' },
      pt: { woord: 'perdão', nl: 'vergiffenis, pardon' },
      en: { woord: 'pardon', nl: 'pardon, vergiffenis' },
    },
  },
  {
    id: 'clarus',
    stam: 'clarus',
    herkomst: 'Latijn',
    stamBetekenis: 'helder',
    weetje: 'Als een Spanjaard claro zegt bedoelt hij glashelder, en dat is precies wat natuurlijk betekent.',
    leden: {
      es: { woord: 'claro', nl: 'helder, natuurlijk' },
      fr: { woord: 'clair', nl: 'helder' },
      it: { woord: 'chiaro', nl: 'helder' },
      pt: { woord: 'claro', nl: 'helder, natuurlijk' },
      en: { woord: 'clear', nl: 'helder, duidelijk' },
    },
  },
  {
    id: 'quattuor',
    stam: 'quattuor',
    herkomst: 'Latijn',
    stamBetekenis: 'vier',
    weetje: 'Een kwartier is een vierde deel van een uur, en een kwartet bestaat uit vier spelers.',
    leden: {
      es: { woord: 'cuatro', nl: 'vier' },
      fr: { woord: 'quatre', nl: 'vier' },
      it: { woord: 'quattro', nl: 'vier' },
      pt: { woord: 'quatro', nl: 'vier' },
      en: { woord: 'quarter', nl: 'kwart' },
    },
  },
  {
    id: 'quinque',
    stam: 'quinque',
    herkomst: 'Latijn',
    stamBetekenis: 'vijf',
    weetje: 'Cinco, cinq en cinque klinken heel verschillend maar tellen alle drie tot vijf.',
    leden: {
      es: { woord: 'cinco', nl: 'vijf' },
      fr: { woord: 'cinq', nl: 'vijf' },
      it: { woord: 'cinque', nl: 'vijf' },
      pt: { woord: 'cinco', nl: 'vijf' },
      en: { woord: 'quintet', nl: 'kwintet, vijftal' },
    },
  },
  {
    id: 'decem',
    stam: 'decem',
    herkomst: 'Latijn',
    stamBetekenis: 'tien',
    weetje: 'December was ooit de tiende maand, tot er twee maanden voorgedrongen werden.',
    leden: {
      es: { woord: 'diez', nl: 'tien' },
      fr: { woord: 'dix', nl: 'tien' },
      it: { woord: 'dieci', nl: 'tien' },
      pt: { woord: 'dez', nl: 'tien' },
      en: { woord: 'decade', nl: 'decennium, tiental jaren' },
    },
  },

  // ─── Uitgaan, stad en reizen ─────────────────────────────────────────
  {
    id: 'museum',
    stam: 'mouseion',
    herkomst: 'Grieks',
    stamBetekenis: 'tempel van de muzen',
    weetje: 'Een museum was ooit een tempel voor de muzen, dus je loopt er nog altijd rond bij de godinnen van de kunst.',
    leden: {
      es: { woord: 'museo', nl: 'museum' },
      fr: { woord: 'musée', nl: 'museum' },
      it: { woord: 'museo', nl: 'museum' },
      pt: { woord: 'museu', nl: 'museum' },
      en: { woord: 'museum', nl: 'museum' },
      de: { woord: 'Museum', nl: 'museum' },
    },
  },
  {
    id: 'kinema',
    stam: 'kinēma',
    herkomst: 'Grieks',
    stamBetekenis: 'beweging',
    weetje: 'De bioscoop heet naar het Griekse woord voor beweging, want bewegende beelden waren de hele truc.',
    leden: {
      es: { woord: 'cine', nl: 'bioscoop' },
      fr: { woord: 'cinéma', nl: 'bioscoop' },
      it: { woord: 'cinema', nl: 'bioscoop' },
      pt: { woord: 'cinema', nl: 'bioscoop' },
      en: { woord: 'cinema', nl: 'bioscoop' },
      de: { woord: 'Kino', nl: 'bioscoop' },
    },
  },
  {
    id: 'filmen',
    stam: 'filmen',
    herkomst: 'Germaans',
    stamBetekenis: 'dun vliesje',
    weetje: 'Een film heet naar een dun vliesje, want dat was precies wat er door de projector liep.',
    leden: {
      fr: { woord: 'film', nl: 'film' },
      it: { woord: 'film', nl: 'film' },
      pt: { woord: 'filme', nl: 'film' },
      en: { woord: 'film', nl: 'film' },
      de: { woord: 'Film', nl: 'film' },
    },
  },
  {
    id: 'theatron',
    stam: 'theatron',
    herkomst: 'Grieks',
    stamBetekenis: 'kijkplaats',
    weetje: 'Theatron betekent kijkplaats, dus het publiek zit al drieduizend jaar in de naam verwerkt.',
    leden: {
      es: { woord: 'teatro', nl: 'theater' },
      fr: { woord: 'théâtre', nl: 'theater' },
      it: { woord: 'teatro', nl: 'theater' },
      pt: { woord: 'teatro', nl: 'theater' },
      en: { woord: 'theatre', nl: 'theater' },
      de: { woord: 'Theater', nl: 'theater' },
    },
  },
  {
    id: 'concertare',
    stam: 'concertare',
    herkomst: 'Latijn',
    stamBetekenis: 'samen optreden, wedijveren',
    weetje: 'In een concert wedijveren de instrumenten met elkaar, en dat zit letterlijk in het woord.',
    leden: {
      es: { woord: 'concierto', nl: 'concert' },
      fr: { woord: 'concert', nl: 'concert' },
      it: { woord: 'concerto', nl: 'concert' },
      pt: { woord: 'concerto', nl: 'concert' },
      en: { woord: 'concert', nl: 'concert' },
      de: { woord: 'Konzert', nl: 'concert' },
    },
  },
  {
    id: 'restaurare',
    stam: 'restaurare',
    herkomst: 'Latijn',
    stamBetekenis: 'herstellen, opknappen',
    weetje: 'Het eerste restaurant verkocht een versterkende bouillon die je moest opknappen, en zo kreeg de zaak zijn naam.',
    leden: {
      es: { woord: 'restaurante', nl: 'restaurant' },
      fr: { woord: 'restaurant', nl: 'restaurant' },
      it: { woord: 'ristorante', nl: 'restaurant' },
      pt: { woord: 'restaurante', nl: 'restaurant' },
      en: { woord: 'restaurant', nl: 'restaurant' },
      de: { woord: 'Restaurant', nl: 'restaurant' },
    },
  },
  {
    id: 'hospes',
    stam: 'hospitale',
    herkomst: 'Latijn',
    stamBetekenis: 'gastenverblijf',
    weetje: 'Hotel is hetzelfde woord als hospitaal, alleen sleet het in het Frans veel sneller af.',
    leden: {
      es: { woord: 'hotel', nl: 'hotel' },
      fr: { woord: 'hôtel', nl: 'hotel' },
      it: { woord: 'hotel', nl: 'hotel' },
      pt: { woord: 'hotel', nl: 'hotel' },
      en: { woord: 'hotel', nl: 'hotel' },
      de: { woord: 'Hotel', nl: 'hotel' },
    },
  },
  {
    id: 'statio',
    stam: 'statio',
    herkomst: 'Latijn',
    stamBetekenis: 'het stilstaan',
    weetje: 'Een station is de plek waar de trein even stilstaat, en dat staat gewoon in het woord.',
    leden: {
      es: { woord: 'estación', nl: 'station, seizoen' },
      fr: { woord: 'station', nl: 'station, halte' },
      it: { woord: 'stazione', nl: 'station' },
      pt: { woord: 'estação', nl: 'station, seizoen' },
      en: { woord: 'station', nl: 'station' },
    },
  },
  {
    id: 'omnibus',
    stam: 'omnibus',
    herkomst: 'Latijn',
    stamBetekenis: 'voor iedereen',
    weetje: 'De bus heet naar omnibus, wat voor iedereen betekent, dus de naam belooft nog steeds openbaar vervoer.',
    leden: {
      es: { woord: 'autobús', nl: 'bus' },
      fr: { woord: 'bus', nl: 'bus' },
      it: { woord: 'autobus', nl: 'bus' },
      en: { woord: 'bus', nl: 'bus' },
      de: { woord: 'Bus', nl: 'bus' },
    },
  },
  {
    id: 'aeroportus',
    stam: 'aēr',
    herkomst: 'Grieks',
    stamBetekenis: 'lucht',
    weetje: 'Een vliegveld heet in vijf talen letterlijk een haven in de lucht.',
    leden: {
      es: { woord: 'aeropuerto', nl: 'vliegveld' },
      fr: { woord: 'aéroport', nl: 'vliegveld' },
      it: { woord: 'aeroporto', nl: 'vliegveld' },
      pt: { woord: 'aeroporto', nl: 'vliegveld' },
      en: { woord: 'airport', nl: 'vliegveld' },
    },
  },
  {
    id: 'billa',
    stam: 'billa',
    herkomst: 'Latijn',
    stamBetekenis: 'briefje met een zegel',
    weetje: 'Een kaartje was ooit een briefje met een zegel erop, en dat zegel zit nog in billete en biglietto.',
    leden: {
      es: { woord: 'billete', nl: 'kaartje, biljet' },
      fr: { woord: 'billet', nl: 'kaartje, biljet' },
      it: { woord: 'biglietto', nl: 'kaartje' },
      pt: { woord: 'bilhete', nl: 'kaartje' },
      en: { woord: 'bill', nl: 'rekening, biljet' },
    },
  },
  {
    id: 'mala',
    stam: 'malha',
    herkomst: 'Frankisch',
    stamBetekenis: 'reistas',
    weetje: 'Het Engelse mail komt van de postzak, dezelfde tas die in maleta en mala zit.',
    leden: {
      es: { woord: 'maleta', nl: 'koffer' },
      pt: { woord: 'mala', nl: 'koffer' },
      fr: { woord: 'malle', nl: 'hutkoffer' },
      en: { woord: 'mail', nl: 'post' },
    },
  },
  {
    id: 'villa',
    stam: 'villa',
    herkomst: 'Latijn',
    stamBetekenis: 'boerderij, landgoed',
    weetje: 'Elke Franse stad heet naar een boerderij, want zo begonnen ze bijna allemaal.',
    leden: {
      fr: { woord: 'ville', nl: 'stad' },
      es: { woord: 'villa', nl: 'stadje, villa' },
      it: { woord: 'villa', nl: 'landhuis' },
      pt: { woord: 'vila', nl: 'stadje' },
      en: { woord: 'village', nl: 'dorp' },
    },
  },

  // ─── Winkelen, geld en werk ──────────────────────────────────────────
  {
    id: 'denarius',
    stam: 'denarius',
    herkomst: 'Latijn',
    stamBetekenis: 'Romeinse zilvermunt',
    weetje: 'Dinero en dinheiro heten nog altijd naar de denarius, een munt die al tweeduizend jaar niet meer bestaat.',
    leden: {
      es: { woord: 'dinero', nl: 'geld' },
      pt: { woord: 'dinheiro', nl: 'geld' },
      it: { woord: 'denaro', nl: 'geld' },
    },
  },
  {
    id: 'carus',
    stam: 'carus',
    herkomst: 'Latijn',
    stamBetekenis: 'dierbaar',
    weetje: 'Duur en dierbaar zijn hetzelfde woord, want wat je lief is kost nu eenmaal geld.',
    leden: {
      es: { woord: 'caro', nl: 'duur' },
      fr: { woord: 'cher', nl: 'duur, dierbaar' },
      it: { woord: 'caro', nl: 'duur, lief' },
      pt: { woord: 'caro', nl: 'duur' },
      en: { woord: 'cherish', nl: 'koesteren' },
    },
  },
  {
    id: 'constare',
    stam: 'constare',
    herkomst: 'Latijn',
    stamBetekenis: 'vaststaan',
    weetje: 'Wat iets kost is wat vaststaat, en dat idee reisde tot in het Duitse kosten.',
    leden: {
      es: { woord: 'costar', nl: 'kosten' },
      fr: { woord: 'coûter', nl: 'kosten' },
      it: { woord: 'costare', nl: 'kosten' },
      pt: { woord: 'custar', nl: 'kosten' },
      en: { woord: 'cost', nl: 'kosten' },
      de: { woord: 'kosten', nl: 'kosten' },
    },
  },
  {
    id: 'comparare',
    stam: 'comparare',
    herkomst: 'Latijn',
    stamBetekenis: 'samen verwerven, vergelijken',
    weetje: 'Kopen komt van vergelijken, dus de Romeinen keken ook al eerst even rond.',
    leden: {
      es: { woord: 'comprar', nl: 'kopen' },
      it: { woord: 'comprare', nl: 'kopen' },
      pt: { woord: 'comprar', nl: 'kopen' },
    },
  },
  {
    id: 'officium',
    stam: 'officium',
    herkomst: 'Latijn',
    stamBetekenis: 'plicht, dienst',
    weetje: 'Een kantoor heet naar de plicht die je er vervult, en dat klinkt in oficina en office nog door.',
    leden: {
      es: { woord: 'oficina', nl: 'kantoor' },
      it: { woord: 'ufficio', nl: 'kantoor' },
      pt: { woord: 'oficina', nl: 'werkplaats' },
      en: { woord: 'office', nl: 'kantoor' },
    },
  },
  {
    id: 'burra',
    stam: 'burra',
    herkomst: 'Latijn',
    stamBetekenis: 'ruwe wollen stof',
    weetje: 'Een bureau was eerst het groene laken op tafel, daarna de tafel zelf en pas later de hele kamer.',
    leden: {
      fr: { woord: 'bureau', nl: 'bureau, kantoor' },
      de: { woord: 'Büro', nl: 'kantoor' },
      en: { woord: 'bureau', nl: 'bureau, dienst' },
    },
  },
  {
    id: 'professor',
    stam: 'professor',
    herkomst: 'Latijn',
    stamBetekenis: 'iemand die openlijk verklaart',
    weetje: 'Een professor is letterlijk iemand die hardop bekent wat hij weet.',
    leden: {
      es: { woord: 'profesor', nl: 'leraar' },
      fr: { woord: 'professeur', nl: 'leraar' },
      it: { woord: 'professore', nl: 'leraar' },
      pt: { woord: 'professora', nl: 'lerares' },
      en: { woord: 'professor', nl: 'hoogleraar' },
    },
  },
  {
    id: 'studere',
    stam: 'studere',
    herkomst: 'Latijn',
    stamBetekenis: 'zich ergens vurig op toeleggen',
    weetje: 'Studeren betekende ijverig zijn best doen, dus het woord verwacht meteen inzet van je.',
    leden: {
      es: { woord: 'estudiar', nl: 'studeren' },
      fr: { woord: 'étudier', nl: 'studeren' },
      it: { woord: 'studente', nl: 'student' },
      pt: { woord: 'estudar', nl: 'studeren' },
      en: { woord: 'student', nl: 'student' },
      de: { woord: 'Student', nl: 'student' },
    },
  },
  {
    id: 'apprehendere',
    stam: 'apprehendere',
    herkomst: 'Latijn',
    stamBetekenis: 'ergens grip op krijgen',
    weetje: 'Leren is letterlijk ergens grip op krijgen, en een apprentice is iemand die dat nog aan het doen is.',
    leden: {
      es: { woord: 'aprender', nl: 'leren' },
      fr: { woord: 'apprendre', nl: 'leren' },
      it: { woord: 'apprendere', nl: 'leren' },
      pt: { woord: 'aprender', nl: 'leren' },
      en: { woord: 'apprentice', nl: 'leerling' },
    },
  },
  {
    id: 'medicus',
    stam: 'medicus',
    herkomst: 'Latijn',
    stamBetekenis: 'genezer',
    weetje: 'De dokter en het medicijn komen van hetzelfde Latijnse woord voor genezen.',
    leden: {
      es: { woord: 'médico', nl: 'arts, dokter' },
      fr: { woord: 'médecin', nl: 'dokter' },
      it: { woord: 'medico', nl: 'arts, dokter' },
      pt: { woord: 'médico', nl: 'arts, dokter' },
      en: { woord: 'medicine', nl: 'medicijn' },
    },
  },
  {
    id: 'parabola',
    stam: 'parabolē',
    herkomst: 'Grieks',
    stamBetekenis: 'vergelijking, verhaal met een les',
    weetje: 'Parler komt van parabel, dus praten was ooit een verhaaltje met een moraal vertellen.',
    leden: {
      fr: { woord: 'parler', nl: 'spreken' },
      it: { woord: 'parlare', nl: 'spreken' },
      es: { woord: 'palabra', nl: 'woord' },
      pt: { woord: 'palavra', nl: 'woord' },
      en: { woord: 'parable', nl: 'gelijkenis' },
    },
  },

  // ─── In huis ─────────────────────────────────────────────────────────
  {
    id: 'coquina',
    stam: 'coquina',
    herkomst: 'Latijn',
    stamBetekenis: 'kookplaats',
    weetje: 'Keuken, kitchen, Küche en cocina komen allemaal van het Latijnse koken, dus dat woord kreeg heel Europa te pakken.',
    leden: {
      es: { woord: 'cocina', nl: 'keuken' },
      fr: { woord: 'cuisine', nl: 'keuken' },
      it: { woord: 'cucina', nl: 'keuken' },
      pt: { woord: 'cozinha', nl: 'keuken' },
      en: { woord: 'kitchen', nl: 'keuken' },
      de: { woord: 'Küche', nl: 'keuken' },
    },
  },
  {
    id: 'tabula',
    stam: 'tabula',
    herkomst: 'Latijn',
    stamBetekenis: 'plank',
    weetje: 'Een tafel was gewoon een plank, en dat hoor je nog in het Duitse Tafel en het Italiaanse tavolo.',
    leden: {
      fr: { woord: 'table', nl: 'tafel' },
      it: { woord: 'tavolo', nl: 'tafel' },
      en: { woord: 'table', nl: 'tafel' },
      de: { woord: 'Tafel', nl: 'tafel, bord' },
      es: { woord: 'tabla', nl: 'plank' },
      pt: { woord: 'tábua', nl: 'plank' },
    },
  },
  {
    id: 'mensa',
    stam: 'mensa',
    herkomst: 'Latijn',
    stamBetekenis: 'tafel',
    weetje: 'In Duitsland en Italië heet de studentenkantine nog gewoon Mensa, oftewel de tafel.',
    leden: {
      es: { woord: 'mesa', nl: 'tafel' },
      pt: { woord: 'mesa', nl: 'tafel' },
      it: { woord: 'mensa', nl: 'kantine' },
      de: { woord: 'Mensa', nl: 'studentenkantine' },
    },
  },
  {
    id: 'cathedra',
    stam: 'kathedra',
    herkomst: 'Grieks',
    stamBetekenis: 'zetel om op te zitten',
    weetje: 'Een kathedraal heet naar de stoel van de bisschop, dus je stoel en die kerk zijn familie.',
    leden: {
      fr: { woord: 'chaise', nl: 'stoel' },
      pt: { woord: 'cadeira', nl: 'stoel' },
      en: { woord: 'chair', nl: 'stoel' },
      it: { woord: 'cattedra', nl: 'leerstoel, katheder' },
    },
  },
  {
    id: 'habitare',
    stam: 'habitare',
    herkomst: 'Latijn',
    stamBetekenis: 'ergens blijven wonen',
    weetje: 'Een habitación is letterlijk een plek om te wonen, en je habitat is dat ook.',
    leden: {
      es: { woord: 'habitación', nl: 'kamer' },
      fr: { woord: 'habiter', nl: 'wonen' },
      it: { woord: 'abitare', nl: 'wonen' },
      pt: { woord: 'habitar', nl: 'wonen' },
      en: { woord: 'inhabit', nl: 'bewonen' },
    },
  },
  {
    id: 'beuza',
    stam: 'beuza',
    herkomst: 'Germaans',
    stamBetekenis: 'bier',
    weetje: 'Bier is een Germaans exportproduct, want zelfs de Italianen bestellen birra.',
    leden: {
      fr: { woord: 'bière', nl: 'bier' },
      it: { woord: 'birra', nl: 'bier' },
      en: { woord: 'beer', nl: 'bier' },
      de: { woord: 'Bier', nl: 'bier' },
    },
  },

  // ─── Seizoenen ───────────────────────────────────────────────────────
  {
    id: 'hibernum',
    stam: 'hibernum',
    herkomst: 'Latijn',
    stamBetekenis: 'winter',
    weetje: 'Een winterslaap heet hibernatie, dus wie hiberneert doet gewoon aan invierno.',
    leden: {
      es: { woord: 'invierno', nl: 'winter' },
      fr: { woord: 'hiver', nl: 'winter' },
      it: { woord: 'inverno', nl: 'winter' },
      pt: { woord: 'inverno', nl: 'winter' },
    },
  },
  {
    id: 'autumnus',
    stam: 'autumnus',
    herkomst: 'Latijn',
    stamBetekenis: 'herfst',
    weetje: 'De Engelsen zeggen autumn en de Amerikanen fall, maar het Latijn zit alleen in de eerste.',
    leden: {
      es: { woord: 'otoño', nl: 'herfst' },
      fr: { woord: 'automne', nl: 'herfst' },
      it: { woord: 'autunno', nl: 'herfst' },
      pt: { woord: 'outono', nl: 'herfst' },
      en: { woord: 'autumn', nl: 'herfst' },
    },
  },
  {
    id: 'primavera',
    stam: 'prima vera',
    herkomst: 'Latijn',
    stamBetekenis: 'de eerste lente',
    weetje: 'Primavera betekent de allereerste lente, en het Franse printemps zegt precies hetzelfde met andere woorden.',
    leden: {
      es: { woord: 'primavera', nl: 'lente' },
      it: { woord: 'primavera', nl: 'lente' },
      pt: { woord: 'primavera', nl: 'lente' },
      fr: { woord: 'printemps', nl: 'lente' },
    },
  },
  {
    id: 'nix',
    stam: 'nix',
    herkomst: 'Latijn',
    stamBetekenis: 'sneeuw',
    weetje: 'Neige, neve en nieve komen uit hetzelfde Latijn, en snow en Schnee uit dezelfde nog veel oudere wortel.',
    leden: {
      es: { woord: 'nieve', nl: 'sneeuw' },
      fr: { woord: 'neige', nl: 'sneeuw' },
      it: { woord: 'neve', nl: 'sneeuw' },
      pt: { woord: 'neve', nl: 'sneeuw' },
      en: { woord: 'snow', nl: 'sneeuw' },
      de: { woord: 'Schnee', nl: 'sneeuw' },
    },
  },
]

/** Maakt van een woord een zoeksleutel: kleine letters, accenten weg, ligaturen uitgeschreven */
function normaliseer(woord: string): string {
  return woord
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/œ/g, 'oe')
    .replace(/æ/g, 'ae')
    .replace(/ß/g, 'ss')
    .replace(/[‘’ʼ´`]/g, "'")
    .trim()
}

/** Lidwoorden die we bij een mislukte zoekopdracht nog even wegknippen */
const LIDWOORDEN = [
  'el', 'la', 'los', 'las', 'un', 'una',
  'le', 'les', 'une', 'du', 'de',
  'il', 'lo', 'gli', 'uno',
  'o', 'a', 'os', 'as', 'um', 'uma',
  'der', 'die', 'das', 'ein', 'eine',
  'the',
]

function sleutel(taal: CourseId, woord: string): string {
  return taal + ':' + normaliseer(woord)
}

/** Eén keer opgebouwd bij het laden van de module, daarna is opzoeken gratis */
const INDEX: Map<string, WoordFamilie> = (() => {
  const kaart = new Map<string, WoordFamilie>()
  for (const familie of FAMILIES) {
    for (const taal of Object.keys(familie.leden) as CourseId[]) {
      const lid = familie.leden[taal]
      if (!lid) continue
      const s = sleutel(taal, lid.woord)
      if (!kaart.has(s)) kaart.set(s, familie)
    }
  }
  return kaart
})()

/** Zoek de familie waar dit woord in deze taal bij hoort */
export function familieVan(taal: CourseId, woord: string): WoordFamilie | undefined {
  const direct = INDEX.get(sleutel(taal, woord))
  if (direct) return direct

  const kaal = normaliseer(woord)

  // Tweede kans: lidwoord met spatie ervoor weghalen, bv. "el gato" of "der Kaffee"
  const delen = kaal.split(/\s+/)
  if (delen.length > 1 && LIDWOORDEN.includes(delen[0])) {
    const zonder = INDEX.get(taal + ':' + delen.slice(1).join(' '))
    if (zonder) return zonder
  }

  // Derde kans: samengetrokken lidwoord, bv. "l'eau", "l'amico", "un'ora"
  const samengetrokken = kaal.match(/^[a-z]{1,4}'\s*(.+)$/)
  if (samengetrokken) return INDEX.get(taal + ':' + samengetrokken[1])

  return undefined
}

export const AANTAL_FAMILIES = FAMILIES.length
